dotnet/buildtools

src/Microsoft.DotNet.Build.Tasks/PackageFiles/clean.targets
Update condition for folder choice to "Windows/not windows" since OSX and Linux use the same paths, and add a Windows-specific one for the C:\users\<user>\.nuget\packages folder.
@maririos ; @dagood
=> Fix for CleanPackagesCache behavior on Windows

src/Run/RunProcess.cs
Previously, we would redirect both the standard output and error streams
when run.exe would run a child process. This allowed us to "batch up" all
the output to stderr and report it at the end of the command.
The redirection prevented colorized output from working (on Win32 the
console color commands are no-ops when the output streams are no going to
a console, and similar logic on Unix causes ANSI escape sequences for
colors to not be included when the output is redirected).
This was a significant regression for MSBuild which uses colors. The
buffering we do for standard output/error also prevented tools from
interleaving errors/warnings and regular output.
Stop doing this redirection. Child processes which spew output to stderr
and then doing "replay" it at the end of command execution …
=> Do not redirect std[out|err] when running command

src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/PackageLibs.targets
We were using a windows path seperator when setting the TargetPath
metadata on source files we added to the ItemGroup of artifacts to pack.
This was causing the logic that splits the nuget package into a product
and symbols package to place the source assets in the product package in
an oddly named 'src\src" directory.
The NuGet logic around dealing with path seperators cross platform has
known issues (e.g. NuGet/Home#3584).
For now, we will use the correct path seperator when adding the metadata.
This seems to be the cleanest solution (I considered changing the path
seperators in the GenerateNuSpec target, but I worry about doing path
normalization there).
Contributes to dotnet/corefx#12758.  This actually fixes the issue, but of
course they will need to tae buildtools update.
=> Fix symbol package generation on Unix

src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj, src/Microsoft.DotNet.Build.Tasks/PackageFiles/FrameworkTargeting.targets, src/Microsoft.DotNet.Build.Tasks/WriteVisualBasicDefineResponseFile.cs
This task generates a response file we can use to pass the correct set of
defines to the complier without having to worry about MSBuild converting
back slashes to forward slashes when running on Unix systems.
=> Add a task to help workaround dotnet/corefx#5230

src/BuildTools.sln, src/Microsoft.DotNet.Build.VstsBuildsApi.net45/Microsoft.DotNet.Build.VstsBuildsApi.net45.csproj, src/Microsoft.DotNet.Build.VstsBuildsApi.net45/project.json, src/Microsoft.DotNet.Build.VstsBuildsApi/Microsoft.DotNet.Build.VstsBuildsApi.csproj, src/Microsoft.DotNet.Build.VstsBuildsApi/Properties/AssemblyInfo.cs, src/Microsoft.DotNet.Build.VstsBuildsApi/VstsBuildClient.cs, src/Microsoft.DotNet.Build.VstsBuildsApi/project.json, src/nuget/Microsoft.DotNet.BuildTools.VstsBuildsApi.nuspec
Implementation for API discussed in https://github.com/chcosta/buildtools/blob/vstsapi_proposal/Documentation/VSTSBuildManagement.md.
This allows us to multiplex build definitions based on a collection id which build orchestrators will utilize based on convention.  
@weshaggard @dagood @dleeapho @AlfredoMS @markwilkie
=> Add VSTS Api package for multiplexing checked in build definitions

src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/PackageLibs.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/PerfTesting.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
cc: @weshaggard @ericstj @karajas 
Now that each TestPath is unique to a build (since TargetGroup and TestTFM are part of it) we can get rid of the need of having TestNugetTargetMoniker being an item, since we don't need its metadata anymore.
=> Changing TestNugetTargetMoniker to be a Property instead of an Item

src/Microsoft.DotNet.Build.Tasks/PackageFiles/FrameworkTargeting.targets
This change fixes builds for buildtools consumers that don't use ConfigurationGroup
Fixes #1143
=> Fix VS Configuration workaround

src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh
Uses `find` to allow compatibility with CLI versions that have the NuGet change that lowercases package ids in the packages directory.
This should fix the buildtools side of https://github.com/dotnet/buildtools/issues/1111.
Tested on OSX and openSUSE 13.2 with https://github.com/dotnet/coreclr/compare/master...dagood:init-tools-insensitive.
@janvorli @chcosta @mellinoe @ericstj
/cc @weshaggard @gkhanna79
=> In init-tools.sh, lenient casing for restored packages

dependencies.props, src/Microsoft.DotNet.Build.CloudTestTasks.net45/project.json, src/Microsoft.DotNet.Build.Tasks.Packaging/src.Desktop/project.json, src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets, src/Microsoft.DotNet.Build.Tasks.Packaging/src/project.json, src/Microsoft.DotNet.Build.Tasks.Packaging/test.Desktop/project.json, src/Microsoft.DotNet.Build.Tasks.Packaging/test/project.json, src/Microsoft.DotNet.Build.Tasks.net45/project.json, src/Microsoft.DotNet.Build.Tasks/BinClashLogger.cs, src/Microsoft.DotNet.Build.Tasks/InstallPackageFromFile.cs, src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj, src/Microsoft.DotNet.Build.Tasks/NugetMsBuildLogger.cs, src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.targets, src/Microsoft.DotNet.Build.Tasks/PrereleaseResolveNuGetPackageAssets.cs, src/Microsoft.DotNet.Build.Tasks/project.json, src/Microsoft.DotNet.VersionTools.net45/project.json, src/Microsoft.DotNet.VersionTools/project.json
This change will allow 
- Install from nupkg to local path for installing locally built packages
- Reading from a lockfile that restored from a local path as a fallback source
These changes are required to enable the buildagainstpackages scenario by default. Associated corefx changes: https://github.com/dotnet/corefx/compare/master...karajas:defaultBAP?expand=1
=> Add tasks to support installing package from nupkg file and reading package folder locations out of the lock file

bootstrap/bootstrap.ps1, bootstrap/bootstrap.sh
Fixes #1165.
This is needed for CLI because their build script takes a architecture parameter that they need to respect.
=> Update boostrapper scripts to allow selecting architecture.

src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
We weren't handling prerelease on FilePackageDependency items well.
I did this before just to ensure that we'd always have a prerelease
dependency, but that's unnecessary, this will always be pre-release
since its not in the index.
=> Don't set prerelease on Unavailable

src/nuget/Microsoft.DotNet.BuildTools.GenAPI.nuspec, src/nuget/Microsoft.DotNet.BuildTools.RepoUtils.nuspec, src/nuget/Microsoft.DotNet.BuildTools.Run.nuspec, src/nuget/Microsoft.DotNet.BuildTools.TestSuite.nuspec, src/nuget/Microsoft.DotNet.BuildTools.VstsBuildsApi.nuspec, src/nuget/Microsoft.DotNet.BuildTools.nuspec, src/nuget/Microsoft.DotNet.VersionTools.nuspec, src/nuget/Microsoft.xunit.extensibility.execution.netcore.nuspec, src/nuget/Microsoft.xunit.netcore.extensions.nuspec, src/nuget/xunit.console.netcore.nuspec, src/nuget/xunit.runner.uwp.nuspec
I'm creating a branch for 1.1.0 to allow for buildtools changes.
As such we need to move the current versions out of the way.
I did the same for 1.0.0.
/cc @MattGal @dagood @karajas @chcosta @weshaggard 
since you all commonly update buildtools.  Take note of the version bumps so you pick up the correct builds when merging changes.
=> Bump buildtools package versions for rel/1.1.0

bootstrap/bootstrap.ps1, bootstrap/bootstrap.sh
- bootstrap.sh did not check for existence of the Shared Framework symlink before trying to create it, causing bootstrap to bomb out.
- When using a specific framework version instead of auto version, the shared framework path would be incorrect.
=> Fix a couple minor bootstrap issues.

src/Microsoft.DotNet.Build.Tasks.Packaging/src/GetLastStablePackage.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/VersionUtility.cs
NuGetVersion was returning a 4-part version even though the version
string it was constructed with only had 3 parts.  As a result, when we
compared it to the 3 part version in the stable version list it came out
as greater even though it was the same.  This caused us to stop 
harvesting from stable packages and resulted in numerous package
validation errors.
Fix this by ensuring we are comparing 3-part versions.
=> [release/1.1.0] Ensure we're comparing 3-part versions

src/Microsoft.DotNet.Build.Tasks/PackageFiles/BlockReflectionAttribute.cs
This cleans up FxCop analyzer warnings.
=> Add AttributeUsage to __BlockReflectionAttribute

src/Microsoft.DotNet.VersionTools/Automation/VersionsRepoUpdater.cs
This avoids adding empty files to the versions repo when releasing stable builds. This flows to auto-update PR titles looking nicer and avoids a GitHub bug where accessing an empty file through the raw API for the first time causes a 503 response.
I don't think this is useful enough to take for the current release, but it will make prerelease => stable auto-PRs smoother in the future.
/cc @gkhanna79 @weshaggard
=> Call non-prerelease builds "stable", not ""

src/Microsoft.DotNet.Build.Tasks/PackageFiles/ApiCompat.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/resolveContract.targets
This allows folks to define metadata on that item like TargetGroup.
Fixes #1041 
I needed to fix this in order to make all the projects contributing to NETCoreApp as TargetGroup='' (/cc @ellismg @chcosta)
/cc @weshaggard @JeremyKuhne
=> Allow for ContractProject to be specified as item

dependencies.props, src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.json, src/Microsoft.DotNet.BuildTools.TestSuite/runtime.json
This updates the version of NETStandard.Library that we are referencing in the tool runtime. This is needed for Fedora 24 support, which I've also enabled in this change. With this, we can turn on full test builds in corefx for Fedora 24.
@dagood
=> Update NETCore platform versions and add support for fedora 24

src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
Looks like this was meant to have a default value, but there was a
copy/paste error in the property definition.
I also fixed the condition on InstallLocallyBuiltPackages.
This will let folks pick up buildtools in CoreFx/elsewhere without making changes to the repo settings.
/cc @alexperovich @karajas @weshaggard
=> Fix typo in PackageInstallPath property

src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.targets
https://github.com/dotnet/buildtools/commit/2ba3679dbccd7ee0a79ae8d18fede36232417aff#diff-c368ca147f7a6d95f33280f334ff9e84R109
incorrectly turned on BuildTestsAgainstPackages (partially) for all
tests consuming BuildTools.  I understand that folks want that to be the
default for CoreFx but it should not be defined that way in buildtools.
/cc @weshaggard @karajas
=> Undo default for BuildTestsAgainstPackages

src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
https://github.com/dotnet/buildtools/commit/2ba3679dbccd7ee0a79ae8d18fede36232417aff
added install package target but didn't account for the fact that the
package may not be built if files were missing.
/cc @karajas @weshaggard
=> Don't try to install packages that were not built

src/nuget/Microsoft.DotNet.BuildTools.nuspec
Roslyn on .NETCore wasn't finding dependencies of analyzers if those
dependencies were not in the same directory as CSC itself.  It should be
looking next to the analyzer but is not.
On desktop this happens automatically but on Core I suspect roslyn's AssemblyLoadContext needs to handle it.
Workaround that by copying these dependencies to lib temporarily.  
/cc @alexperovich @tmat @tmeschter @mavasani
=> Workaround netcore roslyn assembly loading issue

src/Microsoft.DotNet.Build.VstsBuildsApi/VstsBuildClient.cs
https://github.com/dotnet/buildtools/issues/1181
Only iterate "definition" quality build definitions, ignore "drafts".  
=> Ignore "draft" definitions

src/Microsoft.DotNet.Build.Tasks/PackageFiles/PerfTesting.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
It looks like the VS debugging paths were broken by https://github.com/dotnet/buildtools/commit/bd11b84d8d7af2c599d52d51a150c4d06e7931b2
/cc @joperezr @MattGal @weshaggard
=> Fix paths for debugging tests in VS

src/Microsoft.DotNet.CodeAnalysis.net45/project.json, src/Microsoft.DotNet.CodeAnalysis/project.json
The System.Runtime.Analyzers & System.Runtime.InteropServices.Analyzers
packages referenced by Microsoft.CodeAnalysis.FxCopAnalyzers are
unsigned.  Update the package references to pull down signed versions.
/cc @alexperovich @safern
=> Update to signed version of analyzers

Documentation/project-nuget-dependencies.md
Fix a typo NUuGet -> NuGet in Documentation/project-nuget-dependencies.md
=> Fix a typo NUuGet -> NuGet in project-nuget-dependencies.md

src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
Previously we were failing to intersect here.  ProjectReferenceFullPath
had multiple entries for the same project which caused the equal
comparison to fail and we'd miss including these items.
=> Handle multiple runtime deps from same project

dependencies.props, src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.json, src/Microsoft.DotNet.BuildTools.TestSuite/runtime.json
~~This is a direct port of my master PR: #1177 . It will allow us to run tests against Fedora 24 in the release/1.1.0 branch.~~
I've made a small modification to the TestSuite's runtime.json over what is in master, so that we can run tests in the release/1.1.0 branch without retargeting all of the test projects to netcoreapp1.1.
=> Add Fedora 24 support to release/1.1.0 branch

src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.props
Some plugins require both props and targets.  Make sure we import both.
Fixes #1186
/cc @markwilkie @chcosta @dagood @weshaggard
=> Make sure to import MicroBuild.core.props

src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.props
This change exposed a bug introduced with https://github.com/dotnet/buildtools/commit/2d3d95068daf1b3edb6f7eb7001c6030bc23f4f3
That commit added a dependency on find which isn't working on
fedora or alpine.
Builds were still succeeding despite this regression because there was
no hard dependency on the packages pulled down (MS.Portable.Targets
or MicroBuild.Core) during the fedora/alpine builds.  My change to import
MicroBuild.Core props made this break, so I'm just sofenting the dependency
until init-tools can be fixed.
/cc @dagood @weshaggard
=> Only import props if they exist

src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh
No longer depend on `find`, which isn't available in our Fedora builds, and `-iwholename`, which isn't available in our Alpine builds. Allow lowercased package ids using character groups in the path glob.
Undoes the way https://github.com/dotnet/buildtools/pull/1114 solved the problem, which added full insensitivity. We only need to allow for proper-cased and lowercased paths, not any case. I also found `shopt -s nocaseglob` which could help in any other cases if real insensitivity is needed.
Should fix https://github.com/dotnet/buildtools/issues/1201. I haven't tested the full init-tools flow yet.
@ericstj
/cc @ellismg @chcosta @mellinoe
=> Simplify case-insensitive target file copy in init-tools.sh

src/Microsoft.DotNet.Build.Tasks.Packaging/src/GetApplicableAssetsFromPackages.cs
Fixes #1144 and https://github.com/dotnet/corefx/issues/12927.
=> Change Package Report back to using symbols as well as resolved assets.

src/BuildTools.sln, src/Microsoft.DotNet.Build.Tasks.net45/Microsoft.DotNet.Build.Tasks.net45.csproj, src/Microsoft.DotNet.Build.Tasks.net45/project.json, src/Microsoft.DotNet.Build.Tasks/GetTargetMachineInfo.cs, src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.json, src/Microsoft.DotNet.Build.Tasks/project.json
This adds an additional output to the `GetTargetMachineInfo` task: the nuget runtime ID of the machine running the build. We use this rid as the default test rid for x-plat builds. This means that corefx can stop using `ubuntu.14.04-x64` as the default rid for all Linux distros, and instead just rely on a reasonable default being available.
@weshaggard @Priya91 
Related to https://github.com/dotnet/corefx/issues/12461
=> Automatically detect non-Windows test RIDs

src/BuildTools.sln, src/Microsoft.DotNet.Build.Tasks.net45/Microsoft.DotNet.Build.Tasks.net45.csproj, src/Microsoft.DotNet.Build.Tasks.net45/project.json, src/Microsoft.DotNet.Build.Tasks/GetTargetMachineInfo.cs, src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.json, src/Microsoft.DotNet.Build.Tasks/project.json
It looks like I need to hook the logic in somewhere else, as some projects fail to build with this change. I'll follow up tomorrow.
=> Revert "Automatically detect non-Windows test RIDs"

src/Microsoft.DotNet.Build.Tasks.Packaging/src/GeneratePackageReport.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/GetApplicableAssetsFromPackageReports.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/GetLayoutFiles.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/Microsoft.DotNet.Build.Tasks.Packaging.csproj, src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets, src/Microsoft.DotNet.Build.Tasks.Packaging/src/VerifyClosure.cs
This produces flat-file layout directories from corefx.
These look like
ref{tfm}\file.dll
runtime{tfm}{rid}\file.dll
/cc @weshaggard @Petermarcu @ellismg
=> Generate layout from package reports

src/BuildTools.sln, src/Microsoft.DotNet.Build.Tasks.Packaging/src/GetApplicableAssetsFromPackages.cs, src/Microsoft.DotNet.Build.Tasks.net45/Microsoft.DotNet.Build.Tasks.net45.csproj, src/Microsoft.DotNet.Build.Tasks.net45/project.json, src/Microsoft.DotNet.Build.Tasks/GetTargetMachineInfo.cs, src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.json, src/Microsoft.DotNet.Build.Tasks/project.json
Re-submitting #1210 with slight changes. This fixes an issue in the `GetApplicableAssetsFromPackages` task if no target runtime is passed in.
@weshaggard @ericstj
=> Automatically detect TestNugetRuntimeId

src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
The identity package has all the layout information for all runtime
packages, so we shouldn't try to copy the layouts for both id and
runtime packages.  When we do it would cause a race if the two
were building at the same time.
I was trying to avoid this but didn't have the condition correct.
/cc @weshaggard @stephentoub
=> Don't create layout for runtime packages

src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/PackageLibs.targets
Many of our test projects use P2P references to pkgproj's. In order for assets to be resolved correctly out of them for the test run, we need the `TestNugetRuntimeId` to already be set. So I've hooked the new target to before those project references are resolved so that the property is already set when they are built.
@weshaggard @karajas
=> Hook GetDefaultTestRid before BeforeResolveReferences

src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets
This change stops the build from running git commands during every build.
It stops the `git rev-parse` and `git show` commands by persisting their output to a file in the bin directory.
/cc: @weshaggard @ericstj
=> Persist version information to disk

src/Run/Setup.cs
Allows users to (in most cases) add -WhatIf to their arguments and get the command printed out.  
This has the limitation that it may not be obvious what will actually happen when that command is run (often obfuscated by msbuild) but is a good start.  Unfortunately the only way one can "whatif" with msbuild is to either have the targets invoked understand this or just show preprocessor directives, neither is particularly  useful.
=> Add "WhatIf" behavior to Run.exe to simply print commands it will run

src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
msbuild /t:testdebugger=c:\debuggers\windbg.exe automatically runs the next unit tests under the debugger. 
Should work with devenv.exe too.
@joperezr
=> Add $(TestDebugger) flag to easily debug unittests

src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
Sometimes folks will copy and paste a test project without updating the assembly name.  Currently we have a subtle bug where if two test projects produce an assembly with the same name, Rid and TxM combination, a race condition can occur failing test build.  This is much less likely to happen using the project name, which in almost all cases matches the assembly name (or should)
@weshaggard @joperezr
=> Fix dependencylist naming behavior

src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.targets
cc: @naamunds @weshaggard 
Fixes dotnet/corefx#13739
With this, people running `build.cmd -buildArch:x86` will actually have the tests running for x86
=> Changing the test nuget moniker when TestArchitecture is passed in

src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh
https://github.com/dotnet/buildtools/pull/1206 broke the condition that checked to see if `__PUBLISH_RID` has no value. This fix uses an empty string if `__PUBLISH_RID` is undefined rather than erroring out. (Mentioned at top of file.)
I didn't catch it because I only tested without auto-detection--I got an error when trying OSX.
@ellismg Could you take a quick look? Tiny fix.
=> Allow __PUBLISH_RID detection in strict mode

src/Microsoft.DotNet.Build.Tasks/CleanupVSTSAgent.cs, src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj, src/Microsoft.DotNet.Build.Tasks/PackageFiles/scripts/vstsagent/cleanupagent.proj, src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.json
Adding a python script which allows us to cleanup our VSO agents' working folders on our windows, mac, and Linux machines.  We already have python as a pre-req for our builds.  This should help us eliminate the disk space issues we occasionally hit on our build machines.
My fork appears to be in an annoying state where I'm still getting additional commits with my PR's, which are no-op (ie, "Port GetRuntimeTargets and GetRuntimeJsonValues for Package Testing").  I'll probably delete my fork and create a new one, but for now, please ignore the additional commits and just focus on the files changed.
I've never written Python before, but I validated that the below code at least does what I expect. :)
/cc @weshaggard @jhendrixMSFT @wtgodbe
=> VSO Agent cleanup

src/Microsoft.DotNet.Build.Tasks/PackageFiles/CodeCoverage.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets
Allow /p:PopCoverageReport=true to cause the coverage report to open in your browser as soon as it's ready.
Allow eg /p:corelibroot=\git\coreclr.dan\bin\Product\Windows_NT.x64.Release to cause test runs to get your privately built corelib and symbols. This is an easy workaround until we have a fix for https://github.com/dotnet/corefx/issues/13094 (and useful anyway). Disables native images also, so it's not necessary to copy those.
@stephentoub
=> Coverage flags

src/Microsoft.DotNet.Build.Tasks/FilterRuntimesFromSupports.cs
This is to ensure we pass in TestNugetTargetMoniker instead of TestTFM for filtering runtime identifiers from supports.
/cc @weshaggard @ericstj
=> Use full name to compare nuget frameworks instead of shortname in FilterRuntimesFromSupports.

src/Microsoft.DotNet.Build.Tasks/FilterRuntimesFromSupports.cs, src/Microsoft.DotNet.Build.Tasks/PackageFiles/buildagainstpackages.targets
Replace FilterToTestTFM with FilterTestNugetTargetMoniker in buildagainstpackages.targets
=> Fix nuget framework compare with long name

dependencies.props, dir.props
Adding proper xml header to .props files
This helps code editors, like VS Code, to use proper syntax highlight.
Other .props file in this repo already have it
=> Add proper xml header to .props files

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.props, src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
Creating two centralized common properties that will be used in our targets and props files in order to get individual build and test configurations for a project. This will help avoiding build and test clashes in different targets.
cc: @weshaggard @MattGal 
Fixes: https://github.com/dotnet/buildtools/issues/1121
=> Create BuildConfiguration and TestConfiguration properties

src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets
=> Ensure that TestNugetRuntimeId is computed when building in VS

dependencies.props, src/Microsoft.DotNet.Build.Tasks.net45/project.json
Upgrade `System.Runtime.InteropServices.RuntimeInformation` to take a change that removed the need for api-set DLLs, described in https://github.com/dotnet/corefx/issues/13566. This was causing win7 runs to fail. A repro I had of the issue goes away when I use a buildtools package produced with this change.
The only package diff from this is `lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll`.
Is depending on the prerelease package during the buildtools build ok, or should we avoid it at all costs?
Fixes (when flowed through) https://github.com/dotnet/corefx/issues/14165.
@weshaggard @JohnChen0 @stephentoub 
/cc @dleeapho
=> Upgrade net45 System.Runtime.InteropServices.RuntimeInformation

src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
Revert GenerateTestBindingRedirects to use _CombinedListOfTestAssets and
remove the Conditions from the task calls.  The only intended changes to
this target in #1263 were to add the call to FilterNativeAssemblies and
use the output of that as the input to GetAssemblyIdentity.
/cc @karajas @MattGal @ericstj
=> Fix GenerateTestBindingRedirects merge

dependencies.props, src/Microsoft.DotNet.Build.Tasks.Packaging/src.Desktop/project.json, src/Microsoft.DotNet.Build.VstsBuildsApi.net45/project.json, src/Microsoft.DotNet.VersionTools.net45/project.json, src/common/test-runtime/project.json
Enforce `System.Runtime.InteropServices.RuntimeInformation` `4.4.0-beta-24813-03` across buildtools by making it a dependency verification rule.
This is a fix to https://github.com/dotnet/buildtools/pull/1249 which only upgraded this package for one project, causing VersionTools to fail when attempting to create an auto-update PR: https://devdiv.visualstudio.com/DevDiv/_build?buildId=471628:
```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
at …
```
=> Make RuntimeInformation package version consistent across BuildTools

src/Microsoft.DotNet.Build.Tasks.net45/Microsoft.DotNet.Build.Tasks.net45.csproj, src/Microsoft.DotNet.Build.Tasks/AddDependenciesToProjectJson.cs, src/Microsoft.DotNet.Build.Tasks/project.json
This change is necessary for our release branches where we want to be able to point to the latest versions of the release branch packages.
This change is in conjunction with https://github.com/dotnet/buildtools/pull/1105 to address servicing requirements.
@weshaggard @dagood
=> Enable reading versions file from URI

src/Microsoft.DotNet.Build.Tasks.net45/project.json, src/Microsoft.DotNet.Build.Tasks/AddDependenciesToProjectJson.cs, src/Microsoft.DotNet.Build.Tasks/PackageFiles/buildagainstpackages.targets, src/Microsoft.DotNet.Build.Tasks/project.json
In CoreFx release branch builds, we only build / publish packages which we are servicing.  We are unable to build tests with project references converted to packages, because the process does not know what package versions to use (traditionally it can determine this from a package drop which contains all of the packages we built).  The fix for determining package versions, was to check in a versions file which the process can derive information from - https://github.com/dotnet/corefx/commit/252011a470b5586338694219642c411b0d0c3a7d.  However, when a version file is used in conjunction with a package drop (the built packages we are servicing), there can be a conflict between package version numbers.  To address that conflict, we have an option to provide the hint …
=> Port UseNewestPackagesAvailable option to buildtools-release/1.0.0

src/Microsoft.DotNet.Build.Tasks/PackageFiles/BuildVersion.targets
Use UTC instead of current Time Zone.  Ideally this should move to using OfficialBuildId I think but for some reason @joperezr made that change and reverted it way back in July, so I suspect there's a technical hurdle to that approach.  Since TodayTimeStamp was used nowhere else, I've renamed the property for clarity.
Either way, our VSO agents do run in UTC time zones and standardizing on this makes the most sense.
@dagood @markwilkie
=> Change auto-generated build version file path to use UTC 

src/Microsoft.DotNet.Build.Tasks/CleanupVSTSAgent.cs, src/Microsoft.DotNet.Build.Tasks/PackageFiles/scripts/vstsagent/cleanupagent.proj
- Kill git.exe before starting execution; many failures seen recently are due to .idx files being in use when cleanup was attempted, typical of git gc behavior.
- Do unknown folder cleanup in the same way as known folder (previously was only starting the next task after when the first one failed for the first time, which takes too much time).  
- Reduce sleep time to 2 sec default.
@chcosta @markwilkie 
Builds cleanly, tested locally using @chcosta's sample data.
=> VSTS Agent cleanup task tweaks

Documentation/test-targets-usage.md
I'm planning to add a separate page documenting the test target design.
/cc @weshaggard @maririos @MattGal
=> Add usage documentation for test targets

src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/scriptrunner/scriptrunner.py
Add 'args=' to command_main invocation as this can break for some legitimate usages of --args.
Previously we'd always used the script without explicitly stating --args, and due to luck, random pythonism, and my choice of variable names this just worked.  Adding this tweak makes @wtgodbe's (correct) interpretation of how the script should work ALSO work.
=> Fix minor bug with scriptrunner.py

src/Run/CommandLine.cs
By checking qualifier length and changing the value for _qualifiersUseOnlyDash, we can support parameters using --, -, and / from run.exe.
I attempted to get this to work by having the Executor set QualifiersUseOnlyDash but that will take a fair bit of refactoring to actually be able to use the property (due to the protection on its setter).
I am still testing this, so please do not merge.
@weshaggard
=> WIP: Adding support for --, / to Run.exe

src/Microsoft.DotNet.VersionTools/Automation/GitHubApi/GitHubClient.cs, src/Microsoft.DotNet.VersionTools/Automation/GitHubApi/HttpFailureResponseException.cs, src/Microsoft.DotNet.VersionTools/Automation/VersionsRepoUpdater.cs, src/Microsoft.DotNet.VersionTools/Microsoft.DotNet.VersionTools.csproj
This allows a build to succeed on a branch that doesn't have a build-info entry. Without this change, the build would fail to find an existing entry and fail with a 404.
Implemented by catching the 404 in the specific case of requesting file contents, and returning `null` contents. A GitHub 404 can also be an authentication error, so I don't want to catch it very broadly.
@StephenBonikowsky This will fix the publish build problems you're hitting with manual builds of new WCF branches.
@weshaggard @gkhanna79 This will also let us stop having to manually create blank build-info files when setting up new release branch builds.
=> If no "Latest_Packages" versions repository file exists, create one

bootstrap/bootstrap.ps1, bootstrap/bootstrap.sh, src/Microsoft.DotNet.Build.Tasks/PackageFiles/ApiCompat.runtimeconfig.json, src/Microsoft.DotNet.Build.Tasks/PackageFiles/BclRewriter.runtimeconfig.json, src/Microsoft.DotNet.Build.Tasks/PackageFiles/GenAPI.runtimeconfig.json, src/Microsoft.DotNet.Build.Tasks/PackageFiles/GenFacades.runtimeconfig.json, src/Microsoft.DotNet.Build.Tasks/PackageFiles/MSBuild.runtimeconfig.json, src/Microsoft.DotNet.Build.Tasks/PackageFiles/csc.runtimeconfig.json, src/Microsoft.DotNet.Build.Tasks/PackageFiles/vbc.runtimeconfig.json, src/Run/run.runtimeconfig.json
Upgrades buildtools shared framework version to 1.1.0. Helps with https://github.com/dotnet/corefx/issues/14215 by letting CoreFX use CLI version `1.0.0-preview2-1-003182.`
If I stopped there, buildtools would be blocked from uptaking a newer version of itself because bootstrap.sh/ps1 don't support fetching CLI `1.0.0-preview2-1-003182` to get the 1.1.0 framework. To fix this I added `DotNetInstallBranch` that configures which CLI branch dotnet-install comes from. To uptake a new buildtools package, the CLI version will have to be changed and `-DotNetInstallBranch "rel/1.0.0-preview2.1"` passed into bootstrap.ps1 by run.ps1.
~~I also added `invoke_annotated` to bootstrap.sh to remove duplicated code.~~
@crummel @ellismg PTAL
/cc @naamunds
=> Update shared framework to 1.1.0, change CLI version to 1.0.0-preview2-1-003182

src/Microsoft.DotNet.CodeAnalysis/Analyzers/PinvokeAnalyzer.cs, src/Microsoft.DotNet.CodeAnalysis/PackageFiles/PinvokeAnalyzer_Win32Apis.txt
Two changes that are required for running PInvoke Analyer in CoreCLR repo:
1. Ignore QCall (internal calls from BCL to runtime)
2. Add some APIs used by System.Private.CoreLib.dll to allowed list
=> PInvoke Analyer changes need for CoreCLR

src/Microsoft.DotNet.Build.CloudTestTasks/AzureHelper.cs, src/Microsoft.DotNet.Build.CloudTestTasks/DownloadFromAzure.cs
Use NextMarker + Marker Uri parameter to allow downloading > 5000 blobs.   Bug found by @wtgodbe who somehow has a container with > 18K blobs!
Fix query string regex to allow ! in parameter strings. (Thanks @ChadNedzlek )
=> Fix lack of continuation token in DownloadFromAzure task

src/Microsoft.DotNet.Build.Tasks.Packaging/src/ApplyBaseLine.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/ApplyPreReleaseSuffix.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/FilterUnknownPackages.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/GetLastStablePackage.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/GetPackageFromModule.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageIndex.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/ValidatePackage.cs
Previously we'd merge any index we saw during build into an index
singleton.  This was because initially the index was seen as repo data
and not project specific data.  I broke that assumption when I started
using a different index in packages which wanted a different baseline.
I began using indexes specific to individual projects.  This caused
state to bleed across packages.
Fix this by always calling Load and backing it with a cache that will
not reload the index if the same index set was already loaded.
Thanks @StephenBonikowsky for pointing this out.
=> Ensure PackageIndex is not mutated during build

bootstrap/bootstrap.ps1, bootstrap/bootstrap.sh
In `.sh`, creates a new function `invoke_annotated` which takes a summary, command, and arguments. It prints everything then calls the command with its arguments. Tested on OSX and Ubuntu Trusty.
In `.ps1`, creates `Invoke-Annotated` which takes a summary and a string expression to invoke. It prints everything then invokes the string.
=> Deduplicate bootstrap command invocation logging

bootstrap/bootstrap.ps1, bootstrap/bootstrap.sh
Reverts dotnet/buildtools#1297
It looks like the powershell changes unexpectedly broke the official build. https://devdiv.visualstudio.com/DevDiv/_build?buildId=515528
FYI @crummel
=> Revert "Deduplicate bootstrap command invocation logging"

src/Microsoft.DotNet.Build.VstsBuildsApi/VstsBuildHttpClient.cs
`builds` should be `build`.
I messed up my last refactor in https://github.com/dotnet/buildtools/pull/1270 and must have only tested the Release flow. Now I've actually pulled this package into pipebuild and running with a fuller scenario I noticed.
FYI @MichaelSimons @chcosta
=> For checked in definition client, fix VSTS build API url

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/Dumpling.targets
In PR https://github.com/dotnet/buildtools/pull/1254, Dumpling service (a service to collect core dumps) option was added to non-Windows test runs, being ON by default for Helix runs. However, Dumpling.target should have run before target `GenerateTestExecutionScripts` instead of `RunTestsForProject`, to actually be added to `RunTests.sh`. This PR fixes that.
The current changes have been tested on CoreFx locally by pointing CoreFx to packages built by a local BuildTools repo. Also, to make sure Helix would pick Dumpling up for `RunTests` script, the Helix zipped test directory was generated locally by running:
`msbuild <TestProjectPath> /p:EnableDumpling=true /p:SkipTests=true /p:ArchiveTests=true`
and it was verified that Dumpling commands appeared in `RunTests` script.
cc: @danmosemsft …
=> Move Dumpling target before GenerateTestExecutionScripts

src/Microsoft.DotNet.Build.Tasks/GenerateTestExecutionScripts.cs
Removing parenthesis in echo commands was mistakenly added to `WriteCmdExecutionScript` in https://github.com/dotnet/buildtools/pull/1254. This PR corrects that by moving it to `WriteShExecutionScript`.
cc: @MattGal  @danmosemsft
=> Correct parentheses removal in GenerateTestExecutionScripts

src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh
When running from volumes that aren't case-sensitive like a windows
volumne mounted in a linux docker container, the mv command fails.
To help eliminate issues we will just ignore the error code for
the mv command and if it fails it will print out a message but
won't fail the intitialization of tools.
Fixes https://github.com/dotnet/buildtools/issues/1308
cc @joperezr
=> Ignore errors in mv command at the end of init-tools.sh

src/Run/Setup.cs
Addresses https://github.com/dotnet/buildtools/issues/1305.  
However, to get the command they're using in that issue to work as expected, we'll also have to change build.cmd/sh.
@danmosemsft
=> Fix null-ref when unexpected -? args come in

src/Microsoft.DotNet.Build.Tasks/PackageFiles/Roslyn.Common.props, src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd, src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh, src/Microsoft.DotNet.Build.Tasks/PackageFiles/msbuild.sh, src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.json
We are using a very old version of .NET Core MSBuild (from last June). This commit updates the versions we are using. The "MSBuild" and "Microsoft.Build.Targets" packages have been replaced by the "Microsoft.Build.Runtime" package, which I've switched to. There are a couple of path-related breaking changes that I needed to react to in this change, as well.
All of these new packages are available on nuget.org.
@weshaggard @joperezr
=> Update MSBuild package versions and account for breaking changes.

src/nuget/Microsoft.DotNet.BuildTools.nuspec
Apparently the previous line was causing GenFacades.Core.dll to be placed into the lib/net46 folder anyways, so this line was not needed. The nuget publisher gave an error because of this duplicate file, although everything built fine locally.
=> Remove duplicate GenFacades.Core entry in nuspec

src/GenFacades/GenFacades.Core/GenFacades.cs, src/Microsoft.DotNet.Build.Tasks/GenFacadesTask.cs
Instead of ignoring when `FacadeGenerator.GenerateFacade` returns null, I'm now detecting it and returning `false` from this method. The MSBuild task checks that result and propagates it.
@ericstj This should fix the NRE when GenFacades fails, and give better error messages.
=> Propagate errors for GenFacades

src/ApiCompat/Program.cs, src/ApiCompat/Rules/Compat/CannotRemoveGenerics.cs, src/GenFacades/GenFacades.Core/GenFacades.cs, src/Microsoft.Cci.Extensions/Extensions/TypeExtensions.cs, src/Microsoft.Cci.Extensions/Traversers/MappingsTypeMemberTraverser.cs, src/Microsoft.Cci.Extensions/Traversers/SimpleTypeMemberTraverser.cs, src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Attributes.cs, src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Types.cs, src/Microsoft.Cci.Extensions/Writers/DocumentIdWriter.cs
This makes sure the sort order is consistent even with different culture/locale settings.
I thought about using StringComparer.Ordinal since it feels like the more "correct" in this case but unfortunately this generates a huge diff in e.g. the dotnet/standard repo since APIs are being reordered.
Unfortunately, even StringComparer.OrdinalIgnoreCase doesn't produce the exact same result, but the diff is much smaller, e.g. https://github.com/akoeplinger/standard/commit/dd88153291ed83fd0dadfcb585ab4c2477702346.
With this, I can use GenAPI.exe on OSX and it generates the same file as on Windows.
Fixes https://github.com/dotnet/corefx/issues/15445
/cc @mellinoe @weshaggard
=> Use StringComparer.OrdinalIgnoreCase in LINQ OrderBy calls

src/Microsoft.DotNet.Build.Tasks/PackageFiles/VersionTools.targets, src/Microsoft.DotNet.Build.Tasks/VersionTools/BaseDependenciesTask.cs, src/Microsoft.DotNet.VersionTools/Dependencies/Submodule/IndicatorPackageSubmoduleUpdater.cs, src/Microsoft.DotNet.VersionTools/Dependencies/Submodule/LatestCommitSubmoduleUpdater.cs, src/Microsoft.DotNet.VersionTools/Dependencies/Submodule/SubmoduleUpdater.cs, src/Microsoft.DotNet.VersionTools/Microsoft.DotNet.VersionTools.csproj
These will be used in build from source to automatically keep the submodules in sync with the individual product repositories.
`IndicatorPackageSubmoduleUpdater` looks for the current indicator package in dotnet/versions, downloads it, extracts the version.txt inside, and compares it to the submodule's current commit. This is good to only update to a commit that has had an official build, but it only works when the submodule actually points at the official repository. (Not the case for any submodules at the moment.)
`LatestCommitSubmoduleUpdater` uses git's `ls-remote` to check the current commit a remote ref is pointing to, and compares it to the submodule's current commit.
@ellismg
=> Add submodule updaters to VersionTools

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/Dumpling.txt, src/Microsoft.DotNet.Build.Tasks/GenerateTestExecutionScripts.cs
Fixes https://github.com/dotnet/corefx/issues/15472
This PR fixes two issues:
**One.** When we echo all commands in RunTests.sh, the echo of a dumpling command 
`echo echo 0x3F > /proc/self/coredump_filter`
fails with error: `echo: write error: Invalid argument`
The fix to this is to wrap all commands in double quotes (`echo "echo 0x3F > /proc/self/coredump_filter"`)
**Two.** When a test fails but no core file was dumped, Dumpling.targets was trying to upload the non-existing file as the following check wasn't working as expected:
`if [ -n '$_corefile' ]`
converting the line to `if [ -n "$_corefile" ]` fixes the problem.
@MattGal @mellinoe
=> Fix bug in GenerateTestExecutionScripts by wrapping echoCommands in quotes

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/Dumpling.txt
The current version did not work because of the way we are reading the lines out of this file and injecting them into another script. I tested this by causing a test to fail both:
* normally, through an unhandled System.Exception()
* by forcibly seg-faulting the test
Without this change, the first test case was still trying to call Dumpling.py, but with invalid arguments, because no core file was found.
@sepidehMS
=> Fix conditional in Dumpling.txt command template

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/Dumpling.sh, src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/Dumpling.targets
Instead of reading a text file and inserting raw script lines into RunTests.sh, I'm simply running a Dumpling.sh script from RunTests.sh. The way lines were being copied into RunTests.sh was very fragile and was not working anyways. Instead of fixing it, I've just switched to this, which should be simpler and less error-prone.
@sepidehMS
=> Make Dumpling.targets use a proper shell script.

src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj, src/Microsoft.DotNet.Build.Tasks/PackageFiles/scripts/docker/init-docker.sh
The idea behind this script is that we would call it at the beginning of build definitions that utilize Docker images.  This would replace the call to cleanup-docker and the build step to capture the docker version.  The retry logic here will hopefully address some of the flakiness we have been seeing when pulling images.
related to https://github.com/dotnet/core-eng/issues/437
=> Initial version of init-docker.sh

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/Dumpling.sh
Some of our CI machines only have curl. This uses curl if wget is not found, and errors out if neither are found.
@sepidehMS
=> Use either wget or curl, based on what is installed in Dumpling.sh

src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd, src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh
=> Added logic to init-tools to ensure correct MSBuild.runtimeconfig.json is used

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/PerfTesting.targets
Addresses https://github.com/dotnet/core-eng/issues/346
Ensures we don't force all users to create a Packages.zip
@chcosta , @wtgodbe 
Will need a separate PR for corefx if we want to adopt it there (may not be necessary)
Weird diff is from fixing XML formatting on CloudTest.targets;  I can undo this if you really want, otherwise please just use a diff tool that can ignore whitespace.
=> Move Packages.zip to be a Supplemental Payload

src/Microsoft.DotNet.Build.Tasks/AddItemIndices.cs, src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj, src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/Symbols.targets
Symbols.targets can submit to the Microsoft symbol server, and includes the logic to extract symbol packages and publish Windows symbols to a file share. If `SymbolsRequestDryRun` is `true`, the request is created but not submitted. This is useful for trying out the targets.
The plan is to use this in the Publish definition, having it index during master/dev/daily builds and archive during stabilizing builds, using symbol packages.
=> Add symbol server request submission targets

src/Microsoft.DotNet.Build.Tasks/PackageFiles/CodeCoverage.targets, src/common/test-runtime/project.json
The version we depend on is gone and this tool is rarely used anyway
/cc @stephentoub
=> Remove coveralls.io support

src/Microsoft.DotNet.Build.Tasks.Packaging/src/CreateTrimDependencyGroups.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/GeneratePackageReport.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/GetInboxFrameworks.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/GetPackageFromModule.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/Microsoft.DotNet.Build.Tasks.Packaging.csproj, src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/PackageLibs.targets, src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.common.targets, src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets, src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageIndex.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/PromoteDependencies.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/SplitReferences.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/UpdatePackageIndex.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/ValidatePackage.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/VersionUtility.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/test/CreateTrimDependencyGroupsTests.cs, src/nuget/Microsoft.DotNet.BuildTools.nuspec
We're growing the inbox concept to accomodate the flat framework packages (eg: NETStandard.Library, MS.NETCore.App, UWP).  As such it no longer makes sense to have these things defined as static framework lists that live in the buildtools package.  I've moved the data into the packageindex and created mechanisms for migration.
=> Move Inbox data to package index

src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj, src/Microsoft.DotNet.Build.Tasks/PackageFiles/VersionTools.targets, src/Microsoft.DotNet.Build.Tasks/VersionTools/BaseDependenciesTask.cs, src/Microsoft.DotNet.Build.Tasks/VersionTools/LocalUpdatePublishedVersions.cs, src/Microsoft.DotNet.Build.Tasks/VersionTools/UpdatePublishedVersions.cs, src/Microsoft.DotNet.VersionTools/Automation/GitHubVersionsRepoUpdater.cs, src/Microsoft.DotNet.VersionTools/Automation/LocalVersionsRepoUpdater.cs, src/Microsoft.DotNet.VersionTools/Automation/NupkgInfo.cs, src/Microsoft.DotNet.VersionTools/Automation/VersionsRepoUpdater.cs, src/Microsoft.DotNet.VersionTools/BuildInfo.cs, src/Microsoft.DotNet.VersionTools/Microsoft.DotNet.VersionTools.csproj
Adds `VersionsRepoDir`, which points the tasks to use a versions-repo-like directory on disk.
For dependency update, change the `DependencyBuildInfo` to specify `VersionsRepoDir` metadata rather than `RawVersionsBaseUrl` metadata. E.g. https://github.com/dagood/corefx/commit/4e43203298e1d9c81daa5be91287371e69587716.
The packages created during a source build can be written to the local versions repo directory using `LocalUpdatePublishedVersions`, enabling local flow between two repos.
=> Add local build-info flow for source build

src/Microsoft.DotNet.Build.Tasks.Packaging/src/CreateTrimDependencyGroups.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/test/CreateTrimDependencyGroupsTests.cs
Previously we were explicitly excluding PCL profiles from creating
trimmed dependency groups.
/cc @davidfowl @chcosta
=> Create trimmed dependency groups for PCL profiles

src/Microsoft.DotNet.Build.Tasks/WriteVisualBasicDefineResponseFile.cs
We write VB defines to a defines.rsp for the VB compiler to work around an MSBuild issue. If the file is already present and already has longer content this task will corrupt it causing a build failure. It should replace the content.
@mellinoe
=> Fix overwrite of VB response file

src/Microsoft.DotNet.Build.Tasks/VersionTools/BaseDependenciesTask.cs, src/Microsoft.DotNet.VersionTools/Dependencies/FilePackageUpdater.cs, src/Microsoft.DotNet.VersionTools/Dependencies/ToolVersionsUpdater.cs, src/Microsoft.DotNet.VersionTools/Microsoft.DotNet.VersionTools.csproj
`ToolVersionsUpdater` is used on `.toolversions` files, for bootstrap-acquired dependencies.
`FilePackageUpdater` updates an entire file with a package's version, for `BuildToolsVersion.txt` (and `DotnetCLIVersion.txt`).
This is the first part of getting to this BfS objective:
> 2. We need a way to update the buildtools dependency of everything that uses it to consume the version we just built.
Steps are set up like this: https://github.com/dagood/corefx/commit/1623bdd45fcd13b7b92d03ce776ff8fec1cb4276 (the `DependencyBuildInfo` is for testing).
=> Create updaters for tooling version files

src/Microsoft.DotNet.Build.Tasks.Packaging/src/ApplyMetaPackages.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/Microsoft.DotNet.Build.Tasks.Packaging.csproj, src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.common.targets, src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets, src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageIndex.cs
Allow PackageIndex to define package IDs that should be rolled into a
meta-package reference rather than individual package references.
/cc @weshaggard @terrajobst 
This lets us reference the NETStandard.Library meta-package instead of the granular packages.  Consumption side of this change looks like this: https://github.com/ericstj/corefx/commit/38c8073910701ed4934a0c65556c5e52a8433b78
=> Add support for meta-package harvesting

src/Microsoft.DotNet.CodeAnalysis/PackageFiles/codeAnalysis.targets
The fxcopy analyzers do not make sense for CoreRT low-level components
Fixes #1349
=> Allow disabling fxcop analyzers

dependencies.props, src/Microsoft.DotNet.Build.Tasks/PackageFiles/IL.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.json
I did a few things here:
* Cleaned up how the "GetIlasmPath" target worked so that we always use that absolute path on Windows. Previously, if you weren't building from VS, we would just use the name "ilasm" to start the process. That only worked if you were in a developer command prompt. Which is most of the time, admittedly, but this way is cleaner and works just as well.
* Give an error if `IlasmToolPath` is not set, which should only happen outside of Windows. Repos need to set that property, for now at least, until we figure out a better way to restore and deploy native assets along with buildtools.
* Call `TargetsTriggeredByCompilation`, which fixes https://github.com/dotnet/buildtools/issues/1338
@weshaggard, @ericstj
This stuff isn't strictly required for us to upgrade ilasm in …
=> Clean IL.targets and make it call TargetsTriggeredByCompilation.

src/Microsoft.DotNet.Build.Tasks/PackageFiles/IL.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.json
Buildtools consumers need to set the IlAsmToolPath property directly in order to build .ilproj files outside of Windows. An error is given outside of Windows if this property is not set. On Windows, we still auto-detect the globally-installed version of ilasm if it is not provided.
@weshaggard Along with a depproj in corefx, this will accomplish what we discussed in-person. For people working in repos that don't have such a depproj for ilasm, they will get a relatively actionable error message instead.
=> Remove the restore/publish of ilasm and its dependencies

src/Microsoft.DotNet.Build.Tasks.Packaging/src/GenerateRuntimeDependencies.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
Previously we were writing runtime.json using a stale copy of the NuGet
code (since it wasn't public yet).
Now support is available in the NuGet.RuntimeModel assembly.  Use that
instead.
/cc @Petermarcu @weshaggard
=> Use NuGet.RuntimeModel instead of stale copy

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/Dumpling.targets, src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/DumplingHelper.py
@sepidehMS Could you take a look?
This adds support for collecting crash dumps on Windows. The differences between this and the Unix script are just a consequence of the different crash dump collection facilities on the operating systems. Unix systems allow us to have the crash dump files placed directly next to the executable file, which makes them very easy to discover. On Windows, we are able to configure a global location for crash dumps via the registry, and our CI machines are configured to do so.
In addition to specifying `EnableDumpling=true`, Windows users must also specify `CrashDumpFolder=<SOMETHING>` in order for this to discover new crash dumps. The process is as follows:
* Ensure dumpling is installed.
* Collect a timestamp and store it in `__TIMESTAMP`.
* Run the tests.
* …
=> Add support for capturing windows crash dumps to Dumpling.targets

src/xunit.netcore.extensions/Discoverers/SkipOnTargetFrameworkDiscoverer.cs, src/xunit.netcore.extensions/TargetFrameworkMonikers.cs, src/xunit.netcore.extensions/XunitConstants.cs
We are currently testing only against latest version of every target framework. We need to update the `Xunit.Netcore.Extensions` to have a non-version behavior when discovering tests. This will help consolidate the behavior when using `SkipOnTargetFramework` test attribute. This is also needed for netfx vertical test runs in order to filter the tests correctly. 
Currently working on the necessary changes in corefx tests to make them build successfully when we try to ingest the new buildtools version.
/cc @weshaggard @ericstj
=> Update xunit constants and TargetFrameworkMonikers to be non-versioned

src/Microsoft.DotNet.Build.Tasks/GenFacadesTask.cs
This task was leaking the TraceListener then which caused a later
project to log to a previous project's dead TaskLoggingHelper.
On MSBuild core this is causing an error.
/cc @mellinoe @weshaggard
=> Detach GenFacadesTask trace listener

src/Microsoft.DotNet.Build.Tasks.Packaging/src/GenerateNuSpec.cs
The PathResolver class used in NuGetPack (https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks.Packaging/src/NuGetPack.cs#L154), takes into account the OS path directory separator character.  See https://github.com/NuGet/NuGet.Client/blob/c98de8b0635144fb89fd2853b802c03b79f46c2e/src/NuGet.Core/NuGet.Common/PathUtil/PathResolver.cs#L56.  We were previously specifying the manifest file target with '/', which would not get matched by the path resolver on Windows (it wouldn't resolve src content).  This caused us to fail here, https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks.Packaging/src/NuGetPack.cs#L187, and not produce symbols packages.
/cc @dagood @ericstj @ellismg
=> Enable windows symbols packages

src/Microsoft.DotNet.Build.Tasks/PackageFiles/PerfTesting.targets
The name of the xml results file created by xunit performance was
different than the file that we were checking andtrying to use.  I have
added the correct ID to resolve the name mismatch.
=> Fix naming issue with results file

Documentation/Samples/CloudTest.Helix.targets.sampleproject, src/Microsoft.DotNet.Build.CloudTestTasks/AzureHelper.cs, src/Microsoft.DotNet.Build.CloudTestTasks/Microsoft.DotNet.Build.CloudTestTasks.csproj, src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.Helix.targets, src/Microsoft.DotNet.Build.CloudTestTasks/RemoveItemMetadata.cs, src/Microsoft.DotNet.Build.CloudTestTasks/SendJobsToHelix.cs, src/Microsoft.DotNet.Build.CloudTestTasks/SendToHelix.cs, src/Microsoft.DotNet.Build.CloudTestTasks/ValidateWorkItems.cs, src/Microsoft.DotNet.Build.CloudTestTasks/WriteItemsToJson.cs
Enables sending to > 1 queue and per-workitem settings.
Repo-independent logic now lives in CloudTest.Helix.Targets.  When a repo is ready for this, they simply construct the required items and properties, and invoke the HelixCloudBuild target.
Stop by my office for a demo of what a project/builds file consuming this would look like (will prepare a sample for the repo as well, but need to strip secrets out of it first)
@wtgodbe @weshaggard @joperezr
=> First iteration of CloudTest.targets refactoring

src/Microsoft.DotNet.Build.Tasks.Packaging/src/ApplyMetaPackages.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
For some packages they are already referenced by the meta-package and for those we should
not convert them to having a reference to the meta-package as it will create a cycle. Instead
those still need to reference the individual packages.
cc @ericstj 
This fixes the current package cycle we have in System.Net.Http and System.Runtime.InteropServices.RuntimeInformation packages.
=> Don't convert to meta-package reference for packages that are part of the meta-package

src/Microsoft.DotNet.Build.Tasks.Packaging/src/NuGetPack.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
packages with symbols.
/cc @ericstj @ellismg 
Build an additional packed package by specifying `/p:CreatePackedPackage=true`
Add symbols to a standard package by specifying `/p:IncludeSymbolsInPackage=true`
=> Enable building packed packages (transport) and enable packing standard

src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Methods.cs, src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Properties.cs
Here is the diff when running on `System.Runtime.CompilerServices.Unsafe`:
```diff
--- D:\Temp\usnafe_compare\before.cs	2017-03-07 15:06:54.000000000 -0800
+++ D:\Temp\usnafe_compare\after.cs	2017-03-07 15:07:46.000000000 -0800
@@ -10,23 +10,23 @@
[assembly:System.Reflection.AssemblyTitleAttribute("System.Runtime.CompilerServices.Unsafe")]
[assembly:System.Runtime.CompilerServices.CompilationRelaxationsAttribute(8)]
[assembly:System.Runtime.CompilerServices.RuntimeCompatibilityAttribute(WrapNonExceptionThrows=true)]
namespace System.Runtime.CompilerServices {
public static partial class Unsafe {
[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)][System.Runtime.Versioning.NonVersionableAttribute]
-    public static T …
```
=> Add support for by-ref returns from methods and properties

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/DumplingHelper.py
This makes sure that `allFiles` is not an empty list before searching it. Fixes https://github.com/dotnet/buildtools/issues/1378
@danmosemsft
=> Windows Dumpling: Handle an empty crash dump folder.

src/ApiCompat.Desktop/ApiCompat.Desktop.csproj, src/ApiCompat.Desktop/App.config, src/ApiCompat.Desktop/project.json, src/BuildTools.sln, src/nuget/Microsoft.DotNet.BuildTools.ApiCompat.nuspec, src/nuget/Microsoft.DotNet.BuildTools.GenFacades.nuspec
The .NET Framework version of GenAPI is already packaged as
Microsoft.DotNet.BuildTools.GenAPI
This commit adds similar packages for API Compat and GenFacades.
@weshaggard
=> Build & package .NET Framework versions of API Compat and Gen Facades

src/nuget/Microsoft.DotNet.BuildTools.Cci.nuspec
There is currently now way to acquire CCI by itself; one can install the build tools package directly but this also installs a bunch of targets which regular projects most likely cannot use anyway.
@weshaggard
=> Provide a package for CCI + CCI Extensions

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.Helix.targets
Also gave it a more helix-specific name.  Write Test List JSON to log folder instead of current folder.
@mmitche
=> Allow user to set HelixCorrelationInfoFileName

src/nuget/Microsoft.DotNet.BuildTools.ApiCompat.nuspec, src/nuget/Microsoft.DotNet.BuildTools.Cci.nuspec, src/nuget/Microsoft.DotNet.BuildTools.GenAPI.nuspec, src/nuget/Microsoft.DotNet.BuildTools.GenFacades.nuspec, src/nuget/Microsoft.DotNet.BuildTools.RepoUtils.nuspec, src/nuget/Microsoft.DotNet.BuildTools.Run.nuspec, src/nuget/Microsoft.DotNet.BuildTools.TestSuite.nuspec, src/nuget/Microsoft.DotNet.BuildTools.VstsBuildsApi.nuspec, src/nuget/Microsoft.DotNet.BuildTools.nuspec, src/nuget/Microsoft.DotNet.VersionTools.nuspec, src/nuget/Microsoft.xunit.extensibility.execution.netcore.nuspec, src/nuget/Microsoft.xunit.netcore.extensions.nuspec, src/nuget/xunit.console.netcore.nuspec, src/nuget/xunit.runner.uwp.nuspec
Putting version.txt (containing the built commit hash) in the packages makes them traceable for automation and people. CoreFX is currently doing this for its packages (using the packaging targets rather than manual nuspecs).
We can use this file to update a checked-in bootstrap script in product repos. An auto-upgrader can take the commit hash from the BuildTools being consumed and download the bootstrap scripts from BuildTools at that hash. It would be better if it were checked into dotnet/versions, but this is an alternative. @MichaelSimons
This also allows the submodule updaters (https://github.com/dotnet/buildtools/pull/1324) to auto-update a BuildTools submodule based on successful builds, by setting BuildTools as an indicator package. @ellismg
=> Add version.txt to every BuildTools package root

src/Microsoft.DotNet.Build.Tasks.Packaging/src/HarvestPackage.cs
Previously we'd crash when a package included two files at the same path.  Now we'll log that and fail gracefully.
/cc @chcosta @weshaggard @lmolkova
=> Explicitly error on packages with clashing files

src/Microsoft.DotNet.Build.Tasks/PackageFiles/Roslyn.Common.props
Re: https://github.com/dotnet/coreclr/issues/10056
@weshaggard @joperezr 
This should unblock building with a VS2017 dev command prompt, but doesn't address the rest of the issues listed in https://github.com/dotnet/corefx/issues/17131
=> Explicitly define csharpcoretargetspath and visualbasiccoretargetspath

src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/PackageLibs.targets
Minor MSBuild syntax fix for accessing a metadata property. I discovered the issue while trying to get the Microsoft/visualfsharp build working on coreclr; some of the bootstrapping there is currently running via xbuild and mono, which is perhaps more strict about syntax checking.
=> Fix syntax for metadata access

src/Microsoft.DotNet.Build.Tasks.Packaging/src/ApplyMetaPackages.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
The condition added previously didn't work because it didn't populate
the trimmed item _ConsolidatedDependencies.
I fixed this by passing the property into the task similar to
ApplyBaseline.
I also added support for an item @(SuppressMetaPackage) that can be used
to suppress a specific meta-package by name.
=> Fix meta-package suppression

src/Microsoft.DotNet.Build.Tasks.Packaging/src/GetSupportedPackagesFromPackageReports.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/Microsoft.DotNet.Build.Tasks.Packaging.csproj, src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.common.targets, src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
This task reads supported framework targeting information from package
reports.
It lets us write tests that can generate project files targeting all of
the frameworks supported by a particular package.
I've also removed two of the validation RIDs that were incorrectly added
to netcoreapp1.1 but weren't actually supported until netcoreapp2.0.
=> Add task for getting supported frameworks

src/GenFacades/GenFacades.Core/GenFacades.cs
It seems that some compilers, like the managed C++ compiler, will emit a bunch of global methods and fields into assemblies. We are removing a lot of other assembly-level metadata from projects being rewritten with GenFacades, but not those. This change causes us to clear out the "<Module>" type, which will wipe out all of those extra global members.
@weshaggard
=> Remove all global fields and methods in GenFacades.

src/nuget/Microsoft.DotNet.VersionTools.nuspec
Make the NuGet package dependencies match the VersionTools project.json to avoid a mismatch trying to build downstream projects.
Hit in https://github.com/dotnet/dotnet-docker-nightly/pull/253#discussion_r108549418
=> Update VersionTools nuspec dependencies to match its project.json

src/Microsoft.DotNet.Build.Tasks/PackageFiles/optional-tool-runtime/optional.json
Bump the UAPTools version to 1.0.2 to use the updated runner.
/cc @weshaggard @MattGal
=> Bump the UAPTools version to 1.0.2

src/Microsoft.Cci.Extensions/Traversers/SimpleTypeMemberTraverser.cs
For namespaces that don't have anything but type forwards they get
skipped because the namespace gets filtered out. Since there are multiple
filters that could be used we can do the filtering of namespaces in
the traversals at the type level to handle this difference.
=> For pure facades type forwards get ignored

src/Microsoft.DotNet.Build.Tasks/PackageFiles/OptionalTooling.targets
cc: @weshaggard @dagood 
FYI: @AlexGhiondea 
Conditioning the optional.json path so that it can be overwritten in a specific repo. The reason for this is that we want to also restore TestILC from the private feed, but we need the version of the package to match the one from the ProjectN TargetingPack which means that this optional.json needs to live in corefx side.
=> Add Extensibility point to optional.json so that it can be overwritten in repos

src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageIndex.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/ValidatePackage.cs
Permit merging inbox assembly data.  I had missed this when I first added it.  We need this for WCF who will pick up that inbox info from corefx.
Fix the ValidatePackage inbox support algorithm to use the same logic as the inbox index model.  In doing so I found a bug in WCF packages that requires suppression.
/cc @MattGal @weshaggard
=> Inbox fixes

src/Microsoft.DotNet.Build.Tasks/PackageFiles/OptionalTooling.targets
FYI: @weshaggard 
I got the original condition for this wrong checking the incorrect variable. This will actually check if the optional.json path is already set.
=> Fix Condition on optional.json

src/Microsoft.DotNet.VersionTools/BuildInfo.cs
Fixes https://github.com/dotnet/buildtools/issues/1028.
It didn't have an effect on the clean machines used for auto-upgrade, but trying to change build info path branches as a dev is really confusing with this bug.
=> Fix BuildInfo cache collisions: use path, not name

src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj, src/Microsoft.DotNet.Build.Tasks/PackageFiles/Symbols.targets
This allows `CreateRequest.cmd` to examine the files locally on the build machine for symbol info. The server then replaces `PrefixToStrip` with `UNCPath` and uses that as the location of the files at rest. See https://github.com/dotnet/buildtools/pull/1333 for when these targets were added.
Also:
* Remove extra Symbols.targets include
* Fix unpredictable behavior if the extract dir is being reused by deleting the dir before trying to use it. This is useful for manual indexing scenarios using this tooling
* Add a few timestamped logs to make it easier to track how long each step of indexing takes
---
This significantly improves the speed of the CreateRequest step. I tested it out on a subset of CoreFX packages and got these results from my machine (similar network bottleneck as our build …
=> Use PrefixToStrip correctly for better symbol indexing performance

src/ApiCompat/Rules/Compat/CannotMakeMoreVisible.cs
fixes https://github.com/dotnet/buildtools/issues/1418
=> ApiCompat CannotMakeMoreVisible rule shouldn't differentiate between Familiy and FamilyOrAssembly

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.Helix.targets, src/Microsoft.DotNet.Build.CloudTestTasks/SendJobsToHelix.cs, src/Microsoft.DotNet.Build.CloudTestTasks/SendToHelix.cs
ApiAccessKey is now optional, and it's possible to set Creator and/or PullRequestId
=> Allow anonymous helix upload

src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh
There are some incompatibilities between GNU sed and the version included in macOS. It seems that passing `-i -e` accomplishes what we want to do here (simple find-and-replace) on all systems.
=> Use 'sed -i -e' for macOS compatibility

src/Microsoft.DotNet.Build.Tasks/PackageFiles/codeOptimization.targets
The end goal is to make IBCMerge's invocation more flexible so that it can be more directly applied in calling repositories:
* `/p:RestoreDefaultOptimizationDataPackage` can be set to false to avoid restoring the default project.json
* `/p:UsePartialNGENOptimization` can be set to false to avoid passing `-partialNGEN -minify`
* Add pre-pass to merge `*.ibc` into `*.dll` and rename the result to `*.pgo` (in case IBC data doesn't come pre-merged into the source IL assembly)
=> Add additional IBCMerge customization options

src/Microsoft.DotNet.Build.Tasks/PrereleaseResolveNuGetPackageAssets.cs
Instead of making the entire package path lower-case, we should only lower-case the part that NuGet changes (the package ID).
@ericstj
=> Fix casing issue in PrereleaseResolveNuGetPackageAssets.

src/Microsoft.DotNet.Build.Tasks/PackageFiles/codeOptimization.targets
This matches a change in CoreFX Tools-Override to restore the data package during Sync, not the build. The build's parallelization can cause this to be a race condition.
=> Move RestoreOptimizationDataPackage to Sync

src/GenAPI.Desktop/Microsoft.DotNet.BuildTools.GenAPI.targets
GenAPI.exe file name was wrong in Microsoft.DotNet.BuildTools.GenAPI.targets. 
And use the mono runtime to use .NETFramework 4.6 on linux.
Issue: https://github.com/dotnet/buildtools/issues/1437
=> Fix Microsoft.DotNet.BuildTools.GenAPI.targets for using on linux

src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageIndex.cs
When merging two PackageIndexes we should handle MetaPackages
This is needed if WCF wants to pick up our MetaPackages definition from
corefx for NETStandard.Library.
/cc @weshaggard @MattGal
=> Merge MetaPackages

src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageIndex.cs
When merging PackageIndexes we give precedence to the first index.
This allows a repo to define its own pre-release and baseline in the
case it happens to overlap with another.
We're hitting this for the first time after corefx has inbox-framework info
for all assemblies (including WCF).
=> Prefer original PreRelease & BaselineVersion

src/Microsoft.DotNet.Build.Tasks/PackageFiles/PerfTesting.targets
We did not have calls to measurement.py behind the LogToBenchview flag
and so when people would do local runs without the Benchview tooling
their runs would fail.  This should be fixed.  I also removed an out of
date comment.
=> Remove Benchview calls when not uploading

src/GenFacades/GenFacades.Console/Program.cs, src/GenFacades/GenFacades.Core/GenFacades.cs, src/Microsoft.DotNet.Build.Tasks/GenFacadesTask.cs, src/Microsoft.DotNet.Build.Tasks/PackageFiles/partialfacades.exe.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/partialfacades.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/partialfacades.task.targets
Adds a mode to GenFacades that starts with an assembly and replaces any
types present in the seeds with typeforwards.  Types not in the seeds
will remain in the assembly.
We'll use this for generating desktop reference facades.
To use this feature set IsPartialFacadeAssembly=true in a reference
project.
After the source is compiled GenFacades will examine all references and
replace any type def in the reference assembly that exists in the
references.
To keep a type in the reference assembly even if it exists in a
reference create an item in the reference project as follows:
```
<SeedTypePreference Include="namespace.type">
<Assembly>assemblyName</Assembly>
</SeedTypePreference>
```
/cc @mellinoe @weshaggard
=> Enable build of partial reference facades

src/GenFacades/GenFacades.Core/GenFacades.Core.csproj, src/GenFacades/GenFacades.Core/GenFacades.cs, src/GenFacades/GenFacades.Core/TypeReferenceRewriter.cs
When creating a partial reference facade we remove types from the
assembly and replace them with typeforwards.
For the types that are left in the reference facade we need to make sure
they refer to the forwarded types rather than local type defs.
=> Rewrite type refs in partial reference facades

src/GenAPI/Program.cs
In case of using XXX.System namespace, types in System namespace of BCL can not be referenced at compilation time due to namespace conflicts. 
For example, 
```
namespace MyLib.System {
public static partial class MyClass {
public static bool IsChecked { get { throw new Systm.PlatformNotSupportedException(); } }
...
}
}
```
at compilation time, Systm.PlatformNotSupportedException can not be found.
To avoid these conflicts, the -global option is needed to explicitly include the global prefix in every types.
=> Add -global option to GenAPI for including global prefix

src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Attributes.cs, src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Types.cs
GenAPI adds incorrect "global" prefix when the parameter of Attribute is not type name.
When using -global option to include "global::" prefix in types, following code can not be built with the generated source code. 
```
using System.Runtime.InteropServices;
namespace Test {
[StructLayout(LayoutKind.Sequential, Size=4)]
public struct MyStruct {
public int X {get; set;}
}
}
```
Because Microsoft.Cci.Extensions adds global prefix to every parameter of StructLayout.
Generated code:
```
namespace Test
{
[global::System.Runtime.InteropServices.StructLayoutAttribute(global::System.Runtime.InteropServices.LayoutKind.Sequential, global::Size=4)]
public partial struct MyStruct
{
public int X { [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]get { throw null; } …
```
=> Fix incorrect including global prefix for Attribute

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.Helix.targets
The JSON blobs here that get uploaded can be sent, with nothing more than an auth token in the header, to the Helix API;  this allows requeuing jobs for experimentation or other fun.
@smile21prc  this will allow you to send existing portable linux jobs to new queues for test with minimal effort.
=> Upload job start json messages; very useful for resending work.

src/Microsoft.DotNet.Build.Tasks.Packaging/src/Microsoft.DotNet.Build.Tasks.Packaging.csproj, src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.common.targets, src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets, src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageIndex.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/ValidateFrameworkPackage.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/ValidatePackage.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/ValidationTask.cs
This adds a task that will run on framework packages and ensure the
package content is consistent with the package index.
I've also taken the opportunity to add some special cases for
IsFrameworkPackage to remove those from the CoreFx targets.
CoreFx changes: https://github.com/ericstj/corefx/commit/ce4d47b43ff6c44ecc3f1c55e0d53e7b69cf90e4
=> Add framework package inbox validation

src/GenAPI/Program.cs, src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Methods.cs, src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.cs, src/Microsoft.Cci.Extensions/Writers/CSharp/CSharpWriter.cs, src/Microsoft.DotNet.Build.Tasks/PackageFiles/notsupported.targets
Resolves https://github.com/dotnet/buildtools/issues/1449. Enables assemblies that set `<GeneratePlatformNotSupportedAssembly>` to pass in an extra optional property to set a custom message for PlatformNotSupportedException like the following:
`<GeneratePlatformNotSupportedAssembly_Message>Operations with CNG keys are only supported on Windows platforms.</GeneratePlatformNotSupportedAssembly_Message>`
cc: @ericstj @weshaggard @danmosemsft
=> Add custom PNSE message to GenAPI

src/Microsoft.DotNet.Build.Tasks.Packaging/src/GetSupportedPackagesFromPackageReports.cs
I'm transitioning the package test infrastructure to CLI and need the short TFM
=> Expose short TFM when examining supported fxs

src/Microsoft.DotNet.Build.Tasks.Packaging/src.Desktop/Microsoft.DotNet.Build.Tasks.Packaging.Desktop.csproj, src/Microsoft.DotNet.Build.Tasks.Packaging/src/Microsoft.DotNet.Build.Tasks.Packaging.csproj, src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.common.targets, src/Microsoft.DotNet.Build.Tasks.Packaging/src/VerifyClosure.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/VerifyTypes.cs
Adds a task which accepts a set of files and flags duplicate public
types in that set.
=> Add VerifyTypes task to catch duplicate types

src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Fields.cs
In case of using "const enum type field" with initialzation, the constant value
is assigned to the const enum field without casting in the generated code from GenAPI
For example, When using const enum field with initialization as follows:
```
using System;
namespace MyTest
{
public class MyClass
{
public const MyEnum ConstEnum1 = MyEnum.A;
}
public enum MyEnum
{
A = 1,
B = 2,
}
}
```
GenAPI generates following source code:
```
namespace MyTest
{
public partial class MyClass
{
public const MyTest.MyEnum ConstEnum1 = 1;
public MyClass() { }
}
public enum MyEnum
{
A = 1,
B = 2,
}
}
```
"MyEnum.A" is converted to a constant value "1", but this constant value can not be assigned to "Enum" type variable without casting.
In CSDeclarationWriter::WriteFieldDefinition() of Cci.Extensions, the …
=> Add casting statement on assignment for const Enum type

src/Microsoft.Cci.Extensions/Writers/CSharp/CSharpWriter.cs
If a class is declared without a namespace, 
```
public class MyTest {
}
```
GenAPI generates following incorrect code. 
```
namespace 
{
public partial class MyTest
{
public MyTest() { }
}
}
```
If a type is declared without a namespace, the namespace block shouldn't be created.
=> Fix incorrect generation of GenAPI when ns is not declared

src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Methods.cs
This should fix errors in https://github.com/dotnet/corefx/pull/19506. When using resource strings as the message for auto-generated PNSE, few projects like the following hit `The name 'SR' does not exist in the current context` errors, as the `System` namespace is missing:
- Microsoft.Win32.Registry
- Microsoft.Win32.Registry.AccessControl
- System.Security.Cryptography.Cng (In some configurations contains APIs from Microsoft.Win32.SafeHandles)
cc: @ericstj @danmosemsft
=> Add System namespace to PNSE Message in GenAPI

src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.csproj
Working around https://github.com/dotnet/sdk/issues/1198
/cc @weshaggard @eerhardt @mellinoe
=> Set output type on tool-runtime project

src/Microsoft.DotNet.Build.Tasks/PackageFiles/packageresolve.targets
If a csproj has P2P references, this property needs to be passed for the PrereleaseResolveNugetPackageAssets to work. It just happens that none of our projects in corefx/standard have P2P references, so we've never hit it. core-setup has a project where we need this.
@weshaggard
=> Pass ProjectReferencesCreatingPackages to resolve task

src/Microsoft.DotNet.Build.Tasks/PackageFiles/packageresolve.targets
This allows you to control arbitrary project properties on the projects you are restoring. This is useful when you want to set things outside of the usual `TargetFramework`, `RuntimeIdentifier` properties, like the `BaseOutputPath`, etc.
=> Allow additional parameters to be passed to restore command

src/Microsoft.DotNet.Build.Tasks/PackageFiles/crossgen.sh
Instead of hard-coding the shared framework version in crossgen.sh, we will now automatically detect it based on the folders present under shared/Microsoft.NETCore.App/. The CoreCLR version is still hard-coded, but I don't see an easy way to fix that with just the information present in the shared framework.
=> Automatically detect shared fx version in crossgen.sh

src/Microsoft.DotNet.Build.Tasks/CleanupVSTSAgent.cs
Path.GetPathRoot doesn't parse ~/.local/share/NuGet correctly. So use
absolute path /home/DDITAdministrator/.local/share/NuGet instead.
=> Use absolutepath because a limitation in Path.GetPathRoot

src/Microsoft.DotNet.Build.CloudTestTasks/DownloadFromAzure.cs, src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/PublishContent.targets, src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/SyncCloudContent.targets
This gets us into a place were we can start using the same
container with just different blob paths moving forward
cc @dagood @MattGal 
After this change we can start to move our build definitions to use the same container and just a different path.
=> Add blob prefix support to our download and upload tasks/targets

src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.props, src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets
Splits out the properties used by `dotnet build` for stamping assembly info.  This permits us to use the same values for assemblies that are producing using msbuild (import versioning.targets), or `dotnet build`.
This change is required for https://github.com/dotnet/core-setup/pull/2331/files
/cc @eerhardt @weshaggard
=> Specify versioning.props properties for assembly info

src/xunit.netcore.extensions/Attributes/ActiveIssueAttribute.cs, src/xunit.netcore.extensions/Discoverers/ActiveIssueDiscoverer.cs, src/xunit.netcore.extensions/TargetFrameworkMonikers.cs
With the desktop test effort we started disabling tests with an active issue on github by doing: 
```cs
[SkipOnTargetFramework(TagetFrameworkMonikers.NetFramework, "dotnet/corefx #issue")]
```
When that is not the intended usage of this attribute. We want to use this attribute when the test is specific to another framework or an intended difference on behavior. 
With this PR we allow to use `[ActiveIssue(1234, TargetFrameworkMonikers.NetFramework)]` in example to disable a test that has an issue open tracking the failure only on desktop, or if we find a failure only on uap or netcoreapp disable the test through ActiveIssueAttribute only for that target framework.
cc: @weshaggard @danmosemsft 
FYI: @stephentoub
=> Enable to pass a TargetFrameworkMoniker to ActiveIssueAttribute

src/xunit.netcore.extensions/TargetFrameworkMonikers.cs
When I did the refactoring for TFM incorrectly refactored NetcoreUWP (which included both Uap and UapAot) to be Uap only. https://github.com/dotnet/buildtools/pull/1355
cc: @danmosemsft @weshaggard
=> Fix Uap TFM to include Aot

src/Microsoft.DotNet.Build.Tasks/PackageFiles/msbuild.sh
I bump into it while trying to pass multiple arguments to xunit:
/Tools/msbuild.sh ~/git/corefx/src/System.Net.Security/tests/FunctionalTests/System.Net.Security.Tests.csproj /t:build,test /p:xunitoptions='-showprogress -method System.Net.Security.Tests.SslStreamEKUTest.SslStream_NoEKUClientAuth_O'
Microsoft (R) Build Engine version 15.1.523.56541
Copyright (C) Microsoft Corporation. All rights reserved.
MSBUILD : error MSB1001: Unknown switch.
Switch: -method
For switch syntax, type "MSBuild /help"
The problem lives in msbuild.sh (I verified that by starting dotnet directly)
The script incorrectly uses $* to expand passed parameters and that will break if passed argument contains spaces. $@ and $* are almost similar any they work same way in most cases, but not in this one. As outlined …
=> change $* to "$@" to properly process arguments with spaces on Unix

src/Microsoft.DotNet.Build.Tasks/UpdateVSConfigurations.cs
Previously we were failing a call to First, guard this and default
to inserting properties at the start of the project.
=> Make UpdateVSConfigurations handle project with no imports

src/xunit.netcore.extensions.46/xunit.netcore.extensions.net46.csproj, src/xunit.netcore.extensions/SkippedTestCase.cs
This is needed because xunit creates different AppDomains, so if it not serializable when the condition in ConditionalFact/Theory attributes is not met the test will be marked as not discovered instead of skipped. So the test summary will not be correct and we will never catch when the tests are skipped for desktop.
=> Mark SkippedTestCase as serializable for Full Framework

src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
If you don't statically evaluate TargetOSTrait then we don't correctly
filter Xunit tests in VS via the default test runs parameters we have.
Should address https://github.com/dotnet/corefx/issues/18469.
=> Statically evaulate TargetOSTrait

src/Microsoft.DotNet.Build.Tasks/PackageFiles/msbuild.sh
This reverts commit 2ec1ba86095671f13ddac5574ea5ba2a66d846fe.
Although this hasn't caused any problems in local builds, we are seeing some problems in our official builds, involving arguments being dropped from subsequent commands. We're not sure why exactly, it most likely has something to do with complicated quote escaping.
@MattGal @wfurt
=> Revert "change $* to "$@" to properly process arguments with spaces"

src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Methods.cs
Move writing of attributes before the method.IsDestructor() check.
=> GenAPI: Destructors can have attributes too

src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Properties.cs
Like it's done e.g. for methods: https://github.com/mono/buildtools/blob/14a12e45dd954bfd6e98aecc366e8742aeaa6590/src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Methods.cs#L32
=> GenAPI: Write security attributes in property accessors too

src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj, src/Microsoft.DotNet.Build.Tasks/PackageFiles/Symbols.targets, src/Microsoft.DotNet.Build.Tasks/ZipFileExtractToDirectory.cs, src/Microsoft.DotNet.Build.Tasks/ZipFileGetEntries.cs, src/Microsoft.DotNet.Build.Tasks/ZipFileInjectFile.cs
Adds targets and new utility tasks to create signed catalog files and inject them into symbol packages for upload to MyGet. Uses `makecat` to create the catalogs and MicroBuild to sign them.
1. Reads the entries in the symbol package zips
2. Finds ones that have an extension we want to sign
3. Extracts those entries into an intermediate directory
4. Creates one catalog file per package
5. Signs the catalog files
6. Injects the signed catalog files
7. Injects a list of cataloged files into each symbol package (for EmbedIndex)
The first commit is from when we were going to have one catalog file per signed file for simplicity, but that ended up being extremely slow: ~1 hour (which would be part of the package publish leg). A single catalog per package takes ~5 minutes total.
I don't like the …
=> Add symbol signing targets

src/xunit.runner.uap/RunnerRemoteExecutionServiceUAP/RunnerRemoteExecutionServiceUAP.cs
Currently the remote execution returning 0 as success code but in corefx repo we use the value 42 as the success code. changing the success code to 42 so corefx tests work seamlessly with the uap runner
=> Fix the success code returned from remote execution

src/Microsoft.DotNet.Build.Tasks/PackageFiles/Symbols.targets
MakeCat apparently does not handle duplicate keys well even though we are supposed to be using the `<HASH>` as the key.  This change makes us use the full file path for the key so there are no duplicates.
=> Fix duplicate file keys when creating catalogs.

src/Microsoft.DotNet.Build.Tasks/PackageFiles/crossgen.sh, src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd, src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.ps1, src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh
Two major changes here:
- Stop publishing the tool runtime standalone.
- Clean up crossgen.sh to pull crossgen from the Microsoft.NETCore.App package, using the version that matches whatever is in the shared folder of the dotnet cli we're using.
I hit these issues while locally tying to move the version of the CLI that CoreFX uses forward to a preview2 build, which lead to these changes.
=> Tool runtime improvements

src/Microsoft.DotNet.Build.CloudTestTasks/AzureBlobLease.cs, src/Microsoft.DotNet.Build.CloudTestTasks/AzureHelper.cs, src/Microsoft.DotNet.Build.CloudTestTasks/CopyAzureBlobToBlob.cs, src/Microsoft.DotNet.Build.CloudTestTasks/CreateAzureContainer.cs, src/Microsoft.DotNet.Build.CloudTestTasks/DeleteAzureBlob.cs, src/Microsoft.DotNet.Build.CloudTestTasks/DownloadFromAzure.cs, src/Microsoft.DotNet.Build.CloudTestTasks/ListAzureBlobs.cs, src/Microsoft.DotNet.Build.CloudTestTasks/ListAzureContainers.cs, src/Microsoft.DotNet.Build.CloudTestTasks/Microsoft.DotNet.Build.CloudTestTasks.csproj, src/Microsoft.DotNet.Build.CloudTestTasks/PublishStringToAzureBlob.cs, src/Microsoft.DotNet.Build.CloudTestTasks/UploadClient.cs, src/Microsoft.DotNet.Build.CloudTestTasks/UploadToAzure.cs, src/Microsoft.DotNet.Build.Tasks/GenerateChecksums.cs, src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj
This change is moving the tasks from https://github.com/dotnet/core-setup/tree/master/tools-local/Microsoft.DotNet.Build.Tasks.Local into BuildTools.  
The files which are modified (not new additions), *should* be non-breaking in repos which utilize these tasks though I will have to make some small modifications to core-setup when I update that repo to consume these changes.
https://github.com/dotnet/core-setup/blob/master/tools-local/Microsoft.DotNet.Build.Tasks.Local/DownloadBlobFromAzure.cs and https://github.com/dotnet/core-setup/blob/master/tools-local/Microsoft.DotNet.Build.Tasks.Local/DownloadBlobsFromAzure.cs have been collapsed into the DownloadFromAzure task.  I've validated previous behavior for DownloadFromAzure task in CoreFx repo.
I'm not porting …
=> Move core-setup tasks into BuildTools

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/Dumpling.targets, src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/DumplingHelper.py
* Don't use "install --full" on OSX because it crashes.
* Use `/cores/` as the default dump path on OSX.
=> Two minor fixes in OSX Dumpling integration.

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/DumplingHelper.py
This variable is actually a string passed from the command line. it needs to be an actual integer to be used in the way that we want.
=> Fix exit code handling in DumplingHelper.py

src/Microsoft.DotNet.Build.Tasks.Packaging/src/GetLastStablePackage.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/test/GetLastStablePackageTests.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/test/Microsoft.DotNet.Build.Tasks.Packaging.Tests.csproj, src/Microsoft.DotNet.Build.Tasks.Packaging/test/packageIndex.json
Fixes #1529
/cc @weshaggard 
We'll need this in order to correctly harvest packages once moving to stable.
=> Ensure we get correct last stable version when building stable

src/Microsoft.DotNet.Build.Tasks/CleanupVSTSAgent.cs
but attempt to kill it before the timeout elapses to prevent leaked processes.
=> Add back Robocopy cleanup 

src/Microsoft.DotNet.Build.Tasks/PackageFiles/optional-tool-runtime/optional.json
I've created a package for the bininspect tool and uploaded it to our optional tooling feed. This change just adds the package to the optional tool runtime so that it can be consumed via BuildTools mechanisms in the Core-Setup build.  
I'll be making a change to this PR, https://github.com/dotnet/core-setup/pull/2561, to use BinInspector via the package feed instead of a separate azure storage download.
I made a couple minor edits to the documentation as some of the property name / values have changed - https://github.com/dotnet/core-eng/blob/master/Documentation/Project-Docs/fetch-internal-tooling.md
=> Add bininspect package to optional tooling

src/Microsoft.DotNet.Build.Tasks/ExecWithRetries.cs, src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj, src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/PublishProduct.targets
This is the workaround for https://github.com/dotnet/core-eng/issues/434.
When running `nuget.exe push foo\*.nupkg -Timeout 3600`, like we do in official build publish legs, if any HTTP call hangs, the entire push times out and the build fails. With this target, each package has a timeout, so a single HTTP hang will not fail the build.
It's preferable in general to use `Exec` to run commands, but here I used `Process` because doing the retry logic in MSBuild isn't reasonable.
An alternative to `Process` is to call into the NuGet methods directly from the task. I think it's better to keep the BuildTools NuGet package version separate, because we can be sure we're using what other MyGet customers are using and can be more flexible when asked to upgrade NuGet.exe as a potential way to fix a …
=> Add NuGetPush task/target with retry logic that handles hangs

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/DumplingHelper.py
`dumpling install --full` has proven to be pretty unreliable. I'm not longer using it here. Additionally, installation errors of any sort (internet connection problems, timeouts, etc) are ignored. Things should just "move along" if dumpling fails to work for whatever reason. We don't want spurious failures because this script couldn't download some file or upload some blob to Azure.
=> Don't use "install --full" in DumplingHelper. Ignore install errors.

src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd
=> Use "-NoProfile -ExecutionPolicy unrestricted" in call to init-tools.ps1

src/nuget/Microsoft.xunit.extensibility.execution.netcore.nuspec
Copy license and project urls from `Microsoft.xunit.netcore.extensions.nuspec` to `Microsoft.xunit.extensibility.execution.netcore.nuspec`. This should avoid some confusion when seeing the package without context.
@brianrob @karajas
=> Change Microsoft.xunit.extensibility.execution.netcore redist package links to BuildTools ones

src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd
Follows the error-handling pattern that other calls use.
@weshaggard
=> Check exit code of call to init-tools.ps1.

src/Microsoft.DotNet.Build.Tasks/PackageFiles/Symbols.targets
- Filter out known empty files (_.pdb, etc) as makecat doesn't handle these.
- Disable page hashing as it causes an error on DLLs that don't look like standard Windows DLLs.
=> Minor fixes for symbol signing.

src/Microsoft.DotNet.Build.CloudTestTasks/DownloadFromAzure.cs
Fixes 
```
2017-06-14T13:39:20.2232748Z E:\A\_work\416\s\Tools\SyncCloudContent.targets(25,5): error : startIndex cannot be larger than length of string. [E:\A\_work\416\s\src\syncAzure.proj]
2017-06-14T13:39:20.2232748Z E:\A\_work\416\s\Tools\SyncCloudContent.targets(25,5): error : Parameter name: startIndex [E:\A\_work\416\s\src\syncAzure.proj]
2017-06-14T13:39:20.2232748Z E:\A\_work\416\s\Tools\SyncCloudContent.targets(25,5): error :    at System.String.Substring(Int32 startIndex, Int32 length) [E:\A\_work\416\s\src\syncAzure.proj]
2017-06-14T13:39:20.2232748Z E:\A\_work\416\s\Tools\SyncCloudContent.targets(25,5): error :    at System.String.Substring(Int32 startIndex) [E:\A\_work\416\s\src\syncAzure.proj]
2017-06-14T13:39:20.2232748Z …
```
=> Trim only directory part of blobnameprefix when deriving local download directory

src/xunit.runner.uap/MainPage.xaml, src/xunit.runner.uap/MainPage.xaml.cs
When there is a lot of failures and we try to dump everything to the UI it slows the test execution and it crashes it so we get no testResults.xml
With this change we will see the output in the console at the end of the execution which is usually fast without the UI logging. 
cc: @danmosemsft @tarekgh @joperezr
=> Disable UI Logging in Xunit.Runner.Uap to avoid crashes when the log is super long

src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.csproj
@mellinoe @ellismg @danmosemsft PTAL
While investigating why init-tools takes 15-20mins on a fresh CI machine I found that we restored a lot of runtime specific packages that we never actually use. We never publish for a given RID after https://github.com/dotnet/buildtools/pull/1536 so we can remove these RuntimeIdentifiers and reduce the cost of this restore by a lot (my local tests go from 12 mins to 1 min on a machine with no packages already).
=> Remove unnecessary RuntimeIdentifiers from tool-runtime project

src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
cc: @danmosemsft @safern @tijoytom
=> Adding option to enable  using shared assemblies for multi-file tests

src/xunit.netcore.extensions/Discoverers/ActiveIssueDiscoverer.cs, src/xunit.netcore.extensions/Discoverers/SkipOnTargetFrameworkDiscoverer.cs, src/xunit.netcore.extensions/TargetFrameworkMonikers.cs
three problems to solve:
1) Making this work ` [SkipOnTargetFramework(~TargetFrameworkMonikers.UapAot)]`
- `SkipOnTargetFrameworkDiscoverer` determines the test has traits `nonXXXXtests` where XXX is every TFM for which `(~TargetFrameworkMonikers.UapAot).HasFlag(TFM)` is true.
- Because `TFM.Uap = TFM.UapAot | 0x2000`, this is NOT true for TFM.Uap (the negated mask of UapAot does not HasFlag of TFM.Uap because it's missing the UapAot bit out of TFM.Uap). So this test is determined to have all nonXXXtests traits except `nonUapaottests` and `nonUaptests`.
- When running tests, `tests.targets` passes `-notrait nonTARGETGROUPtests` to xunit. In the case of a UAP test run, this would be `-notrait nonuaptests`. This does not exclude the test marked with the attribute above, because the test is …
=> add UapNotUapAot to TFM enum

src/Microsoft.DotNet.CodeAnalysis/PackageFiles/codeAnalysis.targets
This is the reason /t:build is not skipping anymore.
=> Fix build incrementality bug

src/Microsoft.DotNet.Build.Tasks/CleanupVSTSAgent.cs, src/Microsoft.DotNet.Build.Tasks/PackageFiles/scripts/vstsagent/cleanupagent.proj
Change file / folder permissions if possible on Unix platforms so that we don't hit "Permission Denied" errors when trying to delete a folder.
Generalize the "additional cleanup directories" concept so it's slightly more extensible and has less hard-coded special knowledge for the temp folders (though still maintain an internal set of known temp locations).
This change is desired so that I can move corefx to use the `docker run with a volume` model which runs each docker command in a new container but using the same mounted volume.  The issue with this method is that it creates artifacts within the docker container with a different file permission set that doesn't allow the cleanup agent task (which runs outside of a docker container) to delete them.  I could specifically add a 'chmod' …
=> Fix Unix folder permissions for deleting

src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
cc: @weshaggard @ericstj 
FYI: @zamont 
This change is required by the upcoming change that will go into corefx where we will be changing the uap moniker for vnext.
=> Change uap10.1 moniker so that the version can be defined by each repo

src/Microsoft.DotNet.Build.Tasks/PackageFiles/Symbols.targets
This adds an additional line with `<Filename>ATTR1=0x11010001:Filename:<Filename>`.
0x11010001 = signed, do not replicate to compatibility entries (we don't use these), plaintext, name-value pair
=> Add signed filename attribute to symbol files.

src/Microsoft.DotNet.Build.Tasks/PackageFiles/Symbols.targets
This makes sure we always have our catalogs in a path MicroBuild is willing to sign.
=> Always overwrite IntermediateOutputPath when signing catalogs.

dependencies.props, src/Microsoft.DotNet.Build.Tasks.net45/Microsoft.DotNet.Build.Tasks.net45.csproj, src/Microsoft.DotNet.Build.Tasks.net45/project.json, src/Microsoft.DotNet.Build.Tasks/ConvertPdbsToPortablePdbs.cs, src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj, src/Microsoft.DotNet.Build.Tasks/PackageFiles/Symbols.targets, src/Microsoft.DotNet.Build.Tasks/project.json
Adds a task and target that are used in the archive process to generate and then publish Windows PDBs for each Portable PDB. I've verified this locally, and I'm working on verifying it with a fake full symbol publish build def now.
I've already mirrored `Microsoft.DiaSymReader.Converter` and `Microsoft.DiaSymReader.Native` on the dotnet-buildtools feed.
There's a workaround in `Microsoft.DotNet.Build.Tasks.net45.csproj` to use `PrereleaseResolveNuGetPackageAssets` to grab the x86 natives. Without it, only the x64 natives end up in the buildtools package, but we run with x86 msbuild. I didn't want to just switch the project to x86 in case there's a compatibility reason for it being x64 now.
Currently I chose not to support this task on .NET Core. The task does compile and ship on Core, and …
=> Convert Portable to Windows PDBs during symbol archive targets

src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/resources.targets
Contributes to: https://github.com/dotnet/corefx/issues/21692
This is needed as MakePri.exe doesn't support .resx files. Also they have to be called as the assembly so that when we create the .pri file the resources are mapped correctly.
cc: @tarekgh @weshaggard @joperezr
=> Copy resx files in resources.targets to AssemblyName.resw file

src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.props, src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets
Previously we had the commit ID in the file version information.  However we have
several Repos so this is needlessly ambigous.  Add the full url.   Now when you do a
filever -v you get something like ths
ProductVersion   4.6.25511.0 built by: vancem-VANCEM1. SrcCode: https://github.com/dotnet/coreclr/tree/de5f92822dbac17160da9e796e21918d2b812e38
Which unambiguously identifies vi the source code.  
@ericstj @dagood  
I have tested this by getting the coreclr repo to use the new build tools and seen that it 
produces the above URL.
=> Add Full GIT URL to version info.

src/Microsoft.DotNet.CodeAnalysis/PackageFiles/PinvokeAnalyzer_Win32UWPApis.txt
1. Remove kernel32.dll!OpenProcessToken since it caused problems to
DllImport using advapi32.dll
2. Add shell32.dll!SHGetKnownFolderPath that per conversation is already
being tracked to be added UAP (it will allow complete deletion of custom whitelists for src/System.Runtime.Extensions)
=> two updates to pinvoke whitelist

src/Microsoft.DotNet.CodeAnalysis/PackageFiles/PinvokeAnalyzer_Win32UWPApis.txt, src/xunit.runner.uap/UpdateScript/AppxManifest_master.xml
Eventually I will enable this API on UWP when I get a RS3 prerelease with it. This change is preparation for when that happens.
=> Preparing for serial ports in UAP

src/Microsoft.DotNet.CodeAnalysis/PackageFiles/PinvokeAnalyzer_Win32UWPApis.txt
Moving CheckTokenMembershipEx to kernel32.dll per https://github.com/dotnet/corefx/issues/22128 /cc @CIPop - after a new nuget is published with this change we can make the change on corefx.
=> move CheckTokenMembershipEx to kernel32.dll

src/Microsoft.DotNet.Build.Tasks/ExecWithRetriesForNuGetPush.cs, src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj, src/Microsoft.DotNet.Build.Tasks/PackageFiles/PublishProduct.targets
Fixes https://github.com/dotnet/core-eng/issues/1375
There's a very special failure scenario that we want to ignore.  That scenario is when NuGet hits a timeout on one "push" attempt, and then gets a "Forbidden" response because the package "already exists" on the next response.  This indicates that the timeout occurred, but the push was actually successful. 
To address the condition, I'm implementing a special "IgnoredErrorMessagesWithConditional" property that allows you to specify error messages which you want to ignore.  If you specify the "ConditionalErrorMessage" metadata on the Item, then the error message is only ignored if the "conditional" error message was detected in a previous (or current) Exec attempt.
It's a bit of an odd feature, but it causes enough failures in our …
=> Enable ignore condition for timeout followed by forbidden 

src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
@ericstj As we discussed, this entry has been removed from the RID graph in netcoreapp2.0.
=> Remove alpine from the list of validate RIDs for netcoreapp2.0.

src/Microsoft.DotNet.Build.Tasks/ExecWithRetries.cs, src/Microsoft.DotNet.Build.Tasks/PackageFiles/Symbols.targets
See https://github.com/dotnet/core-eng/issues/1273
This works around a `System.AccessViolationException` that can happen inside `Microsoft.DiaSymReader.ISymUnmanagedWriter5.Close()`:
```
Converting portable PDB '[...]System.Private.Xml.dll'...
##[error]Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
at Microsoft.DiaSymReader.ISymUnmanagedWriter5.Close()
at Microsoft.DiaSymReader.SymUnmanagedWriter.WriteTo(Stream stream)
at Microsoft.DiaSymReader.Tools.PdbConverter.ConvertPortableToWindows(PEReader peReader, MetadataReader pdbReader, Stream targetPdbStream, PdbConversionOptions options)
at Microsoft.DiaSymReader.Tools.PdbConverter.ConvertPortableToWindows(PEReader peReader, Stream …
```
=> Retry PDB conversion in a new msbuild process

src/xunit.netcore.extensions/Discoverers/ConditionalTestDiscoverer.cs
Conditional Fact and Theory in our xunit filtering is always used types from the test assembly that currently running. We are working on moving PlatformDetection code to CoreFx.Private.TestUtilities assembly as it is naturally fit there and avoid including the cs files in every test project need to use it. We have many tests using Conditional Fact/Theory which calls PlatformDetection methods. The way we apply this filtering is we create the PlatformDetection type from the running test assembly. After we move PlatformDetection to CoreFx.Private.TestUtilities, this mechanism will not work. To make it work, we adding the way to allow specify the assembly containing the type through providing the qualified type name which include the assembly name.
=> Enable XUnit conditional filtering uses other assemblies

src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.props, src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets
In PR #1606 we added logic so that the version resource had not just the GIT commit ID
but also the full Github URL.   This worked well for native code but it turns out that
It did not work for managed code.
This was mostly because for managed code the variables needed to be 'exported' explicitly to a *.props
file so that another instance of MSBUILD would pick it up.   There was already a variable that had this
behavior called BuiltByString, and so this fix is to simply put the additional information for the GIT commit
ID into this variable (which would then be attached appropriately).
While I was at it I change the syntax a bit to make it more friendly to maching parsing.   key-value pairs
now always begin with an @ and are separted by spaces (e.g.  @BuiltBy: vancem @SrcCode: …
=> Enable CoreFX build to tag DLLs with GITHub URL

src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.csproj
Resolves https://github.com/dotnet/buildtools/issues/1617
Gets fresh coreclr builds working again if you've installed 2.1.0 preview; else its very broken
Not sure if it will break 2.0.0 builds?
/cc @weshaggard @mellinoe @ellismg @danmosemsft PTAL
=> Remove deprecated PackageTargetFallback

src/Microsoft.DotNet.Build.Tasks/ExtractResWResourcesFromAssemblies.cs, src/Microsoft.DotNet.Build.Tasks/GenerateResourcesCode.cs, src/Microsoft.DotNet.Build.Tasks/Helper.cs, src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj, src/Microsoft.DotNet.Build.Tasks/PackageFiles/resources.targets
As we generate cs code for accessing the embedded resources. The generated type will be named as FxResources.AsemblyName.SR. if the AssemblyName has characters not allowed in the namespace names (e.g. dashes), this will cause compilation errors. The fix here is we normalize the assembly name before we use it.
=> Allow generate resources with assembly name has dashes

src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.csproj
/cc @mellinoe @weshaggard 
See https://github.com/dotnet/corefx/pull/23513#issuecomment-324726971
=> Tool-runtime should use MS.NETCore.App version built into CLI

src/Microsoft.DotNet.Build.Tasks/ExtractResWResourcesFromAssemblies.cs
This is necessary so that the AssemblyResolver unifies dependencies.
/cc @safern @weshaggard
=> Make ExtractResWResourcesFromAssemblies derive from BuildTask

src/Microsoft.DotNet.Build.Tasks/PackageFiles/Roslyn.Common.props, src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd
Previously f99e5ef88ac3e6b909676619a309147283f7c241 updated the roslyn package restored
by the tool-runtime to 2.0.0-rc4 but missed updating these two other places.
The result was that the new compiler was used on core but not desktop-MSBuild.
This change completes the update.
/cc @weshaggard @benaadams
=> Complete roslyn update to 2.0.0-rc4

src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.props
When using BuildTools in a repo like core-setup, where we want to use the dotnet-cli to build managed projects, we need to be able to not use the Roslyn properties that come in BuildTools.
For example, setting `<RoslynTargetsPath>$(ToolRuntimePath)</RoslynTargetsPath>` breaks any SDK project using the dotnet-cli.
=> Allow projects to disable the Roslyn in BuildTools.

src/Microsoft.DotNet.Build.Tasks/GenerateResourcesCode.cs, src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj, src/Microsoft.DotNet.Build.Tasks/NormalizeAssemblyName.cs, src/Microsoft.DotNet.Build.Tasks/PackageFiles/resources.targets
We used to generate the normalized assembly name in the target GenerateResourcesSource and we override the resw name of the resource file there too. In the incremental build the target GenerateResourcesSource will get skipped but overriding the resw item name still be done as it is used outside the target in other places. This will cause the normalized name property not initialized but it is used in setting the resw name. and that will cause a race condition because many projects will try to access the exact same resw file name while building.
The fix is to move the assembly name normalization outside GenerateResourcesSource so we’ll be sure we always initialize the normalized assembly name property.
Fixes #23618
=> Fix race condition because of assembly name normalization

src/Microsoft.DotNet.Build.Tasks.Packaging/src/ValidatePackage.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/ValidationTask.cs
This allows us to opt out of using placeholders to model inbox state on a given framework.
=> Add an override so that packages can treat frameworks as out of box.

src/Microsoft.DotNet.Build.Tasks/PackageFiles/FrameworkTargeting.targets
This needs some changes in dir.targets in CoreFX to enable it. 
Contributes to: https://github.com/dotnet/buildtools/issues/1587
This is necessary in order to be able to have a test working directory different than the output directory. The output directory is shared across target groups if the test assemblies target netstandard or uap, but when running in different runtimes (uap, netcoreapp, etc.) dependencies in order to be able to run the tests change and we fill the directory with a bunch of items that are specific to that target framework. This causes to have some clashes in the bin when trying to run the same test assembly against different target frameworks without having a clean repo/output test directory. (i.e without this changes if I want to run a test project against both uap …
=> Add necessary configurations in order to binplace the tests per buildconfiguration

src/GenFacades/GenFacades.Core/GenFacades.cs
Not all desktop tooling handles reference assemblies.  This helps reduce the number of reference assemblies we produce: if an assembly contains entirely type-forwards we'll strip the reference assembly attribute.
=> Remove reference assembly attribute from partial ref facade when it is a full facade

src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.props, src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets
You have to set the variable UseSourceLink to activate it.  Thus this change has no effect unless you opt in.   
Also older C# compilers this will fail unless you generate portable PDBs (later C# compilers support MSPDB).  This may limit when you can turn this on.  
There are additional issues getting this working end-to-end but I think this is all we need in build-tools.
I have been testing this on the corefx and coreclr repo.  I need a build of build-tools however before those repos can be updated.   
@dagood, @tmat, @mikem8361
=> Adding SourceLink Support (source code from GitHub) for dotnet builds

src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.props, src/Microsoft.DotNet.Build.Tasks/PackageFiles/Roslyn.Common.props, src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd, src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh, src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.csproj
cc: @weshaggard @jaredpar @VSadov 
Updating the version of roslyn compilers we use for building the repos. With these set of changes I'm able to build corefx in Windows and non-Windows succesfully.
=> Updating the version of the roslyn compilers we use for building

src/Microsoft.DotNet.Build.Tasks/GenerateDepsJson.cs
Previously the GenerateDepsJson task was assuming all assemblies were
dlls, however that is not the case; xunit.console.netcore.exe is an exe.
This didn't seem to cause an issue if the file existed in the
application folder.  If xunit.console.netcore.exe existed in the app folder, the host would
ignore the incorrect entry in the framework deps file.
If, however, the file was missing from the app folder and had incorrect
extension, the host would fail at startup.
This change fixes the deps file to have the correct extension.
The only diff after making this fix can be seen here: https://gist.github.com/ericstj/abdd9ba519dff947c3ac8910c9f37324/revisions#diff-4ed1ec087ae487fff3bdda792419a18e
=> Ensure deps file contains correct extension

src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.props, src/Microsoft.DotNet.Build.Tasks/PackageFiles/Roslyn.Common.props, src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd, src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh, src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.csproj
This reverts commit ef6e0ca1922f9c5d50250484d598d7c1860dab4a.
Temporarily reverting it to unblock buildtools update in corefx. Will re-add it once changes in corefx are ready to consume it.
=> Revert "Updating the version of the roslyn compilers we use for building (#1661)"

src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.props, src/Microsoft.DotNet.Build.Tasks/PackageFiles/Roslyn.Common.props, src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd, src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh, src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.csproj
FYI: @weshaggard @ericstj 
These changes were already in buildtools but I reverted them temporarily so that @ericstj could ingest some other changes into corefx. Now I have the corefx changes in order to be able to build with the new compiler ready, so I'm re-applying this back in buildtools.
=> Updating the version of the roslyn compiler

src/GenFacades/GenFacades.Core/GenFacades.cs
Port of https://github.com/dotnet/buildtools/pull/1663 to release/2.0.0
=> [release/2.0.0] Remove reference assembly attribute from partial ref facade when it is a full facade

src/Microsoft.DotNet.Build.Tasks/PackageFiles/Roslyn.Common.props, src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd, src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.csproj
FYI: @VSadov @weshaggard 
Needed for https://github.com/dotnet/corefx/pull/24076
Updating to a newer version of Roslyn that supports the compiler flag to disable validation generation.
=> Updating Roslyn to version 2.6.0-rdonly-ref-62111-06

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/Dumpling.targets
This adds saving off the full runtime that we unpack as part of running
the tests as well as the system libs that live in lib and usr/lib.
=> Update the include list for dumpling

README.md
The links in the README.md file were out of date.  I have updated them
to inlcude the proper links to the actual jobs that live in Jenkins.
=> Update links for build status

src/Microsoft.DotNet.Build.Tasks/PackageFiles/VersionTools.targets, src/Microsoft.DotNet.Build.Tasks/VersionTools/UpdateDependenciesAndSubmitPullRequest.cs, src/Microsoft.DotNet.VersionTools/Automation/GitHubApi/GitHubClient.cs, src/Microsoft.DotNet.VersionTools/Automation/PullRequestCreator.cs
This change checks this box by default when auto-PRs are created.
That way people don't need access to `dotnet-maestro-bot`'s fork to update the auto-PR.
=> Allow maintainers to modify auto PRs by default.

src/Microsoft.DotNet.Build.Tasks/PackageFiles/RunnerTemplate.Unix.txt
On Alpine Linux, the default shell is ash. To build .NET Core, we
explicitly install bash.
If we run the following command:
```sh
echo 0x3F > /proc/self/coredump_filter
```
in bash, it raises the exception:
> echo: write error: Invalid argument
while with ash, it works fine.
Problem is that, when `echo` is run from `bash`, it adds a trailing
linefeed which kernel seems to reject.
Adding `-n` avoids adding the linefeed.
Original exception while building CoreRT:
```sh
chmod +x /corert/Tools/dotnetcli//dotnet
/corert/bin/Linux.x64.Debug/ILCompiler.DependencyAnalysisFramework.Tests/RunTests.sh: line 67: echo: write error: Invalid argument
/corert/Tools/dotnetcli//dotnet xunit.console.netcore.exe ILCompiler.DependencyAnalysisFramework.Tests.dll  -xml testResults.xml -notrait Benchmark=true …
```
=> Avoid linefeed in /proc/self/coredump_filter

src/Microsoft.DotNet.Build.Tasks.Packaging/src/Extensions.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/GenerateRuntimeGraph.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/Microsoft.DotNet.Build.Tasks.Packaging.csproj, src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.common.targets
This task can be used to generate the RID heirarchy of a runtime.json from a simpler set of inputs.
/cc @eerhardt @weshaggard
=> Add GenerateRuntimeGraph task

src/Microsoft.DotNet.Build.Tasks.Feed/BlobFeed.cs, src/Microsoft.DotNet.Build.Tasks.Feed/BlobFeedAction.cs, src/Microsoft.DotNet.Build.Tasks.Feed/PushToBlobFeed.cs
Handle OverwriteOnUpload=true when the relevant blob does not already exist - previously this was an error, now we skip acquiring a lease. When uploading with OverwriteOnUpload=false & the relevant blob already exists, we now skip uploading rather than exiting with an error. CC @karajas
=> Handle overwriting blob feeds for edge cases

src/xunit.netcore.extensions/Discoverers/ActiveIssueDiscoverer.cs, src/xunit.netcore.extensions/Discoverers/SkipOnTargetFrameworkDiscoverer.cs, src/xunit.netcore.extensions/TargetFrameworkMonikers.cs, src/xunit.netcore.extensions/XunitConstants.cs
For several namespaces we try to reuse .NET Core sources including xunit tests and in most cases mono can pretend to be NetFramework
but in some places it completely uses .NET Core code and behaves more like .NET Core rather than .NET.
Example: https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Numerics/tests/BigInteger/Comparison.cs#L369-L373 - we can't pretend to be NetFramework here as we also have that netcore fix for this case.
/cc: @marek-safar @akoeplinger
=> Add Mono to TargetFrameworkMonikers

src/Microsoft.DotNet.Build.Tasks.Packaging/src/GenerateRuntimeGraph.cs
This adds support for emitting a DGML and a compatibility mapping from a runtime graph.
The DGML is handy for visualizing the runtime graph and the compatibility mapping
helps identify what the effects of a RID graph change will be on package asset resolution.
/cc @weshaggard @eerhardt
=> Add some options to GenerateRuntimeGraph for testing

src/Microsoft.DotNet.Build.Tasks/PackageFiles/Roslyn.Common.props, src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd, src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.csproj
cc: @VSadov @weshaggard 
FYI: @stephentoub @jkotas This version of the compiler should have fixed the problem with the rules that were preventing us to update Roslyn on coreclr. Once we have a build of this change, I'll ingest it into coreclr so that we can have the latest toolset in there as well.
=> Updating roslyn to version 2.6.0-beta1-62126-01

build.cmd
This reverts commit 470ebf035b93d9ea41821e87d9291897a0e151d1, reversing
changes made to 95cebe4159ac5fb3c4d23918242137950202dae7.
There was some confusion here because there are unfortunately too many build tools definitions. I reverted @joperezr's change and proved this works with build:
https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/index?buildId=1024262&_a=summary
... a successful build with the commit from before Joe's change.
I've made the relevant updates to the correct definition as well to support oss signing.
=> Revert "Merge pull request #1699 from joperezr/1.0Branch"

src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.props, src/Microsoft.DotNet.Build.Tasks/PackageFiles/RepoAPI.Mapping.props
Takes APIs from https://github.com/dotnet/source-build/blob/dev/release/2.0/Documentation/auto-dependency-flow/api.md and sets BuildTools properties/items to implement them.
I used these branches in source-build submodules to try it out:
* https://github.com/dotnet/standard/compare/dev/release/2.0.0...dagood:flow-api
* https://github.com/dotnet/corefx/compare/dev/release/2.0.0...dagood:flow-api
I copied the props file directly below the `Build.Common.props` import in those branches to test this out quickly without updating the entire BuildTools package (which could have its own problems).
Confirmed that it works by checking the blob feed dir for the `nupkg`/`symbols.nupkg`s and using `strings` to peek at the DLLs that CoreFX binplaced to `bin/ref/netstandard`.
=> Add Repo API common implementation

src/Microsoft.DotNet.Build.Tasks.Packaging/src/VerifyClosure.cs
Don't crash on an assembly with a reference to itself, instead treat it like any other cycle.
This is a busted assembly and we're not going out of our way to special case it, but it will fail the build.
I had seen this before when I passed in an assembly with the same name as a candidate seed to GenFacades and hadn't bothered to fix it since it was user error, but it never hurts to avoid a crash.
Fixes #1712
/cc @danmosemsft
=> Make VerifyClosure handle an assembly referencing itself

src/Microsoft.DotNet.Build.Tasks/GenerateDepsJson.cs
Prevent failures like
```
C:\git\corefx\src\src.builds(32,5): error MSB4018: The "GenerateDepsJson" task failed unexpectedly.
C:\git\corefx\src\src.builds(32,5): error MSB4018: System.ArgumentException: Can not add property runtimes/win-x64/lib/netcoreapp2.0/mscorlib.dll to Newtonsoft.Json.Linq.JObject. Property with the same name already exists on object.
C:\git\corefx\src\src.builds(32,5): error MSB4018:    at Newtonsoft.Json.Linq.JObject.ValidateToken(JToken o, JToken existing)
C:\git\corefx\src\src.builds(32,5): error MSB4018:    at Newtonsoft.Json.Linq.JContainer.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
C:\git\corefx\src\src.builds(32,5): error MSB4018:    at Newtonsoft.Json.Linq.JObject.InsertItem(Int32 index, JToken item, Boolean skipParentCheck) …
```
=> Fixed GenerateDepsJson msbuild task

src/nuget/Microsoft.DotNet.Build.Tasks.VersionTools.nuspec
Moving PR from https://github.com/dotnet/buildtools/pull/1702 to target release/2.0.0
This addresses feedback in that PR, except for changing BuildTask and the open question of how to handle versioning.
=> Release/2.0.0 Create Microsoft.DotNet.Build.Tasks.VersionTools package

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/Dumpling.targets, src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/DumplingHelper.py
We started by just collecting all of the SOs in the lib and usr/lib
directories, but that proved to be too big.  This brings the list to
just the files that we need.  This also turns off dump triaging as it is
currently broken and blocking regular collection.
=> Pare down include lists for dump collection

src/nuget/Microsoft.DotNet.Build.Tasks.PublishProduct.nuspec
@weshaggard , this is the last repackaging of BuildTools that I'm aware of at the moment.  This package is used to publish to myget.
=> Create Microsoft.DotNet.Build.Tasks.PublishProduct package

src/Microsoft.DotNet.Build.Tasks/DownloadFilesFromUrl.cs
Fixes: https://github.com/dotnet/buildtools/issues/1724
This should be enough to fix the disposed exception you saw.
cc: @danmosemsft
=> Fix disposed exception when downloading a file and calling the task multiple times on the same msbuild process

src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.csproj
cc: @eerhardt @weshaggard 
Supressing package conflict warnings that get thrown from the new CLI so that consumer repos that have the property `TreatWarningsAsErrors` set to true won't fail to initialize tools.
=> Supressing nuget package downgrades

src/Microsoft.DotNet.Build.Tasks/DownloadFilesFromUrl.cs, src/Microsoft.DotNet.Build.Tasks/PackageFiles/Symbols.targets
Do nothing when SymbolPackagesToDownload is empty.
=> Add conditions for DownloadFilesTask and DownloadSymbolPackages

src/Microsoft.DotNet.Build.Tasks/ConvertPortablePdbsToWindowsPdbs.cs, src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj, src/Microsoft.DotNet.Build.Tasks/PackageFiles/Symbols.targets
Fixes https://github.com/dotnet/buildtools/issues/1735. I want to fix this before someone gets a chance to start relying on this build task's name outside of the BuildTools targets.
Thanks for spotting this, @vancem!
=> Rename ConvertPdbsToPortablePdbs to ConvertPortablePdbsToWindowsPdbs

src/Microsoft.DotNet.Build.Tasks/ConvertPortablePdbsToWindowsPdbs.cs, src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj, src/Microsoft.DotNet.Build.Tasks/PackageFiles/Symbols.targets
(cherry picked from commit dfea7f77c5e34f960f61a5ff4881c80a621818f3)
Port https://github.com/dotnet/buildtools/pull/1736 to release/2.0.0. (Issue https://github.com/dotnet/buildtools/issues/1735)
This is a quick fix that we should keep in sync for any future 2.0 servicing symbols work. I plan to go ahead and merge if CI builds.
=> [release/2.0.0] Rename ConvertPdbsToPortablePdbs to ConvertPortablePdbsToWindowsPdbs

src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
Introduce mechanism to allow specifying environment to set before running test
If the msbuild property `PreExecutionTestScript` is set, it must be
a set of script commands that will be incorporated into the generated
runtests script.
For example, this will be used to set JIT stress modes:
```
build-tests.cmd -Release -os:Windows_NT -buildArch:x86 -- /p:WithoutCategories=IgnoreForCI /p:PreExecutionTestScript=c:\SetStressModes.bat
```
=> Introduce mechanism to allow specifying environment to set before running test

src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd, src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh
The "dotnet --version" check has been broken by reversioning dotnet.exe to 15. 
After discussion with @weshaggard, I'm just removing it and all project.json support.
Need to figure out how to test this.
=> Remove project.json from init-tools

src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Methods.cs
Currently for deconstructors we're just producing an empty body and this causes the build to fail if we are generating a PNSE Assembly because in implementation deconstroctors must have a body. This doesn't hurt the regular GenApi scenario of creating an AssemblyReference since `_platformNotSupportedExceptionMessage` will be null and it will produce an empty body. I've tested both scenarios locally and they work fine. 
FYI: @pjanotti
=> Fix GenApi so that when creating a PNSE Assembly Deconstructors throw as well

src/Microsoft.DotNet.Build.CloudTestTasks/DownloadFromAzure.cs
Builds are failing because Downloading large payloads in parallel is causing timeouts. Increase the timeout to 10 minutes.
=> Increase timeout in DownloadFromAzure task

src/Microsoft.DotNet.Build.Tasks/PackageFiles/RepoAPI.Mapping.props
This is generally friendlier in the MSBuild ecosystem. It allows the repo to provide a PackageOutputProps in dir.props if it knows better.
I checked to make sure CoreCLR, CoreFX, and Standard set [Symbol]PackageOutputPath after the `Build.Common.props` import, so this won't break them.
Small change that @eerhardt mentioned when he hit a hard `<PackageOutputPath>foo</PackageOutputPath>` in Core-Setup.
=> [release/2.0.0] Only set [Symbol]PackageOutputPath if empty

src/Microsoft.DotNet.Build.Tasks/PackageFiles/packageresolve.targets
When restoring a .depproj, the Repo API args for dependency flow are not getting passed through, so the correct package versions are not being respected.
=> Fix RestorePackages to respect Repo API args.

src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
So I can set `<XUnitShowProgress>true</XUnitShowProgress>` in my project, which is useful if I'm experiencing occasional hangs in CI and want to know which test is the issue.
A bit cleaner than explicitly passing the flag and I don't have to explicitly append to XUnitOptions
=> Add XUnitShowProgress property

src/Microsoft.DotNet.Build.Tasks/PackageFiles/VersionTools.targets, src/Microsoft.DotNet.Build.Tasks/VersionTools/UpdateDependenciesAndSubmitPullRequest.cs, src/Microsoft.DotNet.VersionTools/Automation/GitHubApi/GitHubClient.cs, src/Microsoft.DotNet.VersionTools/Automation/PullRequestCreator.cs
Port https://github.com/dotnet/buildtools/pull/1686 to `release/2.0.0`. Porting this will help with merge conflicts vs. `master` when forward-porting VersionTools features. (It's also a very useful feature.)
=> [release/2.0.0] Allow maintainers to modify auto PRs by default.

.toolversions, src/Microsoft.DotNet.Build.Tasks.Feed/PackageFiles/Publish.targets
1. Adds the feed package to .toolsversions so that we can publish in the official build def and not have a chicken-egg problem which may occur if we used the version of feeds from the current build
2. ie, it'd be nice if there was a way to use this package without having to always define a wrapper project in the repo which is used simply to define itemstopush and to pass through the rest of the variables..
=> Add feed package to buildtools init

src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj, src/Microsoft.DotNet.Build.Tasks/PackageFiles/VersionTools.targets, src/Microsoft.DotNet.Build.Tasks/VersionTools/BaseDependenciesTask.cs, src/Microsoft.DotNet.Build.Tasks/VersionTools/TaskItemBuildDependencyInfo.cs, src/Microsoft.DotNet.Build.Tasks/VersionTools/UpdateDependencies.cs, src/Microsoft.DotNet.Build.Tasks/VersionTools/UpdateDependenciesAndSubmitPullRequest.cs, src/Microsoft.DotNet.Build.Tasks/VersionTools/UpdateToRemoteDependencies.cs, src/Microsoft.DotNet.Build.Tasks/VersionTools/VerifyDependencies.cs, src/Microsoft.DotNet.VersionTools/Automation/DependencyUpdateResults.cs, src/Microsoft.DotNet.VersionTools/Automation/DependencyUpdateUtils.cs, src/Microsoft.DotNet.VersionTools/Automation/GitHubApi/GitHubClient.cs, src/Microsoft.DotNet.VersionTools/Automation/PullRequestCreator.cs, src/Microsoft.DotNet.VersionTools/Dependencies/BuildOutput/BuildDependencyInfo.cs, src/Microsoft.DotNet.VersionTools/Dependencies/BuildOutput/FilePackageUpdater.cs, src/Microsoft.DotNet.VersionTools/Dependencies/BuildOutput/FileRegexPackageUpdater.cs, src/Microsoft.DotNet.VersionTools/Dependencies/BuildOutput/FileRegexReleaseUpdater.cs, src/Microsoft.DotNet.VersionTools/Dependencies/BuildOutput/ProjectJsonUpdater.cs, src/Microsoft.DotNet.VersionTools/Dependencies/BuildOutput/ToolVersionsUpdater.cs, src/Microsoft.DotNet.VersionTools/Dependencies/DependencyUpdateTask.cs, src/Microsoft.DotNet.VersionTools/Dependencies/FileRegexUpdater.cs, src/Microsoft.DotNet.VersionTools/Dependencies/IDependencyInfo.cs, src/Microsoft.DotNet.VersionTools/Dependencies/IDependencyUpdater.cs, src/Microsoft.DotNet.VersionTools/Dependencies/Submodule/IndicatorPackageSubmoduleUpdater.cs, src/Microsoft.DotNet.VersionTools/Dependencies/Submodule/LatestCommitSubmoduleUpdater.cs, src/Microsoft.DotNet.VersionTools/Dependencies/Submodule/SubmoduleDependencyInfo.cs, src/Microsoft.DotNet.VersionTools/Dependencies/Submodule/SubmoduleUpdater.cs, src/Microsoft.DotNet.VersionTools/Microsoft.DotNet.VersionTools.csproj, src/Microsoft.DotNet.VersionTools/Util/Command.cs, src/Microsoft.DotNet.VersionTools/Util/GitCommand.cs
Port https://github.com/dotnet/buildtools/pull/1741 to master.
I squashed https://github.com/dotnet/buildtools/pull/1752 into the cherry-pick to avoid any merge conflicts.
I haven't tested this yet against CoreFX master and friends. No breaking changes expected for BuildTools MSBuild users. There are some for VersionTools .NET lib users.
=> (Port to master) Add "UpdateToRemote" concept for better submodule update

dependencies.props, dir.props, src/Microsoft.DotNet.Build.Tasks.net45/project.json, src/Microsoft.DotNet.Build.Tasks/project.json
There was a COM bug in the PDB writing code used in the task that
converts portable PDBs to windows PDBs (see https://github.com/dotnet/symreader/pull/70)
This picks up a version with this fix in the build tools.
@tmat  @dagood 
I have confirmed that with this update the fix (which is in the SymUnmanagedWriterImpl.CloseSymWriter method), shows up in the Microsoft.DiaSymReader.dll placed in the bin directory.
=> Update PDB Conversion Task to fix random crash

src/Microsoft.DotNet.Build.Tasks/PackageFiles/CodeCoverage.targets
Code to convert portable pdbs to windows pdbs was being run on UNIX machines.
This is clearly not needed and was causing failures.   Fix it to only run on non Windows
and only for coverage (which is the only thing we know that needs the Windows  PDBs).
Basically just make the conversion condition stricter.  
See also  https://github.com/dotnet/corefx/issues/24807.
=> Fix failure on Unix associate with converting PDBs

src/Microsoft.DotNet.VersionTools/Automation/GitHubApi/GitHubApiModel.cs, src/Microsoft.DotNet.VersionTools/Automation/GitHubApi/GitHubClient.cs, src/Microsoft.DotNet.VersionTools/Automation/PullRequestCreator.cs
Resolves #1773
Resolves #1774
Example of these issues in a live auto-update PR: https://github.com/dotnet/core-setup/pull/3372. Tested fix with https://github.com/dagood/source-build/pull/6, where I applied more than one status with the same context.
=> Auto-update discarded commit list: use combined status; only include Details link if a target exists

src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/sign.targets
As part of our repo API we are using 'public' as the signtype to
indicate what we formally referred to as oss signing. We still work
if oss is specified for back-compat but we now default to public
if it isn't set.
cc @dagood @mmitche
=> Make public the default SignType

src/Microsoft.DotNet.Build.Tasks.Feed/Microsoft.DotNet.Build.Tasks.Feed.csproj, src/nuget/Microsoft.DotNet.Build.Tasks.Feed.nuspec
We found that for net15 based builds there was an error about Sleet not being found since the dll was not being copied along with the Feed dll. This should fix this.
=> Enabling the Feed task to copy nuget dependencies for net15

src/Microsoft.DotNet.Build.Tasks.Feed/BlobFeed.cs, src/Microsoft.DotNet.Build.Tasks.Feed/BlobFeedAction.cs, src/Microsoft.DotNet.Build.Tasks.Feed/Microsoft.DotNet.Build.Tasks.Feed.csproj, src/Microsoft.DotNet.Build.Tasks.Feed/PushToBlobFeed.cs, src/Microsoft.DotNet.Build.Tasks.Feed/SleetLogger.cs
Currently we just support uploading nukpg files to the feeds. With this change if we find non-nupkg files in ItemsToPush, we upload them using Azure APIs and place them in {container}/{relativePath}/assets/.
ItemsToPush can be composed of only nupkgs, only non-nupkgs or a mixture of both
=> Add asset upload support

src/Microsoft.DotNet.Build.CloudTestTasks/CreateAzureContainer.cs, src/Microsoft.DotNet.Build.Tasks.Feed/BlobFeedAction.cs
If a token is not provided in the ExpectedFeedUrl when we create a container we make them public.
/cc: @weshaggard @karajas
=> Create Public containers through PushToFeed

src/GenFacades/GenFacades.Core/GenFacades.cs
PR #1792 had a break on Linux because of course windows PDBs don't exist there (and neither does the converter).     Add condition to simply not call the converter on non-windows platforms.  
@dagood
=> Fix for CoreFX build break on Linux

src/Microsoft.DotNet.Build.Tasks/PackageFiles/RepoAPI.Mapping.props, src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.ps1, src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh
This implementation is in `init-tools.ps1` and `init-tools.sh`, which runs after the BuildTools package is restored. `RepoAPI.Mapping.props` then picks up on the downloaded file inside the MSBuild call.
This downloads the file pointed to by the environment variable `PACKAGEVERSIONPROPSURL` and uses the props file during the build.
CoreFX only needs to add a VSTS variable `PACKAGEVERSIONPROPSURL` with the value of `PB_PackageVersionPropsUrl` to put the URL value in the environment var. (This only works if it's not a secret. For now, this flow does not support a package version props URL that requires auth.)
I rely on the environment to pass the arg deep into the init-tools flow to avoid adding more args that need to pass all the way through. Using the env is bad for discoverability, but …
=> Add init-tools PackageVersionProps download

src/Microsoft.DotNet.Build.Tasks/PackageFiles/partialfacades.task.targets
This is a second attempt.   The first attempt was a misunderstanding of how Linux builds worked.
Before trying to support protable PDBs, GenFacades had a condition that it was never called if
Portable PDBs are used.   However we WANTED to used portable PDBs so we added support for
that and dropped the condition to skip GenFacades if portable PDBs were used.
However this had the effect of running GenFacades on Linux, where previously it never ran there
(because Linux always used portable PDBs).
This fix basically puts the behavior back EXACTLY as it was before on non-windows platforms.
This will fix errors (they happen to be index out of range errors) on Linux builds (because we
are running GenFacades where we should not be).
@dagood  @stephentoub
=> Fix to unbreak Linux build.

src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets
The sourcelink file is generated one for the whole repo so it is possible that
differnet parts of the build will race to write it.   We have seen this show up as a file
access error in builds.
It is already the case that there is logic that avoids running the code most of the time
(see VersionPropsImported).  but races are still possible.  They are avoided in that
scheme by testing for the file existing and simply warning if there is a error trying to
write the file.   We follow suit here.
As a unrelated change there was already a variable SourceLinkFilePath, for the source
link file so I use it instead of building it out of more primitive variable.
@dagood
=> Fix race associted with SourceLink

src/Microsoft.DotNet.Build.Tasks/PackageFiles/scripts/vstsagent/cleanupagent.proj
DiskUsage Reporting alone is taking ~20 mins on OSX machines for each of the folders getting cleaned. Turning off to improve the perf.
=> Turn Off DiskUsage Reporting in CleanUpVSTSAgent

src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.csproj
A change to this file in https://github.com/dotnet/buildtools/commit/21e36983f28a5e587e300c506641f1b698b6decb is causing that when running init-tools errors like the below are thrown:
error : Package Microsoft.Net.Compilers.Targets.NetCore 0.1.5-dev is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Net.Compilers.Targets.NetCore 0.1.5-dev supports: dotnet (.NETPlatform,Version=v5.0) [G:\Code\coreclr\packages\microsoft.dotnet.buildtools\2.0.0-prerelease-02012-01\lib\tool-runtime\project.csproj]
=> Compatibility issue fix

src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.csproj
On a previous PR I added  <PackageTargetFallback Condition=" '$(TargetFramework)' == 'netcoreapp2.0' ">$(PackageTargetFallback);portable-net45+win8</PackageTargetFallback> 
but dnxcore50 was not there and it is needed so there are not compatibility errors
=> dnxcore50 is needed to solve the compat issue

src/Microsoft.DotNet.Build.Tasks.Feed.net45/project.json, src/Microsoft.DotNet.Build.Tasks.Feed/project.json
Previous had a regression and was creating folders in the wrong locations also causing that catalogs were looking in the root of the main container instead of the main sub feed folder
=> Updating Sleet version 

src/Microsoft.DotNet.Build.Tasks.Feed/BlobFeedAction.cs, src/Microsoft.DotNet.Build.Tasks.Feed/GetBlobFeedPackageList.cs, src/Microsoft.DotNet.Build.Tasks.Feed/Microsoft.DotNet.Build.Tasks.Feed.csproj, src/Microsoft.DotNet.Build.Tasks.Feed/PackageFiles/Microsoft.DotNet.Build.Tasks.Feed.targets, src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj, src/Microsoft.DotNet.Build.Tasks/Orchestration/WriteBuildOutputProps.cs
Tasks for an orchestration utility build def that takes in a blob feed and adds a package version props file to it. Usage:
```xml
<Target Name="UpdatePackageVersionProps">
<PropertyGroup>
<TempPackageVersionPropsFile>$(BaseIntermediateOutputPath)PackageVersions.props</TempPackageVersionPropsFile>
</PropertyGroup>
<GetBlobFeedPackageList
ExpectedFeedUrl="$(ExpectedFeedUrl)"
AccountKey="$(AccountKey)">
<Output TaskParameter="PackageInfos" ItemName="PackageInfos" />
</GetBlobFeedPackageList>
<WriteBuildOutputProps
NuGetPackageInfos="@(PackageInfos)"
OutputPath="$(TempPackageVersionPropsFile)"
OnlyUpdatePrereleaseVersions="true" />
<ItemGroup>
<TempPackageVersionPropsFileForUpload Include="$(TempPackageVersionPropsFile)">
<RelativeBlobPath>orchestration-metadata/PackageVersions.props</Relative …
```
=> Tasks to create package version props using Sleet

src/Microsoft.DotNet.Build.Tasks.Feed/BlobFeedAction.cs, src/Microsoft.DotNet.Build.Tasks.Feed/PushToBlobFeed.cs
We've decided that we'll publish symbols to flat containers by default instead of using Sleet. This change disables Sleet's symbols publishing and adds logic to identify and categorize packages and symbols
=> Publish symbols to flat containers

src/Microsoft.DotNet.Build.Tasks/PackageFiles/IL.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/ilasm/ilasm.depproj, src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd, src/dirs.proj
Windows-only for now since that's what I need. I think we would want the bootstrapper (the thing that invokes init-tools) to pass us the RID it used to restore .NET CLI so that we can restore the appropriate version of the native tools. RID in the Windows batch file was easy to hardcode since we seem to hardcode x64 on Windows everywhere.
Contributes to #1363.
=> Add ILAsm to buildtools

src/nuget/Microsoft.DotNet.Build.CloudTest.nuspec, src/nuget/Microsoft.DotNet.Build.Tasks.Feed.nuspec, src/nuget/Microsoft.DotNet.BuildTools.ApiCompat.nuspec, src/nuget/Microsoft.DotNet.BuildTools.Cci.nuspec, src/nuget/Microsoft.DotNet.BuildTools.GenAPI.nuspec, src/nuget/Microsoft.DotNet.BuildTools.GenFacades.nuspec, src/nuget/Microsoft.DotNet.BuildTools.RepoUtils.nuspec, src/nuget/Microsoft.DotNet.BuildTools.Run.nuspec, src/nuget/Microsoft.DotNet.BuildTools.TestSuite.nuspec, src/nuget/Microsoft.DotNet.BuildTools.VstsBuildsApi.nuspec, src/nuget/Microsoft.DotNet.BuildTools.nuspec, src/nuget/Microsoft.DotNet.VersionTools.nuspec, src/nuget/Microsoft.xunit.extensibility.execution.netcore.nuspec, src/nuget/Microsoft.xunit.netcore.extensions.nuspec, src/nuget/xunit.console.netcore.nuspec, src/packages.builds
This allows us to avoid conflicts between BuildTools branches in the most straightforward way. See https://github.com/dotnet/buildtools/issues/1489.
I noticed this was still out of date when reviewing https://github.com/dotnet/corefx/pull/24784.
=> Update all package outputs to 2.1.0-prerelease

src/Microsoft.DotNet.Build.CloudTestTasks/UploadClient.cs, src/Microsoft.DotNet.Build.CloudTestTasks/UploadToAzure.cs, src/Microsoft.DotNet.Build.Tasks.Feed/BlobFeedAction.cs, src/Microsoft.DotNet.Build.Tasks.Feed/PushToBlobFeed.cs
Some core-setup and corefx build are recently failing when trying to upload big symbol packages. At this point HttpClient uses the default timeout of 100 seconds which in some cases is not enough
=> Adding 5 minute timeout to HttpClient for UploadToAzure scenarios

src/Microsoft.DotNet.VersionTools/Automation/GitHubApi/GitHubApiModel.cs, src/Microsoft.DotNet.VersionTools/Automation/GitHubApi/GitHubClient.cs, src/Microsoft.DotNet.VersionTools/Automation/PullRequestCreator.cs
I noticed release/2.0.0 is missing https://github.com/dotnet/buildtools/pull/1775 and https://github.com/dotnet/buildtools/pull/1794 in this submodule auto-update PR: https://github.com/dotnet/source-build/pull/294.
=> [release/2.0.0] Port VersionTools auto-update pull request fixes

src/Microsoft.DotNet.Build.CloudTestTasks/UploadClient.cs, src/Microsoft.DotNet.Build.CloudTestTasks/UploadToAzure.cs, src/Microsoft.DotNet.Build.Tasks.Feed/BlobFeedAction.cs
Prefer explicit content type specification in the item metadata
and only use autodetection when not available. We're using this
for uploading test logs and results to Azure - without proper
content type some browsers have trouble opening them.
This is my first contribution to this repo so I'll be grateful for
any advice regarding testing and the review process in general.
The change passes the default testing as part of building the repo
and I have verified the correct content types in the Azure
Storage Explorer.
=> Support optional ContentType item metadata in UploadToAzure

src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/scriptrunner/scriptrunner.py
- Removed the parameter "--standalone"
- Added a few checks to prevent problems when some Helix environment variables aren't set.
=> Changes required to let scriptrunner.py run commands outside of Helix Context

src/Microsoft.DotNet.Build.Tasks.Feed/BlobFeedAction.cs
Surfacing this as an error will make it easier to spot and correct, rather than browsing blob storage.
Use LogError rather than throwing an exception so that every bad item gets an error message.
@natemcmaster
=> Refuse to create an unnamed virtual directory

src/Microsoft.DotNet.Build.Tasks.Feed.net45/Microsoft.DotNet.Build.Tasks.Feed.net45.csproj, src/Microsoft.DotNet.Build.Tasks.Feed/BlobFeed.cs, src/Microsoft.DotNet.Build.Tasks.Feed/Microsoft.DotNet.Build.Tasks.Feed.csproj, src/Microsoft.DotNet.Build.Tasks.Feed/PushToBlobFeed.cs, src/Microsoft.DotNet.Build.Tasks/LaunchDebugger.cs, src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj, src/Microsoft.DotNet.VersionTools.Tests/BuildManifest/ManifestModelTests.cs, src/Microsoft.DotNet.VersionTools.Tests/Microsoft.DotNet.VersionTools.Tests.csproj, src/Microsoft.DotNet.VersionTools.Tests/Microsoft.DotNet.VersionTools.Tests.sln, src/Microsoft.DotNet.VersionTools/BuildManifest/Model/ArtifactSet.cs, src/Microsoft.DotNet.VersionTools/BuildManifest/Model/BlobArtifactModel.cs, src/Microsoft.DotNet.VersionTools/BuildManifest/Model/BuildIdentity.cs, src/Microsoft.DotNet.VersionTools/BuildManifest/Model/BuildModel.cs, src/Microsoft.DotNet.VersionTools/BuildManifest/Model/EndpointModel.cs, src/Microsoft.DotNet.VersionTools/BuildManifest/Model/OrchestratedBuildModel.cs, src/Microsoft.DotNet.VersionTools/BuildManifest/Model/PackageArtifactModel.cs, src/Microsoft.DotNet.VersionTools/BuildManifest/Model/XElementParsingExtensions.cs, src/Microsoft.DotNet.VersionTools/Microsoft.DotNet.VersionTools.csproj, src/dirs.proj
This adds functionality to `PushToBlobFeed` to create build output manifests. See [core-eng/publish.md](https://github.com/dotnet/core-eng/blob/master/Documentation/Orchestrated-Build/Api/publish.md#cookbook-using-pushtoblobfeed-to-generate-a-manifest) for details on usage.
https://github.com/dotnet/core-eng/issues/2287 "Add output manifest generation to PushToBlobFeed task"
---
This is intended for single/low-use feeds: the manifest(s) would build up over time on a central blob feed. Central feeds can ensure manifests are *never* pushed to them by putting a blob called `disable-manifest-push` at the root of the feed. (The blob's contents aren't examined and don't matter.)
> I initially wanted to use Sleet feed settings for this. However, `PushToBlobFeed` by default runs `Init` on every …
=>  Create build manifest in PushToBlobFeed for orchestrated build final publish

src/Microsoft.DotNet.Build.Tasks/Configuration/ConfigurationFactory.cs, src/Microsoft.DotNet.Build.Tasks/FindBestConfigurations.cs
This will allow to add a build configuration with an _ at the beginning of it and it will be a negation of that build configuration. 
The build system will find those build configurations, will turn them to a valid configuration by removing the prefix and if that configuration is present in the best build configurations then we will return an empty set of best build configurations and will turn in a noop for that project.
Changes will need to be made in corefx to add this negative build configurations to the projects that are inbox on netfx.
Contributes to: https://github.com/dotnet/corefx/issues/24903
cc: @danmosemsft
=> Provide a way to ignore BuildConfigurations through _ prefix in the build configuration

src/Microsoft.DotNet.VersionTools/Automation/PullRequestCreator.cs
Also only add CI info when info exists to avoid creating a confusing empty collapsible section.
Fixes https://github.com/dotnet/buildtools/issues/1827
The commit discard comments will now look like this:
> Discarded [`b31c17b`](https://github.com/dagood-bot/corefx/commit/b31c17b0bf93d8fd5eaace693eb775989b8662d5): `Update BuildTools, CoreClr, CoreFx, CoreSetup, ProjectNTfs, ProjectNTfsTestILC to prerelease-02402-01, preview1-26102-02, preview1-26102-01, preview1-26101-02, beta-26028-00, beta-26028-00, respectively`
> 
> <details><summary>CI Status: 1:x: (click to expand)
> </summary>
> 
>  * :x: **testing-fail** [Desc](https://example.org)
> 
> </details>
=> Move commit link out of summary: make it clickable

src/Microsoft.DotNet.Build.Tasks/UpdateVSConfigurations.cs
Right now if we add a placeholder configuration to .props file (_netfx) when running UpdateVSConfigurations target, this gets added as a configuration to the sln and .csproj file. 
contributes to: https://github.com/dotnet/corefx/issues/24903
cc: @danmosemsft @weshaggard
=> Ignore placeholder configurations in UpdateVSConfigurations task

src/Microsoft.DotNet.Build.Tasks/Configuration/Configuration.cs, src/Microsoft.DotNet.Build.Tasks/Configuration/ConfigurationFactory.cs, src/Microsoft.DotNet.Build.Tasks/FindBestConfigurations.cs
Currently the only scenario that was supported was to add a default placeholder configuration (no osgroup) `_netfx` and in debug mode. If we build for Release, the configuration infrastructure would add a -Release or Windows_NT-Release suffix when parsing the build configuration and it will not be ignored. 
With this change it will allow to add placeholder configurations including the osgroup (`_netfx-Windows_NT`) and to fallback to the default targetgroup (`_netfx`). So this way if I add a `_netfx` configuration all the `_netfx` configurations will be ignored when building for that project. If I add `_netcoreapp-Windows_NT`, it will be ignored only in Windows for netcoreapp. 
Contributes to: https://github.com/dotnet/corefx/issues/24903
cc: @weshaggard @danmosemsft
=> Add osGroup scenario to placeholder build configurations to FindBestConfiguration task

src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
We have a number of cases were we were incorrectly promoting
dependencies from netstandard refs to net4x dependency groups which
aren't needed and cause extra dependencies and in some cases cause
issue (see https://github.com/dotnet/corefx/issues/26129).
A diff of corefx nuspec's before and after this change shows about
14 different affected packages which now have correctly cleaned
up dependency groups for net4x.
cc @ericstj
=> Filter out empty dependencies from promotion consideration

src/Microsoft.DotNet.Build.Tasks.Feed/PushToBlobFeed.cs
This makes it so symbol packages will show up in manifests as `Blob` elements, and standardizes the `AssetRootUrl` that we pass orchestrated builds. https://github.com/dotnet/core-eng/issues/2274
We'll need to respond to this change in the orchestrated build pipelines by changing the url from `symbols/` to `assets/symbols/`. I'll keep watch over the buildtools auto-PRs and make the pipeline change when this BT change gets in.
=> In blob feeds, put detected symbol packages in assets/symbols/

src/ApiCompat/Rules/Compat/ParameterModifiersCannotChange.cs, src/ApiCompat/Rules/Compat/TypeCannotChangeClassification.cs, src/Microsoft.Cci.Extensions/Extensions/CSharp/CSharpCciExtensions.cs, src/Microsoft.Cci.Extensions/Filters/MappingDifferenceFilter.cs, src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Attributes.cs, src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Methods.cs, src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Properties.cs, src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Types.cs, src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.cs
With this change our tools like genapi and apicompat will understand
in params
ref readonly returns
readonly structs
ref structs
Also added apicompat rules to ensure the new annotations are compatible
Addresses https://github.com/dotnet/corefx/issues/25039.
cc @jkotas @jaredpar @VSadov 
These updates were used to find the incompatible annotations and regenerate ref files in PR https://github.com/dotnet/corefx/pull/26175.
=> Update CCI extensions to understand new C# lang features

src/Microsoft.DotNet.Build.Tasks/FindBestConfigurations.cs
If not we would fail with an ArgumentException that the key is already present if a project duplicates a build configuration for some reason. We're currently hitting that on: 
https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netcoreapp+CGroup_Release+AGroup_x86+TestOuter_false_prtest/6768/console
PR: https://github.com/dotnet/corefx/pull/26138
=> When creating the supportedProjectConfigurations dictionary we need to make sure they are distinc elements

src/Microsoft.DotNet.Build.Tasks.Feed/PackageFiles/Microsoft.DotNet.Build.Tasks.Feed.targets
Same addition as https://github.com/dotnet/coreclr/pull/15705 and https://github.com/dotnet/corefx/pull/26192. Adds manifest info properties to the `PushToBlobFeed` task call. Core-Setup needs this changed in BuildTools because it gets the targets from the Feeds package. (CoreCLR and CoreFX implement this targets file themselves.)
=> Include manifest info properties in feed targets

src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
Needed before I can try out a CoreFX build with nupkg signing enabled.  Note that this is just about writing the required files.  
I have changes I believe will work with this for CoreFX (not ready for PR) in https://github.com/MattGal/corefx/commit/49a609059e7259da7af48b0184fafc5fe64af010
=> Add WriteSigningRequired calls to Packaging (for nupkg signing in future)

src/Microsoft.DotNet.Build.CloudTestTasks/ListAzureBlobs.cs
The next marker is often non-empty even when the first page of blob results returned is empty.  Without adding the filter again, we will then list everything in the container
=> Filter should be appended when getting the next page of results

src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
Helps resolve the timeout issue here: https://github.com/dotnet/corefx/issues/26265
The reason we are seeing this issue with System.Memory Performance tests, in particular, is that they heavily use the InnerIterationCount, and hence running those perf tests, especially in debug, will take longer than 20 minutes.
Increasing the Max Iteration from 1 to 2 as per @jorive's suggestion since the data from the first iteration is ignored.
cc @jorive, @danmosemsft, @KrzysztofCwalina, @joperezr, @Priya91, @weshaggard
=> Limit inner iteration count to a max of 2

src/Microsoft.Cci.Extensions/Extensions/CSharp/CSharpCciExtensions.cs, src/Microsoft.Cci.Extensions/Traversers/SimpleTypeMemberTraverser.cs, src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Fields.cs, src/Microsoft.Cci.Extensions/Writers/CSharp/CSharpWriter.cs
For compile-time compat, the following rules should work for producing a reference assembly. We drop all private fields, but add back certain synthesized private fields for a value type (struct) as follows:
- If there are any private fields that are or contain any value type members, add a single private field of type int
- If there are any private fields that are or contain any reference type members, add a single private field of type object.
- If the type is generic, then for every type parameter of the type, if there are any private fields that are or contain any members whose type is that type parameter, we add a direct private field of that type.
For more details see issue https://github.com/dotnet/corefx/issues/6185
this blog is helpful as well …
=> Update CSharpWriter to handle private fields in structs

src/Microsoft.DotNet.Build.Tasks/VersionTools/UpdateToRemoteDependencies.cs
Assuming the match was successful prepended the CurrentRef value to the file because Index and Length are 0 for a failed match. When this value shows up in pull requests due to bad VersionTools config, it can be hard to debug.
Fixes https://github.com/dotnet/buildtools/issues/1374
=> Fix behavior when there is no CurrentRef property

src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Methods.cs
From https://github.com/dotnet/corefx/pull/26518#discussion_r163066777
cc @jkotas, @weshaggard
=> Add space around '=' when defining optional arguments

src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj, src/Microsoft.DotNet.Build.Tasks/ValidateBinInspectResults.cs
Copied from https://github.com/dotnet/core-setup/blob/725e5801bfa81e207e3760ffcb5ab08ba230ec64/tools-local/tasks/ValidateBinInspectResults.cs so that we can easily use it as a post-build step. This lets us set up a much more detailed whitelist than the verification VSTS build step accepts.
=> Move ValidateBinInspectResults from Core-Setup

src/Microsoft.DotNet.Build.Tasks.Packaging/src/CreateTrimDependencyGroups.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/FrameworkUtilities.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets, src/Microsoft.DotNet.Build.Tasks.Packaging/test/CreateTrimDependencyGroupsTests.cs
Previously this task used a bunch of custom logic to decide when to copy dependencies.
This has been simplified to the following:
1. For all frameworks supported by the package that have inbox assemblies.
2. Determine which dependency group applies to them.
3. Copy that dependency group to a framework-specific group and remove all inbox assemblies.
4. Remove any redundant dependency groups.
Here are the changes to corefx nuspecs after making this change: https://github.com/ericstj/scratch/commit/1e1daf516d57feeadce446c3c6273ad0238eacc6
Issue: https://github.com/dotnet/corefx/issues/26162
=> Make CreateTrimDependencyGroups use NuGet.Frameworks

src/Microsoft.DotNet.Build.Tasks.Feed/BuildManifest/PushOrchestratedBuildManifest.cs, src/Microsoft.DotNet.Build.Tasks.Feed/BuildManifest/WriteOrchestratedBuildManifestSummaryToFile.cs, src/Microsoft.DotNet.Build.Tasks.Feed/Microsoft.DotNet.Build.Tasks.Feed.csproj, src/Microsoft.DotNet.Build.Tasks.Feed/PackageFiles/Microsoft.DotNet.Build.Tasks.Feed.targets
When these changes are used by the utility repo, we'll get readmes in dotnet/versions like [README.md](https://github.com/dagood/versions/blob/905a3d202ecdcd9293a5f8756ffa522a14b79566/build-info/dotnet/product/test-push-manifest/master/README.md) uploaded alongside the orchestrated build manifest.
@shawnro, does that example readme file have all the info you're looking for? Should I add in the table of Core-Setup (Runtime) installer links, too?
The table is copied from https://github.com/dotnet/cli/blob/master/README.md, but the links are build-specific, acquired from the manifest.
I hard-coded the blob to link associations into the task to keep it simple for now. In the future, I think the best approach is to have the CLI repo pass along this info in the manifest so we don't have to …
=> Push manifest summary/readme along with manifest

src/Microsoft.DotNet.Build.Tasks.Feed/BuildManifest/WriteOrchestratedBuildManifestSummaryToFile.cs, src/Microsoft.DotNet.Build.Tasks.Feed/PackageFiles/Microsoft.DotNet.Build.Tasks.Feed.targets
I noticed that I got lucky that the first blob this code saw was a core-setup one. I added `EndsWith` to distinguish the dotnet runtime vs. aspnet runtime.
@natemcmaster
=> Add aspnet orchestrated build summary

src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/FrameworkTargeting.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/Roslyn.Common.props, src/Microsoft.DotNet.Build.Tasks/PackageFiles/crossgen.sh, src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh, src/Microsoft.DotNet.Build.Tasks/PackageFiles/msbuild.sh
cc: @weshaggard @ericstj 
These are the changes required in order to build corefx successfully on Linux using the MSBuild inside the CLI. I was able to run both `build.sh` and `build-tests.sh` successfully with these changes. These do not include the cleanup of the MSBuild that we restore on the Tools folder since I haven't verified if that is still needed on other repos. It is worth noting that in order to successfully build corefx with this, we require the SDK to be > 2.1. [Here are the changes](https://github.com/joperezr/corefx/commit/1e99cdb873495965d5d913433de6980c46100826) inside corefx that I needed to do in order to get a successful build.
Once this is merged and repos start ingesting this new version, we can take care of cleaning up all of the things that won't be required in …
=> Changes required in order to build corefx on linux using CLI's MSBuild

src/Microsoft.DotNet.Build.Tasks.Feed/BuildManifest/FetchOrchestratedBuildManifestInfo.cs, src/Microsoft.DotNet.Build.Tasks.Feed/BuildManifest/WriteOrchestratedBuildManifestToFile.cs, src/Microsoft.DotNet.Build.Tasks.Feed/PackageFiles/Microsoft.DotNet.Build.Tasks.Feed.targets, src/Microsoft.DotNet.Build.Tasks.Feed/PushToBlobFeed.cs, src/Microsoft.DotNet.VersionTools.Tests/BuildManifest/BuildManifestClientTests.cs, src/Microsoft.DotNet.VersionTools.Tests/BuildManifest/ManifestModelTests.cs, src/Microsoft.DotNet.VersionTools/BuildManifest/Model/BlobArtifactModel.cs, src/Microsoft.DotNet.VersionTools/BuildManifest/Model/BuildIdentity.cs, src/Microsoft.DotNet.VersionTools/BuildManifest/Model/BuildModel.cs, src/Microsoft.DotNet.VersionTools/BuildManifest/Model/EndpointModel.cs, src/Microsoft.DotNet.VersionTools/BuildManifest/Model/OrchestratedBuildModel.cs, src/Microsoft.DotNet.VersionTools/BuildManifest/Model/PackageArtifactModel.cs, src/Microsoft.DotNet.VersionTools/BuildManifest/Model/XElementParsingExtensions.cs, src/Microsoft.DotNet.VersionTools/Util/EnumerableExtensions.cs
Also improve the required attribute mechanism to avoid redundant writes and verify dictionary contents during ToXml.
Core-Setup and CLI will use this to pass `ProductVersion` to the Copy to Latest post-build step (https://github.com/dotnet/buildtools/pull/1871). The repos need to take this change and add `ManifestBuildData="ProductVersion=$(...)"` on `PushToBlobFeed`.
I made `FetchOrchestratedBuildManifestInfo` put the extra info in MSBuild items so I can use it during final publish steps.
ASP.NET Core should pass this too: with all three repos, we can remove some code that derives product version from the blob artifact paths for README generation: https://github.com/dotnet/buildtools/pull/1876#discussion_r164016705, https://github.com/dotnet/buildtools/pull/1881. (I couldn't wait for …
=> Allow custom attributes in build manifest 'BuildIdentity'

src/nuget/Microsoft.DotNet.VersionTools.nuspec
The library compiles against 4.3.0 NuGet, and the package should have the same dependency.
=> Use project.json dependency versions in VersionTools package

src/packages.builds
I jumped to `2.2.0-prerelease` because BuildTools isn't currently on `preview1`-`preview2` naming, and it's next in the scheme after `2.1.x`, but we could go for that to match the Core repos.
=> Produce 2.2.0-prerelease-* packages

src/Microsoft.DotNet.Build.Tasks.Feed/BuildManifest/FetchOrchestratedBuildManifestInfo.cs, src/Microsoft.DotNet.Build.Tasks.Feed/BuildManifest/WriteOrchestratedBuildManifestToFile.cs, src/Microsoft.DotNet.Build.Tasks.Feed/PackageFiles/Microsoft.DotNet.Build.Tasks.Feed.targets, src/Microsoft.DotNet.Build.Tasks.Feed/PushToBlobFeed.cs, src/Microsoft.DotNet.VersionTools.Tests/BuildManifest/BuildManifestClientTests.cs, src/Microsoft.DotNet.VersionTools.Tests/BuildManifest/ManifestModelTests.cs, src/Microsoft.DotNet.VersionTools/BuildManifest/Model/BlobArtifactModel.cs, src/Microsoft.DotNet.VersionTools/BuildManifest/Model/BuildIdentity.cs, src/Microsoft.DotNet.VersionTools/BuildManifest/Model/BuildModel.cs, src/Microsoft.DotNet.VersionTools/BuildManifest/Model/EndpointModel.cs, src/Microsoft.DotNet.VersionTools/BuildManifest/Model/OrchestratedBuildModel.cs, src/Microsoft.DotNet.VersionTools/BuildManifest/Model/PackageArtifactModel.cs, src/Microsoft.DotNet.VersionTools/BuildManifest/Model/XElementParsingExtensions.cs, src/Microsoft.DotNet.VersionTools/Util/EnumerableExtensions.cs, src/nuget/Microsoft.DotNet.VersionTools.nuspec
This brings 2.1 up to speed after initial creation.
Port https://github.com/dotnet/buildtools/pull/1882 (Needed for product build.)
Port https://github.com/dotnet/buildtools/pull/1884 (A VersionTools package fix we might as well include.)
Excludes https://github.com/dotnet/buildtools/pull/1879 because it's not known if it will be in 2.1. (https://github.com/dotnet/core-setup/pull/3646#issuecomment-361707945)
=> Port recent changes to release/2.1

src/packages.builds
Match the Core repo versioning scheme.
See https://github.com/dotnet/buildtools/pull/1888
=> [release/2.1] Produce 2.1.0-preview1-* packages

src/Microsoft.DotNet.Build.CloudTestTasks/AzureBlobLease.cs, src/Microsoft.DotNet.Build.CloudTestTasks/CopyBlobsToLatest.cs, src/Microsoft.DotNet.Build.CloudTestTasks/FinalizeBuild.cs, src/Microsoft.DotNet.Build.CloudTestTasks/Microsoft.DotNet.Build.CloudTestTasks.csproj
Adds `CopyBlobsToLatest` that will be used to finalize both Core-Setup and CLI blobs in product builds. (https://github.com/dotnet/core-eng/issues/2407.) I started with Core-Setup's `FinalizeBuild` with CLI's `CopyBlobsToLatest` as a reference and made changes to generalize. We should be able to use this central implementation in Core-Setup and CLI. We'll need a way to give CLI CloudTestTasks. (Right now, the focus is final publish.)
~`GetBlobProducts` determines what products a set of blobs represents. It's useful to parse this for final publish because we don't have the product version of Core-Setup at this point in the build.~ (Removed: ProductVersion will be passed in from the manifest for final publish.)
Tested on a cut-down manifest in my own `dagood` container on Core-Setup and CLI …
=> Add Finalize/Copy to Latest task for final publish step

src/Microsoft.DotNet.Build.Tasks/PackageFiles/crossgen.sh
=> Fixing crossgen on core-setup by forcing the implicit NuGet fallback folder

src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets
We already add interesting information like @buildBy, and the @srcCode tags to our version information.
However it is still non-trivial to know what branch the build was from.    Adding this.   Now when you do a 
```
filever -v   coreclr.dll
```
You will get something like this
```
ProductVersion  4.6.26201.0 @BuiltBy: vancem-VANCEM1 @Branch: master @SrcCode: https://github.com/dotnet/coreclr/tree/c137bc294620bbf36a7f0130c7d4a17f9e471ed6
```
The new part is the '@Branch: master' in the ProductVersion.   
This allows you to quickly determine if the build you are using came from the release branch (and exactly which one, or from a daily build from the master branch.     You can actually figure this out from the commit, but it is not a completely trivial process.  This makes it easy.
The …
=> Add branch name to version information

src/Microsoft.DotNet.Build.CloudTestTasks/DownloadFromAzure.cs, src/Microsoft.DotNet.Build.CloudTestTasks/UploadClient.cs, src/Microsoft.DotNet.Build.CloudTestTasks/UploadToAzure.cs, src/Microsoft.DotNet.Build.Tasks.Feed/BlobFeed.cs, src/Microsoft.DotNet.Build.Tasks.Feed/BlobFeedAction.cs, src/Microsoft.DotNet.Build.Tasks.Feed/Microsoft.DotNet.Build.Tasks.Feed.csproj, src/Microsoft.DotNet.Build.Tasks.Feed/PushOptions.cs, src/Microsoft.DotNet.Build.Tasks.Feed/PushToBlobFeed.cs, src/Microsoft.DotNet.Build.Tasks/ExecWithRetriesForNuGetPush.cs, src/Microsoft.DotNet.Build.Tasks/PackageFiles/PublishProduct.targets
Added `PassIfExistingItemIdentical` to `UploadToAzure` and `PushToBlobFeed`. The `PushToBlobFeed` implementation works on asset and package pushes.
Push to MyGet is a little more complicated. I used the existing system to ignore error messages and added a new `ConditionalIdenticalOnFeed` metadata that takes a NuGet v2 feed endpoint. If it encounters the 409, it checks the contents of the package on the v2 feed. (v2 for now because it's dead simple. It avoids having to hop through the redirects of v3 or attempting to use the NuGet library packages.)
I tested each path with a new artifact publish, two publishes with the same artifacts, and modifying the artifact on the endpoint before a publish. Seems to work as intended. Haven't done any regression testing except accidentally when I didn't …
=> Add idempotency options to publish tasks

src/Microsoft.DotNet.Build.CloudTestTasks/UploadClient.cs
@trylek  FYI.  We obviously want to rewrite these tasks using the Azure Client SDKs but folks do hit this bug and it's trivial to fix.
=> Open files for upload with Read access

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/DumplingHelper.py
Current Error
``` 
Finished running tests. End time=22:28:24. Return value was 0
xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.
File "/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/bin/tests/System.Json.Tests/netcoreapp-OSX-Release-x64/dumpling.py", line 1
<!DOCTYPE html>
^
SyntaxError: invalid syntax
/usr/bin/python: can't open file '/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/tempHome/.dumpling/dumpling.py': [Errno 2] No such file or directory
Finished:    System.Net.Http.Unit.
```
Error After this
```
Dumpling cannot be installed due to Site Disabled and HTTP Status Code 403
```
=> Checking Status code for downloading dumpling before executing

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/DumplingHelper.py
It seems it doesn't always, despite [the docs](https://docs.python.org/2/library/urllib2.html).
```
2018-02-11T01:44:02.4080300Z   Traceback (most recent call last):
2018-02-11T01:44:02.4095790Z     File "/root/corefx-1372779/Tools/DumplingHelper.py", line 131, in <module>
2018-02-11T01:44:02.4121220Z       main(sys.argv)
2018-02-11T01:44:02.4135960Z     File "/root/corefx-1372779/Tools/DumplingHelper.py", line 113, in main
2018-02-11T01:44:02.4156070Z       install_dumpling()
2018-02-11T01:44:02.4172300Z     File "/root/corefx-1372779/Tools/DumplingHelper.py", line 30, in install_dumpling
2018-02-11T01:44:02.4188550Z       print("Dumpling cannot be installed due to " + e.reason + " and HTTP Status Code " + str(e.code))
2018-02-11T01:44:02.4204590Z   AttributeError: 'HTTPError' object has …
```
=> Fix dumplinghelper.py to not assume HTTPError.reason exists

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/DumplingHelper.py
My previous fix solved the problem of HTTPError.reason not always being present by using `str()` instead. This caused another problem: to MSBuild, `Dumpling cannot be installed due to : HTTP error 403: Site Disabled` looks like standard error format, so absent other instructions, it fails the build.
Fix _that_ by removing any colon.
=> Fix dumplinghelper to not log 'error format'

src/Microsoft.DotNet.Build.Tasks.Feed/BuildManifest/PushOrchestratedBuildManifest.cs, src/Microsoft.DotNet.Build.Tasks.Feed/BuildManifest/UpdateOrchestratedBuildManifest.cs, src/Microsoft.DotNet.Build.Tasks.Feed/PackageFiles/Microsoft.DotNet.Build.Tasks.Feed.targets, src/Microsoft.DotNet.VersionTools.Tests/BuildManifest/BuildManifestClientTests.cs, src/Microsoft.DotNet.VersionTools/BuildManifest/BuildManifestChange.cs, src/Microsoft.DotNet.VersionTools/BuildManifest/BuildManifestClient.cs, src/Microsoft.DotNet.VersionTools/BuildManifest/BuildManifestLocation.cs, src/Microsoft.DotNet.VersionTools/BuildManifest/JoinSemaphoreGroup.cs, src/Microsoft.DotNet.VersionTools/Microsoft.DotNet.VersionTools.csproj
https://github.com/dotnet/core-eng/issues/2614
> `installers.semaphore` and `packages.semaphore` can each be used to trigger steps that rely on a specific type of publishing to complete. This works for some repos' dependency uptake because they only use packages, but others (e.g. dotnet-docker-nightly) need both packages and installers to be published for auto-PR CI to succeed.
> The join semaphores should be created in "finalize" style: when the `installers` and `packages` steps finish, they check to see if the other step already completed for the current build id. If so, it updates the combined semaphore.
This is related to https://github.com/dotnet/buildtools/pull/1907 which will allow us to make package version build-infos (for the Core repos to consume in particular). I haven't …
=>  Implement "join semaphore" groups

src/Microsoft.DotNet.Build.Tasks/PackageFiles/RunnerTemplate.Unix.txt, src/Microsoft.DotNet.Build.Tasks/PackageFiles/RunnerTemplate.Windows.txt
Often I want to run tests as directly as possible (for example to run them easily under a debugger, or to run them in a loop) but it's obfuscated how to do that.
Update the logging to make it easy to see how to do that.
Fix a mistake in the Unix logging.
=> Improve unit test output to show how to repro directly

src/Microsoft.DotNet.Build.Tasks/PackageFiles/ApiCompat.targets
ApiCompat depends on the order of the references, this change ensures that project references come first.
=> Enforce order of references passed to ApiCompat

src/Microsoft.DotNet.Build.Tasks/PackageFiles/msbuild.sh
This is final part of fix for https://github.com/dotnet/corefx/issues/23360
With this following command works as expected.
msbuild.sh  /t:RebuildAndTest /p:XunitOptions="-showprogress -parallel none"
=> use "$@" instead of $* to properly preserve arguments with spaces

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.Helix.targets
Because my initial in-head implementation had this as "MaxDeliveryCount" I made an off by one error in this.
This explains the hurried fixes we had to crank out to deal with this behavior.
=> Fix default MaxRetryCount

src/Microsoft.DotNet.Build.Tasks/PackageFiles/Symbols.targets
The AccessViolationException being worked around should no longer occur. (https://github.com/dotnet/buildtools/issues/1737)
This allows properties such as SkipCreateWindowsPdbsFromPortablePdbs to flow to CreateWindowsPdbsFromPortablePdbs without specifically being passed. (Fixes https://github.com/dotnet/buildtools/issues/1734.)
=> Run PPDB conversion in the same MSBuild process

src/nuget/Microsoft.DotNet.VersionTools.nuspec
This is so that the feed task can consume versiontools as a PackageReference instead of a ProjectReference.  It needs to be able to compile against the desktop implementation.
=> Package VersionTools desktop implementation

src/Microsoft.DotNet.Build.Tasks.Feed/BuildManifest/WriteOrchestratedBuildManifestSummaryToFile.cs
This resolves https://github.com/dotnet/buildtools/pull/1881#discussion_r164246219 and fixes the aspnet readme after the `Runtime/` -> `aspnetcore/Runtime/` move. (It hasn't been produced for recent builds because the assumptions here didn't line up.)
Doing this as part of https://github.com/dotnet/core-eng/issues/2612 since we're generating checksums for aspnet that I plan to include on the readme.
FYI @natemcmaster
=> Use ProductVersion when creating prodcon readmes

src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.props, src/Microsoft.DotNet.Build.Tasks/PackageFiles/checksum.rsp
csc task uses `ChecksumAlgorithm` property to set the checksum algorithm. No need for .rsp file.
=> Use ChecksumAlgorithm property

src/Microsoft.DotNet.VersionTools.net45/Automation/GitHubApi/GitHubClient.Desktop.cs, src/Microsoft.DotNet.VersionTools.net45/Microsoft.DotNet.VersionTools.net45.csproj, src/Microsoft.DotNet.VersionTools/Automation/GitHubApi/GitHubClient.cs
Fixes https://github.com/dotnet/core-eng/issues/2679
Fiddler confirms TLSv1.2 is being used as shown in the snippet below -
```
A SSLv3-compatible ClientHello handshake was found. Fiddler extracted the parameters below.
Version: 3.3 (TLS/1.2)
```
=> Use TLS 1.2 security protocol in GitHubClient

src/Microsoft.DotNet.VersionTools.net45/Automation/GitHubApi/GitHubClient.Desktop.cs, src/Microsoft.DotNet.VersionTools.net45/Microsoft.DotNet.VersionTools.net45.csproj, src/Microsoft.DotNet.VersionTools/Automation/GitHubApi/GitHubClient.cs
(cherry picked from commit 92bd8486db627660500b878c1836a8eff5228467)
---
Ports https://github.com/dotnet/buildtools/pull/1925 to release/2.1 to fix VersionTools GitHub requests on net45.
=> [release/2.1] Use TLS 1.2 security protocol in GitHubClient (#1925)

src/Microsoft.DotNet.VersionTools.net45/Automation/GitHubApi/GitHubClient.Desktop.cs, src/Microsoft.DotNet.VersionTools.net45/Microsoft.DotNet.VersionTools.net45.csproj, src/Microsoft.DotNet.VersionTools/Automation/GitHubApi/GitHubClient.cs
As seen in dotnet/buildtools#1925, just makes sure that when running on desktop we opt in to TLS 1.2 by default.
=> Manual port of dotnet/buildtools#1925

build.proj, dir.props, src/Microsoft.DotNet.Build.Tasks.net45/Microsoft.DotNet.Build.Tasks.net45.csproj, src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj, src/nuget/Microsoft.DotNet.BuildTools.nuspec
This allows us to use the TLS 1.2 UpdatePublishedVersions fix without upgrading the BuildTools toolset version.
Doing this properly (updating the BuildTools toolset version) is tracked by https://github.com/dotnet/buildtools/issues/1934. I hit enough obstacles that I don't think it's in scope for First Responder.
https://github.com/dotnet/core-eng/issues/2734: Unblocks auto-update of `master` BuildTools builds to subscribing repos. This change will need to be ported to `release/2.1`, at least.
=> Use the built tasks to update dotnet/versions

build.proj, dir.props, src/Microsoft.DotNet.Build.Tasks.net45/Microsoft.DotNet.Build.Tasks.net45.csproj, src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj, src/nuget/Microsoft.DotNet.BuildTools.nuspec
This reverts commit f8444e2bfdd036a2de0fcc7041b12ccc22c09168. (https://github.com/dotnet/buildtools/pull/1935)
The fix didn't work: my local validation was using Visual Studio 2017 where the fix apparently isn't needed, but official builds use 2015. `VersionTools.dll` was still being loaded from `Tools\net45\` rather than `bin\`. I haven't seen a clear way to influence the DLL loading dir, so this fix seems like a dead end.
Instead, we can change the official build to use `Tools\dotnetcli\dotnet.exe Tools\MSBuild.exe /t:UpdatePublishedVersions` to update dotnet/versions rather than `build.cmd`. .NET Core doesn't require the TLS1.2 fix. (build.cmd uses the full framework.) This is a cleaner fix anyway. I tried this out and it worked: …
=> Revert "Use the built tasks to update dotnet/versions"

src/Microsoft.DotNet.Build.Tasks/CleanupVSTSAgent.cs
Currently we include directories like "temp", "LocalAppData/Nuget", etc folders in our list of things to be cleaned/removed. The root folder is deleted along with the cleanup and this might lead to build failures as in this issue: https://github.com/dotnet/core-eng/issues/2812
This recreates a "known" folder after the whole contents have been removed.
=> Don't delete additional directory root

src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/Directory.Build.props, src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/Directory.Build.targets
so the tool-runtime project doesn't pick up the Directory.Build.props and targets from the calling repo.
=> Add empty Directory.Build.props and targets files 

src/Microsoft.DotNet.Build.Tasks.Feed.net45/Microsoft.DotNet.Build.Tasks.Feed.net45.csproj, src/Microsoft.DotNet.Build.Tasks.Feed.net45/PushToBlobFeed.Desktop.cs, src/Microsoft.DotNet.Build.Tasks.Feed/PushToBlobFeed.cs
Fixes failure to resolve NuGet.Common, Version=4.3.0.5 from Sleet dependency.
https://github.com/dotnet/core-eng/issues/2828
=> Use AssemblyResolver during PushToBlobFeed

src/Microsoft.DotNet.Build.Tasks/PackageFiles/RunnerTemplate.Unix.txt
- The dumps were in $EXECUTION_DIR. Pushd to that to find them.
- Corerun is someplace else. Use $RUNTIME_PATH/dotnet instead. It's what we actually ran, anyway.
- Add random suffix to keep more than one old dump
Tested locally by using `kill -SIGABRT` on running tests.
Fixes https://github.com/dotnet/corefx/issues/27818
=> Fix dumping stack from test coredumps on Linux

src/Microsoft.DotNet.Build.Tasks/DownloadFilesFromUrl.cs
Extract async task to avoid swallowing of TaskCanceledException from HttpClient.GetStreamAsync() in DownloadFilesFromUrl
=> Extract async task to avoid swallowing of TaskCanceledException

src/Microsoft.DotNet.Build.Tasks/PackageFiles/ApiCompat.targets
There are a lot of libraries that have a 1:1 ref and implementation
which want to keep the API surface in sync. In order to enforce that
we have a reverse APICompat check that will verify that the ref
has a matching compatibile set of APIs that the implementation has.
This target is called RunMatchingRefApiCompat. It is only enabled
if RunApiCompat=true and there are no ReferenceFromRuntime references.
It is skipped for projects with runtime references because those are
typically many implementation to one ref which doesn't work as well
for verifying the APIs match.
It can be individually controlled per-project:
1) RunMatchingRefApiCompat = false to disable the check completely
2) Add a baseline file MatchingRefApiCompatBaseline[.$(TargetGroup)]txt
Should address …
=> Add target reverse APICompat check for libraries

src/packages.builds
This matches what the Core repos are doing in `master` to make room for `release/2.1` starting preview2 builds.
=> Produce 2.1.0-preview3-* packages

src/Microsoft.DotNet.Build.Tasks/PackageFiles/partialfacades.task.targets
The current check enables PDB generation only when the assembly is
being built as Windows-specific.  What it really means is that the
GenFacades PDB writer crashes on non-Windows systems, and thus that PDBs
cannot be generated when running on non-Windows.
This corrects the check to be about what OS the tool is executing on,
rather than what OS the binary is intended for.
AnyOS partial facades will now produce PDBs on Windows, allowing them
to run code coverage.
=> Fix partial facade PDB generation for AnyOS libraries

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/DumplingHelper.py
Fixes https://github.com/dotnet/corefx/pull/28225#issuecomment-374409319
Earlier Version
```
Traceback (most recent call last):
File "src\Microsoft.DotNet.Build.CloudTestTasks\PackageFiles\DumplingHelper.py", line 131, in <module>
main(sys.argv)
File "src\Microsoft.DotNet.Build.CloudTestTasks\PackageFiles\DumplingHelper.py", line 113, in main
install_dumpling()
File "src\Microsoft.DotNet.Build.CloudTestTasks\PackageFiles\DumplingHelper.py", line 34, in install_dumpling
print("An unexpected error was encountered while installing dumpling.py: " + sys.exc_info()[0])
TypeError: cannot concatenate 'str' and 'type' objects
```
New Version
```
An unexpected error was encountered while installing dumpling.py: Traceback (most recent call last):
File …
```
=> Using traceback library to give call stack

src/GenFacades/GenFacades.Core/GenFacades.cs, src/Microsoft.DotNet.Build.Tasks/PackageFiles/partialfacades.task.targets
Our genfacades task targets file was missing some options we support
this exposes those as properties.
This change also includes a fix in GenFacades tool to force all
assembly references to 0.0.0.0 when the option is set. Currently it
forces all the seed assemblies to 0.0.0.0 but not any pre-existing
references from our partial facade inputs. This change will force those
to 0.0.0.0 as well.
cc @ericstj
=> Update GenFacades targets to support all options

src/GenFacades/GenFacades.Core/GenFacades.cs, src/Microsoft.DotNet.Build.Tasks/PackageFiles/partialfacades.task.targets
Porting https://github.com/dotnet/buildtools/pull/1970 to release/2.0.0
Our genfacades task targets file was missing some options we support
this exposes those as properties.
This change also includes a fix in GenFacades tool to force all
assembly references to 0.0.0.0 when the option is set. Currently it
forces all the seed assemblies to 0.0.0.0 but not any pre-existing
references from our partial facade inputs. This change will force those
to 0.0.0.0 as well.
cc @ericstj
=> [release/2.0.0] Update GenFacades targets to support all options

src/Microsoft.DotNet.Build.Tasks/PackageFiles/VersionTools.targets, src/Microsoft.DotNet.Build.Tasks/VersionTools/BaseDependenciesTask.cs, src/Microsoft.DotNet.Build.Tasks/VersionTools/UpdateToRemoteDependencies.cs, src/Microsoft.DotNet.VersionTools/BuildManifest/BuildManifestClient.cs, src/Microsoft.DotNet.VersionTools/Dependencies/BuildManifest/OrchestratedBuildDependencyInfo.cs, src/Microsoft.DotNet.VersionTools/Dependencies/Submodule/OrchestratedBuildSubmoduleUpdater.cs, src/Microsoft.DotNet.VersionTools/Microsoft.DotNet.VersionTools.csproj, src/Microsoft.DotNet.VersionTools/Util/GitCommand.cs
This will be used by source-build to move the submodules to the hashes that were successful in the latest orchestrated build.
Setting this up in source-build: https://github.com/dagood/source-build/commit/47918930761a74b6b92f9f432cec8b7839a52596. To avoid duplicating info outside the project files, I used the MSBuild task and Target output flow @eerhardt suggested a while back.
https://github.com/dotnet/source-build/issues/342
=> Update submodules from ProdCon orchestrated build manifests

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/DumplingHelper.py
Related to https://github.com/dotnet/corefx/pull/28211#issuecomment-374684879
Master PR - https://github.com/dotnet/buildtools/pull/1969
Earlier Version
```
Traceback (most recent call last):
File "src\Microsoft.DotNet.Build.CloudTestTasks\PackageFiles\DumplingHelper.py", line 131, in <module>
main(sys.argv)
File "src\Microsoft.DotNet.Build.CloudTestTasks\PackageFiles\DumplingHelper.py", line 113, in main
install_dumpling()
File "src\Microsoft.DotNet.Build.CloudTestTasks\PackageFiles\DumplingHelper.py", line 34, in install_dumpling
print("An unexpected error was encountered while installing dumpling.py: " + sys.exc_info()[0])
TypeError: cannot concatenate 'str' and 'type' objects
```
New Version
```
An unexpected error was encountered while installing dumpling.py: Traceback (most recent …
```
=> using traceback to get call stack 

src/Microsoft.DotNet.Build.Tasks/PackageFiles/VersionTools.targets, src/Microsoft.DotNet.Build.Tasks/VersionTools/BaseDependenciesTask.cs, src/Microsoft.DotNet.Build.Tasks/VersionTools/UpdateToRemoteDependencies.cs, src/Microsoft.DotNet.VersionTools/BuildManifest/BuildManifestClient.cs, src/Microsoft.DotNet.VersionTools/Dependencies/BuildManifest/OrchestratedBuildDependencyInfo.cs, src/Microsoft.DotNet.VersionTools/Dependencies/Submodule/OrchestratedBuildSubmoduleUpdater.cs, src/Microsoft.DotNet.VersionTools/Microsoft.DotNet.VersionTools.csproj, src/Microsoft.DotNet.VersionTools/Util/GitCommand.cs
Adds an updater and dependency info that allow updating submodules from an orchestrated build manifest created by a successful ProdCon build.
(cherry picked from commit fbe388dcfb86968a5405616664a6b3528ae5e862)
---
Ports https://github.com/dotnet/buildtools/pull/1968 to `release/2.1`, where source-build `dev/release/2.1` is pulling BuildTools versions from.
https://github.com/dotnet/source-build/issues/342
=> [release/2.1] Update submodules from orchestrated build manifest

src/Microsoft.Cci.Extensions/Filters/DocIdExcludeListFilter.cs, src/Microsoft.Cci.Extensions/Filters/DocIdIncludeListFilter.cs, src/Microsoft.Cci.Extensions/Traversers/SimpleTypeMemberTraverser.cs
Before it only excluded empty namespaces, now we support the exclude list too.
This simplifies lists such as https://github.com/dotnet/standard/blob/64bdab44e93e4f156b677f36ccebd528b0cae7c3/platforms/xamarin.android/apiExcludeList.txt since whole namespaces can be excluded.
=> Allow excluding namespaces via DocId in Microsoft.Cci.Extensions

src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
This reverts commit e8f73c0d8d8891fddacc344ddda1e702015d5dbd.
This commit causes other issues like https://github.com/dotnet/corefx/issues/26390
we need to revert and find another solution to the original issue
https://github.com/dotnet/corefx/issues/26129
cc @ericstj @joperezr
=> Revert "Filter out empty dependencies from promotion consideration"

src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets
Previously I tried to include the GIT branch name in the versioning information.   I used the 
rev-parse command , which worked locally but does not work if you don't have a local branch (which 
is what we do when we build in our automation).   The result is we get a unhelpful 'HEAD' as the 
name of the commit.
Changed this to use 'git describe -all' which should use all the remote branches as well.   I also changed
the logic so that if we don't get something reasonably sane out of 'git describe' I give up and don't put
any branch information in.  
I have tested this locally, but it still may need tweeks.   Still at worst it doesn't include branch information.
=> Make finding the branch from GIT more robust.

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/DumplingHelper.py
Previous error
```
An unexpected error was encountered while installing dumpling.py: Traceback (most recent call last):
File "C:\git\buildtools\src\Microsoft.DotNet.Build.CloudTestTasks\PackageFiles\DumplingHelper.py", line 21, in install_dumpling
response = urllib2.urlopen(url)
File "C:\Python27\lib\urllib2.py", line 154, in urlopen
return opener.open(url, data, timeout)
File "C:\Python27\lib\urllib2.py", line 429, in open
response = self._open(req, data)
File "C:\Python27\lib\urllib2.py", line 447, in _open
'_open', req)
File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
result = func(*args)
File "C:\Python27\lib\urllib2.py", line 1241, in https_open
context=self._context)
File "C:\Python27\lib\urllib2.py", line 1195, in do_open
h.request(req.get_method(), req.get_selector(), …
```
=> Dumpling Url Updated to dumpling.int-dot.net 

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.Helix.targets, src/Microsoft.DotNet.Build.CloudTestTasks/ValidateWorkItems.cs
Addresses https://github.com/dotnet/core-eng/issues/2989
=> Fix validate workitem task when there are 0 workitems

src/Microsoft.DotNet.Build.Tasks/PackageFiles/crossgen.sh
```
Tools/crossgen.sh: line 21: NoWarn: command not found
```
Simply escape the dollar sign so the shell doesn't interpret it.
=> Fix NoWarn warning in builds

src/Microsoft.DotNet.Build.Tasks/PackageFiles/RunnerTemplate.Unix.txt
Fixes https://github.com/dotnet/corefx/issues/28509
Sample output wrt to https://github.com/dotnet/corefx/pull/27899
```
Discovering: System.Collections.Specialized.Tests
Discovered:  System.Collections.Specialized.Tests
Starting:    System.Collections.Specialized.Tests
/git/corefx/bin/tests/System.Collections.Specialized.Tests/netcoreapp-Linux-Debug-x64/RunTests.sh: line 100: 40236 Segmentation fault      (core dumped) $RUNTIME_PATH/dotnet xunit.console.netcore.exe System.Collections.Specialized.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonlinuxtests -notrait category=OuterLoop -notrait category=failing
/git/corefx/src/System.Collections.Specialized/tests
----- end 07:14:51 ----- exit code 139 …
```
=> Printing Managed Call stack, native call stack and managed exceptions using lldb

src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.props, src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets
When repo's try to use pieces of buildtools, they get warnings because the versioning.props file is already imported.  This change checks the versioning.props file is already imported, and not importing it again.
=> Allow versioning.props to be imported directly.

src/Microsoft.DotNet.Build.Tasks/PackageFiles/RunnerTemplate.Unix.txt
Related to https://github.com/dotnet/buildtools/issues/1995
Running lldb output only when the task fails
=> Disabling lldb

src/xunit.console.netcore/Visitors/StandardOutputVisitor.cs, src/xunit.console.netcore/xunit.console.netcore.csproj
This is meant to improve our ability to triage hanging tests in CI runs. 
It is also somewhat temporary fix. The whole Visitor class is obsolete in current version on Xunit (2.3.x) and it will need to be re-written when we upgrade. 
In mean time, this should provide some more insight. It won't fore-fail tests (yet) but it should provide more visibility. 
I tested this using private tests with sleep as well as I followed instructions for dog-fooding and I modified one of HTTP tests to have incorrect async await. When I run the test, after 5 minutes I see following console output:
> Discovering: System.Net.Http.Functional.Tests
> Discovered:  System.Net.Http.Functional.Tests
> Starting:    System.Net.Http.Functional.Tests
>    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientMin …
=> detect long running tests and print out warning on console

src/Microsoft.DotNet.Build.Tasks/GenerateResourcesCode.cs, src/Microsoft.DotNet.Build.Tasks/PackageFiles/resources.targets
I needed the ability to generate an SR file that only has constant IDs in it, ala the old desktop source.  I added this as an option on GenerateResourcesCode.  It's opt-in on a per-project basis so it does nothing as is.  Projects that opt-in will need to call SR.GetResourceString themselves in order to get the actual resource string.
While I was at it I refactored the code here a bit to be more readable and removed the DebugOnly property which doesn't appear to be used by anyone.
I've validated that my changes produce white-space-only diff in the generated SR files corefx.
=> Generate resources code.refactor

dir.props, src/xunit.console.netcore/Visitors/StandardOutputVisitor.cs
Currently our official builds still have msbuild 15 and an
older compiler so to prevent breaks we are pinning the version.
This also fixes the current breaks.
Fixes break in https://github.com/dotnet/buildtools/pull/1992/files#r180842286
cc @wfurt
=> Pin to LangVersion 6 to match our official build machines

src/Microsoft.DotNet.Build.Tasks/PackageFiles/PerfTesting.targets
- About the run types:
- Profile run is the existing one with the addition of `Allocated bytes in current thread`
-    Profile: Stopwatch Time, Clr Etw events, Allocated bytes in current thread.
- Diagnostic: Stopwatch Time, Clr Etw events, Allocated bytes in current thread, Branch Mispredictions, Cache Misses, Instructions Retired.
- In addition, cleaned up the `PerfTesting.targets` file by removing a lot of duplication.
=> Enable Profile and Diagnostic performance runs on CoreFx.

src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
fedora.23-x64, opensuse.13.2-x64, and ubuntu.16.10-x64 are no longer supported RIDs
Don't validate for them (even if they would work on portable RID packages).
=> Remove legacy RIDs from testing

src/Microsoft.DotNet.Build.Tasks.Feed/BlobFeedAction.cs, src/Microsoft.DotNet.Build.Tasks.Feed/PushToBlobFeed.cs
This change allows the task to be called with an optional MakeContainerPublic param that can be overridden to create a private container.
=> Add ability to make feed container private even if no token is present

src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
Port of change https://github.com/dotnet/buildtools/pull/2015.
Needed to fix package validation when moving to the latest SDK. 
PTAL @ericstj
=> [release/2.1] Update supported ri ds for package validation

.toolversions
This should fix the errors encountered on official builds while trying to publish to Azure Feeds and the feed is locked.
=> Updating 'Microsoft.DotNet.Build.Tasks.Feed' version

.toolversions, src/Microsoft.DotNet.Build.Tasks.Feed/PackageFiles/Microsoft.DotNet.Build.Tasks.Feed.targets
Before it was pointing to a target that no longer existed. Also reverted the version to the previous one so this is actually published. Will need to update the version to the package containing this change in a following PR
=> Updating DefaultTarget property

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/DumplingHelper.py
This adds in the steps that we need to ensure that we are able to do
triage of the dumps before they are uploaded so that we can get failing
stack information.
=> Add triage step to dumpling upload

src/xunit.console.netcore/CommandLine.cs, src/xunit.console.netcore/Filters/ExtendedXunitFilters.cs, src/xunit.console.netcore/Program.cs, src/xunit.console.netcore/Project/ExtendedXunitProject.cs, src/xunit.console.netcore/Utility/TransformFactory.cs, src/xunit.console.netcore/xunit.console.netcore.csproj
Workaround until https://github.com/xunit/xunit/issues/1701 is resolved. 
This allows methods/namespaces and classes to be skipped via command line switches.
This doesn't support regex or wildcards, so the names passed need to include a fully-qualified namespace. 
@weshaggard, could you take a look?
cc @sergiy-k
=> Add XUnitFilter wrapper to exclude Methods, Classes and Namespaces

src/Microsoft.DotNet.Build.Tasks/OpenSourceSign.cs
Fixes https://github.com/dotnet/corefx/issues/29495
The OpenSourceSign task modifies the file in place. It also has a test when it runs that the file has not been already signed. Its execution is gated by comparing the assembly timestamp against a fake file with the extension ".oss_signed" which is written after the task executes.
Modifying a file in place is not good practice for builds because it is hard to fail atomically. Eg., if the build is interrupted between the signing and the writing of the ".oss_signed" file then the next build will attempt to sign again and get the error. There are likely other failure modes.
Options to fix include 
(1) signing to a new location (note - signing to a temporary location then renaming back does not count.)
(2) stop erroring when file is already …
=> Fix 'File is already strong-name signed'

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.Helix.targets, src/common/ZipFileCreateFromDirectory.cs
Issues when using this directly from NuPKg reference:
- Don't try to create directory if the destination directory is fully unset.
- ToolsDir isn't set in this case; if it's unset make it be the directory the .targets is in.
@adityapatwardhan FYI.
=> Fix a couple issues noted with standalone CloudTest targets usage

src/GenFacades/GenFacades.Core/GenFacades.cs, src/Microsoft.DotNet.Build.Tasks/GenFacadesTask.cs
Relates to https://github.com/dotnet/corefx/pull/29813
=> Make GenFacades errors appear in MSbuild logs

src/xunit.netcore.extensions/Attributes/ConditionalClassAttribute.cs, src/xunit.netcore.extensions/Discoverers/ConditionalClassDiscoverer.cs, src/xunit.netcore.extensions/Discoverers/ConditionalTestDiscoverer.cs, src/xunit.netcore.extensions/Discoverers/SkipOnTargetFrameworkDiscoverer.cs, src/xunit.netcore.extensions/xunit.netcore.extensions.csproj
This new attribute can help to disable an entire test class based on runtime information/conditions, instead of using `[ConditionalFact/Theory]` for each test method.
[ConditionalClass] is similar to [ConditionalFact/Theory], but here are the differences:
1. Implements ITraitAttribute, and has a `GetTraits` method returning an IEnumerable<KeyValuePair<string, string>> to skip test run.
- The downside for this approach is that, we are not returning test cases (as `[ConditionalFact/Theory]` will do). So it won't notify developer how many test cases are "skipped", instead just silently not running them (behave like `ActiveIssue` and `SkipOnTargetFramework`).
2. Only has one ctor which accepts `Type` and `string[]`. 
- Since [ConditionalClass] is used to disable the entire test class, we …
=> Add new [ConditionalClass] attribute 

src/Microsoft.DotNet.Build.Tasks/GenFacadesTask.cs
Previously some detailed errors/warnings/messages were not reaching the build log at all. Recent change fixed that but there are some errors in CoreFX. Temporarily changing errors to warnings while the cause is fixed.
https://github.com/dotnet/corefx/issues/29861
=> Workaround new errors from genfacades

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/Dumpling.targets
We need psutil install for the dumpling script to work. This will ensure
that we have it installed on the machine before we use it.
=> Add pip install of psutil

src/Microsoft.DotNet.Build.Tasks/GenerateResourcesCode.cs, src/Microsoft.DotNet.Build.Tasks/PackageFiles/resources.targets
Previously I added support for customizing the namespace and class name of the generated
SR class.  This led to some duplication of the common SR source
with the new namespace / class name.
To better handle this I'll allow reuse of the common source.
In conjunction with this change the common SR can be changed as follows:
```C#
#if CUSTOM_SR_NAMESPACE
using System;
namespace #CUSTOM_SR_NAMESPACE#
#else
namespace System
#endif
{
#if CUSTOM_SR_CLASSNAME
internal partial class #CUSTOM_SR_CLASSNAME#
#else
internal partial class SR
#endif
```
This change need not be made in order to ingest the changes, only if folks want to use the changes.
In addition to this I also am fixing a problem where we need to qualify System.Type when specifying a non-system namespace.
All of these changes are …
=> Better handle renamespacing SR

src/Microsoft.DotNet.Build.Tasks/PackageFiles/crossgen.sh
Addresses #2050
@weshaggard, this is backwards compatible change. We can probably remove the `case` block once/if the usage is updated everywhere.
=> Update crossgen.sh to accept RID arg

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/Dumpling.targets
We need to set CrashDumpFolder to unblock https://github.com/dotnet/corefx/pull/29965
```text
15:02:13 D:\j\workspace\windows-TGrou---c60886e1\Tools\Dumpling.targets(48,5): error : CrashDumpFolder must be set to use Dumpling on Windows. [D:\j\workspace\windows-TGrou---c60886e1\src\System.Security.Cryptography.Xml\tests\System.Security.Cryptography.Xml.Tests.csproj]
```
cc @DrewScoggins, @Anipik
=> Set CrashDumpFolder on Windows and create folder if it doesn't exist.

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/Dumpling.targets
Resolves the failures seen in https://github.com/dotnet/corefx/pull/29965.
https://mc.dot.net/#/user/ahsonkhan/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/a674b4ff48a0f4962b7dbe7406eabf17e2d92658/workItem/System.IO.Compression.Tests/wilogs
```text
2018-05-30 20:53:11,394: INFO: proc(54): run_and_log_output: Output: C:\dotnetbuild\work\9eacf393-d860-4035-b461-aaa39e2a3ab4\Work\f970046d-c748-42f9-9823-8f2f1a15c1e9\Unzip>python -m pip install psutil 
2018-05-30 20:53:11,394: INFO: proc(54): run_and_log_output: Output: 'python' is not recognized as an internal or external command,
2018-05-30 20:53:11,394: INFO: proc(54): run_and_log_output: Output: operable program or batch file.
```
cc @DrewScoggins, @MattGal
=> Use HELIX_PYTHONPATH instead of python directly since it may not be on the path.

src/Microsoft.DotNet.Build.CloudTestTasks/SendJobsToHelix.cs
…  give it a 30 second timeout and allow retrying.
@sunandabalu FYI.  You inspired me to learn about something we're doing wrong in many , many places.
=> Fix TaskCancelledException seen on HttpClient timeout

src/Microsoft.DotNet.Build.Tasks/VersionTools/BaseDependenciesTask.cs, src/Microsoft.DotNet.VersionTools/Dependencies/BuildManifest/OrchestratedBuildIdentityMatch.cs, src/Microsoft.DotNet.VersionTools/Dependencies/BuildOutput/FilePackageUpdater.cs, src/Microsoft.DotNet.VersionTools/Dependencies/BuildOutput/OrchestratedBuild/FileOrchestratedBuildCustomUpdater.cs, src/Microsoft.DotNet.VersionTools/Dependencies/BuildOutput/OrchestratedBuild/FileRegexOrchestratedBuildCustomUpdater.cs, src/Microsoft.DotNet.VersionTools/Dependencies/BuildOutput/OrchestratedBuild/OrchestratedBuildUpdateHelpers.cs, src/Microsoft.DotNet.VersionTools/Dependencies/DependencyReplacement.cs, src/Microsoft.DotNet.VersionTools/Dependencies/FileUpdater.cs, src/Microsoft.DotNet.VersionTools/Dependencies/Submodule/OrchestratedBuildSubmoduleUpdater.cs, src/Microsoft.DotNet.VersionTools/Microsoft.DotNet.VersionTools.csproj
* Build attribute from orchestrated build
* Orchestrated blob feed attribute
* Orchestrated blob feed package version
Each updater can update a single-line file (e.g. BuildToolsVersion.txt) or make changes based on regex (with ElementName shortcut for XML).
Also fixes issue with CRLF/LF handling when updating a single-line file when autocrlf isn't set consistently with the running platform.
(cherry picked from commit 338f4b059ef26b1ee718aafca49cfb6cf69e7d6a)
---
Ports https://github.com/dotnet/buildtools/pull/2047 to `release/2.1`. No conflicts.
=> [release/2.1] Implement additional ProdCon manifest updaters

src/Microsoft.DotNet.Build.Tasks/PackageFiles/PerfTesting.targets
1. Profile runs are not the same across operating systems because on Windows it collects extra information through Etw. In order to make results comparable across operating systems, I am changing how metrics are collected.
* Profile now becomes time-only (stopwatch)
* Diagnostic now becomes everything else: Clr events, GC API metrics, Pmc, Stopwatch, etc.
2. Fixed a file operator for bash: replaced `-a` (considered deprecated) with `-f`
=> Updating collected metrics.

src/Microsoft.DotNet.Build.Tasks/PackageFiles/ReferenceAssemblies.targets
We've stopped putting all security annotations on our assemblies so this should be removed as well.
=> Don't mark ReferenceAssemblies with APTCA

src/Microsoft.DotNet.Build.Tasks/PackageFiles/FrameworkTargeting.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/GenerateAssemblyInfo.NonSdk.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/GenerateAssemblyInfo.Sdk.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets
- Don't import Microsoft.$(Language).targets in buildtools - the SDK will do that.
- Use the Sdk's GenerateAssemblyInfo target when possible
Still support non-SDK projects for backwards compatiblity.
Note: I removed support for @(AssemblyInfoSource) during GenerateAssemblyInfo because it is no longer used as of dotnet/corefx/pull/30400.
=> Support using the Microsoft.NET.Sdk with dotnet/buildtools

src/Microsoft.DotNet.Build.Tasks/PackageFiles/GenerateAssemblyInfo.Sdk.targets
There are some test projects that don't set AssemblyMetadata, and are failing to build using the Microsoft.NET.Sdk.  The fix is to not generate an assembly attribute in these cases.
=> Fix compile error when AssemblyMetadata is empty.

src/Microsoft.DotNet.Build.Tasks/PackageFiles/CodeCoverage.targets
This is another part of https://github.com/dotnet/corefx/issues/23588
This one replaces CoreLib crossgen in coverage runs that specified it as one of the included assemblies. It tries to restore the crossgen version at the end of the coverage run, but also whenever starting any test to avoid running against the IL version unexpectedly.
=> Replaces CoreLib with respective IL when doing coverage runs

src/Microsoft.DotNet.Build.Tasks.net45/Microsoft.DotNet.Build.Tasks.net45.csproj, src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj, src/Microsoft.DotNet.Build.Tasks/VersionTools/BaseDependenciesTask.cs, src/Microsoft.DotNet.VersionTools/Dependencies/BuildManifest/OrchestratedBuildDependencyInfo.cs, src/Microsoft.DotNet.VersionTools/Dependencies/BuildManifest/OrchestratedBuildIdentityMatch.cs, src/Microsoft.DotNet.VersionTools/Dependencies/BuildOutput/OrchestratedBuild/OrchestratedBuildUpdateHelpers.cs, src/Microsoft.DotNet.VersionTools/Dependencies/FileRegexUpdater.cs, src/Microsoft.DotNet.VersionTools/Dependencies/FileUpdater.cs, src/nuget/Microsoft.DotNet.BuildTools.nuspec
On-disk manifest allows you to download or generate a manifest, then use it to update without uploading it to GitHub (dotnet/versions) first.
`SkipIfNoReplacementFound` reduces the maintenance burden in source-build. Right now we have to disable updaters when ProdCon stops building particular repos. More importantly, we have to remember to enable them again later or we start missing updates. With this attribute, we can leave the updaters enabled all the time.
If this looks ok to merge, I'm porting to `release/2.1` immediately.
=> Allow auto-updating from on-disk ProdCon manifest; add SkipIfNoReplacementFound

src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.props
We need to address https://github.com/dotnet/buildtools/issues/1186 in 1.0 tools because the 1.0 servicing branches moved passed the pinned microbuild version.
Ports https://github.com/dotnet/buildtools/pull/1199 and https://github.com/dotnet/buildtools/pull/1200
cc @wtgodbe @ericstj
=> [release/1.0.0] Import MicroBuild props

src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj, src/nuget/Microsoft.DotNet.BuildTools.nuspec
This allows GenFacades (and other tasks that depend on DiaSymReader) to use DiaSymReader on .NET Core's MSBuild.
This is needed in order to get corefx's build on Windows to use .NET Core MSBuild.
=> Package Microsoft.DiaSymReader assemblies in buildtools nuget package.

src/Microsoft.DotNet.Build.CloudTestTasks/project.json, src/Microsoft.DotNet.Build.Tasks.Feed/project.json, src/Microsoft.DotNet.Build.Tasks.Packaging/src/project.json, src/Microsoft.DotNet.Build.Tasks.Packaging/test/project.json, src/Microsoft.DotNet.Build.Tasks/project.json
This fixes the build errors https://github.com/dotnet/corefx/pull/30675. As it exists currently, the old MSBuild packages pull in references to System.Resources.ReaderWriter, which no longer exists. Thus when building on .NET Core's MSBuild, our tasks fail because that assembly can't be found.
Updating to an officially supported MSBuild package version updates the transitive references to System.Resources.Reader, which exists in the shared framework.
=> Update MSBuild references to `15.1.548`.

src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
VS2015 tools are less forgiving: the two tasks that I added to tests.targets were under an ItemGroup and that is fine for VS2017 tools, but for VS2015 they need to be at the Target level. This should fix the issues with https://github.com/dotnet/coreclr/pull/18694
=> Fix build for VS2015 tools

src/Microsoft.DotNet.Build.Tasks/GenerateEncryptedNuGetConfig.cs, src/Microsoft.DotNet.Build.Tasks/PackageFiles/OptionalTooling.targets
Need to add support for MSBuild projects instead of project.json files, so builds running on .NET Core can restore optional tooling.
Partial change for https://github.com/dotnet/corefx/issues/30758
=> Fix OptionalTooling so it works on .NET Core

src/Microsoft.DotNet.Build.Tasks/PackageFiles/FrameworkTargeting.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/partialfacades.task.targets, src/Microsoft.DotNet.Build.Tasks/UpdateVSConfigurations.cs
1. Turn off FillPartialFacadeUsingTask during design-time builds. These builds don't produced output assemblies, and the task fails if there is no output assembly.
2. The design-time builds run targets in a different order than with the legacy .csproj format. Hook our targets into different locations to make VS design-time builds work correctly.
3. Update UpdateVSConfigurations to write out .sln and .csproj files for SDK-style projects.
See https://github.com/dotnet/project-system/blob/master/docs/configurations.md for more information on the VS configurations change for the new project system.
=> Add BuildTools support for SDK-style projects in VS.

src/Microsoft.DotNet.Build.Tasks/GenerateResourcesCode.cs, src/Microsoft.DotNet.Build.Tasks/PackageFiles/resources.targets
/cc @tarekgh 
One remaining mode to address porting of desktop code.  Some libraries used an Enum to represent resource IDs.  I ran into a case where one library was mapping a range of that enum to a range of error codes and relying on a numeric conversion.
EG: resourceId = (ResourceEnumType) (ResourceEnumType.FirstErrrorId + (errorCode - firstErrorCode))
=> Add support for generating resource IDs as an enum

src/Microsoft.DotNet.Build.Tasks/PackageFiles/RunnerTemplate.Unix.txt
https://github.com/dotnet/coreclr/pull/18160 and https://github.com/dotnet/coreclr/pull/18213 added a new `dumpasync` command to sos that will dump out data on async methods currently in use.  Including this in the core dump analysis has similar value to dumping out all call stacks, in that it'll give us more details into what was going on in the process.
cc: @danmosemsft, @Anipik
=> Include dumpasync command when evaluating core dumps

src/Microsoft.DotNet.Build.Tasks/VersionTools/BaseDependenciesTask.cs, src/Microsoft.DotNet.VersionTools/Dependencies/FileUpdater.cs
Add `ReplacementSubstituteOld` / `ReplacementSubstituteNew`, which can be used to replace a part of the new value being updated to.
---
This continues from https://github.com/dotnet/buildtools/pull/2069 "Allow auto-updating from on-disk ProdCon manifest". The on-disk manifest might not have the exact values the repo should auto-update to.
Originally I was going to modify the manifest itself (https://devdiv.visualstudio.com/DevDiv/_git/DotNet-Orchestration-Utilities/pullrequest/128309) but here the logic is more flexible and might be useful for other things.
Used for https://github.com/dotnet/core-eng/issues/3815.
=> Support simple auto-update value substitutions

src/Microsoft.DotNet.Build.Tasks.net45/Microsoft.DotNet.Build.Tasks.net45.csproj, src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj, src/Microsoft.DotNet.Build.Tasks/VersionTools/BaseDependenciesTask.cs, src/Microsoft.DotNet.VersionTools/Dependencies/BuildManifest/OrchestratedBuildDependencyInfo.cs, src/Microsoft.DotNet.VersionTools/Dependencies/BuildManifest/OrchestratedBuildIdentityMatch.cs, src/Microsoft.DotNet.VersionTools/Dependencies/BuildOutput/OrchestratedBuild/OrchestratedBuildUpdateHelpers.cs, src/Microsoft.DotNet.VersionTools/Dependencies/FileRegexUpdater.cs, src/Microsoft.DotNet.VersionTools/Dependencies/FileUpdater.cs
Port:
https://github.com/dotnet/buildtools/pull/2069 Allow auto-updating from on-disk ProdCon manifest; add SkipIfNoReplacementFound
https://github.com/dotnet/buildtools/pull/2088 Support simple auto-update value substitutions
These are needed for source-build `release/2.1` auto-update: https://github.com/dotnet/core-eng/issues/3815.
=> [release/2.1] Port orchestrated build manifest updater enhancements

src/Microsoft.DotNet.Build.Tasks/PackageFiles/ReferenceAssemblies.targets
When using SDK-style projects, Microsoft.Common.targets are getting imported before buildtools' targets. Thus when we overwrite $(OutputPath), we need to also reset the other output properties.
Fixes the issue described here https://github.com/dotnet/corefx/pull/29831#discussion_r200525701
=> Need to re-default output properties after writing $(OutputPath).

src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.props
With this, corefx can build on FreeBSD without having to pass -OSGroup=FreeBSD every time.
Note that I was puzzled for a while as even with OSGroup set, tests would still target Linux. 
That is caused by:
```
tests.targets:    <TargetOS Condition="'$(TargetOS)' == ''">$(DefaultOSGroup)</TargetOS>
```
using DefaultOSGroup instead of OSGroup seems wrong here. 
However since my fix fixes DefaultOSGroup, it will also fix test script generation. 
So the risk is for next OS.
=> add recognition for FreeBSD

src/Microsoft.DotNet.Build.Tasks.Feed/BlobFeed.cs
Should end up making the PushToBlobFeed task a little more resilient to random network failures on our end.
Follows a similar retry pattern as the SendToHelix task.
=> Add retries to CheckIfBlobExistsAsync

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/Dumpling.targets
Coverage runs are without dumplings due to the dependency on HELIX_PYTHONPATH env var. 
On my local box I noticed the following:
1. DumplingHelper.py requires Python 2.7 (no problem, just noticing)
2. My runs on local box report:
```
Traceback (most recent call last):
File "C:\s\github\pjanotti\corefx\bin\tests\System.Net.Mail.Unit.Tests\netcoreapp-Windows_NT-Debug-x64/dumpling.py", line 18, in <module>
ImportError: No module named requests
C:\Python27\python.exe: can't open file 'C:\Users\pauloja/.dumpling/dumpling.py': [Errno 2] No such file or directory
C:\Python27\python.exe: can't open file 'C:\Users\pauloja/.dumpling/dumpling.py': [Errno 2] No such file or directory
```
not sure if this is something to pursue or not.
=> Fix python path for coverage runs

src/Microsoft.DotNet.Build.Tasks/GenerateTestExecutionScripts.cs
Remove line breaks from echoed run commands to keep from executing multiline commands (including ILC) during echo. Fixes #2044.
=> Remove line breaks from echoed run commands

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/Dumpling.targets
This is meant as a temporary workaround to get dumps for coverage runs, long term we should move them to Helix instead. The fix is targeted only at what is broken on coverage runs to avoid the problems of the previous attempt to fix it in https://github.com/dotnet/buildtools/pull/2094
=> Temp workaround to collect dumplings for coverage runs

src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
For tests that have custom xunit.console.runtimeconfig.json coverage runs need to respect the request to not setup the default xunit.console.runtimeconfig.json. Part of https://github.com/dotnet/corefx/issues/31041
=> Coverage: allow test projects with custom runtimeconfig.json

src/Microsoft.DotNet.Build.Tasks/PackageFiles/PerfTesting.targets
The fix is to fully qualify the attribute.
Fix https://github.com/dotnet/corefx/issues/31053
=> When building perf tests, the build fails because it can't find OptimizeForBenchmarks.

src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/PackageLibs.targets, src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/FrameworkTargeting.targets
This is a replacement for https://github.com/dotnet/corefx/pull/30850 - exclude source code files from packaging if the consuming repo sets `ExcludeSourceFiles=true`. I tested this locally, and the built packages in CoreFx wound up not including source files.
@weshaggard @dagood @ericstj @MattGal PTAL
Once this is in I'll repurpose https://github.com/dotnet/corefx/pull/30850 to set `ExcludeSourceFiles` & take a buildtools update.
=> Remove code that places source files in packages

src/Microsoft.DotNet.Build.Tasks.Packaging/src/Extensions.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/GenerateNuSpec.cs, src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
FYI. @weshaggard, this is the buildtools change required to support moving the ILProj SDK into CoreCLR (see https://github.com/dotnet/arcade/pull/317 for more details).
=> Updating Packaging.targets to support specifying the PackageType

src/Microsoft.DotNet.Build.Tasks/PackageFiles/CodeCoverage.targets
[EDIT: Updated instructions after validation on macOS 10.13]
/cc @tarekgh @tonerdo @stephentoub 
This change allows one to experiment with coverlet.msbuild to generate coverage information on the CoreFx repo. Some notes:
* There are some issues to consume dotnet/cli global tools on CoreFx repo, it is possible to workaround them but I opted to use the msbuild due to the large set of exclusion files, making easier for me to debug/tweak things via a msbuild task.
* There is a related PR in CoreFx to bring the coverlet.msbuild package, see https://github.com/dotnet/corefx/pull/31171.
* Once this reach the CoreFx repo I will update the wiki with the instructions below - please, review them too.
As of 07/2018 CoreFx is only able to get coverage information on Windows. To correct this we are …
=> Option to use coverlet.msbuild for coverage (allow coverage in Unix)

src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Methods.cs, src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Properties.cs, src/Microsoft.DotNet.Build.Tasks/PackageFiles/notsupported.targets
Also enable use of -global for not-supported assemblies
@luqunl hit this when trying to enable System.Runtime.WindowsRuntime's not-supported assembly.
=> Ensure global prefix handles explicit interface implementations

src/Microsoft.DotNet.Build.Tasks/UpdateVSConfigurations.cs
My VB project did not end with VisualBasic.vbproj so it got the C# guid.
=> Fix VB solution guid in solution generation

src/Microsoft.DotNet.CodeAnalysis/PackageFiles/PinvokeAnalyzer_Win32UWPApis.txt
Adding the API needed to fix https://github.com/dotnet/corefx/issues/20588 API doc is here: https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-getcommports
=> Add GetCommPorts API to UWP whitelist

src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Methods.cs
This should let us use this in S.R.WinRT: https://github.com/dotnet/corefx/blob/724ffdee9db1c95314ca3c45f2692c2b7f73d78e/src/System.Runtime.WindowsRuntime/src/System.Runtime.WindowsRuntime.csproj#L17
=> Ensure global prefix is used for not supported assembly message

src/Microsoft.DotNet.Build.Tasks/VersionTools/BaseDependenciesTask.cs
This will allow the the ILProj SDK to be automatically updated. See https://github.com/dotnet/corefx/pull/31512 for more details.
=> Adding an MSBuildSdkUpdater to the BaseDependenciesTask

src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd, src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh
This ensures that all packages get restored to `PACKAGES_DIR`, rather than a mix of `PACKAGES_DIR` and the NuGet default.
=> Updating init-tools to always use PACKAGES_DIR

src/Microsoft.DotNet.Build.Tasks/PackageFiles/CodeCoverage.targets
This version has a performance improvement that will benefit corefx. I will update src/external/test-runtime/XUnit.Runtime.depproj as soon as dotnet-bot brings this change to corefx.
=> Update coverlet.msbuild to 2.2.1

src/Microsoft.DotNet.Build.Tasks/PackageFiles/IL.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/ilasm/ilasm.depproj
This is in order to fix this issue: https://github.com/dotnet/corefx/issues/24012
S.R.CS.Unsafe is built as an ilproj where we call ilasm directly. This causes that the write version headers are not built into the managed library. With these changes (plus a PR comming up in corefx) we will be able to produce a resource file and then pass it down to ilasm so that the dll will have the right headers on it.
=> Adding ILDasm restore and resources switches in order to be able to produce resources for System.Runtime.CompilerServices.Unsafe.dll

src/Microsoft.DotNet.Build.CloudTestTasks/DownloadFromAzure.cs, src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/PublishContent.targets, src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/SyncCloudContent.targets
Port of https://github.com/dotnet/buildtools/pull/2070 for 1.0.0. We need this so that we can download packages from a specific folder in blob storage in core-setup 1.x.x. Without it, we're currently restoring 2 different versions of buildtools, and only using the second one for downloading stuff from Azure.
@dagood PTAL.
=> Port 'Add blob prefix support' to 1.0.0 buildtools

src/Microsoft.DotNet.Build.Tasks/PackageFiles/CodeCoverage.targets
Recently updated release of coverlet correctly supports Include so we can get rid of the verbose exclude. 
Opportunistically fixing the exclube by file filter (see https://github.com/dotnet/corefx/issues/31255).
=> Exclude SR.* sources and switch to assembly include

src/Microsoft.DotNet.Build.CloudTestTasks/AzureConnectionStringBuildTask.cs, src/Microsoft.DotNet.Build.CloudTestTasks/AzureHelper.cs, src/Microsoft.DotNet.Build.CloudTestTasks/DownloadFromAzure.cs, src/Microsoft.DotNet.Build.CloudTestTasks/ListAzureBlobs.cs, src/Microsoft.DotNet.Build.CloudTestTasks/Microsoft.DotNet.Build.CloudTestTasks.csproj
Partial port of https://github.com/dotnet/buildtools/pull/1572, https://github.com/dotnet/buildtools/pull/1535, and https://github.com/dotnet/buildtools/pull/1321. Allows for passing `/p:BlobNamePrefix=path/with/slashes`, which previously gave an error.
@chcosta PTAL
=> Allow BlobNamePrefixes with slashes while syncing from Azure (1.0.0)

src/Microsoft.DotNet.Build.CloudTestTasks/AzureConnectionStringBuildTask.cs, src/Microsoft.DotNet.Build.CloudTestTasks/AzureHelper.cs, src/Microsoft.DotNet.Build.CloudTestTasks/DownloadFromAzure.cs, src/Microsoft.DotNet.Build.CloudTestTasks/ListAzureBlobs.cs, src/Microsoft.DotNet.Build.CloudTestTasks/Microsoft.DotNet.Build.CloudTestTasks.csproj
Partial port of https://github.com/dotnet/buildtools/pull/1572, https://github.com/dotnet/buildtools/pull/1535, and https://github.com/dotnet/buildtools/pull/1321. Allows for passing `/p:BlobNamePrefix=path/with/slashes`, which previously gave an error.
@chcosta PTAL
=> Allow BlobNamePrefixes with slashes while syncing from Azure

src/Microsoft.DotNet.Build.Tasks/PackageFiles/codeOptimization.targets
This change adds support to consume IBC data packages that are created by the dotnet/optimization repository. With these changes and https://github.com/dotnet/core-setup/pull/4385 to enable PartialNGEN for crossgening NetCoreApp, and changes to coreclr to enable IBC optimizations for System.Private.CoreLib, we will see a 32% decrease in the size of NetCoreApp (and an overall decrease of 16%), a 30% reduction in ref set, a 5% improvement in time to first request and steady state performance for MusicStore.
**Size**
  | Crossgen | Partial | Partial vs Crossgen (lower is better)
-- | -- | -- | --
Shared (MB) | 185.6 | 137.3 | 0.74
Microsoft.NETCore.App (MB) | 115.6 | 67.4 | 0.58
**RefSet**
MusicStore
  | Crossgen | Partial | Partial vs Crossgen (lower is better)
-- | -- | -- | --
Total | …
=> Add Corefx Ibc Package support

src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
As part of adding the netcoreappaot flavor in https://github.com/dotnet/corefx/pull/30980, this change decouples AoT and UAP testing by switching to using the UseDotNetNativeToolchain build variable. It also enables testing with the ```-win32``` ILC flag, which disables WinRT support and matches the netcoreappaot profile.
The CoreFX and Buildtools changes can be merged in either order (it just won't be possible to test the CoreFX change until the Buildtools change is merged).
=> Decouple AoT and UAP testing

src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
Test runs were not executed on helix as -skiptests is usually passed to the build-tests script which then builds each test assembly, compresses it and uploads it to helix. There was a wrong condition that didn't generate the execution script and compressed the test directory, which is now fixed.
**I will merge this as soon as its green as fixing this is critical. I tested the different scenarios offline and now everything behaves as expected. I will react to feedback as it comes with a follow-up PR.**
=> Fix test runs not executed

src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
Excluding Microsoft.TestPlatform and Microsoft.VisualStudio.TestPlatform resw and dlls from `CreateReswFilesForExternalDependencies` computation.
=> Exclude Microsoft TestPlatform assemblies and resw

src/Microsoft.DotNet.Build.Tasks/GenerateTestExecutionScripts.cs
Port the fix for echoes triggering commands to be re-executed to the Windows scripts. This correctly prevents running ILC a second time. This should be a complete fix for https://github.com/dotnet/corefx/issues/31723 (#2106 worked around it by not echoing for uapaot, but that doesn't handle netcoreappaot or any other case we might accidentally be hitting this today).
=> Remove echo line breaks on Windows

src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.props, src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets
The `<Copyright>` value has two spaces after the period. This breaks compliance checks with nuget.org, since they only expect a single space.
=> Removing the archaic two spaces after peroid in our copyright.

src/Microsoft.DotNet.Build.Tasks.net45/project.json, src/Microsoft.DotNet.Build.Tasks/project.json
Newer versions of VS/msbuild have higher versions of these
and so our tasks need to align with the higher versions in order
to unify with those higher versions.
Addresses https://github.com/dotnet/corefx/issues/31925
=> Update to latest S.R.Metadata and S.C.Immutable

src/Microsoft.DotNet.Build.CloudTestTasks/DownloadFromAzure.cs
This change modifies the DownloadFromAzure task by only constructing
the HttpClient once in ExecuteAsync and passing it to DownloadItem
instead of allocating it over and over again for each file; after
I checked in the compiled binary of CloudTestTasks with this fix
into ProjectN about 3 weeks back, we stopped seeing the occasional
failure when accessing the Azure storage:
System.Net.Http.HttpRequestException: An error occurred while
sending the request. ---> System.Net.WebException: Unable to connect
to the remote server ---> System.Net.Sockets.SocketException:
Only one usage of each socket address (protocol/network address/port)
is normally permitted 13.88.144.240:443
Thanks
Tomas
P.S. Sadly the diff looks extensive due to honoring whitespace
that naturally changed after I removed one …
=> Only construct HttpClient once in the DownloadFromAzure task

src/Microsoft.DotNet.Build.Tasks/PackageFiles/packageresolve.targets
Set RestoreOutputPath to the values it used to have, if and only if it is unset when this targets file is imported.
(@ViktorHofer  if you want to make a more correct fix or something, to repro this I only had to run `set __TestIntermediateDir=int  && build.cmd checked x64  -priority=0` locally)
=> Set RestoreOutputPath to the values it used to have

src/Microsoft.DotNet.Build.Tasks.net45/project.json, src/Microsoft.DotNet.Build.Tasks/project.json
System.Collections.Immutable is included with msbuild from at
least 15.7+ and between 15.7 and 15.8 they updated the version they
include which conflicts with our usages across both. To eliminate
this mismatch we instead stop carrying the version with our tasks
and depend on the one they carry with them.
cc @ericstj 
FYI @tmat
=> Exclude System.Collections.Immutable

src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
Add the 3.0 supported tfm/rid combinations.
Also add a SupportedFramework filter to exclude unknown versions
from the set. The unknown version only comes from package harvesting
where we cannot figure out the version number from the package, in
those cases we don't have a great way to get the expected version so
we should just filter them out from validation.
cc @ericstj @joperezr
=> Add support for netcoreapp3.0 to packaging targets

src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
Hit another bad merge that needs fixed from https://github.com/dotnet/buildtools/pull/2142.
=> Fix bad merge which accidently added net47 twice

src/Microsoft.DotNet.Build.Tasks/PackageFiles/packageresolve.targets
Relates to https://github.com/dotnet/coreclr/pull/19728/files#diff-0b192804a6349e8c26d2b027afbd89a2
It seems that there is a default RestoreOutputPath set in coreclr. Adding a switch so that we override the default RestoreOutputPath but only for coreclr.
=> Add OverrideRestoreOutputPath switch for coreclr

src/Microsoft.DotNet.Build.Tasks.Feed/BlobFeedAction.cs, src/Microsoft.DotNet.Build.Tasks.Feed/GetBlobFeedPackageList.cs, src/Microsoft.DotNet.Build.Tasks.Feed/PushToBlobFeed.cs
Closes: dotnet/core-eng#4180
Add support for informing a timeout for the feed container lock.
=> Adding parameter to control timeout of feed lock

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.Helix.targets
* Adds an input property to `CloudTest.Helix.targets` that will determine whether the created Azure Storage container will be public.
* Exposes the `IsPublic` flag on the [`CreateAzureContainer` build task](https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.CloudTestTasks/CreateAzureContainer.cs#L61) 
* Default value is set to `false`
This infrastructure update will allow the build drops from the dotnet/corefx repo to be easily accessible to developers and the coreclr ci pipeline.
CC - @sergiy-k @MattGal @weshaggard @adityamandaleeka @AaronRobinsonMSFT 
dotnet/coreclr#19690
=> Allow build drops to be public

src/Microsoft.DotNet.Build.Tasks/PackageFiles/PerfTesting.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
The `UploadToBenchview` target wasn't executed because I wrongly conditioned importing the PerfTesting.targets. The target wasn't queued correctly after the `TestAllProjects` target because at that time the PerfTesting.targets project wasn't imported.
=> Reenable benchview upload target

src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.targets
Adds a property `ExcludeApiCompatImport` to allow for consumers to opt-out of importing `ApiCompat.targets`. This is similar to `ExcludePartialFacadesImport` at https://github.com/dotnet/buildtools/compare/master...wtgodbe:ExcludeApiCompat?expand=1#diff-c368ca147f7a6d95f33280f334ff9e84L220. We need this in order for Buildtools consumers to use the `Microsoft.DotNet.ApiCompat` package being produced by Arcade.
@weshaggard PTAL
=> Add option to exclude importing ApiCompat.targets

src/Microsoft.DotNet.Build.Tasks/PackageFiles/DesktopRunnerConfigFile.config, src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
Set randomized hashing globally so that we don't need to enable it at places where we assert on it in our corefx tests. Other work is fixing an issue with the runtime copying when measuring code coverage on netfx (theoretical fix, we aren't doing that currently).
Fixes the currently failing netfx tests in corefx.
=> Cleanup runtimeconfigs and set randomized hashing for netfx

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.Helix.targets
Adds the `HelixBlobPrefix` property to the Helix targets file.  This property allows users to specify a prefix that gets applied to all uploaded blobs, i.e., allows the specification of a relative root for all artifacts used for Helix.
Users just need to specify the property `HelixBlobPrefix` in their proj file.  This will be applied to the `RelativeBlobPath` metadata field of all `ItemGroups` that are uploaded via `UploadToAzure` tasks.  This _includes_ the work items, which typically already have a relative path specified by users.
The default value for this property is `''`, so current usage won't change.  Making use of this new property, however, will allow for the CoreFX build pipeline to generate fewer Azure Storage containers because uniqueness information can now be moved to the …
=> Add HelixBlobPrefix

src/Microsoft.DotNet.Build.Tasks/PackageFiles/CodeCoverage.targets
Preparing to make CoreLib coverage to be explicit (see https://github.com/dotnet/corefx/issues/32420), opportunistically fixing report filter that was not correctly set when targeting all projects.
=> Allow explicit coverage target

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.Helix.targets
Fixes bug introduced in #2169 where the generated `TestList.json` would have URIs missing the `HelixBlobPrefix` if one was supplied.
Fixed by applying the prefix directly to the processed work items rather than the derived `ItemGroup
CC - @MattGal
=> Fix bug where TestList.json has wrong URI for workitems when using HelixBlobPrefix

src/Microsoft.DotNet.Build.Tasks.net45/project.json, src/common/AssemblyResolver.cs
We should prefer the task directory over the AppDomain base, since
AppDomain will point to MSBuild's path.
Undo portion of 1a798965c8d4100cc927af3b23398f93a7beed41 that removed
System.Collections.Immutable.  The current fix will work in both MSBuild
versions which include Immutable as well as do not.
Replaces previous fix for https://github.com/dotnet/corefx/issues/31925.
There are two potential causes for the issue:
1.	Bad ordering of probing in our AssemblyResolve event.
2.	A successful bind that we expected to fail.
The first issue is simply a bug.  We were probing the AppDomain base directory before looking next to the task.  MSBuild tasks run in a shared appdomain and this points to the MSBuild bin directory.  As a result we would start unifying to the MSBuild version for mismatches, …
=> Fix probing order in AssemblyResolver

src/Microsoft.DotNet.Build.Tasks/PackageFiles/FrameworkTargeting.targets
Fixing coreclr build breaks with newer buildtools versions. That allows coreclr to use the 3.0 versions.
=> Support non SDK projects in targeting packs

src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
For the coverage runs it seems that coreclr doesn't import the Build.Common.targets and therefore the DefinitionGroup is missing. That issue didn't surface before as no custom attributes were used.
Moving the definitiongroup to tests.targets as it belongs there.
=> Move SupplementalTestData definition to tests.targets

src/Microsoft.DotNet.Build.Tasks/PackageFiles/CodeCoverage.targets
When `<TestRuntime>true</TestRuntime>` is specified in a test project we should keep the assembling being tested since it may also have code, if it doesn't exist that is not a problem.
=> TestRuntime property handling improvement

src/ApiCompat.Desktop/ApiCompat.Desktop.csproj, src/ApiCompat/Program.cs, src/ApiCompat/Rules/Compat/AttributeDifference.cs, src/Microsoft.Cci.Extensions/Microsoft.Cci.Extensions.csproj, src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Attributes.cs, src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Enums.cs, src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Fields.cs, src/Microsoft.DotNet.Build.Tasks/PackageFiles/ApiCompat.targets
This makes ApiCompat diff attributes applied to classes between contract and implementation.
By default all attributes are included and attributes can be opted out via an exclude list, similar
to how we exclude the same attributes from being written by GenAPI.
=> Diff attributes applied to classes between contract and implementation

src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
Refactor SupplementalTestData code and avoid the custom ItemDefinitionGroup which currently causes issues in coreclr.
(This is a backport from the arcade test framework effort)
Tested in corefx.
=> Refactor SupplementalTestData

src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd, src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh
Since the generated `project.csproj` is an SDK style project, it was automatically importing the root `Directory.Build.props/targets` in SDK-style repos that consumed it. This was causing problems - for example, in CoreFx & Standard, `project.csproj` would get PackageReferences that were defined in Arcade, but didn't have access to the right RestoreSource, causing restore errors if those packages weren't already in the cache. This PR turns off the automatic `Directory.Build.props/targets` imports.
@weshaggard @ericstj PTAL
=> Opt out of importing Directory.Build.props/targets in generated project.csproj

src/Microsoft.DotNet.Build.Tasks.Packaging/src/ApplyPreReleaseSuffix.cs
Microsoft.private.packagebaseline\4.6.0-preview.18555.4\build\packageIndex.json has  
``` 
"PreRelease": "preview.18555.4"
```
This change tolerates that and adds the `-` before the suffix if needed.
=> Tolerate missing leading '-' in prerelease suffix specification

src/Microsoft.DotNet.Build.Tasks/PackageFiles/PerfTesting.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
We are currently transitioning from xunit-performance to BenchmarkDotNet.
All of the benchmarks live in the performance repo, however when CoreFX developers want to run benchmarks against new API that is not exposed by any contracts yet they need to test it locally.
This is why I am adding support for BDN to CoreFX. Before I do that, I need these changes to merged and propagated ofc ;)
Some reasoning behind the changes:
1. All changes are inside a `'$(IsBenchmarkDotNetProject)' == 'true'` condition to make sure I don't break anybody
2. I did not remove xunit-performance stuff, just added BDN
How it's going to work in the CoreFX repo for running benchmarks against new API: exactly the same way it was with xunit-performance:
Default run:
> dotnet msbuild /t:BuildAndTest …
=> adding BenchmarkDotNet support for CoreFX purpose

src/Microsoft.DotNet.Build.Tasks.Feed/PackageFiles/Microsoft.DotNet.Build.Tasks.Feed.targets
aspnet-Extensions ocassionally has no items to push to the prodcon feed (if no packages are being patches). We could remove this repo from the build, but it does have valuable testing that pulls  in the latest netcoreapp.
The other alternative is to rework the way that aspnet-Extensions uses the push to blob feed targets, but this is more work and doesn't end up pushing the manifest.
=> Add property to allow empty items to push

src/Microsoft.DotNet.Build.Tasks.Feed/PackageFiles/Microsoft.DotNet.Build.Tasks.Feed.targets
aspnet-Extensions ocassionally has no items to push to the prodcon feed (if no packages are being patches). We could remove this repo from the build, but it does have valuable testing that pulls  in the latest netcoreapp.
The other alternative is to rework the way that aspnet-Extensions uses the push to blob feed targets, but this is more work and doesn't end up pushing the manifest.
=> Add property to allow empty items to push (#2202)

src/Microsoft.DotNet.Build.Tasks/PackageFiles/crossgen.sh
=> Exclude crossgen of Microsoft.DotNet.Build.Tasks.dll

src/Microsoft.DotNet.Build.Tasks/PackageFiles/ReferenceAssemblies.targets
I'm not sure if this _usingRoslyn check is still meaningful (don't we always build with Roslyn now?), but recent Visual Studio builds include a tools version coming back as "Current", which then causes the failure:
```
error MSB4086: A numeric comparison was attempted on "$(MSBuildToolsVersion)" that evaluates to "Current" instead of a number, in condition "'$(MSBuildToolsVersion)' == 'dogfood' OR '$(MSBuildToolsVersion)' >= '14.0'"
```
when building Corelib, so I'm adding "Current" to the list of versions that means we're using Roslyn.
Fixes https://github.com/dotnet/coreclr/issues/21069
cc: @danmosemsft, @jkotas
=> Update MSBuildToolsVersion check to support "Current"

src/Microsoft.DotNet.Build.Tasks/PackageFiles/OptionalTooling.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd
Contributes to https://github.com/dotnet/corefx/pull/34315
Fix build errors when paths contain empty spaces in the init-tools and optional tools setup.
=> Fix build for paths with spaces

src/Microsoft.DotNet.VersionTools/Automation/GitHubApi/GitHubClient.cs
GitHub seems to have changed to no longer handle null in create tree calls. The API returns a 422 Unprocessable Entity error "Must supply tree.sha or tree.content" when we specify tree.sha as null *and* tree.content as the text content we want. Omit the tree.sha property completely to fix this.
For example, this doesn't work anymore:
```js
{
"base_tree": "1abcea798bad23c4ff88e89ebaf2a3ff51733c48",
"tree": [
{
"path": "build-info/dotnet/core-setup/master/Last_Build_Packages.txt",
"mode": "100644",
"type": "blob",
"sha": null,
"content": "Microsoft.DotNet.PlatformAbstractions 3.0.0-preview-27316-0..."
},
// ...
]
}
```
This does:
```js
{
"base_tree": "1abcea798bad23c4ff88e89ebaf2a3ff51733c48",
"tree": [
{
"path": "build-info/dotnet/core-setup/master/Last_Build_Packages.txt",
"mode": …
```
=> Use NullValueHandling.Ignore in GitHub client

src/Microsoft.DotNet.VersionTools/Automation/GitHubApi/GitHubClient.cs
UWP CoreFX and CoreCLR builds are blocked on buildtools dotnet/core-eng#5044
=> Use NullValueHandling.Ignore in GitHub client (#2213)

src/Microsoft.DotNet.VersionTools/Automation/GitHubApi/GitHubClient.cs
In Core-Setup, I upgraded buildtools, but continue to get 422 error responses from this method in the official build. I strongly suspect there's some cleanup or stale DLL issue because it hasn't repro'd in any other situation, but  I want to print the tree to narrow it down for sure. This also makes the method more diagnosable in general.
Tested by copying the new VersionTools DLL into a Core-Setup Tools dir.
=> Trace body when submitting tree to GitHub

src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd
This updates init-tools.cmd to also restore Microsoft.NETCore.Compilers which allows CoreCLR to be compiled using `dotnet msbuild` on Windows.
=> Updating init-tools.cmd to also restore Microsoft.NETCore.Compilers

src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh
Fixes https://github.com/dotnet/buildtools/issues/2224
dotnet cli team changed on how we pass arguments to dotnet commands. The change was introduced in this https://github.com/dotnet/cli/pull/9892
More info is available here https://github.com/dotnet/cli/issues/10802
I tested 4 testcases here
- path without spaces on netcore2.1
- path without spaces on netcore3.0
- path with spaces on netcore2.1
- path with spaces on netcore3.0
@safern @eerhardt any other good way to test these changes
=> Using eval and explicit variables

src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd, src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh
After the adoption of the new publishing feed, new versions of ILasm live in the new feed. Addiing the feed for the restore step of ILasm using buildtools.
=> Update sources for ILasm restore

src/Microsoft.DotNet.Build.Tasks/PackageFiles/crossgen.sh
Currently the buildtools gives error if we try to use them with netcoreapp3.0 
```
/git/machinelearning/Tools/crossgen/crossgen.csproj : error NU1202: Package Microsoft.NETCore.App 3.0.0-preview-27324-5 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.NETCore.App 3.0.0-preview-27324-5 supports: netcoreapp3.0 (.NETCoreApp,Version=v3.0)
/git/machinelearning/Tools/crossgen/crossgen.csproj : error NU1202: Package Microsoft.NETCore.App 3.0.0-preview-27324-5 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0) / linux-x64. Package Microsoft.NETCore.App 3.0.0-preview-27324-5 supports: netcoreapp3.0 (.NETCoreApp,Version=v3.0)
```
=> Setting the targetFramework Dynamically

src/packages.builds
In keeping with branching buildtools to release/3.0, which is marked preview3: https://github.com/dotnet/buildtools/commit/2912fd36eaffe4e998073044d0be9319ff5213dd
CC @danmosemsft @leecow @mmitche
=> Bump version to preview4

tools-local/versions-fix/versions-fix.proj
This provides a path to use a later, published UpdatePublishedVersions task to resolve dotnet/core-eng#5054.
=> Provide alternate UpdatePublishedVersions task

tools-local/versions-fix/versions-fix.proj
This fixes evaluation of the glob path to shipping NuGet packages.
@dagood Please have a look
=> Fix parameter evaluation of publish task

src/Microsoft.DotNet.Build.Tasks/PackageFiles/Roslyn.Common.props, src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd, src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh
CC. @jaredpar, @jkotas, @safern 
This pulls in the latest compiler (same one as CoreFX was just moved to) in order to get some of the nullable fixes that have recently gone in.
We now have `Microsoft.Net.Compilers.Toolset` that contains both .NET Core and Desktop binaries, rather than having separate/independent packages.
=> Updating the toolset compiler to use the cross-platform package and target v3.1.0-beta1-19172-05

src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd, src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh
CoreClr still publishes to dotnet-core (rather than dotnet-coreclr) in 2.1 - we should add it as a restore source for restoring ILAsm, now that we don't publish it to myget regularly.
CC @mmitche
=> Add blob feed as restore source for ILASM in init-tools

src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/scriptrunner/scriptrunner.py
Use `open` instead of `file` to read results file
Remove unnecessary semicolons
=> Python 3 changes to scriptrunner

src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/scriptrunner/scriptrunner.py
Use `open` instead of `file` to read the results
Remove unnecessary semicolons
=> Python 3 changes for scriptrunner

src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/scriptrunner/scriptrunner.py
In Python 2, open from io module takes encoding parameters
=> Make scriptrunner.py compatible with Python 2 and 3

src/Microsoft.DotNet.Build.Tasks.Feed.net45/project.json, src/Microsoft.DotNet.Build.Tasks.Feed/CopyBlobDirectory.cs, src/Microsoft.DotNet.Build.Tasks.Feed/project.json
@dagood
This is exclusively for use in the dotnet orchestration utilities for 2.1 and 2.2. For whatever reason, that repo is using a master branch of buildtools, so I can't just check this into 2.1 and use that (there are additional changes).
This allows me to automate the process of moving a private 2.1 and 2.2 build into the public locations without any manual steps. This requires a cross-account copy which is most efficiently done by not downloading to an intermediate location first.
Also update the sleet version so that the final package push is a lot faster.
=> Allow different source and target accounts for CopyBlobDirectory

src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/sign.targets
modified:   src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
=> [release/2.1] Update authenticode certs from sha1 to sha2

src/Microsoft.DotNet.Build.CloudTestTasks/AzureHelper.cs
Because a retry logged a warning, even though upload passed on the second try, cli enables warnings-as-errors and the build will fail.
=> Do not log a warning when a retry will happen

.toolversions, README.md, bootstrap/bootstrap.ps1, bootstrap/bootstrap.sh, dir.props, run.ps1, src/Microsoft.DotNet.Build.Tasks/PackageFiles/codeOptimization.targets, src/Microsoft.DotNet.Build.Tasks/PackageFiles/crossgen.sh, src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd, src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh, src/NuGet.Config
Cleanup nuget feeds.
To handle bootstrap problems, this also makes potentially temporary changes of:
- Bootstrap from self instead of going to GitHub (to get script with fixed URLs)
- Replace BuildTools dependency with experimental version having updated feed URLs
=> Cleanup feeds
