README.md

Switch to Jenkins-CI links.

---

src/Microsoft.DotNet.Build.Tasks/Targets/tests.targets
src/nuget/Microsoft.DotNet.BuildTools.nuspec

Enable the ability to gather exit codes from the xunit execution.

Correct exit codes

---

src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime-packages.config
src/nuget/Microsoft.DotNet.BuildTools.nuspec

Includes commit df2ffbbd.. from stephentoub
https://github.com/FiveTimesTheFun/xunit/commit/df2ffbbdf736bc0855ac68d0aec4235f975f484e
"Change how Task is created in XunitWorkerThread"

Update xunit.runner.dependencies.netcore depend.. to v1.0.1-prerelease

---

src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime-packages.config
src/nuget/Microsoft.DotNet.BuildTools.nuspec
src/nuget/xunit.console.netcore.nuspec

This bumps the package versions for the xml report changes.

Bump nuget package versions.

---

dir.props
src/.nuget/packages.config

Build 00006 is the latest official build from VSO.

Update build tools package dependency to latest build.

---

src/Microsoft.DotNet.Build.Tasks/Targets/packages.targets

Provide a way to specify which target the LocalPackagePublish runs after

---

src/BuildTools.sln
src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj

Updated pull. Messed up my master history in my last request.
I went ahead and created a separate solution folder for the nuspec files.  Also added the scripts folder.

Include the various target/script files in the solution.

---

src/Microsoft.DotNet.Build.Tasks/Targets/sign.targets
src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime-packages.config
src/nuget/xunit.console.netcore.nuspec
src/xunit.console.netcore/packages.config
src/xunit.console.netcore/xunit.console.netcore.csproj

See individual commits for more details

Bump package versions to latest

---

src/Microsoft.DotNet.Build.Tasks/Targets/packages.targets
src/dirs.proj

Added a few tweaks to enable testing of build tools packages locally. Also added https://github.com/dotnet/buildtools/wiki/Local-testing-of-BuildTools-in-another-repo to the wiki so people know how to do this.

Testing build tools

---

src/Microsoft.DotNet.Build.Tasks/ResolveNuGetPackages.cs

Fixes #117 
OptimizedZipPackage extracts packages to %TEMP%\nuget in order to access the files; however, installing the packages already extracts them to the local packages directory. Using SharedPackageRepository uses the packages in their already extracted locations, eliminating the need for the cache.

Resolve NuGet packages from packages folder without using temp cache

---

src/Microsoft.DotNet.Build.Tasks/Targets/packageresolve.targets

Follow up to https://github.com/dotnet/buildtools/pull/138 addressing feedback.

Remove unneeded property and correct condition on log message.

---

src/Microsoft.DotNet.Build.Tasks/Targets/publishtest.targets

@weshaggard can you have a look.

Again fix typo in publishtest.targets

---

src/xunit.netcore.extensions/PlatformID.cs

refer commit dotnet/corefx@c96932da11940e0bae05de8e364eac90a6e1786b
This is in preparation to remove XunitTraitDiscovers from corefx. 
cc @stephentoub

Add AnyUnix to PlatformID enum.

---

src/Microsoft.DotNet.Build.Tasks/ResolveNuGetPackageAssets.cs

On Linux I'm seeing
"compile": {
"ref/any/System.Collections.dll": {}
},
instead of
"compile": [
"ref/any/System.Collections.dll"
],

Check for token type before casting

---

src/Microsoft.DotNet.Build.Tasks/Targets/PerfTesting.targets

Fix path to perf tools

---

src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime-project.json
src/nuget/xunit.console.netcore.nuspec
src/nuget/xunit.netcore.extensions.nuspec
src/xunit.console.netcore/Program.cs
src/xunit.console.netcore/packages.config
src/xunit.console.netcore/xunit.console.netcore.csproj

Revert "Update build tools to use xUnit.net 2.1 Beta 2"

---

src/Microsoft.DotNet.Build.Tasks/Targets/ReferenceAssemblies.targets

These attributes are added to all reference assemblies in our internal build.
/cc @weshaggard @nguerrera

Add ReferenceAssemblyAttribute + others

---

src/Microsoft.DotNet.Build.Tasks/Targets/CodeCoverage.targets
src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime/project.json

Has several improvements, including support for generating badges.
cc: @mmitche

Update to latest code coverage ReportGenerator version

---

dir.props
publishexe.targets
src/.nuget/packages.Unix.config
src/.nuget/packages.Windows_NT.config
src/GenAPI.Desktop/project.lock.json
src/GenAPI/project.lock.json
src/GenFacades.Desktop/project.lock.json
src/GenFacades/project.lock.json
src/Microsoft.Cci.Extensions/project.lock.json
src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime/project.json
src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime/project.lock.json
src/Microsoft.DotNet.Build.Tasks/Targets/tool-runtime/project.lock.json
src/xunit.console.netcore/project.lock.json
src/xunit.netcore.extensions/project.lock.json

Update the build tools version to 87 and update to DNU beta7.
This also updates all the lock files in this repo.

Update build tools version of build tools repo

---

src/Microsoft.DotNet.Build.Tasks/Targets/PerfTesting.targets

Fixed error with perf runner path

---

README.md

Repoint badges to new location

---

src/Microsoft.DotNet.Build.Tasks/Targets/tests.targets

When diagnosing test runs it is useful to run multiple times without
changes.
@weshaggard

Add the ability to force test runs.

---

src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime/project.json
src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime/project.lock.json
src/Microsoft.DotNet.Build.Tasks/Targets/tool-runtime/project.json
src/Microsoft.DotNet.Build.Tasks/Targets/tool-runtime/project.lock.json
src/Microsoft.DotNet.Build.Tasks/Targets/toolruntime.targets

The casing of corerun has changed in newer x-plat packages, pick up the
changes.

Update Tool Runtime Packages

---

src/nuget/xunit.console.netcore.nuspec
src/nuget/xunit.netcore.extensions.nuspec

This should make build tools 101 what we want for CoreFX. Will update https://github.com/dotnet/corefx/pull/3599/files accordingly.
@pgavlin @ellismg @mellinoe

Updated lock files and netcore nuspec

---

dir.props
src/.nuget/packages.Unix.config
src/.nuget/packages.Windows_NT.config

I need this for my upcoming PR that will enable building corefx repo with .NetCore version of msbuild

Upgrading buildtools package version

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/PerfTesting.targets
src/Microsoft.DotNet.Build.Tasks/PackageFiles/test-runtime/project.json
src/Microsoft.DotNet.Build.Tasks/PackageFiles/test-runtime/project.lock.json

Fix for the change made in https://github.com/dotnet/buildtools/pull/320
@mellinoe @weshaggard

Fix for perf commandline

---

src/BuildTools.sln
src/Microsoft.DotNet.Build.CloudTestTasks/CreateAzureContainer.cs
src/Microsoft.DotNet.Build.CloudTestTasks/CreateAzureFileShare.cs
src/Microsoft.DotNet.Build.CloudTestTasks/GetPerfTestAssemblies.cs
src/Microsoft.DotNet.Build.CloudTestTasks/Microsoft.DotNet.Build.CloudTestTasks.csproj
src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
src/Microsoft.DotNet.Build.CloudTestTasks/SendToEventHub.cs
src/Microsoft.DotNet.Build.CloudTestTasks/UploadToAzure.cs
src/Microsoft.DotNet.Build.CloudTestTasks/WriteItemsToJson.cs
src/Microsoft.DotNet.Build.CloudTestTasks/packages.config
src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj
src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets
src/Microsoft.DotNet.Build.Tasks/packages.config
src/nuget/Microsoft.DotNet.BuildTools.nuspec

Extracting CLoud Test tasks into a new task library called Microsoft.DotNet.Build.CloudTestTasks.dll (I'm open to name changes if anybody has any suggestions.)

Extracting Cloud Test changes into a new task library

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/CodeCoverage.targets
src/Microsoft.DotNet.Build.Tasks/PackageFiles/test-runtime/project.json
src/Microsoft.DotNet.Build.Tasks/PackageFiles/test-runtime/project.lock.json

Upgrade to ReportGenerator 2.3.4

---

src/common/XmlTestExecutionVisitor.cs

From:
https://github.com/xunit/xunit/commit/9749ad1bd871342ba3f4ca936a0904c01673bd42
Will need this to fix https://github.com/dotnet/corefx/issues/2370
(Editorial: We should really try to get off our own custom runner.)
cc: @mellinoe, @weshaggard

Port a fix from xunit.console.exe to xunit.console.netcore.exe

---

dir.props
src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj
src/Microsoft.DotNet.Build.Tasks/PackageFiles/test-runtime/project.json
src/Microsoft.DotNet.Build.Tasks/PackageFiles/test-runtime/project.lock.json

Doing this to cleanup my other PR.

Update test runtime and add targets back to BuildTools project

---

src/Microsoft.DotNet.Build.Tasks/PrereleaseResolveNuGetPackageAssets.cs

Previously the ReferencedPackages item list was only
returning the list of packages listed under the root
dependencies section.  This changes it to return that
as well as any TFM specific dependencies.
/cc @weshaggard @jasonmalinowski @dsgouda

ReferencedPackages should include TFM specific deps

---

src/Microsoft.DotNet.Build.Tasks.Packaging/src.Desktop/GenerateNuSpec.cs
src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/PackageLibs.targets
src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets

These fixes all help enable transitioning our internal infrastructure
to use the open-source projects and infrastructure.

Packaging fixes

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/CodeCoverage.targets
src/Microsoft.DotNet.Build.Tasks/PackageFiles/test-runtime/project.json
src/Microsoft.DotNet.Build.Tasks/PackageFiles/test-runtime/project.lock.json

Necessary to pick up some css changes for problems we're hitting in rendering on Jenkins.
cc: @weshaggard, @mmitche

Update ReportGenerator to v2.4.0-beta2

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh

Related: https://github.com/dotnet/corefx/pull/5342

Fix init-tools.sh for osx

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/BlockReflectionAttribute.cs
src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.targets

Add the attribute __BlockReflectionAttribute to the libraries that have targerGroup as netcore50 or netcore50aot, instead of running FxTransform

Add attribute __BlockReflectionAttribute target

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh

Fix scripts to work on Unix.

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/PerfTesting.targets
src/Microsoft.DotNet.Build.Tasks/PackageFiles/test-runtime/project.json

Updating nugget package dependency for build tools so we can run the latest runner version and related tools
@ianhays @davmason

Updating nuget package for perf xunit runner

---

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.Perf.targets
src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets

Added target PreCloudBuild as an extensibility point for other targets to
run before packaging and uploading.
Added CloudTest.Perf.targets containing targets to be executed as part of
PreCloudBuild.
Updated SupplementalPayload item group to support recursive directory
inclusion and consolidated creation of relative path.

Changes to support performance testing.

---

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
src/Microsoft.DotNet.Build.Tasks/PackageFiles/PerfTesting.targets

Compress and upload supplemental payload files.
Use ConfigurationGroup to properly detect the build flavor (debug or
release).

Some clean-up for cloud and perf testing targets.

---

src/Microsoft.DotNet.Build.CloudTestTasks/Microsoft.DotNet.Build.CloudTestTasks.csproj
src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/xunitrunner-perf/csvjsonconvertor.py
src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/xunitrunner-perf/serialobj.py
src/nuget/Microsoft.DotNet.BuildTools.nuspec

Utility scripts that will convert the results csv to json consumable by bench view; this is a stop-gap solution that should allow us to run perf on multiple OSes; moving forward, the benchview team should provide a script/exe to do this conversion for us.
@davmason @ChadNedzlek @MattGal @jhendrixMSFT @mmitche

Python script to convert csv results to BV jsons

---

src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/xunitrunner-perf/xunitrunner-perf.py

Xunit runner script to perform perf specific jobs on helix
@ChadNedzlek @MattGal @Chrisboh @davmason @brianrob @karajas

Xunit runner for perf in helix

---

src/Microsoft.DotNet.Build.Tasks/BinClashLogger.cs

Parse append parameter to BinClashLogger

---

netci.groovy

Revert "[Do not Merge] Simplify and move to the branch CI model"

---

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.Perf.targets
src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/xunitrunner-perf/csvjsonconvertor.py
src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/xunitrunner-perf/xunitrunner-perf.py

Improvements to csv to json conversion logic to generate a tree-like json with namespaces/identifiers denoting each node on benchview
Improvements to perf xunitrunner to extract machine-specific information 
Improvements to build targets to pass perf relevant information to the test machines
@brianrob @jhendrixMSFT @ChadNedzlek @MattGal

Perfrunner

---

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.Perf.targets
src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/xunitrunner-perf/xunitrunner-perf.py

Added meta info so that we can identify the build for which we ran tests, and the user who triggered the test
@brianrob

More build info to identify official builds

---

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets

@jhendrixMSFT Please have a look.

Adding TargetOS to the Container Name

---

src/ApiCompat/project.json

#485 
@jhendrixMSFT : Please have a look.

Removed floating nuget version numbers

---

src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/baseline.packages.targets
src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/stable.packages.targets

Update stable package list to include packages shipped for VSUpdate2
and System.Reflection.Metadata 1.2.
Update baselines to move folks to latest packages past these stable
versions.
/cc @weshaggard @tmat @khdang

Update stable package list

---

src/xunit.netcore.extensions/Discoverers/ConditionalFactDiscoverer.cs
src/xunit.netcore.extensions/Discoverers/ConditionalTheoryDiscoverer.cs

cc @stephentoub @ellismg 
EDIT: Add support to conditionalfact, to search for type.member in assembly

Support type.member parsing in ConditionalFact and ConditionalTheory

---

src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/xunitrunner-perf/xunitrunner-perf.py
src/Microsoft.DotNet.Build.Tasks/PackageFiles/PerfTesting.targets

Updating xunit perf package reference to latest version
@brianrob

Updating xunit perf package version

---

BuildToolsVersion.txt
src/Microsoft.DotNet.Build.Tasks/PackageFiles/resolveContract.targets

Replace back-tick char with single-quote char.
Add missing closing parenthesis.

Update build tools to latest version.

---

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets

Added optional property ConfigurationSuffix that when specified will
append a suffix to the configuration value.

Add a configuration suffix to cloud test jobs.

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets

Copy over locally built native shim for testing.

---

src/Microsoft.DotNet.Build.Tasks.Packaging/src/ValidatePackage.cs

Previously we validated for strict version match when a package contains
both reference and implementation assembly.
This change adds an override PermitHigherCompatibleImplementationVersion
to be specificed in case a package needs to ship a higher implemetnation
version that reference.  This is needed for
https://github.com/dotnet/corefx/issues/7114

Allow a compatible version match between ref/impl

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/packages.targets
src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets
src/packages.builds

I had some merge issues with my last PR that I just found out plus I'm adding the buildversion to the packages.targets which is the one we use to create packages when a nuspec already exists.
CC: @weshaggard @ericstj

Fixing Merging issues

---

BuildToolsVersion.txt
build.proj
dir.props
src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets
src/dirs.proj

Updating Buildtools and using the new versioning scheme.
cc: @weshaggard @ericstj 
FYI: @jhendrixMSFT

Adding new versioning scheme to buildtools

---

BuildToolsVersion.txt

With this last change, Buildtools will me moved to using the new versioning scheme.

Updating BuildTools to get RevisionNumber

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.json

Updating MSBuild packages
fixes: #574 
FYI: @stephentoub @dsplaisted

Update MSBuild package references

---

src/BuildTools.sln
src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.targets
src/Microsoft.DotNet.CodeAnalysis.net45/Microsoft.DotNet.CodeAnalysis.net45.csproj
src/Microsoft.DotNet.CodeAnalysis.net45/project.json
src/Microsoft.DotNet.CodeAnalysis/Analyzers/AppContextDefaultsAnalyzer.cs
src/Microsoft.DotNet.CodeAnalysis/Analyzers/MembersMustExistAnalyzer.cs
src/Microsoft.DotNet.CodeAnalysis/DiagnosticIds.cs
src/Microsoft.DotNet.CodeAnalysis/Helpers.cs
src/Microsoft.DotNet.CodeAnalysis/Microsoft.DotNet.CodeAnalysis.csproj
src/Microsoft.DotNet.CodeAnalysis/PackageFiles/codeAnalysis.targets
src/Microsoft.DotNet.CodeAnalysis/project.json
src/nuget/Microsoft.DotNet.BuildTools.nuspec

Provide a way to write and deploy analyzers as part of buildtools.
/cc @pallavit @weshaggard @joperezr

Build validation analyzers

---

src/Microsoft.DotNet.Build.CloudTestTasks.net45/Microsoft.DotNet.Build.CloudTestTasks.net45.csproj
src/Microsoft.DotNet.Build.CloudTestTasks.net45/project.json
src/Microsoft.DotNet.Build.CloudTestTasks/AzureHelper.cs
src/Microsoft.DotNet.Build.CloudTestTasks/CreateAzureContainer.cs
src/Microsoft.DotNet.Build.CloudTestTasks/GetPerfTestAssemblies.cs
src/Microsoft.DotNet.Build.CloudTestTasks/Microsoft.DotNet.Build.CloudTestTasks.csproj
src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
src/Microsoft.DotNet.Build.CloudTestTasks/SendToEventHub.cs
src/Microsoft.DotNet.Build.CloudTestTasks/UploadClient.cs
src/Microsoft.DotNet.Build.CloudTestTasks/UploadToAzure.cs
src/Microsoft.DotNet.Build.CloudTestTasks/WriteBuildStatsJson.cs
src/Microsoft.DotNet.Build.CloudTestTasks/WriteItemsToJson.cs
src/Microsoft.DotNet.Build.CloudTestTasks/project.json
src/nuget/Microsoft.DotNet.BuildTools.nuspec

This is to convert CloudTestTasks to run on Core. This will allow us to run full matrix test runs from any platform. 
/cc: @Chrisboh. @sokket @ChadNedzlek

Convert CloudTestTasks to run on Core

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/PerfTesting.targets

Fixing minor error in Perftesting.targets
@MattGal

Fixing error in Perftesting.targets

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd
src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.json

cc @weshaggard @stephentoub @joshfree 
fixes dotnet/corefx#7294

Add win-api set dependency for win7.

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets

Adding new versioning support for native libraries

Adding new versioning support for native libraries

---

src/Microsoft.DotNet.Build.Tasks.net45/Microsoft.DotNet.Build.Tasks.net45.csproj
src/Microsoft.DotNet.Build.Tasks/AddDependenciesToProjectJson.cs
src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj
src/Microsoft.DotNet.Build.Tasks/PackageFiles/buildagainstpackages.targets
src/Microsoft.DotNet.Build.Tasks/PackageFiles/packageresolve.targets
src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets
src/Microsoft.DotNet.Build.Tasks/ParsePackageNames.cs
src/Microsoft.DotNet.Build.Tasks/project.json

Enable project reference to package dependency test build conversion

---

src/Microsoft.DotNet.Build.CloudTestTasks/DownloadFromAzure.cs
src/Microsoft.DotNet.Build.CloudTestTasks/ListAzureContainers.cs
src/Microsoft.DotNet.Build.CloudTestTasks/Microsoft.DotNet.Build.CloudTestTasks.csproj
src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/SyncCloudContent.targets

Download product packages from Azure BLOB.
cc: @chcosta @jhendrixMSFT

Download product packages from Azure

---

src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/baseline.packages.targets

/cc @weshaggard @chcosta 
Http has already changed, Linq.Expressions and Regex are changing in https://github.com/ericstj/corefx/commit/ecdca800cc7cf0d2a014615d021137a7588a6cf0

Update package baseline to reflect API changes

---

src/Microsoft.DotNet.Build.CloudTestTasks/Microsoft.DotNet.Build.CloudTestTasks.csproj
src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
src/Microsoft.DotNet.Build.CloudTestTasks/SendToHelix.cs

@ChadNedzlek  Please have a look.
I tested out build.cmd with and without the api as well as the error when neither params are present in the rsp

Changes to use helixApi for EventHub.

---

src/Microsoft.DotNet.Build.Tasks/GenerateCurrentVersion.cs

Using OfficialBuildId as the seed date if it gets passed in.

Using OfficialBuildId as the seed date if it gets passed in.

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/PerfTesting.targets
src/Microsoft.DotNet.Build.Tasks/PackageFiles/test-runtime/project.json

Updated xunit.performance.analysis package has bug fix for proper escaping of special characters in csv files
@lt72 @MattGal

Updated xunit.perf.analysis versions to 0030

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets

CC: @weshaggard 
FYI: @gkhanna79 
fixes: #621

Calculate BuiltBy String for non-Windows environments

---

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/PublishContent.targets

- Change `$(ToolsDir)/net45` to `$(BuildToolsTaskDir)`
- Replace backslash for slash  
cc: @karajas

Change build tools directory in PublishConten.targets

---

src/Microsoft.DotNet.Build.Tasks/AddDependenciesToProjectJson.cs
src/Microsoft.DotNet.Build.Tasks/PackageFiles/buildagainstpackages.targets

Only update test dependencies which reference specific repo built packages 

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets

CC: @weshaggard @AtsushiKan 
fixes: dotnet/corefx#8048

Add -parallel none argument to the xunit call

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets

Create Directory if not exists

---

src/Microsoft.DotNet.Build.CloudTestTasks/UploadClient.cs

According to the PUT Block documentation,
blockid - Required. A valid Base64 string value that identifies the block. Prior to encoding, the string must be less than or equal to 64 bytes in size.
For a given blob, the length of the value specified for the blockid parameter must be the same size for each block.
Note that the Base64 string must be URL-encoded.
/cc @schaabs @jhendrixMSFT

Add UrlEncode to block id for block upload url

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/ApiCompat.targets

This changes how we are finding the various parameters, in particular
dependencies for ApiCompat runs. It also simplifies the running to
only a few targets.
cc @ericstj

Update ApiCompat targets

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.props
src/Microsoft.DotNet.Build.Tasks/PackageFiles/ReferenceAssemblies.targets
src/Microsoft.DotNet.Build.Tasks/PackageFiles/checksum.rsp

Adding checksum .rsp for managed libraries

---

src/Microsoft.DotNet.Build.CloudTestTasks/AzureHelper.cs

Ensure that response is not null before dereferencing it, and reset it to
null at the start of each iteration.

Failure to send HTTP request can lead to NullReferenceException.

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets

Generating VersionSourceDir if not exists

---

src/Microsoft.DotNet.Build.Tasks/AddDependenciesToProjectJson.cs

If a JProperty includes a '.', then it gets encoded as ['property'].
Example: frameworks.netcoreapp1.0 becomes frameworks.['netcoreapp1.0'].  This broke our project.json generation because it was searching for the unencoded path.
```
2016-05-19T12:42:55.9234470Z D:\A\_work\24\s\Tools\buildagainstpackages.targets(181,5): error MSB4018: The "AddDependenciesToProjectJson" task failed unexpectedly. [D:\A\_work\24\s\src\System.Security.Cryptography.OpenSsl\tests\System.Security.Cryptography.OpenSsl.Tests.csproj]
2016-05-19T12:42:55.9234470Z D:\A\_work\24\s\Tools\buildagainstpackages.targets(181,5): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object. [D:\A\_work\24\s\src\System.Security.Cryptography.OpenSsl\tests\System.Security.Cryptography.OpenSs …
```

escape jproperties for token matching

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/ApiCompat.targets

Fixes https://github.com/dotnet/buildtools/issues/728
Fixes https://github.com/dotnet/corefx/issues/8617
Also adds support need for our baseline generation
cc @ericstj

Api compat update

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/RunnerTemplate.Windows.txt

Add popd to not change environment after test execution.

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/ApiCompat.targets

This should address dotnet/corefx#8815

Use platform specific CoreRun in API tasks

---

src/Microsoft.DotNet.Build.Tasks/AddDependenciesToProjectJson.cs

There was a spurious "version == null" check that always evaluated to
false causing the AddDependenciesToProjectJson task to omit the package
build number suffix.  As a result the test build would fail.
Fixed a case where external package versions weren't getting updated.

Fix generation of project.json for tests built against packages.

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets

Adding Commit hash to native Windows binaries as well

---

src/packages.builds

Fixes an issue with https://github.com/dotnet/buildtools/commit/fc2ad4f6202a3ca6a52da7ae3d2513ce0bf26700

Use configuration specific packaging task

---

src/nuget/Microsoft.DotNet.BuildTools.GenAPI.nuspec
src/nuget/Microsoft.DotNet.BuildTools.nuspec
src/nuget/xunit.console.netcore.nuspec
src/nuget/xunit.runner.uwp.nuspec

Need to do this to get out of the way of the release branch.
/cc @jhendrixMSFT

Bump package versions

---

src/Microsoft.DotNet.Build.Tasks.Packaging/src/GetRuntimeJsonValues.cs
src/Microsoft.DotNet.Build.Tasks.Packaging/src/GetRuntimeTargets.cs
src/Microsoft.DotNet.Build.Tasks.Packaging/src/Microsoft.DotNet.Build.Tasks.Packaging.csproj

Port these tasks from CoreFx.Build.Packaging.Tasks for open sourcing the package testing tooling.
/cc @weshaggard @ericstj

Port GetRuntimeTargets and GetRuntimeJsonValues for Package Testing.

---

init-tools.cmd

Set exit codes for init-tools.cmd if there is an error.

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets

Include Unix binaries when testing with local bits

---

src/common/AppxCommandLine.cs
src/xunit.console.uwp/HostedAppxTest.cs
src/xunit.runner.uwp/xunit.runner.uwp.csproj

- Move AppPackages folder into bin\.
- Fix default reporter.
- Fix not waiting long enough for testResults.xml to finish writing out.

Update for some issues Mariana and Karthik found.

---

src/Microsoft.DotNet.Build.Tasks.Packaging/src/GetApplicableAssetsFromPackages.cs

For runtime assets we want the PKGProj to include the PDB if it is
available.
Alternate fix for https://github.com/dotnet/buildtools/pull/837
/cc @MattGal @karajas

Pass PDBs along with runtime assets

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/ReferenceAssemblies.props
src/Microsoft.DotNet.Build.Tasks/PackageFiles/ReferenceAssemblies.targets

Adding support for Compat reference and facade assemblies to override the OutputPath location

---

src/Run/Setup.cs

Let's say that the command `build-managed` in the config.json file is:
```
"build-managed":{
"alias":{
"binaries":{
"description": "Only builds binaries. It doesn't restore packages.",
"settings":{
"RestoreDuringBuild": false,
"OSGroup": "default"
}
}
}
```
where the default value of `OSGroup=AnyOS`
Calling: `build-managed -binaries -OSGroup=Linux` will fail because the value of `OSGroup` is being overwritten.
This behavior es not expected as we want the users to custom the value of the settings.
With this change if a setting has a "default" value, it could be overwritten if the user provides a different value.
Calling: `build-managed -binaries -OSGroup=Linux` will work.
cc: @joperezr

Fix run command overwriting value of setting

---

src/Microsoft.DotNet.Build.Tasks/GenerateAssemblyList.cs
src/Microsoft.DotNet.Build.Tasks/GenerateTestExecutionScripts.cs
src/Microsoft.DotNet.Build.Tasks/PackageFiles/RunnerTemplate.Windows.txt
src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets
src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
src/nuget/xunit.runner.uwp.nuspec
src/xunit.console.uwp/HostedAppxTest.cs
src/xunit.console.uwp/Program.cs
src/xunit.netcore.extensions/project.json
src/xunit.runner.uwp/project.json

/cc @crummel @MattGal @Chrisboh

Add support to run UWP Runner with CoreFx

---

src/Microsoft.DotNet.Build.CloudTestTasks/FilterForUpload.cs
src/Microsoft.DotNet.Build.CloudTestTasks/Microsoft.DotNet.Build.CloudTestTasks.csproj
src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets

Fix test list filtering for CloudTest

---

Documentation/RunCommand.md
Documentation/configTemplate.json

cc: @joperezr @sokket @Priya91 @wtgodbe @tyoverby

Adding documentation for the Run Command Tool

---

src/Run/Constants.cs
src/Run/Interop.cs
src/Run/Run.csproj
src/Run/RunProcess.cs
src/Run/SettingValueProvider.cs
src/Run/Setup.cs

cc @maririos @weshaggard @sokket @markwilkie

Add CPUArch and OSName helpers to Run.exe

---

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
src/Microsoft.DotNet.Build.CloudTestTasks/SendToHelix.cs
src/xunit.console.uwp/HostedAppxTest.cs
src/xunit.console.uwp/Program.cs

Add ability to submit filtered TestTFM runs for CloudTest using updated API
Add test list filtering based on TestTFM and OSGroup
/cc @ChadNedzlek @MattGal

Add ability to send JobType runs for CloudTest using updated API

---

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets

Fix to set HelixSource variable for official builds, non-official builds and fallback on unknown

---

src/Run/Interop.cs

For rhel just return the major version number is OSRid.

---

src/Run/Constants.cs
src/Run/SettingValueProvider.cs

Update logic for OSName to include more OS Names.

---

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
src/Microsoft.DotNet.Build.CloudTestTasks/WriteItemsToJson.cs

Tested by submitting job ed46e5ad-5bb3-4f83-8531-38bfb2d8c353
@ChadNedzlek .

Fix issues around inclusion of Official build id

---

src/Microsoft.DotNet.Build.Tasks.Packaging/src/GetApplicableAssetsFromPackageReports.cs
src/Microsoft.DotNet.Build.Tasks.Packaging/src/Microsoft.DotNet.Build.Tasks.Packaging.csproj

Add task to get applicable assets from package reports

---

src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
src/Microsoft.DotNet.Build.Tasks.Packaging/src/ValidatePackage.cs

cc @ericstj 
This change will require some changes in corefx once merged. See https://github.com/weshaggard/corefx/commit/cfa8c43401dc80e19dcd14f3099d7504b42b14d5 for the corefx changes that will need to be made.

Add UAP support to validation and reporting

---

Documentation/RepoCompose.md

Initial documentation describing a method for composing our repos together.

Documentation on compose commands

---

src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/xunitrunner-perf/csvjsonconvertor.py
src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/xunitrunner-perf/postprocessperfresults.py
src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/xunitrunner-perf/xunitrunner-perf.py
src/Microsoft.DotNet.Build.Tasks/PackageFiles/PerfTesting.targets
src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets

Generating csvs per metric calculated and constructing json using these csvs, this is required to display multiple metrics on benchview
Fixing error codes returned by .cmd/.sh for perf tests
@MattGal @lt72

Adding multi-metric analysis to perf results jsons

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets

fix corerun hardcoding to netcoreapp1.1

---

src/Run/SettingValueProvider.cs
src/Run/Setup.cs

Make settings search case insensitive.

---

src/Run/Interop.cs

Parse id for quotes from /etc/os-release.

---

src/Microsoft.DotNet.Build.Tasks.Packaging/src/GenerateNuSpec.cs
src/Microsoft.DotNet.Build.Tasks.Packaging/src/GetLastStablePackage.cs
src/Microsoft.DotNet.Build.Tasks.Packaging/src/HarvestPackage.cs
src/Microsoft.DotNet.Build.Tasks.Packaging/src/Microsoft.DotNet.Build.Tasks.Packaging.csproj
src/Microsoft.DotNet.Build.Tasks.Packaging/src/NuGetAssetResolver.cs
src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageItem.cs
src/Microsoft.DotNet.Build.Tasks.Packaging/src/ValidatePackage.cs
src/Microsoft.DotNet.Build.Tasks.Packaging/src/VersionUtility.cs
src/Microsoft.DotNet.Build.Tasks.Packaging/test.Desktop/project.json
src/Microsoft.DotNet.Build.Tasks.Packaging/test/HarvestPackageTests.cs
src/Microsoft.DotNet.Build.Tasks.Packaging/test/Microsoft.DotNet.Build.Tasks.Packaging.Tests.csproj
src/Microsoft.DotNet.Build.Tasks.Packaging/test/project.json

See the individual commits for details.  This PR adds support for redistributing assets from the last shipped packages.  It also validates the latest package to ensure it supports all frameworks supported by the last package.

Redist NuPkg assets

---

src/Run/CommandLine.cs

Fixing some typos

---

src/Microsoft.DotNet.VersionTools/Dependencies/FileRegexUpdater.cs
src/Microsoft.DotNet.VersionTools/Dependencies/ProjectJsonUpdater.cs
src/Microsoft.DotNet.VersionTools/Microsoft.DotNet.VersionTools.csproj
src/Microsoft.DotNet.VersionTools/Util/ArgumentEscaper.cs
src/Microsoft.DotNet.VersionTools/Util/Command.cs
src/Microsoft.DotNet.VersionTools/Util/CommandResult.cs
src/Microsoft.DotNet.VersionTools/Util/FileUtils.cs

Fixes #935.
cc: @dagood @eerhardt

Preserve BOM when updating files in VersionTools

---

src/Microsoft.DotNet.Build.Tasks.Packaging/src/GetPackageVersion.cs
src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/PackageLibs.targets
src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
src/Microsoft.DotNet.Build.Tasks.Packaging/src/ValidatePackage.cs

A few fixes for various packaging annoyances that have cropped up recently.
See individual commit messages for details.
/cc @weshaggard @chcosta @joperezr

Packaging updates

---

src/Microsoft.DotNet.Build.Tasks.Packaging/src/ValidatePackage.cs

Fix typo in log message.

---

config.json

Add /nodeReuse:false to MsBuildParameters setting in config.json

---

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets

/cc @ChadNedzlek @MattGal 
Helix Run: e54e0bfa-8825-4fa6-9dfe-86f043348711

Replace container name with a random GUID

---

src/GenFacades/Program.cs

Adding a check to see if a typeforward already exists

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
src/xunit.netcore.extensions/Attributes/SkipOnTargetFramework.cs
src/xunit.netcore.extensions/Discoverers/SkipOnTargetFrameworkDiscoverer.cs
src/xunit.netcore.extensions/TargetFrameworkMoniker.cs
src/xunit.netcore.extensions/XunitConstants.cs
src/xunit.netcore.extensions/xunit.netcore.extensions.csproj

cc @weshaggard @tarekgh @danmosemsft 
fixes #960

Add xunit Traitattribute to conditionally run tests on TFMs.

---

src/xunit.netcore.extensions/Attributes/SkipOnTargetFrameworkAttribute.cs
src/xunit.netcore.extensions/Discoverers/SkipOnTargetFrameworkDiscoverer.cs
src/xunit.netcore.extensions/TargetFrameworkMonikers.cs
src/xunit.netcore.extensions/xunit.netcore.extensions.csproj

Rename APIs to match naming guidelines.

---

src/xunit.netcore.extensions/Attributes/SkipOnTargetFrameworkAttribute.cs

Allow specifying metadata for skip reason.

---

src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/scriptrunner/scriptrunner.py

Return appropriate values for workitem failure for reporting.
@ChadNedzlek @MattGal

Add Workitem exit codes

---

src/xunit.console.uwp/HostedAppxTest.cs
src/xunit.runner.uwp/App.xaml.cs
src/xunit.runner.uwp/xunit.runner.uwp.csproj

These caused AppX startup to time out and the test to fail.

Fix issue with running async tests in startup code.

---

bootstrap/bootstrap.ps1

New script to be used when boot-strapping build tools for a repo.  A bash
version will be implemented a bit later.

Add new CLI and build tools boot-strapping script.

---

src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageIndex.cs
src/Microsoft.DotNet.Build.Tasks.Packaging/src/UpdatePackageIndex.cs
src/Microsoft.DotNet.Build.Tasks.Packaging/src/ValidatePackage.cs

This updates indexing to handle cases where we bump up the package
version during pre-release.

Improve package indexing and validation

---

src/GenFacades/GenFacades.csproj
src/Microsoft.DotNet.Build.Tasks/PackageFiles/ApiCompat.targets
src/Microsoft.DotNet.Build.Tasks/PackageFiles/partialfacades.targets
src/common/CommandLine.cs

cc @ericstj @mellinoe @joperezr

Switch to response files for GenFacades

---

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets

This work only needs the list of tests that are supported on various OS.
@MattGal @markwilkie @schaabs

Test payload indexing

---

src/Microsoft.DotNet.CodeAnalysis/PackageFiles/PinvokeAnalyzer_OneCoreApis.txt

@weshaggard, @stephentoub, @danmosemsft

Add new shell apis to OneCore list.

---

src/GenAPI/Program.cs
src/Microsoft.Cci.Extensions/Extensions/DocIdExtensions.cs
src/Microsoft.Cci.Extensions/Extensions/FakeCustomAttribute.cs
src/Microsoft.Cci.Extensions/Extensions/TypeExtensions.cs
src/Microsoft.Cci.Extensions/Microsoft.Cci.Extensions.csproj
src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Attributes.cs

cc @ericstj @terrajobst 
Adds attribute filtering to genapi, including changes to cci extensions to filter some fake attributes.
Adds support for genapi to output one file per assembly.

Gen api updates

---

src/Microsoft.DotNet.Build.Tasks.Packaging/src/ValidatePackage.cs

Fix case where package contains no DLLs

---

src/xunit.runner.uwp/XmlTestExecutionVisitor.cs

Fixes dotnet/corefx#7166, where this test will 'fail' because invalid characters are being written to `testResults.xml`:
```cs
public static IEnumerable<object[]> Equal_TestData()
{
yield return new object[] { "\uD800", "\uD800" };
}
[Theory]
[MemberData(nameof(Equal_TestData))]
public void Equal(string expected, string actual)
{
Assert.Equal(expected, actual);
}
```
Related xUnit PRs upstream: xunit/xunit#804 and xunit/assert.xunit#1
cc @weshaggard @stephentoub

Escape invalid chars when writing test output to XML

---

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.targets
src/Run/CommandLine.cs
src/Run/Executor.cs
src/Run/Setup.cs

Fixes for:
#756 
#1074 
#928 (this enables removing it from Config.json)

Various Issue fixes

---

src/Microsoft.DotNet.VersionTools/Automation/GitHubApi/GitHubClient.cs

When there is an error response code in `GitHubClient`, include the response contents in the exception so the error can be diagnosed. Also trace rate limit information with every request for informational purposes.
An example rate limit error with these changes:
> Response code does not indicate success: 403 (Forbidden) with content: {"message":"API rate limit exceeded for 198.51.125.2. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}
Fixes https://github.com/dotnet/buildtools/issues/1001.
@chcosta @weshaggard 
/cc @gkhanna79

Trace GitHub rate limit info, print error contents

---

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets

Fix issue where AnyOS Tests have not been included for a while
@bryanar , @weshaggard , @joperezr

Fix AnyOS Uploading bug

---

Documentation/RunCommand.md

Add information about defaultAlias as well as remove blurb about ExtraParameters (no longer required)
@maririos

Update docs for defaultAlias and extra params

---

bootstrap/bootstrap.ps1

This change adds two optional parameters to the bootstrapper script:
1. Selecting the directory to install the CLI (by default, this remains in <toolsDir>\dotnetcli).  This is needed for e.g., CLI, which wants its bootstrapping CLI in the .stage0 folder.
2. Selecting the shared framework version to use.  This is to set up buildtools' dotnetcli\shared\Microsoft.NETCore.App\version symlink correctly.  We could attempt to automatically detect this but the bootstrapper never sees the install package, it's all handled by dotnet-install - the options I see are either modifying dotnet-install to check the version and pass it back, or requiring a Microsoft.NETCore.App.version similar to the other version files in each consuming repo.
The fixes the buildtools portion of #918.

Parameterize bootstrapper for CLI install path and shared framework version.

---

bootstrap/bootstrap.sh

I attempted to keep this very close to the PowerShell bootstrapper (some of it is also cribbed from CLI's init-tools.sh).  Only tested on Ubuntu so far.

Add Linux bootstrapper script.

---

src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Attributes.cs

Fix default parameter values for value types

---

src/Microsoft.DotNet.Build.Tasks.Packaging/src/GeneratePackageReport.cs
src/Microsoft.DotNet.Build.Tasks.Packaging/src/NuGetAssetResolver.cs
src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageReport.cs

Added support to record native assets in the package report.

Record native assets in package report

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.props
src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.targets
src/Microsoft.DotNet.Build.Tasks/PackageFiles/buildagainstpackages.targets

Fix condition for SkipGenerateTestProjectJson to match new default

Resolve ordering issue with IsTestProject

---

bootstrap/bootstrap.sh

- Symlink argument were switched.
- Typo in clearing the local tools directory.

Fix a couple minor issues found when adding the bootstrap in CLI.

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.targets

This is to support the source indexer.
/cc: @weshaggard @ericstj

Add extension import in packageresolve.targets

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets
src/nuget/Microsoft.DotNet.BuildTools.TestSuite.nuspec

@karajas @ericstj 
Needed along with another change I will make after this to run Xunit tests on .NET Framework Desktop.

Add back Xunit Console Runner

---

src/Microsoft.DotNet.Build.Tasks.Packaging/src/GetApplicableAssetsFromPackageReports.cs
src/Microsoft.DotNet.Build.Tasks.Packaging/src/VersionUtility.cs

A couple fixes for build issues that cropped up after recent changes to always produce package reports.

Report fixes

---

src/Microsoft.DotNet.Build.CloudTestTasks/SendToHelix.cs

Happens in the case of unreachable host in SendToHelix task
@ChadNedzlek  @sokket

Handle possibility of unhandled exception in SendToHelix task

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/CodeCoverage.targets
src/common/test-runtime/project.json

Upgrade ReportGenerator for code coverage to 2.5.0

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets

Show test log path when a test fails

---

src/Run/CommandLine.cs
src/common/CommandLine.cs

Space does not dismiss a Console.ReadLine()

Fix message to be accurate

---

bootstrap/bootstrap.ps1
bootstrap/bootstrap.sh

Bootstrap needs cli subdirectory to exist

---

src/Microsoft.DotNet.Build.Tasks.net45/FilterRuntimesFromSupports.Desktop.cs
src/Microsoft.DotNet.Build.Tasks.net45/Microsoft.DotNet.Build.Tasks.net45.csproj
src/Microsoft.DotNet.Build.Tasks/AddDependenciesToProjectJson.cs
src/Microsoft.DotNet.Build.Tasks/FilterRuntimesFromSupports.cs
src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj
src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.targets
src/Microsoft.DotNet.Build.Tasks/PackageFiles/buildagainstpackages.targets
src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
src/Microsoft.DotNet.Build.Tasks/project.json
src/Microsoft.DotNet.BuildTools.TestSuite/runtime.json

Allow Filtering of rids from SupportsFile

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/buildagainstpackages.targets

Change _RemovePackageProjectReference condition to work on non-Windows platforms.

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/buildagainstpackages.targets

Fix regex for removing project refs

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh

Copy over "strict" settings from `bootstrap.sh` to `init-tools.sh`. The main advantage is that the script will now exit as soon as any command gets a non-zero exit code (NZEC), so `init-tools.sh` can't silently fail like it did for #1201.
Tested on Alpine docker container.
See https://github.com/dotnet/buildtools/pull/1202.
@ericstj @ellismg @crummel 
/cc @chcosta

Use "set -e" rather than catching NZECs manually

---

src/Microsoft.DotNet.Build.Tasks/AddDependenciesToProjectJson.cs
src/Microsoft.DotNet.Build.Tasks/FilterRuntimesFromSupports.cs

/cc @naamunds @weshaggard 
This should unblock official builds.

Make Supports filtering optional

---

src/GenAPI/Program.cs

Have GenAPI also include exported types when writing typeforward list

---

src/Microsoft.DotNet.Build.Tasks/GenerateBindingRedirect.cs
src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj
src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets
src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets

/cc @danmosemsft @AlexGhiondea @ericstj @weshaggard

Add binding redirect generation for desktop tests

---

src/Microsoft.DotNet.Build.Tasks/FilterNativeAssemblies.cs
src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj
src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets

Filter native assemblies from binding redirect generation

---

src/Microsoft.DotNet.Build.CloudTestTasks.net45/project.json

Unify System.Reflection.Metadata version between Desktop projects

---

src/Microsoft.DotNet.Build.Tasks.net45/Microsoft.DotNet.Build.Tasks.net45.csproj
src/Microsoft.DotNet.Build.Tasks/AddDependenciesToProjectJson.cs
src/Microsoft.DotNet.Build.Tasks/project.json

* Enable reading versions file from URI
* Remove unncessary variable
* Change scheme for determining if a path represents a local path or a web
path.
* Iterate on streamreader lines

Enable reading versions file from URI (#1112)

---

src/Microsoft.DotNet.Build.Tasks/AddDependenciesToProjectJson.cs
src/Microsoft.DotNet.Build.Tasks/PackageFiles/buildagainstpackages.targets

* Add retry logic
* Allow overrides
* Fix spacing

Release/1.0.0  add retry logic to reading versions file (#1280)

---

Documentation/test-targets-design.md
src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets
src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets

/cc @weshaggard @chcosta @MattGal

Add design documentation for test targets

---

src/Microsoft.DotNet.Build.Tasks.Packaging/src/ApplyPreReleaseSuffix.cs

Fix null-ref for repos that don't use index

---

src/Microsoft.DotNet.Build.Tasks/CleanupVSTSAgent.cs

Also added support for long-path cleanup.   I avoided PInvoking to Windows shell APIs as this same task is used on Linux.
@chcosta

Handle UnauthorizedAccessException in CleanupVSTSAgent task

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/PerfTesting.targets

I have ripped out most of the guts that were in the PerfTesting.targets
file and moved everything over to run using the dotnet cli and the new
dev/eng model.  This includes removing all of the previous goo that
helped with loading the analysis and runner exes as those have been
replaced by the PerfRunner.

Update to run on Jenkins

---

src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
src/Microsoft.DotNet.Build.Tasks.Packaging/src/PromoteDependencies.cs

Fix dup keys

---

src/Microsoft.DotNet.Build.Tasks.Packaging/src/ApplyPreReleaseSuffix.cs

Make ApplyPreReleaseSuffix skip pre- deps

---

src/Microsoft.DotNet.Build.Tasks.Packaging/src/GenerateRuntimeDependencies.cs

Fix runtime.json workaround for version range

---

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/DumplingHelper.py

I fixed up all of these other mistakes, but didn't catch this one because it wasn't running on my machine...

Fix python3-python2 translation mistake in DumplingHelper.py

---

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.Helix.targets
src/Microsoft.DotNet.Build.CloudTestTasks/SendJobsToHelix.cs
src/Microsoft.DotNet.Build.CloudTestTasks/WriteItemsToJson.cs

- Insert understanding of helix-specific scriptrunner.py
- Add environment variable info for users.
- Address https://github.com/dotnet/core-eng/issues/546 for @mmitche

More CloudTest.targets refactoring work

---

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.Helix.targets

… since this needs to vary with Queue Id.
@chcosta , @weshaggard 
I'll also make a parallel PR to CoreFX, which can't be merged until this goes in.

Change the way the Properties metadata gets into jobs

---

src/Microsoft.DotNet.Build.Tasks.Packaging/src/FrameworkLists/MonoAndroid,Version=v1.0/FrameworkList.xml
src/Microsoft.DotNet.Build.Tasks.Packaging/src/FrameworkLists/MonoTouch,Version=v1.0/FrameworkList.xml
src/Microsoft.DotNet.Build.Tasks.Packaging/src/FrameworkLists/Xamarin.Mac,Version=v2.0/FrameworkList.xml
src/Microsoft.DotNet.Build.Tasks.Packaging/src/FrameworkLists/Xamarin.TVOS,Version=v1.0/FrameworkList.xml
src/Microsoft.DotNet.Build.Tasks.Packaging/src/FrameworkLists/Xamarin.WatchOS,Version=v1.0/FrameworkList.xml
src/Microsoft.DotNet.Build.Tasks.Packaging/src/FrameworkLists/Xamarin.iOS,Version=v1.0/FrameworkList.xml

Release/1.1.0 version of https://github.com/dotnet/buildtools/pull/1348

[release/1.1.0] Make ValueTuple inbox on Xamarin

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/scripts/docker/cleanup-docker.sh

Additionally, I changed the formatting of the output so that it is easier to distinguish the various phases of the cleanup.  I found the volumes and containers sections blended together without this.
```
Cleaning up containers
----------------------
delete corefx1234
corefx1234
delete coreclr1234
coreclr1234
Cleaning up volumes
-------------------
delete coreclr123453
coreclr123453
delete corefx123453
corefx123453
Cleaning up images
------------------
delete 978d85d02b87 (debian:jessie)
Untagged: debian:jessie
Untagged: debian@sha256:52af198afd8c264f1035206ca66a5c48e602afb32dc912ebf9e9478134601ec4
Deleted: sha256:978d85d02b87aea199e4ae8664f6abf32fdea331884818e46b8a01106b114cee
Deleted: sha256:d17d48b2382adda1fd94284c51d725f0226bf20b07f4d29ce09596788bed7e8e
delete 0ef2e08ed3fa …
```

Refactor cleanup-docker to cleanup volumes

---

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.Helix.targets

Fix to address https://github.com/dotnet/core-eng/issues/596.

Add new delimiter "+" for TargetQueues

---

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.Helix.targets

Fix the multi-queue "+" replacement logic

Fix the multi-queue "+" replacement logic

---

src/Microsoft.DotNet.Build.Tasks.Packaging/src/VerifyClosure.cs

Add option to emit DGML to VerifyClosure

---

src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/PackageLibs.targets

Add a hook to specify additional files to package

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/DesktopRunnerConfigFile.config

Adding config file for desktop runners (xunit and remote executor).
cc: @weshaggard @joperezr @tarekgh

Add config file for desktop test runners

---

src/BuildTools.sln
src/Microsoft.DotNet.Build.CloudTestTasks.net45/project.json
src/Microsoft.DotNet.Build.CloudTestTasks/Microsoft.DotNet.Build.CloudTestTasks.csproj
src/Microsoft.DotNet.Build.CloudTestTasks/SimulateHelixExecution.cs

Will require small additional changes to projects which wish to use this.  I have this ready to go for CoreFX here: https://github.com/dotnet/corefx/pull/18229 but cannot merge that one without a build tools update.

Add support for Helix local execution. 

---

src/Microsoft.DotNet.Build.Tasks.Packaging/src/HarvestPackage.cs
src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
src/Microsoft.DotNet.Build.Tasks.Packaging/src/ValidatePackage.cs
src/Microsoft.DotNet.Build.Tasks.Packaging/test/HarvestPackageTests.cs

Explicit harvesting

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets

Address PR feedback

---

src/Microsoft.DotNet.Build.Tasks/CleanupVSTSAgent.cs

Enable disk usage reporting for TEMP and Nuget Cache。

Morediskusagetelemetry

---

src/Microsoft.DotNet.Build.Tasks/CleanupVSTSAgent.cs

Fix the Nuget and TEMP path on Linux/OSX.

Fix the Nuget and TEMP path on Linux/OSX.

---

src/Microsoft.DotNet.Build.Tasks/CleanupVSTSAgent.cs

Don't report disk usage info on deleted dirs.

Don't report disk usage info on deleted dirs.

---

src/Microsoft.DotNet.Build.Tasks/CleanupVSTSAgent.cs

Try to use AddDirToListIfExist because it now might works with full
path.

Clean up the code

---

src/Microsoft.DotNet.Build.Tasks/GetNetCoreAppVersionsFromFile.cs
src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj

PTAL: @weshaggard 
Adding a simple task that will read the netcoreapp versions file to parse out repo's hashes.

Adding task that will read netcoreapp versions file to get out repo's hashes

---

src/xunit.runner.uap/Package.appxmanifest

Enable more capabilities for our uap/uapaot test runs.
https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations

Adding all required capabilities for our uap/uapaot runs

---

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/DumplingHelper.py

Address https://github.com/dotnet/corefx/issues/20172

Return exit code from dumpling collect script

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets

Remove unnecessary ItemGroup in tests.targets

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/CodeCoverage.targets
src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets

This is to allow people to pass additional options to xunit through msbuild.
cc: @weshaggard @danmosemsft

Xunit options

---

src/Microsoft.DotNet.Build.Tasks/CleanupVSTSAgent.cs

- Add MaximumTimeInMinutes, which will cause the build task to quit after the specified time (default 10.0 mins)
- Add MaximumWorkspacesToClean to prevent taking on every workspace on the machine
- Remove usage of Robocopy (which can fail to return)
@chcosta @smile21prc @weshaggard

Fixups for Build agent cleanup task

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.ps1

This is to unblock Maestro updates failing with directory already exists.
https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=792972&_a=summary
/cc @ellismg @dagood

Add -Force to init-tools.ps1

---

src/WindowsStoreAppLauncher/App.h
src/WindowsStoreAppLauncher/AppxApp.cpp
src/WindowsStoreAppLauncher/AppxApp.h
src/WindowsStoreAppLauncher/Args.h
src/WindowsStoreAppLauncher/Stream.cpp
src/WindowsStoreAppLauncher/Stream.h
src/WindowsStoreAppLauncher/Support.cpp
src/WindowsStoreAppLauncher/Support.h
src/WindowsStoreAppLauncher/WindowsStoreApp.cpp
src/WindowsStoreAppLauncher/WindowsStoreApp.h
src/WindowsStoreAppLauncher/WindowsStoreApp.rc
src/WindowsStoreAppLauncher/WindowsStoreAppLauncher.cpp
src/WindowsStoreAppLauncher/WindowsStoreAppLauncher.sln
src/WindowsStoreAppLauncher/WindowsStoreAppLauncher.vcxproj
src/WindowsStoreAppLauncher/WindowsStoreAppLauncher.vcxproj.filters
src/WindowsStoreAppLauncher/stdafx.cpp
src/WindowsStoreAppLauncher/stdafx.h

cc: @jkotas @weshaggard @danmosemsft @alexperovich 
Adding the Launcher that is used for uap tests to buildtools. 
I'm also adding one temp line to run.cmd to build the project since we want to have the launcher signed before its packaged, which is for now done as a separate step. Once one official build goes through and this package is signed, I will undo the change to that line.

Adding WindowsStoreAppLauncher project

---

src/xunit.runner.uap/UpdateScript/AppxManifest_master.xml

cc: @JeremyKuhne @AlexGhiondea @tarekgh 
Already did a private Helix run with these changes and have verified that it fixes the issues and it doesn't cause any regressions.

Add CodeGeneration capability which is required for some of our MemoryMappedFile tests

---

src/xunit.runner.uap/XUnit.Runner.Uap.csproj

Skip merging framework resources in uap runners PRI

---

src/Microsoft.DotNet.CodeAnalysis/PackageFiles/PinvokeAnalyzer_Win32UWPApis.txt

Per differences found on recent changes to modernapis.xml

Uwp api list update

---

src/Microsoft.DotNet.Build.CloudTestTasks/ListAzureContainers.cs

It looks like Sync -ab is still supported and mostly works in master, so instead of deleting this task I fixed it.
Incidentally fixed it when a Prefix is not supplied (as this will null ref otherwise)
@dagood , @weshaggard  FYI

Support listing > 5000 containers in ListAzureContainers

---

src/xunit.netcore.extensions/Attributes/ConditionalFactAttribute.cs
src/xunit.netcore.extensions/Attributes/ConditionalTheoryAttribute.cs
src/xunit.netcore.extensions/Discoverers/ConditionalFactDiscoverer.cs
src/xunit.netcore.extensions/Discoverers/ConditionalTestDiscoverer.cs
src/xunit.netcore.extensions/Discoverers/ConditionalTheoryDiscoverer.cs

[ConditionalFact(typeof(PlatformDetection), "nameof(PlatformDetection.IsNonZeroLowerBoundArraySupported)")]

Support passing Type to XUnit ConditionalFact/Theory

---

src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets

Add netcoreapp2.1 as a valid option for SupportedFrameworks

---

src/Microsoft.DotNet.Build.Tasks.Packaging/src/HarvestPackage.cs

/cc @weshaggard 
I ran into this when updating corefx to net471.
I need to copy a harvested asset into a runtime-specific folder since latest package added RID-split cross-compile.

Allow for files to be copied to a new path while harvesting

---

dependencies.props
dir.props
src/BuildTools.sln
src/Microsoft.DotNet.Build.CloudTestTasks/AzureBlobLease.cs
src/Microsoft.DotNet.Build.CloudTestTasks/AzureHelper.cs
src/Microsoft.DotNet.Build.CloudTestTasks/ListAzureBlobs.cs
src/Microsoft.DotNet.Build.CloudTestTasks/UploadClient.cs
src/Microsoft.DotNet.Build.Tasks.Feed.net45/Microsoft.DotNet.Build.Tasks.Feed.net45.csproj
src/Microsoft.DotNet.Build.Tasks.Feed.net45/project.json
src/Microsoft.DotNet.Build.Tasks.Feed/BlobFeed.cs
src/Microsoft.DotNet.Build.Tasks.Feed/BlobFeedAction.cs
src/Microsoft.DotNet.Build.Tasks.Feed/ConfigureInputFeed.cs
src/Microsoft.DotNet.Build.Tasks.Feed/Microsoft.DotNet.Build.Tasks.Feed.csproj
src/Microsoft.DotNet.Build.Tasks.Feed/PackageFiles/Publish.targets
src/Microsoft.DotNet.Build.Tasks.Feed/PackageFiles/Restore.targets
src/Microsoft.DotNet.Build.Tasks.Feed/PushToBlobFeed.cs
src/Microsoft.DotNet.Build.Tasks.Feed/project.json
src/Microsoft.DotNet.Build.Tasks.net45/Microsoft.DotNet.Build.Tasks.net45.csproj
src/nuget/Microsoft.DotNet.Build.Tasks.Feed.nuspec

Initial PR for collecting feedback.
This introduces a set of tasks to control the input and output feeds of a repo. It currently only supports the creation of Transport Feeds.
/cc @weshaggard @chcosta @jaredpar

Add Microsoft.Dotnet.Build.Tasks.Feed toolset

---

src/Microsoft.DotNet.Build.Tasks.Feed/BlobFeedAction.cs
src/Microsoft.DotNet.Build.Tasks.Feed/PackageFiles/Publish.targets
src/Microsoft.DotNet.Build.Tasks.Feed/PackageFiles/Restore.targets

Clean up fixes for Microsoft.Dotnet.Build.Tasks.Feed

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.props
src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets

A few tabs merged in https://github.com/dotnet/buildtools/pull/1665, just doing a quick fixup.

Fix a few indentation problems, tab characters

---

appveyor.yml

Cleaning up this file that is no longer used

Removing appveyor.yml

---

build.cmd

cc: @weshaggard @Chrisboh 
Fixing the build.cmd script so that it works with the existing build definition.

Fix release/1.0.0 official build

---

src/Microsoft.DotNet.Build.Tasks.Packaging/src/GenerateRuntimeGraph.cs

This makes the task do a diff with existing files by default and only updates the files
when UpdateRuntimeFiles is set to true.
When updating the files we'll clear the readonly bit to handle the case where someone
has made the files readonly (since they are explicitly setting UpdateRuntimeFiles).
This is a buildtools implementation of https://github.com/dotnet/corefx/pull/24306.

Make GenerateRuntimeGraph diff files by default

---

src/Microsoft.DotNet.Build.Tasks.Feed/BlobFeed.cs
src/Microsoft.DotNet.Build.Tasks.Feed/BlobFeedAction.cs
src/Microsoft.DotNet.Build.Tasks.Feed/PushToBlobFeed.cs
src/nuget/Microsoft.DotNet.Build.Tasks.Feed.nuspec

/cc @mmitche 
This depends on deploying a service that handles the conversion.

Add ability to create secure feed

---

src/Microsoft.DotNet.Build.Tasks.Feed/PackageFiles/Publish.targets

Update sample Publish.targets to match current parameters in Microsoft.DotNet.Build.Tasks.Feed

---

src/Microsoft.DotNet.Build.Tasks.Feed/BlobFeed.cs
src/Microsoft.DotNet.Build.Tasks.Feed/BlobFeedAction.cs

Pass relativePath instead of feedUrl in BlobFeed constructor

---

src/Microsoft.DotNet.Build.Tasks/DownloadFileFromUrl.cs
src/Microsoft.DotNet.Build.Tasks/DownloadFilesFromUrl.cs
src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj
src/Microsoft.DotNet.Build.Tasks/PackageFiles/Symbols.targets

This task will be used in order to download CoreCLR symbol package in CoreFX. 
cc: @weshaggard @danmosemsft

Add task to download files from url

---

src/Microsoft.DotNet.Build.Tasks.Feed/BlobFeed.cs
src/Microsoft.DotNet.Build.Tasks.Feed/BlobFeedAction.cs

Fix Flat upload of assets

---

src/Microsoft.DotNet.Build.Tasks/GenerateDepsJson.cs
src/Microsoft.DotNet.Build.Tasks/PackageFiles/MSBuild.runtimeconfig.json
src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.csproj

cc: @weshaggard @ericstj 
Porting required changes to release/2.0 branch so that we can update the CLI used in 2.0 corefx

Changes required in order to onboard 2.0.0 CLI to corefx

---

src/nuget/Microsoft.DotNet.Build.Tasks.Symbols.nuspec

@weshaggard , this PR is creating a task library which includes just the minimum tasks for handling signed symbols injection.

Create Symbols package task library

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/CodeCoverage.targets
src/common/test-runtime/project.json

See https://github.com/dotnet/corefx/issues/23588 - this works around a stack overflow.

Update ReportGenerator to 3.0.1

---

src/Microsoft.DotNet.Build.Tasks.Feed/BlobFeed.cs
src/Microsoft.DotNet.Build.Tasks.Feed/BlobFeedAction.cs

Update timeout and delay time for lease during upload

---

src/Microsoft.DotNet.Build.Tasks.Feed/BlobFeed.cs

/cc @wtgodbe 
this breaks intermediate restore otherwise.

Make nupkg lowercased

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd
src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh

Porting https://github.com/dotnet/buildtools/pull/1743 to release/2.0.0
cc @danmosemsft @eerhardt

Remove project.json from init-tools (#1743)

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.props
src/Microsoft.DotNet.Build.Tasks/PackageFiles/RepoAPI.Mapping.props
src/Microsoft.DotNet.Build.Tasks/PackageFiles/packageresolve.targets

Ports https://github.com/dotnet/buildtools/pull/1707, https://github.com/dotnet/buildtools/pull/1751, https://github.com/dotnet/buildtools/pull/1749 to `master`.

Port to master: Repo API common implementation

---

src/xunit.runner.uap/RunnerRemoteExecutionServiceUAP/RunnerRemoteExecutionServiceUAP.cs

Matching change for https://github.com/dotnet/corefx/pull/24890

Allow UAP remote runner service to run methods that return void

---

src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj
src/Microsoft.DotNet.Build.Tasks/PackageFiles/packageresolve.targets
src/Microsoft.DotNet.Build.Tasks/PackageRestoreLogger.cs

This logger creates a log of all the package urls, used to determine where the packages are being restore from.
@chcosta @jcagme

Add PackageRestoreLogger to log restore urls

---

src/Microsoft.DotNet.VersionTools/BuildInfo.cs

Fixes https://github.com/dotnet/buildtools/issues/1677

Improve build-info Get failure error message

---

src/Microsoft.DotNet.Build.Tasks/ConvertPortablePdbsToWindowsPdbs.cs

This unblocks the symbol publish leg from a known GenFacades issue: https://github.com/dotnet/buildtools/issues/1739.

Warn and skip PPDB conversion if a DLL has no Debug directory

---

src/Microsoft.DotNet.Build.CloudTestTasks/AzureBlobLease.cs
src/Microsoft.DotNet.Build.CloudTestTasks/AzureHelper.cs
src/Microsoft.DotNet.Build.CloudTestTasks/UploadClient.cs
src/Microsoft.DotNet.Build.Tasks.Feed/BlobFeed.cs
src/Microsoft.DotNet.Build.Tasks.Feed/BlobFeedAction.cs

Fix renew lease function and enable more logging

---

.toolversions

Bumping to 1.0.0-prerelease-02131-03

Update Microsoft.DotNet.Build.Tasks.Feed version

---

src/Microsoft.DotNet.Build.Tasks/EncryptedConfigNuGetRestore.cs

Work around ArgumentNullException encountered in NuGet when restoring optional tooling from a project.json file.
When we get a chance, we should change this to work with msbuild-based restore. (https://github.com/dotnet/buildtools/issues/1550)
I was able to repro https://github.com/dotnet/core-eng/issues/1999 on my dev machine, and this fixed it.
Filed https://github.com/NuGet/Home/issues/6131 with more details about what seems to have broken. (Link included in source.)
/cc @mmitche @weshaggard

Optional tooling restore null argument workaround

---

src/Microsoft.DotNet.Build.Tasks.Feed/BlobFeed.cs
src/Microsoft.DotNet.Build.Tasks.Feed/BlobFeedAction.cs
src/Microsoft.DotNet.Build.Tasks.Feed/SleetLogger.cs

In case overwrite is not set to true then we have to check whether the blob exists.

Checking for blob existence

---

src/Microsoft.DotNet.Build.CloudTestTasks/DownloadFromAzure.cs
src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/SyncCloudContent.targets

Enable download flat files and download in parallel

---

src/Microsoft.DotNet.Build.Tasks.Feed/PackageFiles/Microsoft.DotNet.Build.Tasks.Feed.targets

Update feed targets file to add docs and examples

---

src/Microsoft.DotNet.Build.Tasks/ConvertPortablePdbsToWindowsPdbs.cs

The partially-failed state may still be useful to users of this task.
I implemented this for my own benefit when doing conversions to archive a release's symbols, but it is part of https://github.com/dotnet/core-eng/issues/2073 so I'm submitting a PR.
Specifically, this can be used in CoreFX to make symbols available to downstreams in this case:
> When PDB conversion fails, as much as possible should still be converted and indexed. The package publish leg is independent, which means that even when the symbol leg fails, the packages may be used in downstream builds (e.g. CoreFX -> Core-Setup).
/cc @vancem

Try to convert all Portable PDBs to Windows PDBs even if some fail

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh

Also restore ILAsm on Unix. Turns out this will make my life easier, so just doing that too. Fixes #1363.

Restore ILAsm on Unix

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/IL.targets

See https://github.com/dotnet/coreclr/blob/06828ca1eea8af9b2a0ac147ba8827f128a306e2/tests/src/IL.targets.

Unify IL.targets with CoreCLR's version

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/PublishProduct.targets

Addresses https://github.com/dotnet/core-eng/issues/1422

Handle additional false-positive NuGet push scenarios

---

src/Microsoft.DotNet.Build.Tasks/ExtractResWResourcesFromAssemblies.cs
src/Microsoft.DotNet.Build.Tasks/GenerateResourcesCode.cs
src/Microsoft.DotNet.Build.Tasks/Helper.cs
src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj
src/Microsoft.DotNet.Build.Tasks/NormalizeAssemblyName.cs
src/Microsoft.DotNet.Build.Tasks/PackageFiles/resources.targets
src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
src/Microsoft.DotNet.Build.Tasks/project.json

Per @shmao request I'm porting the resources extraction related work. 
Is this all that you need? Or did you only need partial port of this? 

Port resources file changes to 2.0.0

---

netci.groovy
run.cmd
run.sh

Also add the dotnet cli env variables to both run.cmd/sh.
cc @dagood

Update run.cmd and update CI to not call VS2015 any longer

---

src/Microsoft.DotNet.Build.Tasks.Feed/PackageFiles/Microsoft.DotNet.Build.Tasks.Feed.props
src/Microsoft.DotNet.Build.Tasks.Feed/PackageFiles/Microsoft.DotNet.Build.Tasks.Feed.targets

Addresses https://github.com/dotnet/core-eng/issues/2439

Add Feed props file, alleviate taskdir property conflict 

---

src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets

@ericstj This will just add extra package validation for UAP TFM RS3.
FYI: @weshaggard

Adding UAP RS3 package validation

---

src/Microsoft.DotNet.Build.Tasks/ValidateBinInspectResults.cs

The metadata name is `SpecificError`. If none is provided, the whitelist will continue to apply to all errors.

Allow specific bininspect baseline error per regex

---

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.Helix.targets

@sunandabalu , @botaberg  FYI.
Tested with 3998cdc2-452a-442f-aeb3-b09e88b5ff56.

Support MaxRetryCount

---

src/packages.builds

Match the Core repo versioning scheme.
See https://github.com/dotnet/buildtools/pull/1888

[master] Produce 2.1.0-preview2-* packages

---

src/Microsoft.DotNet.Build.CloudTestTasks/UploadToAzure.cs

Tested using dagood's special container of 7293 blobs.  Quick and dirty given we will reimplement these using the client libs soon.

Use continuation marker in UploadToAzure

---

src/Microsoft.DotNet.Build.CloudTestTasks/UploadToAzure.cs

Reverts dotnet/buildtools#1904
@MattGal @dagood I'm reverting this to fix the timeouts we are hitting in core-setup builds. 
See https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1390865 for detailed log.

Revert "Use continuation marker in UploadToAzure"

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/resources.targets

Fixes https://github.com/dotnet/corefx/issues/26971

Allow generating resources cs code at design time

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/resources.targets

Reverts dotnet/buildtools#1921

Revert "Allow generating resources cs code at design time"

---

src/Microsoft.DotNet.Build.Tasks/CleanupVSTSAgent.cs

Fix #1929 which I saw in a build log.

Add SafeFindHandle to fix OverflowException

---

src/nuget/Microsoft.DotNet.VersionTools.nuspec

Updating NuGet versions on nuspec

---

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.Helix.targets

Optionally read and pass the HelixAttempt variable through to the job start call

Add HelixAttempt support to helix job sending

---

src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.Helix.targets

Add HelixAttempt (and MaxRetryCount)

---

src/nuget/Microsoft.DotNet.Build.CloudTest.nuspec
src/nuget/Microsoft.DotNet.BuildTools.ApiCompat.nuspec
src/nuget/Microsoft.DotNet.BuildTools.Cci.nuspec
src/nuget/Microsoft.DotNet.BuildTools.GenAPI.nuspec
src/nuget/Microsoft.DotNet.BuildTools.GenFacades.nuspec
src/nuget/Microsoft.DotNet.BuildTools.RepoUtils.nuspec
src/nuget/Microsoft.DotNet.BuildTools.Run.nuspec
src/nuget/Microsoft.DotNet.BuildTools.TestSuite.nuspec
src/nuget/Microsoft.DotNet.BuildTools.nuspec
src/nuget/Microsoft.DotNet.VersionTools.nuspec

https://github.com/dotnet/buildtools/issues/1957

Change version string to non-colliding uwp60

---

src/Microsoft.Cci.Extensions/Extensions/CSharp/CSharpCciExtensions.cs
src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Methods.cs
src/Microsoft.DotNet.Build.Tasks/PackageFiles/notsupported.targets

Fixes: https://github.com/dotnet/corefx/issues/25605
cc: @weshaggard @tarekgh @danmosemsft

Produce empty dispose methods and not create finalizers when creating a dummy assembly

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/RunnerTemplate.Unix.txt

Fixes https://github.com/dotnet/buildtools/issues/1956

directory exist check added

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets

This is a side request from #1980

Reduce priority of logging message

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/CodeCoverage.targets

Fixes: https://github.com/dotnet/corefx/issues/28574
cc: @danmosemsft @stephentoub @weshaggard

Disable performance tests from code coverage

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/RunnerTemplate.Unix.txt

Related to https://github.com/dotnet/buildtools/issues/1995

Switching lldb and gdn outputs

---

src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Fields.cs
src/Microsoft.Cci.Extensions/Writers/CSharp/CSharpWriter.cs
src/Microsoft.Cci.Extensions/Writers/DocumentIdWriter.cs

Part of https://github.com/dotnet/corefx/issues/28870
Related PR in corefx: https://github.com/dotnet/corefx/pull/28906
cc @weshaggard, @nguerrera, @joshfree

Update the ref assembly generation rules and logic for structs.

---

src/packages.builds

Move prerelease label to rc1

---

src/packages.builds

Move master to 2.2 preview1

---

src/Microsoft.DotNet.Build.Tasks.Feed/BlobFeedAction.cs
src/Microsoft.DotNet.Build.Tasks.Feed/PushToBlobFeed.cs

[release/2.1] Add ability to make feed container private even if no token is specified

---

.toolversions

Upgrading version to the one containing the correct default target

Upgrade Feed version

---

src/Microsoft.DotNet.Build.Tasks/FindBestConfigurations.cs

Related to: https://github.com/dotnet/corefx/pull/28866
cc: @weshaggard @ericstj

Change placeholder configurations filtering to just skip that config instead of exiting

---

dependencies.props
src/GenFacades/GenFacades.Core/GenFacades.cs
src/GenFacades/GenFacades.Core/project.json
src/Microsoft.DotNet.Build.Tasks.net45/project.json
src/Microsoft.DotNet.Build.Tasks/ConvertPortablePdbsToWindowsPdbs.cs
src/Microsoft.DotNet.Build.Tasks/PackageFiles/Symbols.targets
src/Microsoft.DotNet.Build.Tasks/project.json

Fixes https://github.com/dotnet/corefx/issues/29861
cc @danmosemsft, @tmat, @stephentoub

Update MicrosoftDiaSymReaderConverterPackageVersion to latest 1.1.0-beta version

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/Roslyn.Common.props
src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd
src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh
src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.csproj

Part of https://github.com/dotnet/corefx/projects/3
CC @weshaggard @joperezr @eerhardt @safern

Remove msbuild dependency from buildtools

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/crossgen.sh

Based on https://github.com/dotnet/buildtools/pull/2051#discussion_r194077549
@dagood, TIL, http://redsymbol.net/articles/unofficial-bash-strict-mode/. Thanks for your pointers too! :)

Set default value of RID to empty string

---

src/Microsoft.DotNet.Build.CloudTestTasks/DownloadFromAzure.cs
src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/PublishContent.targets
src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/SyncCloudContent.targets

Port of https://github.com/dotnet/buildtools/pull/1494 for the sake of https://github.com/dotnet/core-setup/pull/4241
@weshaggard PTAL

Port 'Add blob prefix support' to 1.1.0 buildtools

---

src/xunit.netcore.extensions/Discoverers/ConditionalClassDiscoverer.cs

Follow up PR for: https://github.com/dotnet/buildtools/pull/2040#discussion_r190044557

Add error message for invalid input in ConditionalClass

---

src/Microsoft.DotNet.Build.Tasks.Packaging/src/GenerateRuntimeGraph.cs

/cc @morganbr 
This allows us to generate a separate package that refers to external RIDs

Allow for externally defined RID graph when validating generated RID graph

---

src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj
src/Microsoft.DotNet.Build.Tasks/PackageFiles/VersionTools.targets
src/Microsoft.DotNet.Build.Tasks/VersionTools/PullRequestServiceType.cs
src/Microsoft.DotNet.Build.Tasks/VersionTools/SubmitPullRequest.cs
src/Microsoft.DotNet.VersionTools/Automation/ClientHelpers.cs
src/Microsoft.DotNet.VersionTools/Automation/GitHubApi/GitHubClient.cs
src/Microsoft.DotNet.VersionTools/Automation/GitHubApi/IGitHubClient.cs
src/Microsoft.DotNet.VersionTools/Automation/PullRequestCreator.cs
src/Microsoft.DotNet.VersionTools/Automation/PullRequestOptions.cs
src/Microsoft.DotNet.VersionTools/Automation/VstsApi/VstsAdapterClient.cs
src/Microsoft.DotNet.VersionTools/Automation/VstsApi/VstsApiModel.cs
src/Microsoft.DotNet.VersionTools/Microsoft.DotNet.VersionTools.csproj

Port https://github.com/dotnet/buildtools/pull/2135 to `release/2.1`. Cherry picked from commit 91726ae38c66579e77cbd4437eb602217701f41e, no conflicts.

Add minimal VSTS VersionTools auto-PR client

---

src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets

Fixes an error introduced in https://github.com/dotnet/buildtools/pull/2151

Fixing an illegal nested item-group

---

src/Microsoft.DotNet.Build.Tasks.Feed/BlobFeed.cs

Add retries to CheckIfBlobExistsAsync in case of HttpClient timeouts.
(cherry picked from commit 5d4d0646ce36b8bb3b9e835dacd84834240aa7ae)

Add retries to CheckIfBlobExistsAsync (rel/2.1 Port of #2093)

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets

Relates to https://github.com/dotnet/corefx/issues/32452

Set test errorlevel for uap correctly

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/CodeCoverage.targets

Related to https://github.com/dotnet/corefx/pull/32537#issuecomment-425685002
For now as WIP just to track needed changes.

Add property to disable code coverage for project

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets

For helix submissions and coreclr tests of corefx. Offline discussion.

Add xunit dependencies to test path

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets
src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets

Relates to https://github.com/dotnet/corefx/issues/20109

Automatically copy runtime config files if executable

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.targets

Add option to opt out from code analysis import

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/FrameworkTargeting.targets

cc @weshaggard @stephentoub 
This is the final commit. The previous ones didn't quite work but this one now builds fine in corefx. I probably discovered at least one msbuild issue which I'll log.
Again merging this one now to unblock the maestro PRs in all repos and gonna apply feedback later.

Fix wrong condition in BinPlace

---

src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.props
src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.targets

PTAL @ericstj @wtgodbe @safern

Condition MicroBuild imports based on ExcludeSigningImport

---

src/Microsoft.DotNet.Build.Tasks.Packaging/src/GenerateNuSpec.cs

Porting over https://github.com/dotnet/arcade/pull/2165

Port way to workaround NuGet breaking change

---

src/versions-fix/versions-fix.proj
tools-local/versions-fix/versions-fix.proj

This provides a path to use a later, published UpdatePublishedVersions task to resolve dotnet/core-eng#5054.

Provide alternate UpdatePublishedVersions task

---

src/Microsoft.DotNet.Build.CloudTestTasks/SendJobsToHelix.cs
src/Microsoft.DotNet.Build.CloudTestTasks/SendToHelix.cs

Tested sending 5 jobs to assorted Helix queues:
```
SendCompletionEvent:
Posting job to https://helix.dot.net/api/2016-06-28/jobs
Started Helix job: CorrelationId = 106a1d39-1170-4673-b225-eb4cd7cf6a7b
Started Helix job: CorrelationId = 665776db-d33a-4440-b35b-ec678884b0ac
Started Helix job: CorrelationId = a5624c9d-2f06-4840-b269-19bab9159c16
Started Helix job: CorrelationId = 99bead85-e026-4226-a0b0-07d04d2ada9c
Started Helix job: CorrelationId = ff62786e-3ce4-44f3-9a86-471915a79e05
Writing correlation info to: Helix-correlation-infos.json
Writing Helix-correlation-infos.json.
Begin uploading blobs to Azure account **********in container build-27ea50557e824d41895bbf1ad5907892.
Uploading Helix-correlation-infos.json to build-27ea50557e824d41895bbf1ad5907892.
Upload to Azure is complete, …
```

Harden send to helix tasks

---

README.md

Point out that this repo shouldn't be used anymore

---

src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/scriptrunner/continuationrunner.py
src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/scriptrunner/scriptrunner.py

See https://github.com/dotnet/core-eng/issues/11628 for details

Change helix.io -> helixio (breaking change introduced in scripts)
