dotnet/buildtools

- src/xunit.console.netcore/packages.config
xunit.console.netcore project had an incorrect package dependency
version on xunit.runner.dependencies.netcore, which failed appvoyer.
Correct the version to 1.0.0-prerelease
> Correct package dependency version to xunit.run..dep..netcore

- src/Microsoft.DotNet.Build.Tasks/Targets/depending.targets
- src/Microsoft.DotNet.Build.Tasks/Targets/packages.targets
This solves a problem on Mono where the path would be created as
specified (i.e. including the spaces).
The spaces are only necessary to avoid an ending backslash escaping
the quote char on Windows. Trimming the backslash has the same effect.
> Trim backslash from commands instead of adding space

- src/xunit.console.netcore/xunit.console.netcore.csproj
xunit.console.netcore.csproj to reference its dependencies from the
new package version set in commit
79df2888b464f96b840c7f7f17136d1058873887
> Correct package dependency version to xunit.run..dep..netcore - part 2

- src/Microsoft.DotNet.Build.Tasks/Targets/tests.targets
- src/nuget/Microsoft.DotNet.BuildTools.nuspec
The way we were attempting to expand the properties for the exclude traits was only including the last trait.  Hence we were running outerloop tests when we shouldn't have been.
> Fix issues with the include and exclude traits.

- src/Microsoft.DotNet.Build.Tasks/Targets/sign.targets
It used to run before 'CopyFilesToOutputDirectory', but that target has a different name on Mono's xbuild (namely 'DeployOutputFiles'), so it doesn't run there.
Using AfterTargets="Compile" shouldn't make a difference and works on Mono as well.
Note: I'm not that well versed in the intricacies of MSBuild targets, so if this causes problems on Windows please let me know.
> Run OpenSourceSign target after Compile target

- src/Microsoft.DotNet.Build.Tasks/Targets/depending.targets
Renamed the target to make it more descriptive to RestoreAllPackageDependencies
while keeping the old EnsureDependencies target as a wrapper for now.
Added inputs/outputs to make incremental build work without requiring the
restore of all the packages on every build.
Added an empty PackageConfigsToExclude so people can override the wildcard Include
if needed.
Started outputing a message whenever the target starts as it tends to take a little
while and it is useful for people to know that restore is happening.
> Clean up depending.targets file to make it more general purpose

- src/Microsoft.DotNet.Build.Tasks/ResolveNuGetPackages.cs
As described [here](https://github.com/dotnet/corefx/issues/449), builds of the corefx repo will fail if Xamarin has installed its frameworks into the PCL profiles.  A workaround that has worked in the past for these type of issues has been to rename the XML files that Xamarin adds to something else to disable them.  This doesn't currently work for corefx builds, because Microsoft.DotNet.Build.Tasks looks at all the files in the SupportedFrameworks folder, not just XML files.
This PR changes it to only look at XML files, bringing it in line with Visual Studio and NuGet.
> When loading supported frameworks for a PCL profile, only look at files with .xml extension

- src/BuildTools.sln
- src/xunit.console.netcore/Program.cs
This adds support for the -wait option to our xunit.console.netcore runner so that we can use that option while using CTRL+F5 in VS and see the results.
> Add wait option to xunit.console.netcore

- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime-packages.config
- src/Scripts/set-package-build.cmd
- src/nuget/xunit.console.netcore.nuspec
- src/xunit.console.netcore/packages.config
- src/xunit.console.netcore/xunit.console.netcore.csproj
We're getting in to a state where building is restoring 3 copies of every package. We should keep the build numbers bumped until we have either a wildcard (latest build) mechanism or we have RTM'ed most packages and most dependencies are stable.
This bumps *.config, *.nuspec, and *.csproj to 22512 in the buildtools repo.
A script is included to do this again next time and I will do the same in the corefx repo.
> Add script to bump package build numbers and use it

- src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj
Fixes building in VS 2015 without the 2013 build tools installed.
> Reference in-box v4 assemblies for msbuild v12 and v14 compat

- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime-packages.config
- src/nuget/Microsoft.DotNet.BuildTools.nuspec
- src/nuget/xunit.console.netcore.nuspec
This is needed so that I can upload a new package to myget to get -wait support, 
which in turn will allow me to wire things up so that Ctrl+F5 in VS actually pauses
after a test run.
> Bump xunit.console.netcore version (for Ctrl+F5 pause)

- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime-packages.config
- src/xunit.console.netcore/Utility/TransformFactory.cs
- src/xunit.console.netcore/packages.config
This change adds the ability to create an xml report when running xunit.
The package changes are required because System.IO.FileStream has a dependency on System.Threading.ThreadPool
> Add xml report generation support to xunit runner.

- src/xunit.console.netcore/Utility/TransformFactory.cs
When I cleaned up my previous PR I removed the explicit setting async to false.
This results in a runtime dependency on System.Threading.Overlapped.
Setting async to false removes this dependency.
> Remove dependency on System.Threading.Overlapped.

- build.proj
- dir.props
- src/.nuget/packages.config
- src/BuildNumber.props
- src/BuildTools.sln
- src/JSon2Txt/JSon2Txt.csproj
- src/Microsoft.DotNet.Build.Tasks/GetNextDailyBuildNumber.cs
- src/Microsoft.DotNet.Build.Tasks/GetPackageVersion.cs
- src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj
- src/Microsoft.DotNet.Build.Tasks/Targets/UpdateBuildNumber.targets
- src/Microsoft.DotNet.Build.Tasks/Targets/packages.targets
- src/dir.targets
- src/dirs.proj
- src/nuget/Microsoft.DotNet.BuildTools.nuspec
- src/nuget/xunit.console.netcore.nuspec
Add necessary metadata to enable Authenticode signing in VSO builds.
Nuget packages can now automatically be pushed to a nuget server
specified via MSBuild var PublishPackageSource.
Added a daily build number in version.prop to be used in file and
nuget packages.  By setting MSBuild var DailyBuildNumGenEnabled to
true when building the build will increment the value before building
and commit and push to origin after package publishing.
Updated MSBuild task GetPackageVersion to generate a nuget package
verison by combining the embedded package version in the nuspec file
with the daily build number.
Added a dependency on the build tools nuget package so this repo can
take advantage of this new functionality.
> Feature work to support official daily builds from VSO.

- src/Microsoft.DotNet.Build.Tasks/Targets/packages.targets
The original testing performed was against a private feed which didn't
require an API key.  For public feeds we need to provide an API key.
I've added a new property SourceAPIKey where this is specified.
> Fix publishing of NuGet packages.

- src/Microsoft.DotNet.Build.Tasks/Targets/NativeVersion.rc
- src/Microsoft.DotNet.Build.Tasks/Targets/versioning.targets
- src/nuget/Microsoft.DotNet.BuildTools.nuspec
These target files will generate the necessary _AssemblyInfo file
with the various assembly level attributes, like assembly and file
version, as well as name and copyright, etc.
> Add assembly versioning targets to the build tools package.

- src/Microsoft.DotNet.Build.Tasks/Targets/sign.targets
The OpenSourceSign target does not obey the SkipSigning property.  It's possible that I don't understand the intent of this property, but in my mind it is used to opt out of the open source signing system entirely.
If the property is not true, then a few properties are not set, but there is still an attempt to run the OpenSourceSign target.  This can cause an issue if you're expecting to use the property to opt out of open source signing and use your own custom signing because the file will try to be signed twice.  Whichever signing task happened to run first, will sign the assembly, and the second will throw an error trying to sign an already signed assembly.
> Obey SkipSigning Property in OpenSourceSign target

- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime-packages.config
- src/nuget/Microsoft.DotNet.BuildTools.nuspec
One that will match the package produced from CoreCLR and one that will contain the additional assemblies required but not produced from the CoreCLR repo
> Split the Microsoft.DotNet.TestHost into 2 packages.

- dir.props
- src/.nuget/packages.config
- src/Microsoft.DotNet.Build.Tasks/Targets/packages.targets
Providing the API key as a property exposes the key via the build
definition and build logs which is a security risk.  We will configure
the build machine with the appropriate API key instead.
> Remove the SourceAPIKey property.

- build.cmd
- Set name of build log file and build project file into env variable so
they are more easily discoverable in the log file, and only defined
once.
- Fix URL for .NET Developer Guide and minor typo in comments.
> Build log filename variable

- src/common/XmlTestExecutionVisitor.cs
- src/xunit.console.netcore/packages.config
- src/xunit.console.netcore/xunit.console.netcore.csproj
This change sets the IFormatProvider for number formatting in the xml output to CultureInfo.InvariantCulture
The test results were output with mixed british and regular decimal places. This resulted in multiplying durations by 1000 when the results were processed.
> Add InvariantCulture to xml output.

- dir.props
- src/.nuget/packages.config
- src/JSon2Txt/JSon2Txt.csproj
- src/Microsoft.DotNet.Build.Tasks/Targets/sign.targets
- src/ResourceGenerator/ResourceGenerator.csproj
- src/dir.targets
Moved metadata for real signing in VSO builds to sign.targets file;
this way all projects that reference build tools will automatically
have real signing enabled.
Added metadata to enable strong name signing with a new MSBuild
property UseOpenSourceSign to toggle between OSS and real signing.
Updated build tools dependency to latest version.
> Centralize authoring for real signing.

- src/Microsoft.DotNet.Build.Tasks/GetPackageVersion.cs
- src/Microsoft.DotNet.Build.Tasks/Targets/packages.targets
If BuildNumber is not defined then skip target GetNuGetPackageVersions
and use the package version embedded in the NuSpec file.
For task GetPackageVersion only append the build number to prerelease
packages to comply with the SemVer v1.0 spec.
> A few fixes for handling of BuildNumber.

- src/Microsoft.DotNet.Build.Tasks/Targets/packages.targets
This is going to be driven by the localpublish.props file at the source root
of the repo. By default this file does not exist and it is not tracked by git.
You can create the file with contents similar to this to enable the repo that
is currently built from publishing to a local path. This enables the scenario
when one package has a dependency to the other and you want to test your
changes locally.
If the file is present the following are going to happen:
- The package folder in the target repo is going to be removed
- A packages.config file is going to be created for the package that we are
installing. This is required to bypass the resolving of dependencies that is
triggered by installing a packaged referenced by name.
- A nuget install command is issued to install the package in the …
> Create the infrastructure to allow testing changes across repos.

- src/Microsoft.DotNet.Build.Tasks/Targets/versioning.targets
By default this will not be included but a project or custom target
can set AssemblyComVisible to true or false to get this included in
the _AssemblyInfo.cs file.
This enables issue #77
> Add support for adding ComVisible to the generated _AssemblyInfo.cs file

- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime-packages.config
There is a new package for the CoreCLR package on the myget feed that matches the version that we produce from the CoreCLR repo.
This change updates the version of the CoreCLR package used by tests to the latest one available.
> Bump the version number for the CoreCLR package used

- src/Microsoft.DotNet.Build.Tasks/Targets/sign.targets
Real signing is time consuming so disable it for test projects.
> Disable official signing for test projects.

- src/Microsoft.DotNet.Build.Tasks/Targets/packageresolve.targets
While doing other work I noticed we use PackagesConfigFile and
PackagesConfig in various places. The most common is PackagesConfig
so switch the targets to use that consistently.
> Use PackagesConfig in the packageresolve targets.

- src/Microsoft.DotNet.Build.Tasks/Targets/publishtest.targets
This fixes one more issue where we reference PackagesConfigFile and instead reference PackagesConfig.
> Remove another reference to PackagesConfigFile.

- src/BuildValues.props
- src/Microsoft.DotNet.Build.Tasks/GetNextRevisionNumber.cs
- src/Microsoft.DotNet.Build.Tasks/GetPackageVersion.cs
- src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj
- src/Microsoft.DotNet.Build.Tasks/Targets/UpdateBuildValues.targets
- src/Microsoft.DotNet.Build.Tasks/Targets/packages.targets
- src/dirs.proj
- src/nuget/Microsoft.DotNet.BuildTools.nuspec
The VSO official build defines global property BuildNumber which is
colliding with our property with the same name.  I have renamed the
property to RevisionNumber to avoid the collision.
Rename BuildNumber.props to the more generic BuildValues.props as it's
likely we'll have other build values in the in the future.
> Fix issues with BuildNumber property.

- dir.props
- src/.nuget/packages.config
- src/Microsoft.DotNet.Build.Tasks/Targets/packages.targets
- src/dir.props
The corefx repro ends PackagesOutDir with a trailing '\' character while
build tools does not.  In packages.targets property PackagesForPublishing
adds a backslash to PackagesOutDir which works for build tools but fails
for corefx.  This change removes the inconsistency.
Updated build tools package dependency to latest build with this fix.
> Make value of PackagesOutDir consistent with corefx repo.

- src/xunit.console.netcore/Program.cs
Reading current foreground color is not supported on Unix
> Use Console.ResetColor() to restore color settings

- src/Microsoft.DotNet.Build.Tasks/GenerateResourcesCode.cs
- src/Microsoft.DotNet.Build.Tasks/Targets/resources.targets
This fix is fixing the issue of generating resource code lines
ended with consistent marks (CRLF on Windows and LF on Linux)
Also fixed the task to fail the build when there is any code
generation failure
> Fix the end of line mark in generated code

- src/Microsoft.DotNet.Build.Tasks/Targets/CodeCoverage.targets
- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime-packages.config
- src/Microsoft.DotNet.Build.Tasks/Targets/tests.targets
Pull in https://github.com/dotnet/corefx/pull/1116 into the build tools repo and fix command line options to correctly handle the xunit traits that are computed in the target.
> Fix code coverage in common targets

- src/Microsoft.DotNet.Build.Tasks/Targets/tests.targets
We don't have a way to set the xunit traits for debugging in VS as they have to be computed via a target. We are just going to exclude the trait options while launching in VS by default.
This should fix https://github.com/dotnet/buildtools/issues/112, although I don't have a way to test right now so if anyone would like to test this that would be helpful.
cc @ellismg @nguerrera
> Fix VS command line arguments used for debugging

- src/EventTracer/CollectTraceEventsHelper.cs
- src/EventTracer/TraceEventsReportGenerator.cs
- src/GenPerfBaseline/Program.cs
The TraceEventsReportGenerator was incorrectly reporting the bitness of
itself rather than the test run.
Added messages to various exceptions thrown in GenPerfBaseline.
> Perf tools bug fixes.

- src/Microsoft.DotNet.Build.Tasks/Targets/versioning.targets
This is needed by the store toolchain when generating PRI files from the embedded resources.
> Add NeutralResourcesLanguageAttribute to assemblies which contain resources

- src/Microsoft.DotNet.Build.Tasks/Targets/CodeCoverage.targets
This ensures that when gathering relative paths to the source files in the reports, we are relative to the root of the repository.  Report generator doesn't have an issue with this per-se, but coveralls.io looks up the github sources based on the root of the repo.
> Modify report generator and coveralls working dirs

- src/Microsoft.DotNet.Build.Tasks/Targets/PerfTesting.targets
- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime-packages.config
- src/Microsoft.DotNet.Build.Tasks/Targets/tests.targets
Add PerfTesting.targets file defining properties and targets used to
enable perf testing during the build. Testing is enabled via msbuild
properties. At present there is one properties, TestConsumptiveMetrics
used to enable collection of perf data.
Added a reference to the perf tools nuget package.
Updated tests.targets to start/stop collection of perf data.
> Initial integration of perf testing tools into the build system.

- src/Microsoft.DotNet.Build.Tasks/Targets/publishtest.targets
- src/Microsoft.DotNet.Build.Tasks/Targets/tests.targets
Fixes #60 
Uses a marker file and Inputs/Outputs on the RunTestsForProject target to skip running tests when nothing has changed since the last successful test run. Also moves copying of the test files into the RunTestsForProject target so that they are only copied if the tests are going to run.
On my machine, this change cuts the build time for CoreFX for an incremental build with no changes from 45-55 seconds to 5 seconds*.
> Only run tests (and copy test files) if test results are out of date

- src/Microsoft.DotNet.Build.Tasks/Targets/PerfTesting.targets
The nuget package dependency was updated in change 33cb4e but the msbuild
property wasn't updated to match; this brings them both in sync.
> Update perf tools version property.

- src/Microsoft.DotNet.Build.Tasks/Targets/tests.targets
corresponds to https://github.com/dotnet/corefx/pull/1276.
cc @stephentoub @krwq
> Add nonwindowstests category to skip running linux and mac specific tests on windows

- src/Microsoft.DotNet.Build.Tasks/Targets/tests.targets
Fixes dotnet/corefx#1286
ReferenceCopyLocalPaths is populated by ResolveAssemblyReferences, which requires (but does not depend on) ResolveProjectReferences. AllItemsFullPathWithTargetPath is populated by GetCopyToOutputDirectoryItems. These targets are executed during Build; executing Test without Build was leaving these items unpopulated, causing them to not be copied to the test directory.
> Ensure required properties are set prior to copying files for testing

- src/Microsoft.DotNet.Build.Tasks/Targets/tests.targets
This fixes dotnet/corefx#1275.
The semaphore file now includes the test categories that were selected to run or not run; selecting new categories will re-run the test if that set of category inclusions/exclusions is out of date.
> Make incremental build conditional on selected test categories

- src/Microsoft.DotNet.Build.Tasks/Targets/tests.targets
If the coverage.xml got deleted after running coverage once, and then the build was run with coverage again, it would not rerun the actual coverage step.  It still would attempt to recreate then coverage report, which would fail because of a missing coverage file.  Fix this by adding the coverage output to the outputs of the test target (only set when coverage is set to true).
Fixes dotnet/corefx#1308
> Fix missing coverage dependency

- src/Microsoft.DotNet.Build.Tasks/GenerateResourcesCode.cs
- src/Microsoft.DotNet.Build.Tasks/Targets/resources.targets
This change is to embed the resources with different name for each assembly
to avoid the resource merge conflict in the store app scenario as
the resources get merged into the app PRI file.
> Embed the resources with different names

- src/Microsoft.DotNet.Build.Tasks/MSBuildDependencyResolver.cs
- src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj
- src/Microsoft.DotNet.Build.Tasks/PatternDefinitions.cs
- src/Microsoft.DotNet.Build.Tasks/PropertyDefinitions.cs
- src/Microsoft.DotNet.Build.Tasks/ResolveNuGetPackageAssets.cs
- src/Microsoft.DotNet.Build.Tasks/ResolveNuGetPackages.cs
- src/Microsoft.DotNet.Build.Tasks/Targets/Build.Common.targets
- src/Microsoft.DotNet.Build.Tasks/Targets/FrameworkTargeting.targets
- src/Microsoft.DotNet.Build.Tasks/Targets/packageresolve.targets
- src/Microsoft.DotNet.Build.Tasks/Targets/publishtest.targets
- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime-packages.config
- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime-project.json
- src/Microsoft.DotNet.Build.Tasks/Targets/tests.targets
- src/Microsoft.DotNet.Build.Tasks/packages.config
- src/NuGet.Config
- src/nuget/Microsoft.DotNet.BuildTools.nuspec
This change enables buildtools to restore packages referenced by project.json.  New "nuget v3" style packages must be referenced via project.json. /cc @mellinoe @weshaggard @jasonmalinowski @JeremyKuhne
> Add project.json support to build tools

- src/Microsoft.DotNet.Build.Tasks/Targets/tests.targets
Adding <UnsupportedPlatforms>OSX;Windows_NT;Linux</UnsupportedPlatforms> in csproj will exclude tests from the specified OS'es. Corresponding change to run-test.sh to rename UnsupportedOperatingSystems to UnsupportedPlatforms for linux will follow in corefx.
cc @stephentoub @mmitche
> Add support to skip whole test projects based on platform.

- src/Microsoft.DotNet.Build.Tasks/Targets/publishtest.targets
Copy-paste error when replicating the logic from packageresolve.targets.
> Fix typo in publishtest.targets

- src/Microsoft.DotNet.Build.Tasks/Targets/packageresolve.targets
This is necessary to support some internal build scenarios where we import a CSProj in order to override some build settings.  We still need to use the other CSProj when resolving packages.
> Override project file to resolve during ResolveNuGetPackages

- src/Microsoft.DotNet.Build.Tasks/Targets/publishtest.targets
This test mode will overwrite when possible, libraries downloaded as nugget references from the ones built locally.
> Add test mode that uses built libraries

- src/Microsoft.DotNet.Build.Tasks/Targets/tests.targets
- src/xunit.console.netcore/Program.cs
With this change, the csproj need not specify the available categories in the project with TestCategories property. RunTestsWithCategories has been renamed to WithCategories, RunTestsWithoutCategories to WithoutCategories.
By default outerloop and failing tests are excluded. They will only be run if specified in WithCategories.
xunit.console.netcore is modified to return warning if it does not find any tests in the project.
cc @krwq @weshaggard @joshfree
> Support WithCategories and WithoutCategories msbuild properties.

- src/Microsoft.DotNet.Build.Tasks/MSBuildDependencyResolver.cs
- src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj
- src/Microsoft.DotNet.Build.Tasks/PatternDefinitions.cs
- src/Microsoft.DotNet.Build.Tasks/PropertyDefinitions.cs
- src/Microsoft.DotNet.Build.Tasks/ReadNuGetPackageReferences.cs
- src/Microsoft.DotNet.Build.Tasks/ResolveNuGetPackageAssets.cs
- src/Microsoft.DotNet.Build.Tasks/Targets/packageresolve.targets
- src/Microsoft.DotNet.Build.Tasks/Targets/partialfacades.targets
- src/Microsoft.DotNet.Build.Tasks/Targets/publishtest.targets
- src/Microsoft.DotNet.Build.Tasks/Targets/tests.targets
This version handles transitive dependencies via the .lock.json.  We aren't yet using the .lock.json for asset selection. /cc @weshaggard @jasonmalinowski
> Update to latest copy of ResolveNuGetPackageAssets.

- src/Microsoft.DotNet.Build.Tasks/Targets/tests.targets
This feature will enable extensibility as more categories are added, and need to be excluded from a dev test run (plain build.cmd). So if there are more categories in future, like perf, stress, etc, these can be excluded by specifying <DefaultNoCategories>Perf;Stress</DefaultNoCategories> or /p:DefaultNoCategories=Perf;Stress
CC @krwq
> Expose DefaultNoCategories property to enable specifying the categories(like perf) that are not in innerloop.

- src/Microsoft.DotNet.Build.Tasks/ExecWithMutex.cs
- src/Microsoft.DotNet.Build.Tasks/MSBuildDependencyResolver.cs
- src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj
- src/Microsoft.DotNet.Build.Tasks/Targets/publishtest.targets
- src/Microsoft.DotNet.Build.Tasks/packages.config
- src/NuGet.Config
DNX has an issue with concurrent restore: https://github.com/aspnet/dnx/issues/1682
Previously I would workaround by copying to intermediate, but this breaks in official build where intermediate is not under the scope of our nuget.config, so custom package sources are ignored.
Fix this instead by wrapping the call to dnu restore with a mutex unique to the project.json name.  We only need to do this for the test project.json because that is the only one we'll restore concurrently.
> Prevent concurrent restore of same project.json

- src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj
- src/Microsoft.DotNet.Build.Tasks/ParseTestCoverageInfo.cs
- src/Microsoft.DotNet.Build.Tasks/Targets/CodeCoverage.targets
This commit adds a new coverage report that can be selected. Basically it parses all of the opencover output xml and generates a new file, VisitedMethodsReport.xml. This will be used to match changes in code to tests.
> Add coverage report that shows test and the methods it visits

- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime-packages.config
TestHost package has been updated to include a new APISet. This change updates the BuildTools to reference the new package.
> Update Microsoft.DotNet.TestHost package version.

- src/Microsoft.DotNet.Build.Tasks/Targets/CodeCoverage.targets
/cc @stephentoub @AlfredoMS 
@ericstj I think this is related to your build tools updates.  Can you take a look?
> Fix paths coverage and report tools

- src/Microsoft.DotNet.Build.Tasks/Targets/versioning.targets
Tagging the framework assemblies with the metadata attribute to identify
the framework assemblies .
This attribute will be used during the app compilation to special handle
any framework assembly as needed.
> Add the AssemblyMetadataAttribute to the framework assemblies

- src/Microsoft.DotNet.Build.Tasks/Targets/partialfacades.targets
If there are spaces in the path to the repository that we are building
in, the partialfacade targets fail, because the exec command and
argument parsing logic gets confused.
Wrap invocations with quotes, so this doesn't happen.
> Fix build break when spaces in path

- src/Microsoft.DotNet.Build.Tasks/Targets/tests.targets
Shorten the test succeeded semaphore file to avoid cases where we might create a path that is too long for some tools on Windows.
dotnet/corefx#1701
> Shorten semaphore path

- src/Microsoft.DotNet.Build.Tasks/Targets/UpdateBuildValues.targets
When Team Build enlists in tracking branches it puts them into a
detached head state (see https://github.com/dotnet/corefx/issues/1791).
Check out the working branch before committing and pushing changes.
> Pushing automated build changes doesn't work for tracking branches.

- src/Microsoft.DotNet.Build.Tasks/ResolveNuGetPackageAssets.cs
If a path starts with '\' on Unix it isn't considered rooted. This causes Path.Combine to not take just the second argument because we've converted it from rooted to unrooted.
@ericstj; @weshaggard
> Fix path combine on Unix.

- src/nuget/Microsoft.DotNet.PerfTools.nuspec
These dependencies prevent it from being installed outside VS (e.g. in a CI system).
> Remove dependencies from PerfTools Nuget package

- src/Microsoft.DotNet.Build.Tasks/Targets/tests.targets
This was useful in detecting issues in test concurrency.  A high number of threads appears to expose problems
> Add option to change number of threads that xunit uses

- src/Microsoft.DotNet.Build.Tasks/Targets/packageresolve.targets
This is specifically targeted toward the new json package format.  The issue we have is that the coreclr tests have project names that sometimes non-unique in the tests (there are template projects).  This causes locking issues when restoring packages, or occasionally packages do not get restored at all.  This is because the semaphore file is based off of the project name.  This implicitly adds a restriction that project file names must be unique within an msbuild invocation.  The semaphore file was an attempt to have incremental package restore.  Under  dnx, the lock files dramatically speed up restore and so always restoring is okay.
This changes removes the incremental restore and unblocks coreclr's move to dnx.
/cc @ericstj
> Always run the package restore step

- src/Microsoft.DotNet.Build.Tasks/Targets/publishtest.targets
Missed a spot where the lock semaphore files were being referenced, causing corefx not to copy all dependencies to test directories
> Fix issue introduced by removal of lock semaphore files

- src/Microsoft.DotNet.Build.Tasks/Targets/IL.targets
This change introduces a targets file to support projects that are
written in MSIL. Like Microsoft.{CSharp,VisualBasic}.targets, the
targets file builds on the infrastructure provided by
Microsoft.Common.targets, which provides the usual Build, Clean,
etc. targets. Currently the only tool that this file understands
is ILAsm, so compilation will fail on platforms where this tool is
not available.
> Add support for compiling CIL files.

- src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj
- src/Microsoft.DotNet.Build.Tasks/Targets/publishtest.targets
- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime/project.json
- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime/project.lock.json
- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime/readme.txt
- src/nuget/Microsoft.DotNet.BuildTools.nuspec
I previously moved test-runtime project.json to using * dependencies.  Doing so without checking in a locked lock file causes the dependencies to float to the highest version.  This change adds a lock file with the same versions as are currently used by corefx.  I also added conditions on TestRuntimeProjectJson and TestRuntimeProjectLockJson to permit overriding them.
> Use locked dependencies for test-runtime.

- src/Microsoft.DotNet.Build.Tasks/Targets/CodeCoverage.targets
- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime/project.json
Fixes a bug in the report generation that's causing some of our Interop types to be left out of the reports.
> Update to ReportGenerator v2.1.6

- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime/project.lock.json
The lock file format changed and we need to update our file in order for it to work with the DNX update we are doing in corefx branch.
> Update to latest project.lock.json generated by DNX 1.0.0-beta5-12077

- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime/project.lock.json
Previous lock file was out of date with what was in buildtools due to merge issue.
> Update version of ReportGenerator in lock file.

- dir.props
- src/EventTracer/EventTracer.csproj
- src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj
- src/PerfEventsData/Platform.cs
- src/xunit.netcore.extensions/Discoverers/ActiveIssueDiscoverer.cs
- src/xunit.netcore.extensions/Discoverers/PlatformSpecificDiscoverer.cs
- src/xunit.netcore.extensions/Interop.PlatformDetection.cs
- src/xunit.netcore.extensions/PlatformID.cs
- src/xunit.netcore.extensions/XunitConstants.cs
Refs: https://github.com/dotnet/corefx/pull/2068
R=@stephentoub,@mmitche,@josteink,@janhenke,@ghuntley
> xplat: Adds FreeBSD support

- src/Microsoft.DotNet.Build.Tasks/Targets/CodeCoverage.targets
This avoids any additional custom attributes in corefx and avoids churning the SR.cs/vb files.  We'll just need to remember to update build tools if we ever move those files to a different location or otherwise rename them, or if we put additional code into those files that for some reason shouldn't be excluded.
> Exclude injected SR.cs/vb file from code coverage

- src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj
- src/Microsoft.DotNet.Build.Tasks/RemoveDuplicatesWithLastOneWinsPolicy.cs
- src/Microsoft.DotNet.Build.Tasks/Targets/publishtest.targets
- src/Microsoft.DotNet.Build.Tasks/Targets/tests.targets
Move test deployment to build phase and speed it up
The experience around building and running tests in VS got broken by a
change to only copy tests when they're run from msbuild. Move them back
to PrepareForRun to bring back the VS workflow.
In doing so, it became apparent that the test deployment step was
copying files on every invocation regardless of whether there were any
changes. That turned out to be because there are different versions of
files with the same simple name destind for the same output folder. As
such, every iteration would swap them back and forth. The fix here is
too trim out the duplicates before invoking the Copy task. Some of the
duplication is by design (e.g. to override nuget assets with local
assets), but we are also getting multiple nuget package versions out …
> Fix VS debugging iteration experience

- src/Microsoft.DotNet.Build.Tasks/Targets/publishtest.targets
- src/Microsoft.DotNet.Build.Tasks/Targets/tests.targets
Fixes #132
Allows the test host and the test executable to be overridden. Also paves the way for #125.
> Allow override of test host and executable

- src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj
- src/Microsoft.DotNet.Build.Tasks/PrereleaseResolveNuGetPackageAssets.cs
- src/Microsoft.DotNet.Build.Tasks/Targets/packageresolve.targets
- src/Microsoft.DotNet.Build.Tasks/Targets/partialfacades.targets
- src/Microsoft.DotNet.Build.Tasks/Targets/publishtest.targets
This is a quick change to avoid naming collision and always disable
the built-in nuget resolution targets in favor of what we've used
in buildtools to bootstrap building against the .NET Core packages.
#192 tracks getting things fixed so that we actually consume the
built-in targets when they're available.
cc @ericstj @ljw1004
> Avoid conflict with built-in nuget targets

- src/Microsoft.DotNet.Build.Tasks/Targets/Build.Common.targets
- src/Microsoft.DotNet.Build.Tasks/Targets/packageresolve.targets
This avoids a deadlock with VS endlessly resolving references. Fixes #191. @weshaggard, @nguerrera
> Skip restoring packages in VS2015 background build

- src/Microsoft.DotNet.Build.Tasks/Targets/publishtest.targets
Allow overriding where the local libraries come from and search in .CoreCLR directories as well.
@weshaggard
> Fix and extend TestCopyLocal

- src/Microsoft.DotNet.Build.Tasks/Targets/CodeCoverage.targets
- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime/project.json
- src/Microsoft.DotNet.Build.Tasks/Targets/tests.targets
Recent changes to enable overriding of test run properties broke the code coverage build.  There were two issues.  CodeCoverage needed to be updated to use the new property names, and we need to revert to the way we were passing in the Xunit trait options before.  The complication around code coverage is that the coverage line isn't just a simple wrapper around the original command line.  It needs to know the host as well as the full set of arguments passed to that host.
In addition, this change updates the code coverage version
> Fix code coverage build

- src/Microsoft.DotNet.Build.Tasks/Targets/CodeCoverage.targets
The last change to avoid setting {XunitTraitOptions} on TestArguments broke setting of xunit traits on code coverage.
> Fix code coverage traits

- src/Microsoft.DotNet.Build.Tasks/Targets/publishtest.targets
CreateHardLinksIfPossible does not yet work in x-plat msbuild.
Fix #197 
cc @chcosta @JeremyKuhne @akoeplinger
> Only hard-link by default on Windows

- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime/project.json
- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime/project.lock.json
- src/nuget/xunit.netcore.extensions.nuspec
- src/xunit.console.netcore/project.json
- src/xunit.console.netcore/project.lock.json
- src/xunit.netcore.extensions/project.json
- src/xunit.netcore.extensions/project.lock.json
This moves us to the latest version of all of the xunit assemblies, including in our test-runtime project.json. We were previously using a "xunit.runner.dependencies.netcore" NuGet package, which we aren't building from anywhere public (it seems to be a holdover from our very early build process). This switches to just referencing the official xunit NuGet packages directly.
This also includes changes in our custom xunit assemblies (the console runner and our extensions assembly) to build directly against the official xunit packages.
NOTE: We also recently un-published some of our old NuGet packages, including one we were actually still using (PerfTools version 0.0.1-prerelease-00022), so this moves some things to floating versions to avoid that in the future.
> Update xunit versions to latest

- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime/project.json
- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime/project.lock.json
- src/nuget/xunit.netcore.extensions.nuspec
- src/xunit.console.netcore/project.json
- src/xunit.console.netcore/project.lock.json
- src/xunit.netcore.extensions/project.json
- src/xunit.netcore.extensions/project.lock.json
This reverts commit d5b48b4302a5899f9f9adb87d3847370208051e4.
This will take more work than I had expected to get working in corefx. There are some breaking API changes, which require some changes that I have made in my fork.
But, I also believe that there is a bug in the latest xUnit packages that causes some tests using [MemberData] to fail to run. It affects 4 of the projects in corefx. I'll re-submit this later when I've verified that all of the tests in corefx run correctly, probably on a newer version of the xUnit packages.
> Revert "Update xunit versions to latest 2.1.0-beta3"

- src/Microsoft.DotNet.Build.Tasks/Targets/tests.targets
Under code coverage, a System.Diagnostics.Process test was failing because the invoked process name did not match in casing to the expected value.  The expected value matches with the casing of CoreRun.exe, while the test was seeing corerun.exe on Windows.  The issue here appears to be that under OpenCover, the invoked target process (corerun) doesn't have its name canonicalized vs. the file system.  Fix this by setting the test host for Windows and Linux with the correct casing.
Fixes dotnet/corefx#2570
> Fix tests running under code coverage

- src/Microsoft.DotNet.Build.Tasks/Targets/packageresolve.targets
The current buildtools break on XBuild because of a syntax error (using a property without quotes) and using metadata references inside a metadata definition of an item. This should fix both problems.
> Make buildtools compatible with xbuild

- src/GenFacades.Desktop/project.lock.json
- src/GenFacades/project.lock.json
- src/Microsoft.Cci.Extensions/project.lock.json
- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime/project.json
- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime/project.lock.json
- src/nuget/xunit.netcore.extensions.nuspec
- src/xunit.console.netcore/project.json
- src/xunit.console.netcore/project.lock.json
- src/xunit.netcore.extensions/project.json
- src/xunit.netcore.extensions/project.lock.json
After filing this issue here: https://github.com/xunit/xunit/issues/515, I found there is a small modification we can make to our tests to accommodate for the difference in behavior with MemberDataAttribute. I have a set of changes made in corefx that will be able to consume these changes:
https://github.com/mellinoe/corefx/commits/latest-xunit
PR coming shortly there as well.
> Update buildtools to use latest xunit beta

- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime/project.lock.json
- src/nuget/xunit.netcore.extensions.nuspec
Second half of the buildtools changes needed to move to the latest xUnit beta.
This change just re-locks the dependencies of the test-runtime package, which brings us to the version of the packages built from the last official build of this repo. The next official build should give us a package with version prerelease-00069 which is what my corefx PR is set up to consume.
> Re-lock test-runtime dependencies

- src/xunit.console.netcore/Program.cs
1. Console.CancelKeyPress is now exposed from the Console contract, so we no longer have to exclude ctrl-C behavior.
2. Brad added the ability to disable discovery enumeration of theories, which is only necessary when there's UI associated with showing test cases (https://github.com/xunit/xunit/commit/07178782a6ea455ae42f1fa6f4b3bfec935cd587).  Just as in xunit.console, I'm disabling such preenumeration of theories as it's unnecessary overhead.
Note that I've not yet tested this against corefx; I'll do so once @mellinoe's xunit changes in corefx go in.
> Two improvements to xunit.console.netcore

- src/Microsoft.DotNet.Build.Tasks/Targets/ReferenceAssemblies.targets
This enables us to have the reference assemblies built to the contracts folder for internal builds.
> Allow override of reference assembly output path

- src/Microsoft.DotNet.Build.Tasks/Targets/Build.Common.targets
- src/Microsoft.DotNet.Build.Tasks/Targets/localization.targets
This localization code is common to all C# projects, and is the code
added by the Multilingual App Toolkit (MAT) for maintaining localization
in a project.
When building a project on a machine with MAT installed, MAT
synchronizes the .xlf files in the project with the Strings.resx, and
synchronizes the localized Strings.resx files with the .xlf files.  If
MAT is not installed on the machine, the loc file synchronization is
skipped and a message is written to the log file.
For the files to show up in Solution Explorer, it is necessary to set
Visible to True.
> Add common localization code

- src/Microsoft.DotNet.Build.Tasks/Targets/publishtest.targets
- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime/project.json
- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime/project.lock.json
- src/Microsoft.DotNet.Build.Tasks/Targets/versioning.targets
- src/nuget/xunit.netcore.extensions.nuspec
AssemblyInfoFileDir will not exist on a clean open build.  Ensure it is created.
xunit.netcore.extensions took a dependency on RuntimeInformation but didn't add it to the nuspec, add it.
The test architecture change broke some tests.  Add an opt out.
> Various fixes to enable migrating to latest build tools in corefx

- src/xunit.console.netcore/Program.cs
The xunit.console.netcore runner is printing out "Warning: " when there are no tests to run in the specified assembly.  This causes msbuild to treat that as a warning, which gets flagged and accumulated in the warnings statistics when doing a full build.  That results in 17 warnings when building corefx today, which is very noisy and ends up making it difficult to spot real warnings that should be fixed.
This commit simply changes the string to be "Info" instead of "Warning", and also uses a slightly different shade of yellow in order to differentiate it from more important warnings.  This brings the number of warnings generated during a full corefx build back down to 0.
> Disable "warning" for no tests in assembly

- src/xunit.netcore.extensions/Attributes/OuterLoopAttribute.cs
- src/xunit.netcore.extensions/Attributes/PlatformSpecificAttribute.cs
Technically, a trait can be applied to a class in addition to a method. This would let us mark a whole class as OuterLoop, something I might be interested in doing if I were to re-organize some of the Tasks tests.
> Allow OuterLoop on a class

- src/Microsoft.DotNet.Build.Tasks/Targets/PerfTesting.targets
Was causing the consumptive metrics to not find EventTracer.
> Fix the perf tools version mentioned in the targets file

- src/nuget/Microsoft.DotNet.BuildTools.nuspec
This change adds the AssemblyInfoPartial files to the BuildTools NuGet
package; these files are required by the build (see https://github.com/dotnet/buildtools/pull/251)
> Add AssemblyInfoPartial to BuildTools NuGet package

- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime/project.json
- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime/project.lock.json
With this change we are now importing Microsoft.NETCore.Platforms
which gives us the runtime mappings for windows and unix. For
example win7-x86 falls back to win7 and win-x86 and win etc.
This also refreshes the project.lock.json file as it was not updated after the last merge.
> Add platform support to test-runtime\project.json

- src/GenFacades/Program.cs
- src/Microsoft.DotNet.Build.Tasks/Targets/partialfacades.targets
When DebugSymbols is set to false (which is the case when building on
OSX or Linux, the FillPartialFacade task fails since it wants to the the
PDB (which was not produced) into the folder GenFacades uses as
input. With this fixed, GenFacades still issues a warning saying it will
not produce a PDB.
- Update the MSBuild authoring to not try to move a PDB when
DebugSymbols is false.
- Add a flag to GenFacades telling it to not try to produce a PDB and
use that flag to supress the warning when DebugSymbols is false.
> Stop GenFacade errirs when DebugSymbols is false

- src/Microsoft.DotNet.Build.Tasks/Targets/Build.Common.targets
- src/Microsoft.DotNet.Build.Tasks/Targets/partialfacades.targets
- src/Microsoft.DotNet.Build.Tasks/Targets/tool-runtime/project.json
- src/Microsoft.DotNet.Build.Tasks/Targets/tool-runtime/project.lock.json
- src/Microsoft.DotNet.Build.Tasks/Targets/toolruntime.targets
- src/nuget/Microsoft.DotNet.BuildTools.nuspec
Add support for running tools on top of .NET Core, things like GenFacades.
This change will restore a version of the Console .NET Core meta-package and any other dependencies into a shared directory, $(ToolRuntimePath), also including a host set via $(ToolHost).
Right now this only works on windows because we don't have all the necessary packages for x-plat yet. I'm actively working to get those enabled.
> Tool runtime support

- src/BuildTools.sln
- src/GenFacades/GenFacades.csproj
- src/nuget/GenFacades-Win7-x64.nuspec
- src/nuget/GenFacades.Desktop.nuspec
Reverts dotnet/buildtools#263
This actually break running GenFacades on .NETCore because it no longer has an entry point. I will revisit this after I push an updated buildtools to unblock other issues.
> Revert "Clean-up GenFacade individual packages"

- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime/project.json
- src/xunit.console.netcore/CommandLine.cs
- src/xunit.console.netcore/Program.cs
- src/xunit.console.netcore/project.json
- src/xunit.netcore.extensions/project.json
For performance tests to function correctly with corefx, we need to upgrade from xunit-beta3. Since xunit-rc1 is already out, I skipped beta4 and updated buildtools straight to rc1 instead.
I've excluded the project.lock.jsons with the intention of uploading them when they have an updated buildtools nuget package to reference.
I tested this with CoreFX and unit tests passed with the exception of a System.Console import error that is known and is being fixed by @weshaggard. With that said, I would greatly appreciate another tester :)
cc: @mellinoe
> Updated build tools to use xunit-rc1

- src/Microsoft.DotNet.Build.Tasks/Targets/IL.targets
Add property $(IlasmFlags) to the exec command to support additional arguments if necessary.
Change the separator between compile items to a space, so it doesn't break.
Fixes #262
> IL.Targets: Support Multiple Compile Items and Additional Arguments

- src/Microsoft.DotNet.Build.Tasks/Targets/PerfTesting.targets
- src/Microsoft.DotNet.Build.Tasks/Targets/tests.targets
PerfTesting.targets was inadvertently deleted in commit ca22795; this
change adds it back along with some fixes provided by ianhays.
> Add PerfTesting.targets back

- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime/project.json
- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime/project.lock.json
- src/Microsoft.DotNet.Build.Tasks/Targets/tool-runtime/project.json
- src/Microsoft.DotNet.Build.Tasks/Targets/tool-runtime/project.lock.json
Having the '*' versioning wih these keeps getting builds into
unpredictable states because they are pulling the latest packages
more often then we would like. This commit fixes the versions
to a specific version so we can have more deterministic results.
> Remove '*' versions from test and tool runtime project.json

- src/Microsoft.DotNet.Build.Tasks/Targets/partialfacades.targets
- src/Microsoft.DotNet.Build.Tasks/Targets/toolruntime.targets
We believe hardlinks make for an interesting race condition in some cases
while writing to the same location. Given that this is only copied to
the one location we will disable the hardlinks to see if it helps with
reliability.
While running CoreRun in a build enviroment that as COMPLUS_InstallRoot
set the COM activation for things like the PDB APIs fail to activate
because the runtimes don't match. To help eliminate this problem
we clear the COMPLUS_InstallRoot before calling CoreRun. This new
ToolHostCmd also allows folks to also add other such env variable tweaks
as part of the command if necessary.
> Remove tool runtime hardlinks and add extensibility for cmd

- src/Microsoft.DotNet.Build.Tasks/Targets/CodeCoverage.targets
- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime/project.json
- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime/project.lock.json
Code coverage is failing because the path to the report generator tool is
being created incorrectly.  It appears this is due to the version number
of the report generator changing from 2.3.0.0 to 2.3.0.  As long as I was
fixing that, I updated it to the most recent version, 2.3.1.  I verified
code coverage works now with the change.
cc: @weshaggard, @mmitche
> Fix code coverage report generation

- netci.groovy
This adds a file that defines the CI information for the buildtools repo.  This is a transition from the manually configured jobs.
> Add netci.groovy for automatic job generation

- src/Microsoft.DotNet.Build.Tasks/Targets/PerfTesting.targets
Updated perf testing targets to throw an error if an attempt is made to run performance tests without the required v5.0 .NET libraries.
Goes along with PR: https://github.com/dotnet/corefx/pull/3304
> Updated perf testing targets

- src/nuget/xunit.console.netcore.nuspec
- src/xunit.console.netcore/project.json
- src/xunit.console.netcore/project.lock.json
- src/xunit.console.netcore/xunit.console.netcore.csproj
This will allow the test runner to be deployed by NuGet when xunit.console.netcore package is referenced from project.json in test projects.  For example, see [here](https://github.com/dsplaisted/msbuild/blob/00d48e80ff5c46c86e08c3bf0f1ede98863ba7bc/src/Framework/UnitTests/project.json#L26)
> Deploy xunit.console.netcore.exe via NuGet

- src/Microsoft.DotNet.Build.Tasks/Targets/toolruntime.targets
By default, build tools would restore the windows version of the runtime
packages (even when '$(OS)' was not 'Windows_NT'). While a project
consuming the build tools could override this, it meant if they did not
the chmod would fail because it couldn't find corerun (since we instead
restored CoreRun.exe).
Guard the chmod with a test to ensure corerun actually exists.
Fixes #292
> Fix build breaks on Linux with 00097

- src/Microsoft.DotNet.Build.Tasks/Targets/FrameworkTargeting.targets
- src/Microsoft.DotNet.Build.Tasks/Targets/ReferenceAssemblies.targets
- src/Microsoft.DotNet.Build.Tasks/Targets/depProj.targets
- src/Microsoft.DotNet.Build.Tasks/Targets/packageresolve.targets
- src/Microsoft.DotNet.Build.Tasks/Targets/partialfacades.targets
This adds depProj.targets which minimally extend Microsoft.Common.Targets
to merely copy assets out of packages referenced by project.json.  The targets
can be configured to copy a specific asset type: (default) ReferenceCopyLocalPaths
for runtime assets, Reference for compile assets, or Analyzer for analyzers.
They do very little to change the nuget resolution process so that remains
driven as it is today by the normal project properties like TargetFramework,
TargetPlatform, and PlatformTarget.
I also made a change to plug these in to build tools for .depproj extension,
and a change to our reference assembly targets to set the property to indicate
that compile time assets should be used.
I plan to follow this up with changes in corefx that use .depproj's to deploy
older versions of our …
> Support a project type to deploy assets from nuget packages

- src/Microsoft.DotNet.Build.Tasks/Targets/PerfTesting.targets
- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime/project.json
- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime/project.lock.json
- src/xunit.console.netcore/project.json
- src/xunit.console.netcore/project.lock.json
- src/xunit.netcore.extensions/project.json
- src/xunit.netcore.extensions/project.lock.json
This PR and a yet-to-be-posted CoreFX PR accompanying it will update to the latest xunit.
> Upgrade buildtools to xunit 2.1.0 Release

- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime/project.json
- src/Microsoft.DotNet.Build.Tasks/Targets/test-runtime/project.lock.json
This should remove all references to older versions of xunit
@ellismg @weshaggard @mellinoe
> Updated buildtools to use netcore 101

- src/Microsoft.DotNet.Build.Tasks/Targets/FrameworkTargeting.targets
While we label ourselves as .NETPortable v4.5 we aren't a traditional
portable project and we can correctly reference a .NETPortable v5.0 project.
So this disabled the RAR warning for projects that target the default.
We will eventually switch our defaults to .NETPortable v5.0 as that is
closer to what we truely are be we aren't ready to force everyone to use
VS 2015 yet and require the new portable targeting pack when we don't even
really use it.
cc @ericstj @nguerrera
> Disable RAR warning about mismatched portable references

- src/Microsoft.DotNet.Build.Tasks/Targets/depProj.targets
Our internal build needs to distinguish newly built files from
redistributed binaries.  Provide a hook in depProj.targets to
do this for assets that are copied from nuget packages.
> Add a hook for dropping marker files

- src/xunit.console.netcore/CommandLine.cs
- src/xunit.console.netcore/Program.cs
- src/xunit.console.netcore/Visitors/StandardOutputVisitor.cs
When debugging problems in hanging tests, it's very useful to be able to know which tests have started but haven't finished.  This commit adds a "-showprogress" option to the xunit.console.netcore.exe command line which, when set, will result in xunit tracing out to the console the starting and finishing of each individual test, e.g.
```
System.Threading.Tasks.Dataflow.Tests.ActionBlockTests.TestPost [STARTING]
System.Threading.Tasks.Dataflow.Tests.ActionBlockTests.TestPost [FINISHED] Time: 0.0316922s
```
cc: @FiveTimesTheFun, @mellinoe, @weshaggard, @ellismg
> Show starting/finishing test progress in xunit console

- src/Microsoft.DotNet.Build.Tasks/Targets/publishtest.targets
- src/Microsoft.DotNet.Build.Tasks/Targets/toolruntime.targets
Adding support to set an Env Variable that points to a directory with the tool runtime, so that we support building mscorlib in different linux distros like Fedora
> Adding support for tool-runtime in different linux distros

- src/Microsoft.DotNet.Build.Tasks/Targets/toolruntime.targets
Changing ToolRuntimePath to be in the Intermediate folder instead of bin output
> Changing ToolRuntimePath to be in the Intermediate folder instead of bin output

- src/GenFacades/Program.cs
Only add a type forward if the nested type is visible outside of the assembly. This is the fix for issue #274
> Only add a type forward if the nested type is visible outside of the assembly

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/PackageLibs.targets
Looks like all our open projects were setting this property but it wasn't having an effect.  I caught this with a new validation task I am working on.
> Honor UsePackageTargetRuntimeDefaults

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
Some minor changes needed to the build tools to enable the testing
targets to work cross platform.
- We need to ensure corerun is executable before we run it.
- corerun is not on the path and neither with the CWD, so we pass a
full path to corerun when invoking it.
- Use OSGroup to compute the platform specific attribute to pass to
xunit to disable tests that are not valid for the OS in question.
> Enable testing when running cross plat

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Post.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/CloudTest.targets
Add Build.Post.targets to be wired up after product and test binaries have
been built (see https://github.com/dotnet/corefx/pull/4141 for context).
Add CloudTest.targets to be conditionally imported post-build.
> Add post-build targets and support for cloud testing.

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/PerfTesting.targets
My old targets were buggy and didn't allow perf tests to be included when building the tests but not running them. I've modified them and renamed them to better accomodate this.
I also removed the v5.0 TargetFramework declarations that are no longer required.
@mellinoe @jhendrixMSFT
> Updated perf targets

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
Move the logic to produce a full path for corerun to when we define
$(TestHost) insteead of when we actually execute the tests. Doing so
fixes a break when we try to run coverage which overides $(TestHost)
with a full path to OpenCover (previously we would generate an invalid
path).
> Fix coverage build

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/CloudTest.targets
Current test runs are running all tests on Windows which is creating false
failures, i.e. the non-Windows tests are failing.  This change filteres
them out of test runs.
> Filter out non-Windows tests for cloud test runs.

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
$(TestProgram) is now a full path, so we don't need to prepend it with
the working directory.
> Fix running test projects in VS

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/CloudTest.targets
- src/Microsoft.DotNet.Build.Tasks/SendToEventHub.cs
This change adds an optional PartitionKey property to the SendToEventHub build task and then consumes it to send the official build event to the appropriate partition.
This fixes a caching issue where test runs could be duplicated.
> Update SendToEventHub with PartitionKey property any use it.

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets
When BUILDTOOLS_OVERRIDE_RUNTIME is set, if we are hard linking the shared
runtime in the test folder, then trying to copy an updated coreclr (or
other files used by the runtime) will cause races due to a file being in
use.
Update the logic to fold the over-ridden files into the general ItemGroup
we filter and then copy as needed.
> Fix build races with BUILDTOOLS_OVERRIDE_RUNTIME

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
https://github.com/dotnet/corefx/pull/4118 made it so that perf tests ran as unit tests by default. Although this is the desired behavior, the InnerIterations structure that they use is causing an unacceptable amount of slowdown to the other CoreFX unit tests.
I need to get a more permanent solution but in the meantime this commit is a quick and easy reversion that disables the perf tests by default. Running with Performance=true still works as expected.
@stephentoub @mellinoe
> disable perf as unit tests temporarily

- src/xunit.netcore.extensions/Attributes/ConditionalFactAttribute.cs
- src/xunit.netcore.extensions/Attributes/ConditionalTheoryAttribute.cs
- src/xunit.netcore.extensions/Discoverers/ConditionalFactDiscoverer.cs
- src/xunit.netcore.extensions/Discoverers/ConditionalTheoryDiscoverer.cs
- src/xunit.netcore.extensions/SkippedTestCase.cs
- src/xunit.netcore.extensions/xunit.netcore.extensions.csproj
This lets us write tests like:
```C#
[ConditionalFact("RunningWithElevatedPrivileges")]
public void TestThatOnlyRunsAsAdmin() { ... }
...
private static bool RunningWithElevatedPrivileges() { ... }
```
and
```C#
[ConditionalTheory("WebSocketsAvailable")]
[InlineData("http://someUrl")]
[InlineData("https://someUrl")]
public void TestThatOnlyRunsWithWebSockets(string url) { ... }
...
private static bool WebSocketsAvailable { get { ... } }
```
cc: @davidsh, @weshaggard, @mellinoe, @Priya91, @Chrisboh 
Related to https://github.com/dotnet/corefx/issues/3349
> Adds ConditionalFact/Theory attributes and discoverers

- src/Microsoft.DotNet.Build.Tasks/GenerateAssemblyList.cs
- src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets
Added modifications for AssemblyList generated during Cloud Tests to add pattern support. This is to help differentiate Runtime dependencies and xunit dependencies during test execution.
> Added modifications for AssemblyList generated during Cloud Tests

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/partialfacades.targets
These workarounds were in place because, in order to reference mscorlib in our partial facades, we were referencing a Microsoft.DotNet.CoreCLR NuGet package, which had a variety of extra assemblies that got automatically pulled in as references. Also, the mscorlib we were referencing was architecture-specific, which brought in a compiler warning that we suppressed. None of this is necessary any longer now that we have published proper reference assembly packages for mscorlib and the rest.
@weshaggard
> Remove the workarounds in partialfacades.targets

- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
- src/Microsoft.DotNet.Build.Tasks.net45/Microsoft.DotNet.Build.Tasks.net45.csproj
- src/Microsoft.DotNet.Build.Tasks.net45/project.json
- src/Microsoft.DotNet.Build.Tasks.net45/project.lock.json
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/CodeCoverage.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/UpdateBuildValues.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/encoding.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/gitpush.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/packageresolve.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/packages.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/partialfacades.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/resources.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/sign.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/toolruntime.targets
- src/nuget/Microsoft.DotNet.BuildTools.nuspec
Bringing back Full Framework version of the task library to be able to build in razzle and linux.
When we moved this Task library to .Net Core we verified that it would be able to be loaded also when using full framework. What we didn't validate, is that it requires full framework 4.6 which means that it won't work in linux(mono msbuild doesn't support 4.6) nor Razzle builds(razzle runs with full framework 4.5). Because of this, after upgrading the buildtools version broke corefx repo in both environments. This change will add back the 4.5 version of the task library and store it under the 'net45' folder inside the package, so that razzle and linux builds can load that instead of the .Net Core version.
> Bringing back Full Framework version of the task library to be able to build in razzle and linux

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/packageresolve.targets
This add support for filtering out resolved assets from the
targeting pack packages. It does this based on the following property
TargetingPackNugetPackageId which is set to the id of the package
to filter. It will remove any packages references from that package
except for the ones explicitly listed in the TargetingPackageReference
item group.
cc @mellinoe @ericstj
> Add support for filtering resolved packages from targeting packages

- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
There is currently no way to submit just the performance tests to the
cloud test infrastructure.  This new property, FuncTestsDisabled, will
disable the functional tests when perf tests are enabled.
Stop excluding test data from packages.zip as it causes test failures.
> Add a msbuild property to disable functional tests for cloud testing.

- dir.props
- src/Microsoft.DotNet.Build.Tasks.net45/Microsoft.DotNet.Build.Tasks.net45.csproj
- src/Microsoft.DotNet.Build.Tasks.net45/project.json
- src/Microsoft.DotNet.Build.Tasks.net45/project.lock.json
- src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/packageresolve.targets
- src/Microsoft.DotNet.Build.Tasks/UpdatePackageDependencyVersion.cs
- src/Microsoft.DotNet.Build.Tasks/UpdatePrereleaseDependencies.cs
- src/Microsoft.DotNet.Build.Tasks/UpdateProjectDependencies.cs
- src/Microsoft.DotNet.Build.Tasks/ValidateProjectDependencyVersions.cs
- src/Microsoft.DotNet.Build.Tasks/VisitProjectDependencies.cs
- src/Microsoft.DotNet.Build.Tasks/project.json
- src/Microsoft.DotNet.Build.Tasks/project.lock.json
This adds a new target `ValidatePackageVersions` and two tasks `UpdatePrereleaseDependencies` and `UpdatePackageDependencyVersion`. This diff shows what I needed to do to use them in corefx: https://github.com/dotnet/corefx/compare/master...dagood:dagood/no-lockfile-tooling
(Note: this adds a NuGet source of the nugetbuild MyGet repository to `dir.props` for `NuGet.Versioning`, but it was already in `src/NuGet.config` anyway.)
---
`ValidatePackageVersions` runs after `ResolveNuGetPackages` and can check all project.json files for `*` (floating) dependencies and/or can make sure all packages match a given prerelease version. What it does depends on the properties/item collections when the target is run. By default, the task runs but no validation happens when no properties are passed.
This …
> Add project.json tooling for an alternative to checking in lockfiles

- src/Microsoft.DotNet.Build.Tasks/VisitProjectDependencies.cs
When I used `.Any(...)` to check if dependencies needed to change after being visited, only the first change happens because `.Any` short-circuits. Changed to `.Select(...).ToArray().Any()` so that all visits are always evaluated.
> Allow multiple dependency updates to one project.json

- src/common/AssemblyResolver.cs
MSBuild does not provide a convention for task dll's to specify bindingRedirects.
Sometimes a task may need to use two different libraries that use use different versions
of a common library (EG: Newtonsoft.JSON).  NuGet ensures that the higher version, is
used by the task, but one dependency will still have static reference to the lower version.
Without binding redirects this will result in a failure to load the assembly with the
lower version.  Address this by hooking AssemblyResolve and probing for the
assembly by simple name and choosing the first assembly that satisfies the request,
permitting higher versions.
> Add AssemblyResolver to load conflicting assemblies without bindingRedirects

- src/Microsoft.DotNet.Build.CloudTestTasks/Microsoft.DotNet.Build.CloudTestTasks.csproj
- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
- src/Microsoft.DotNet.Build.CloudTestTasks/SendJsonToDocumentDb.cs
- src/Microsoft.DotNet.Build.CloudTestTasks/WriteBuildStatsJson.cs
- src/Microsoft.DotNet.Build.CloudTestTasks/packages.config
- src/Microsoft.DotNet.Build.Tasks.net45/project.lock.json
- src/nuget/Microsoft.DotNet.BuildTools.nuspec
These changes are currently scoped to the cloud-based test infrastructure.
Generate a JSON file containing test build statistics and upload it to
DocumentDB for later processing.  At present, the only statistic captured
is the number of successfully built tests.
Stop adding xunit and corerun zip packages to the list of downloads as
they are no longer required (they are pulled from packages.zip).
> Add initial support for reporting build statistic.

- src/Microsoft.DotNet.Build.Tasks.net45/Microsoft.DotNet.Build.Tasks.net45.csproj
- src/Microsoft.DotNet.Build.Tasks.net45/project.json
- src/Microsoft.DotNet.Build.Tasks.net45/project.lock.json
- src/Microsoft.DotNet.Build.Tasks/project.json
- src/Microsoft.DotNet.Build.Tasks/project.lock.json
- src/dir.targets
Add an `UpdateImportedProjectRelativePaths` to remap items that came from an imported project.
Have Microsoft.DotNet.Build.Tasks.net45.csproj import Microsoft.DotNet.Build.Tasks.csproj 
rather than duplicating the project.
> Import BuildTools project rather than duplicating

- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
We no longer want to use Azure file shares for results storage so
replace the task with one to create Azure blob storage containers.
Cleaned up properties for account names and access tokens.
> Switch to using Azure blob storage for cloud job results.

- src/Microsoft.DotNet.Build.Tasks/VisitProjectDependencies.cs
Previously this was re-writing any project.json that
had dependencies.  It should have been checking
the flag returned by VisitPackage to ensure that a
write was required.
/cc @dagood @weshaggard
> Only write project.json when changes are required

- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
Remove hard-coded xUnit test args and replace with a property so the value
can be specified at build time.
> Make xUnit test args configurable.

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/packageresolve.targets
Add two new targets that run automatically during the build to validate `tool-runtime/project.json` and `test-runtime/project.json` automatically.
These new validation steps (and the earlier project.json validation) are individually optional. This should be useful because it makes sense to keep the `test-runtime/project.json` override in the corefx repo in step, but with `tool-runtime/project.json` in the buildtools package it doesn't seem worth it to keep that in step.
> Add tool-runtime and test-runtime project.json validation

- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets
Add a new target, CopySupplementalTestData, that projects can use to copy
test data to the test directory.  In addition, the task will also copy the
assets to the output directory so it can be picked up by the cloud test
infrastructure (it will be included in the test archive).
Exclude the test data from packages.zip as it's now being distributed with
the test binary.
> Consolidate copying of supplemental test data.

- src/Microsoft.DotNet.Build.Tasks.Packaging/src.Desktop/Microsoft.DotNet.Build.Tasks.Packaging.Desktop.csproj
- src/Microsoft.DotNet.Build.Tasks.Packaging/src.Desktop/NuGetPack.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/packages.targets
.pkgprojs will now produce a nupkg.
This ports some code that was using NuGet.Core
to do the packing and thus it is only in the desktop
build of the tasks.  We'll eventually need a core-CLR
friendly implementation of this.  Once we have that
library from NuGet we can move this to the shared
source.
> Add Pack to packaging targets

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/Generations.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/PackageLibs.targets
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/ValidatePackageTargetFramework.cs
Previously we weren't skipping ignored references if they
were direct (only indirect).  This fixes that.
I've also added an override in case we hit something similar
again.
Previously I made this fix for some NETNative assemblies
that were claiming to be generational.  We'll need that 
in the future if we make NETNative more generic than
just netcore50.
> Skip ignored references during Generation validation

- src/Microsoft.DotNet.Build.Tasks.Packaging/src.Desktop/NuGetPack.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/ApplyPreReleaseSuffix.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/CreateTrimDependencyGroups.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/EnsureOOBFramework.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/GenerateRuntimeDependencies.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/GetAssemblyReferences.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/GetInboxFrameworks.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/GetPackageDescription.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/GetPackageVersion.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackagingTask.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/ValidatePackage.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/ValidatePackageTargetFramework.cs
Mono's implementation of TaskLoggingHelper seems
to capture the BuildEngine property of the task during
construction of the TaskLoggingHelper.  This breaks
when someone constructs a TasksLoggingHelper in
the constuctor of their task, since none of the fields
are initialized.
Work around this by making our TaskLoggingHelper
lazily initialized.
> Workaround nullref in Mono's MSBuild

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/CreateTrimDependencyGroups.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/Generations.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Generations.json
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
Generations.cs
Make dll probing in version calculation more flexible
We weren't finding a reference assembly for System.Threading.Tasks.Extensions
so were falling back to package store probing.  Package store brobing would
fail if no stable package existed (as is the case here).
To fix this I've made the probing much more flexible.  This is a temporary
fix, the code is dead in the Open-source port of the task which uses
the actual project references to do the generation calculation.
Generations.json
Move System.ServiceModel.Http 5.4 to 4.1.0.0.  API changes supported
by existing desktop framework 4.6.
Packaging.targets
@chcosta - Packaging for native shims.
@weshaggard - Support project-authored stable packages.
- Project .builds work.
CreateTrimDependencies.cs
@chcosta - NuGetFramework …
> Sync packaging infrastructure with TFS changes

- src/Microsoft.DotNet.Build.Tasks/PrereleaseResolveNuGetPackageAssets.cs
- src/Microsoft.DotNet.Build.Tasks/Strings.Designer.cs
- src/Microsoft.DotNet.Build.Tasks/Strings.resx
After I bumped the build tools version up I started getting NPEs from the resolve assets tasks. Apparently the ProjectLanguage task parameter is now mandatory.
In order to save investigation time I added a null check and an error message.
An alternative implementation would be to mark the task parameter as required.
> Throw exception if ProjectLanguage is null

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
I had a typo where I was still using "nuproj" in
an item name.  This was causing a problem when
trying to consume buildtools in our internal build
where we build and validate meta-packages.
> Fix remaining nuproj references

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
We were collecting the list of TFMs to project
naked project references to before adding the
OOB framework assets.  As a result we were
not projecting to netcore50.
> Assign package refs to OOB tfm as well

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Generations.json
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/PackageLibs.targets
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/stable.packages.targets
Make packages build library references by default.
Allow TFS to set PackagePlatform.
Fix up formatting.
> Packaging fixes for TFS build

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/partialfacades.targets
Now with the builds files we get race conditions for projects like
System.Collections that build multple partial facades in parallel and so
the building of the ref with different OSGroup or TargetGroup combinations
causes this to build multiple times which conflict given that the output
directores aren't parameterized on those properties. This change simply
undefines these global properties so the project references get folded into one
and there is no longer a race.
cc @ericstj @mellinoe
> UndefineProperties OSGroup and TargetGroup for contract project references

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/FrameworkTargeting.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets
I've been seeing a need in recent work to have extensibility in place to exclude both the mscorlib design-time reference as well as the assemblyinfopartial.cs file, so I've added a way to exclude them.
> Add couple exclude properties to targets

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
Add a property SkipCreatePackageOnMissingFiles that will
skip the creation of the nuget package when missing files
are detected.
> Support SkipCreatePackageOnMissingFiles

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/partialfacades.targets
This target has actually never worked on Ubuntu, or presumably any other platform than Windows. We had a backup target kicking in here ("FindPartialFacadeContractReference"), which would run if FindPartialFacadeProjectReference did not locate the project reference. The backup target did not work for net46 configurations, because it produced a malformed project.json which it tried to restore. I talked with Wes and we agreed to just remove the backup target because we should always be able to find the reference assembly project. It was also using * versioning still which may have been problematic and also made builds less predictable. If we are for some reason not able to locate the reference assembly project still, we will get the same error as before ("No single matching contract …
> Fix backslashes in FindPartialFacadeProjectReference

- src/Microsoft.DotNet.Build.Tasks.Packaging/src.Desktop/project.lock.json
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/CodeCoverage.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/test-runtime/project.json
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/test-runtime/project.lock.json
Our code coverage runs recently started failing consistently in CI, and it looks like there may be some related fixes in more recent releases.
cc: @mmitche, @weshaggard
> Update OpenCover and ReportGenerator versions

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
This was previously hard-coded to only consider things that were not supported on Windows. Instead, I'm just comparing the identities of the unsupported platforms with the current OSGroup. This should fix all of the unsupported tests being run in x-plat builds (outside of run-tests.sh).
@weshaggard , @Priya91
> More robust UnsupportedPlatform handling

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd
Adding the option to set the Buildtools target runtime instead of always using win7-x64
> Adding the option to set the Buildtools target runtime instead of always using win7-x64

- dir.props
/cc @weshaggard @markwilkie 
FYI to anyone who breaks with 
```
Error: FindPackagesById: <packageId>
Response status code does not indicate success: 404 (Not Found).
```
This is the error you'll get whenever any feed in your source list cannot be resolved.  NuGet/DNX fails rather than just skipping that feed.
> Remove dotnet-corefx feed since it no longer exists

- dir.props
- src/Microsoft.Cci.Extensions/project.lock.json
dotnet-corefx feed was deleted yesterday, hence builds started failing since the calls to get the packages returned a 404. I checked and it looks like all the packages are already on the other feeds, so simply removing it and updating one lock file gave a green build for me.
> Removing unused nuget feed

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/FrameworkTargeting.targets
The common metadata includes things like OSGroup and TargetGroup,
as well as some common packaging properties.
cc @ericstj
> Add shortcuts for common metadata to all ProjectReferences

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh
If the user has specified a value for BUILDTOOLS_OVERRIDE_RUNTIME
(e.g. if they are building on an OS or distro for which a package
is not available), copy the specified runtime into the necessary
locations for dotnet, dnx, etc.
> Respect BUILDTOOLS_OVERRIDE_RUNTIME in init-tools.

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/clean.targets
Based on the feedback for https://github.com/dotnet/corefx/pull/4643,
I've decided to add clean targets to BuildTools so that they can be
shared between clean.sh and clean.cmd, and used for both CoreFX and
CoreCLR.  Note that these targets are in addition to the Clean target
which is defined in build.proj in CoreFX and removes the bin directory.
> Add additional clean targets

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/CodeCoverage.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/test-runtime/project.json
To workaround an OpenCover regression around filters.
> Upgrade to OpenCover v4.6.476-rc

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/test-runtime/project.json
Applies the workaround mentioned here: https://github.com/dotnet/corefx/issues/4448#issuecomment-156255106
Fixes these errors I'm hitting when restoring test-runtime\project.json with xplat nuget:
EXEC : warning : xunit.abstractions 2.0.0 is not compatible with DNXCore,Version=v5.0 (win7-x64).
EXEC : warning : xunit.abstractions 2.0.0 is not compatible with DNXCore,Version=v5.0 (win7-x86).
EXEC : warning : xunit.abstractions 2.0.0 is not compatible with DNXCore,Version=v5.0.
cc @weshaggard @ericstj
> Add framework import to test-runtime making xunit.abstractions compatible with DNXCore

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/CodeCoverage.targets
The report generator command is failing because the path gets generated with "-beta2".
> Fix ReportGeneratorVersion

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets
When TestWithLocalLibraries=true it will find local copied binaries
from AnyOS as well as from the matching OsGroup binary directory.
@stephentoub @ellismg
> Update TestWithLocalLibraries support to understand AnyOS

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/packageresolve.targets
We now always filter both references and copy-local references from
any packages that starts with "Microsoft.TargetingPack". For references
we still keep any reference included in TargetingPackReference item group.
This also add some default entries to the TargetingPackReference to avoid
duplication in all projects that use these.
cc @ericstj @dagood @mellinoe
> Update TargetingPack filtering

- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
- src/Microsoft.DotNet.Build.CloudTestTasks/WriteItemsToJson.cs
In order to support arbitrary workloads folks need the ability to upload
arbitrary payloads.  A new item group, SupplementalPayload, has been added
that is to contain content to be uploaded to the root of the container.
Added property RunnerScript that allows one to override the default runner
script.
Switch to using ';' char for array delimiter as it aligns with how msbuild
writes out an expanded item group.
> Add support for uploading supplemental payloads.

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/partialfacades.targets
Given that we have moved to using .Net Core MSBuild in non-Windows corefx builds, we are now able to produce Portable PDBs as part of the build. The problem is that CCI doesn't support Portable PDB reading yet, so GenFacades can't rewrite them as part of the build. This change is to disable the PDB rewriting for now when the PDBs are portable and will be removed once CCI supports it.
> Add check to GenFacades command so that if DebugType is Portable we disable the rewrite in genfacades.

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/NuGetPack.cs
Adding Base Directory to NugetPack task. This is required for the open PR for updating build tools.
> Adding Base Directory to NugetPack task

- init-tools.cmd
- src/dirs.proj
This is a temporary fix to unblock folks. The right fix is comming which is adding support to overriding Versions in NugetPack task.
> Falling back to using NuGet.exe for package creation temporary to fix no revision in packages bug.

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/NuGetPack.cs
Adding PackageVersion parameter to NugetPack task so that nuspec version can be overriden
> Adding PackageVersion parameter to NugetPack task so that nuspec version can be overriden

- src/Microsoft.DotNet.Build.Tasks/GatherFoldersToRestore.cs
- src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj
- src/Microsoft.DotNet.Build.Tasks/project.json
In CoreFX we spend a bunch of time restoring packages, because we end up invoking
dotnet restore 300+ times to work around DNX bugs. This tool helps us batch up
these invocations which decreases the number of processes we have to launch and
should help dotnet restore do some additional caching
These problems may go away when we switch to a dotnet CLI which restores using
nuget, but for now this has a measurable impact on package restore.
In my measurements, package restore where the "packages" folder did not exist (but
the NuGet/DNX caches had not been cleared) dropped from ~20 mins to ~4.5 and a
package restore where everything had already been restored previously (e.g. calling
sync.cmd /p twice and measuring the second run) went from ~17 mins to ~50 seconds.
> Add a custom helper command to speed up restores

- src/Microsoft.DotNet.Build.CloudTestTasks/CreateAzureContainer.cs
- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
- src/Microsoft.DotNet.Build.CloudTestTasks/UploadToAzure.cs
Add a new property, FailIfExists, to task CreateAzureContainer that when
set to true will cause the task to fail if it attempts to create a
container that already exists.
In the UploadToAzure task, if the operation fails don't simply let an
exception go unhandled.  Instead, log an error message and have the task
return false.
Disable overwriting of upload content by default.  To overwrite, set
property OverwriteOnUpload to true.
> Fixes for cloud testing tasks.

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/GetAssemblyReferences.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/Microsoft.DotNet.Build.Tasks.Packaging.csproj
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/SplitReferences.cs
Previously we'd try to determine if an assembly was mscorlib-based
or System.Runtime-based.  If mscorlib-based we assumed all
dependencies were framework assemblies.  This was incorrect, partial
facades may still reference packages and those packages may have an
OOB implementation.  This was recently the case for
System.IO.Compression's reference to System.Buffers.
https://github.com/dotnet/corefx/issues/5941
/cc @sokket @weshaggard @chcosta
> Split references by FrameworkAssembly/Dependency

- src/Microsoft.DotNet.Build.Tasks/BinClashLogger.cs
- src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj
This msbuild logger detects binclashes by recording all projects that
build and their TargetPath.  Once the build is done it logs all
clashes that occurred during the build.
This is a work in progress and I plan to refine the logging and
sequence of the error message.
/cc @weshaggard @mellinoe
> [WIP]Add BinClash detecting build logger

- build.proj
- dir.props
- src/BinaryRewriting/BclRewriter/project.json
- src/GenAPI.Desktop/project.json
- src/GenAPI/project.json
- src/GenFacades.Desktop/project.json
- src/GenFacades/project.json
- src/Microsoft.Cci.Extensions/project.json
- src/Microsoft.DotNet.Build.Tasks.Packaging/src.Desktop/project.json
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/project.json
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/test-runtime/project.json
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.json
- src/Microsoft.DotNet.Build.Tasks/project.json
- src/xunit.console.netcore/project.json
- src/xunit.netcore.extensions/project.json
NuGet restore couldn't find rhel.7-x64 runtimes for old packages, so I updated the tool-runtime project.json.
After that, to finish https://github.com/dotnet/buildtools/issues/402, I added the dependency validation task to the build and upgraded the other project.jsons in `src\`.
/cc @ericstj
> Update prerelease versions, add pre-restore dependency validation

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets
Content files from the test csproj weren't considered as special in the publishing to the tests directory. For all dependencies we take the file name and extension, append that to the tests directory and call it a day. Sub-directories are never considered, regardless of the type of the item (content, none, etc.).
We do something special for restoring supplemental test data from a nuget package (i.e. testdata), but do not do anything along those lines for content within the csproj directly.
This commit adds logic to respect the subdirectories of Content items.
@mellinoe
> Add logic for local Content to correctly binplace to the tests directory

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.json
Restoring the full framework roslyn compilers to the Tools directory so that they may be consumed by corefx Windows builds.
> Restore Roslyn Compilers to Tools directory

- src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj
- src/Microsoft.DotNet.Build.Tasks/PreprocessFile.cs
Add a very simple task that understands the limited form of #if/#endif
used by mscorlib.txt used for mscorlib's resources. This will allow us
to preprocess the file to generate a new .txt file that has only the
resources mscorlib needs (based on what FEATURE_ flags are defined)
and then use that as the .txt file MSBuild will use to generate
resources.
This will be used to resolve dotnet/coreclr#3090.
> Add a simple preprocessor task

- src/Microsoft.DotNet.Build.CloudTestTasks/CreateAzureContainer.cs
- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
In the CreateAzureContainer task, append a '/' to the storage URI if one
doesn't exist.
Don't append $(BuildArch) and $(BuildType) properties to the root of the
URI as not all repos define these properties.  It's also redundant as
architecture-specific content is already copied to the appropriate
subdirectories in the container.
This fixes the bug mentioned in issue https://github.com/dotnet/buildtools/issues/460.
> Fixes for cloud testing targets.

- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets
Added property OtherRunnerScriptArgs allowing additional runner script
args to be specified at build time.
Replaced hard-coded Windows-specific Helix python root path environment
variable with a dynamic property supporting Windows and Unix variants.
Change assembly list file name to all lower case to avoid issues on case-sensitive
file systems.
> Fixes to cloud test targets.

- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
Make TimeoutInSeconds value configurable.
Gather ForUpload items in the VerifyInputs target to ensure it's evaluated
after the Build target complets.
> Fixes for cloud testing.

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh
In init-tools.sh we expect dotnet publish to copy the native artifacts in `tool-runtime/project.json` packages into the Tools dir. If we upgrade the version of dotnet CLI that we use, native artifact copy doesn't happen due to ~~https://github.com/dotnet/cli/issues/710~~ https://github.com/dotnet/cli/issues/1528.
This works around it by manually copying the expected native artifacts to the Tools dir.
**Open question**: hardcoding the path feels really bad. Another option is to restore `tool-runtime/project.json` *again* into a folder under the tool runtime dir and copy the files out from there. This also would mean that we can use better wildcards rather than hardcoding the path, because we know only the packages we want are in the folder. This would slow down the init though. Is it worth …
> Workaround to copy native artifacts to the tools dir (for CLI upgrade)

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.json
In CI, the OS X builds are failing intermittently because restoring the tool
runtime is pulling down an old version of the runtime assemblies for
System.Runtime.Extensions. This version expects some exports from
System.Native which have been renamed.
Setting the correct version of System.Runtime.Extensions seems to
address this issue (I tried restoring the tool-runtime from this
project.json a bunch of times and each time the right thing happened,
whereas without this fix it only worked about a quarter of the time).
Obviously there is some larger issue at play here as I would not expect
this to be needed, but I would really like to unblock our CI runs so
here's a pragmatic change which should do that.
> Specify specific version of S.R.Extensions

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh
Reverses https://github.com/dotnet/buildtools/pull/463 because https://github.com/dotnet/cli/issues/1528 has been fixed. Native artifacts like `MSBuild.exe` and `Microsoft.CSharp.targets` are now correctly copied by dotnet publish.
(The fix is available starting with CLI `1.0.0.001504`.)
/cc @ericstj @weshaggard @joperezr
> Remove workaround for dotnet publish not copying native artifacts

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh
The `\"` in init-tools.cmd was causing a `error: Illegal characters in path.` error with new dotnet CLI. Edited .cmd and .sh for symmetry.
Here's DNU (old) behavior vs xplat nuget (new) behavior:
> dotnet000973\bin\dotnet.exe restore --packages "packages\"
Microsoft .NET Development Utility CoreClr-x64-1.0.0-rc1-16231
...
Restoring packages for E:\temp\toolruntimepublish\tool-runtime\project.json
...
> dotnet001496\bin\dotnet.exe restore --packages "packages\"
log  : Restoring packages for E:\temp\toolruntimepublish\tool-runtime\project.json...
error: Illegal characters in path.
error: Parameter name: path
/cc @ericstj @joperezr
> Remove trailing slash from package directories.

- src/Microsoft.DotNet.Build.Tasks/GenerateAssemblyList.cs
Fix Issue #480 - GenerateAssemblyList task writes to exisiting output file without deleting previous contents.
> Fix issue #480 - GenerateAssemblyList task writes to exisiting output file without deleting previous contents.

- init-tools.cmd
ToolRuntime dir was not being cleaned correctly when a new version of BuildTools was selected. This fixes that issue.
> Fix Issue 474 were ToolRuntime dir wasn't getting deleted

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd
Add Microbuild.Core 0.2.0 package to the build tools bootstrap restore;
this is required for internal builds to consume MicroBuild v2 features.
> Add support for MicroBuild v2.

- dir.props
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
- src/xunit.netcore.extensions/Discoverers/ActiveIssueDiscoverer.cs
- src/xunit.netcore.extensions/Discoverers/PlatformSpecificDiscoverer.cs
- src/xunit.netcore.extensions/PlatformID.cs
- src/xunit.netcore.extensions/XunitConstants.cs
NetBSD support has been added to CoreCLR, CoreRT and CoreFX (native).
In order to proceed with managed code port, buildtools support is
required.
> xplat: Adds NetBSD support

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/FrameworkLists/MonoTouch,Version=v1.0/FrameworkList.xml
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/FrameworkLists/Xamarin.TVOS,Version=v1.0/FrameworkList.xml
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/FrameworkLists/Xamarin.WatchOS,Version=v1.0/FrameworkList.xml
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/FrameworkLists/Xamarin.iOS,Version=v1.0/FrameworkList.xml
- Fix typo in Xamarin TVOS and WatchOS Frameworklist.xml, they still referred to Xamarin.iOS.
- Fix Redist and Name in the Xamarin FrameworkList.xml. Name is supposed to be the display friendly string, but some of the profiles had that one in Redist instead.
/cc @ericstj
> Xamarin FrameworkList.xml fixes

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd
https://github.com/dotnet/buildtools/commit/d852b602fc85b463defafbd6cf2e4ed62cc2c092 removed a leading quote from the emitted project.json content.
/cc @jhendrixMSFT @weshaggard
> Fix typo in init-tools.cmd

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/ApplyBaseLine.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/test/ApplyBaseLineTests.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/test/Microsoft.DotNet.Build.Tasks.Packaging.Tests.csproj
The ApplyBaseLine task was downgrading dependencies. This was an
oversight, I meant for this task to only lift up the dependencies to a
baseline version but didn't implement it that way.
I added some tests (which I should have done initially) to validate this
behavior.
> ApplyBaseLine should not downgrade dependencies

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh
Fixes a break introduced by https://github.com/dotnet/buildtools/commit/d852b602fc85b463defafbd6cf2e4ed62cc2c092
/cc @jhendrixMSFT @iamjasonp
> Add MicroBuild.Core restore to init-tools.sh

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/Extensions.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/GenerateNuSpec.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/Microsoft.DotNet.Build.Tasks.Packaging.csproj
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PromoteReferenceDependencies.cs
Use Exclude:Compile for implementation-only dependencies so that implementation dependencies don't leak to the compiler & folks can't take a dependency on our implementation referencing a particular package.
> Suppress implementation dependencies

- dir.props
- init-tools.cmd
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh
I noticed in CoreCLR that Tools\init-tools is restoring from v2 www.myget.org feeds. This updates that. (Earlier I updated buildtools project restore sources, but didn't change init-tools which ends up in the package.)
> Move init-tools.cmd/sh from v2 www.myget.org feeds to v3 enterprise feeds

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/PackageLibs.targets
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
Cleaning up the feature flags I added for nestandard rename, baselining,
and runtime.json exclusion now that all branches set these flags.
To summarize:
1. Repos no longer need to set UseNetPlatform to false in order to build/validate as `NETStandard` instead of `dotnet`.  `NETStandard` is now the default.  Set UseNetPlatform=true to use `dotnet`.
2. Baselining is now on by default.  To opt out of package baselining folks can set BaseLinePackageDependencies=false.
3. Runtime.jsons will be excluded by default from normal packages.  Only lineup packages (IsLineupPackage=true) or packages explicitly opting in (IncludeRuntimeJson=true) will get runtime.jsons.
> Clean up required flags

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/UpdateBuildValues.targets
Add property GitPushRemote that allows the repository to be specified
when pushing the commit of the automated build value change.
> Remove hard-coded repository for "git push" when updating build values.

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PromoteReferenceDependencies.cs
We were already doing this similar filtering in SplitReferences.
The only package impacted by this change is System.Net.WinHttpHandler.
> Don't promote reference depencies if inbox

- BuildToolsVersion.txt
This should get us unblocked for MicroBuild v2.
> Update build tools to latest version to pick up fixes.

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/baseline.packages.targets
Previously the baseline version for InteropServices was 4.1.0.  The
API surface in 4.1.0 requires a type forward to System.Runtime 4.1.0,
which breaks the baseline.
We were lifting all references of System.Runtime.InteropServices to
4.1.0 and only lifting System.Runtime to 4.0.21, essentially causing a
downgrade warning in all packages that referenced IS.
This lowers the baseline for IS to 4.0.21, which I restored in commit
https://github.com/dotnet/corefx/commit/c402f76ccbb649c6005882f5076dfd45b9251dad
Folks who must reference the latest version still can but we won't
artificially rase the version for folks that don't need to.
> Lower InteropServices baseline version

- src/Microsoft.DotNet.Build.Tasks/UpdatePackageDependencyVersion.cs
- src/Microsoft.DotNet.Build.Tasks/ValidateProjectDependencyVersions.cs
This allows a restore compatibility error workaround needed for https://github.com/dotnet/buildtools/pull/515.
Verified basic use cases manually: updated a version to another version, validated, and upgraded versions that were strings as well as inside objects.
/cc @ericstj
> Allow dependency value to be object with version property instead of only a version string

- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
- src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/xunitrunner-func/xunitrunner-func.py
@jhendrixMSFT , @venkat-raman251 
XUnit and other Helix test execution functionality are now supported parts of the platform in the XUnitExecution() class.  This allows runners to grow and change as much as they'd like, with breaking changes requiring a build tools update which then doesn't become a surprise for users of Helix.
While testing this, due to some changes in the way the .rsp files are set up, I wasn't sure how to get this working for non-Windows systems.  As a result I only tested this on Windows; however the platform-specific differences are small.
> Initial commit of functional test runner

- src/ApiCompat/project.json
- src/GenAPI/project.json
- src/GenFacades/project.json
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.json
- src/Microsoft.DotNet.Build.Tasks/project.json
The auto-upgrade in https://github.com/dotnet/buildtools/pull/515 resulted in some dependencies not existing due to the minor/patch versions changing. Corrected throughout the repository.
/cc @ericstj @stephentoub
> Fix dependency versions after automatic prerelease upgrade

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/depProj.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/sign.targets
By default skip signing when building depproj projects.
Renamed property UseOpenSourceSign to SignType to better align with real
signing requirements.
Disable Authenticode signing when doing OSS signing.
For real-signed builds that don't use the "open" key add build metadata so
the assembly gets a real strong name.
> Fixes to support real-signed builds in CoreFx.

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.json
System.Reflection.Metadata 1.2.0 removed some types from a previous
build.  See https://github.com/dotnet/corefx/commit/7152971f4a940aa897c29fcdbed8934a692a928e.
Roslyn depended on those types.
The rc2-23907 references the stable 1.2.0 build of Metadata (and so does
rc2-23908 and rc2-23909).  The rc2-23910 build of the packages that
comes out tonight will have the fix to reference 1.3.0, but we don't
want to wait for that.  For now reference 1.3.0-rc2-23907 directly.
We can remove the direct reference when we update the baseline,
and in fact should remove lots of these direct references at that point
/cc @dagood @mellinoe
> Update System.Reflection.Metadata to 1.3.0

- dir.props
- publishexe.targets
- src/Microsoft.DotNet.Build.CloudTestTasks/Microsoft.DotNet.Build.CloudTestTasks.csproj
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/Microsoft.DotNet.Build.Tasks.Packaging.csproj
- src/Microsoft.DotNet.Build.Tasks.Packaging/test/Microsoft.DotNet.Build.Tasks.Packaging.Tests.csproj
- src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/sign.targets
- src/xunit.console.netcore/xunit.console.netcore.csproj
In commit eca81d0 I changed how property SkipSigning is evaluated so that
when it's true no signing is performed.  Unfortunately we set this
property in most of the build tools projects and as a result they are no
longer Authenticode signed.  I have removed the SkipSigning property from
the offending projects.
Set the default strong name signing key to the "open" one.
The PublishFilesToRuntime task was running before real signing happens, as
a result we do not sign the renamed binary (e.g. GenAPI.exe ->
GenAPI.dll).  To fix this I sequenced this target after the SignFiles
target which is where the official signing happens.  To ensure this works
for dev builds I stubbed out this target in sign.targets.  It also
required me to re-order the import of the MicroBuild bootstrapper in …
> Fix signing of build tools binaries.

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/CreateTrimDependencyGroups.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/Framework.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PromoteReferenceDependencies.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/test/CreateTrimDependencyGroupsTests.cs
Fixes https://github.com/dotnet/corefx/issues/6813
The CreateTrimDependencyGroups task was incorrectly projecting
implementation dependencies to dependency groups that had a different
implementation assembly.
For example:
NETStandard1.0 implementation dll
NET45 facade dll
We were copying the portable implementation's dependencies into the
facade's dependency group.
This was happening because the task wasn't considering all existing
dependency goups.  Instead it was just considering the placeholder
groups "specially" via the TrimFrameworks parameter.
I removed this parameter and refactored the algorithm a bit to
consider any dependency group, which includes the placeholders
as well as any dependency group created by harvesting the references.
This fixed the projection problem, but now we …
> Fix dependency projection

- build.proj
- publishexe.targets
- src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/sign.targets
- src/Microsoft.DotNet.Build.Tasks/ReadSigningRequired.cs
- src/Microsoft.DotNet.Build.Tasks/SignTypeItem.cs
- src/Microsoft.DotNet.Build.Tasks/WriteSigningRequired.cs
- src/sign.builds
The current signing implementation signs files one by one which is
incredibly slow.  We can get better throughput by submitting all files for
signing in one item group.
If a file requires signing it will create a ".requires_signing" marker
file that will be read during a post build step; this post build step will
process all of the marker files and submit the signing job in one group.
> Move signing to a post-build step so it batch signs.

- build.proj
- src/dirs.proj
- src/packages.builds
Builds packages happens when building src\dirs.proj; this doesn't work
with the recent switch to batch signing as the binaries are now signed
after the packages are created.
Move the package build step into its own project packages.builds file to
be built after signing.
> Split package building into its own step.

- src/GenAPI/GenAPI.csproj
- src/GenAPI/Program.cs
- src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Methods.cs
- src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.cs
- src/Microsoft.Cci.Extensions/Writers/CSharp/CSharpWriter.cs
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/notsupported.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/partialfacades.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/resolveContract.targets
- src/nuget/Microsoft.DotNet.BuildTools.nuspec
This adds infrastructure to buildtools to create NotSupported assemblies.
These assemblies expose API described by the contract and throw PlatformNotSupported from every method.
> Add infrastructure to support IsNotSupportedAssembly 

- src/BuildValues.props
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/CommitBuildValues.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/UpdateBuildValues.targets
- src/packages.builds
In commit e89c9d2 I split packaging into its own build step; this had the
unintended side-effect of causing the automated commit of build numbers to
stop.  To fix this I have moved the automated commit into
CommitBuildValues.targets which is imported by packages.builds causing the
commit to happen post building of packages.
I have also bumped the build number to match the latest built package.
> Split updating and committing of build number into separate files.

- src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Fields.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/GenerateNuSpec.cs
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/notsupported.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/resources.targets
Default dependency groups to "any" to avoid exception in nuget 3.4 update.
Clean up "NotSupported" assembly contents and add a metadata attribute.
> Package fixes

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
The current test targets will always add "-notrait category=outerloop" to the xunit runner, so you can only ever run just innerloop or just outerloop. I added a simple check to the "Outerloop" property before the default notrait is added.
To run innerloop alongside outerloop, just pass "/p:Outerloop=true" to msbuild.
affects https://github.com/dotnet/corefx/issues/1477 and provides a resolution path to https://github.com/dotnet/corefx/issues/1742 pending a corefx PR to modify the properties passed in the coverage build.
@Priya91 @stephentoub
> Add ability to run OuterLoop and InnerLoop tests simultaneously

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/ApiCompat.targets
ApiCompat needed a minor fix that needed to be checked in. The property _PreviousContractVersion was not referenced correctly in a few conditions
> Fixed a property for running ApiCompat on ref assemblies

- src/GenAPI.Desktop/Microsoft.DotNet.BuildTools.GenAPI.targets
- src/GenAPI/Program.cs
CommandLineParser chokes on unix-style paths for positional parameters.
@Priya91 , @ericstj 
After this fix is published to NuGet, we need to update the version grabbed by the tool runtime, and update notsupported.targets slightly (to pass this qualifier).
> Force explicit qualifier usage of required parameter in GenAPI

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/notsupported.targets
Didn't realize that this program was included directly in buildtools. We need this change to use GenAPI.exe, which is already merged.
@Priya91
> Update notsupported.targets to use required qualifier

- dir.props
- dir.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/sign.targets
Removes platform-specific assembly metadata from test-built assemblies and turns off signing them. This allows the .NET Native toolchain to process them correctly.
This is to support dotnet/corefx#6945 
@jhendrixMSFT , @weshaggard
> Remove ".NETFrameworkAssembly", "Serviceable" attributes from Tests

- dir.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.targets
Discussed this with @weshaggard, and made his suggested change.  The previous change to dir.targets was irrelevant as I should have made this change in the CoreFX dir.targets.
Now, this functionality is in Build.Common.targets and only included if IsDotNetFrameworkProductAssembly is explicitly set to true.  This same functionality exists in CoreFX today (sans check for IsTestProject).  
Once this goes in, I have another change ready that would remove the corresponding snippet from CoreFX repo and add IsDotNetFrameworkProductAssembly.
> Fix issues from Pull Request 555

- src/Microsoft.DotNet.Build.Tasks/ValidateProjectDependencyVersions.cs
In order to support easier maintenance of the valid dependency versions, allow the version information to be specified in a text file. This allows automated tools to update the version numbers easier than updating MSBuild files. It also removes having to put regular expressions in MSBuild files (which requires non-trivial work arounds).
@dagood @weshaggard
> Add support for ValidationPatternsFile.

- src/GenFacades/Program.cs
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/partialfacades.targets
Permit different build.revision in facade than contract to enable
https://github.com/dotnet/corefx/issues/7114
> Allow build.revision mismatch in GenFacades

- src/Microsoft.DotNet.Build.Tasks.net45/project.json
- src/Microsoft.DotNet.Build.Tasks/GetTargetOS.cs
- src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
- src/Microsoft.DotNet.Build.Tasks/project.json
fixes #563
cc @stephentoub @weshaggard
> Get runtime OS info to add xunit categories.

- src/nuget/xunit.console.netcore.nuspec
- src/nuget/xunit.netcore.extensions.nuspec
This is needed to ensure that if a dependency is only brought in by
these xunit packages it will support NETStandard (not require import)
and pass guardrails.
/cc @weshaggard @MattGal
> Update xunit netcore pkgs to latest corefx

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/packages.targets
- src/dirs.proj
- src/nuget/xunit.console.netcore.nuspec
- src/nuget/xunit.netcore.extensions.nuspec
XUnit was referencing old versions of packages without support for
latest TFMs.  Now that we don't lift dependencies with the lineup we
need to reference newer packages.
Continuation of https://github.com/dotnet/buildtools/pull/559
> Lifting XUnit's dependencies to latest.

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
- src/Microsoft.DotNet.Build.Tasks/GenerateCurrentVersion.cs
- src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/BuildVersion.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets
CC: @weshaggard ~~The PR is not ready to be merged yet, but I wanted to send this out to you today so that if you have some time to take a look I can get early feedback. I plan to have this ready by tomorrow.~~ <- PR is ready to merge after feedback now.
FYI: @ericstj ~~We are still considering on adding another optional target that will generate a props file in the root of the repo, so that this doesn't need to be calculated over and over, which I know was more or less what you wanted.~~ <- I've changed the behavior now such that we will create a BuildVersion.props file which will contain the Build Version.
I'll send out a [sample corefx PR](https://github.com/dotnet/corefx/pull/6982) soon on how to consume this.
CC: @gkhanna79 
related: dotnet/coreclr#3559 dotnet/coreclr#3133
> Add Versioning control for Repos.

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/baseline.packages.targets
Fix the annoying \r\n from our package descriptions
Update the baseline list.
Don't warn when folks have opted to skip missing files.
Set targetpath so that binclashlogger can catch package bin-clashes.
> Various packaging fixes

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.targets
Change https://github.com/dotnet/buildtools/commit/daac863e9ea367338d6295c42264a58f4eb5bf1e
broke package build.  Two problems: BuildNumberMinor was not defined,
and NuGet didn't like a dash followed by a 2-part version (eg -00001.00)
For now I've changed to use a hyphen instead of a dash.  We may want to
file a bug on NuGet for this.
/cc @joperezr @weshaggard @Priya91
> Fix package versioning break

- dir.props
- src/ApiCompat/project.json
- src/BinaryRewriting/BclRewriter/project.json
- src/GenAPI.Desktop/project.json
- src/GenAPI/project.json
- src/GenFacades.Desktop/project.json
- src/GenFacades/project.json
- src/Microsoft.Cci.Extensions/project.json
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.json
Validate Microsoft.Cci package with the rest of the prerelease packages. Fixes https://github.com/dotnet/buildtools/issues/451.
Also minor fix of changing validation regex to case-insensitive.
/cc @joperezr
> Check Microsoft.Cci dependency version with validation

- src/Microsoft.DotNet.Build.Tasks/GenerateCurrentVersion.cs
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets
VSO cannot pass in the Revision number directly, so with this we are stripping it out from the BuildNumber
> Adding BuildNumber Minor since VSO can't pass in the Revision Number

- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/PublishContent.targets
The build pipeline requires the ability to publish build artifacts to
various endpoints.  This change adds a targets file that will contain
various publishing targets.  At present the only endpoint we need is Azure
blob storage.
> Add targets file to be used for publishing build artifacts.

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/test-runtime/project.json
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
This change is to add the necessary test publishing filters and restore the xunit desktop runner pack to allow compiling and running the tests against the desktop
> Support Desktop test Build and Run

- src/Microsoft.DotNet.Build.CloudTestTasks/GetPerfTestAssemblies.cs
- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
- src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/xunitrunner-perf/csvjsonconvertor.py
- src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/xunitrunner-perf/xunitrunner-perf.py
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/PerfTesting.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/test-runtime/project.json
Changes to allow packaging and running building perf tests for CoreCLR via Helix
•Gathering full paths of test binaries instead of relative paths since we need it to mitigate for perf tests in subdirectories under CoreCLR
•Adding support for different xunit performance versions in xunit perf runner
•Conditional AssemblyList creation and CopyTestToTestDirectory since CoreCLR currently does not support running individual tests in isolation in an automated manner
•Fixing mismatch in xunit performance versions and copying proper execution assemblies for xunit performance
@MattGal @brianrob @lt72 @jhendrixMSFT @rahku
> Adding Perf tests support for CoreCLR

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/Framework.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/GenerateNetStandardSupportTable.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/Microsoft.DotNet.Build.Tasks.Packaging.csproj
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/ValidatePackage.cs
Add functionality to emit some of the results from package validation to
use for generating documentation.
I'm not currently using the emitted AllSupportedFrameworks items but we
could use this in the future to append a list of supported frameworks to
the package description.  Folks have various opinions about what is the
right amount of data to show here, until we have some concensus I'm
going to avoid shoving more data into the publicly facing package
description.
I'll follow up to a pointer of the CoreFx change that consumes this.
> Add validation report and doc generation task.

- src/Microsoft.DotNet.CodeAnalysis/PackageFiles/codeAnalysis.targets
- src/nuget/Microsoft.DotNet.BuildTools.nuspec
There were a couple of issues with the way analyzers were enabled:
- The net core version of the analyzer was placed in the root of the Tools directory. This meant that it became part of the TPA (Trusted Platform Assemblies) list when the net core compiler was run with corerun. 
- This lead to a very mysterious issue where the runtime complained that it could not load the analyzer file because it could not find its dependencies.
- In reality, this was caused by the fact that the assembly was part of the TPA list and the way the Roslyn compiler loads assemblies.
- **Fix: Move the analyzer in a separate folder under Tools to prevent it from showing up in the TPA list.**
- The property that was used to decide the path where the assembly should be loaded from was `$(BuildToolsTaskDir)`
- This …
> Make sure code analyzers can be correctly loaded on all supported platforms.

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.targets
- src/Microsoft.DotNet.CodeAnalysis/PackageFiles/Microsoft.DotNet.CodeAnalysis.ruleset
- src/Microsoft.DotNet.CodeAnalysis/PackageFiles/codeAnalysis.targets
By default, all analyzers are going to be enabled and their default level (error, warning) will be specified by each analyzer as it sees fit.
If you need to change the default behavior at the repo level, you can update the Microsoft.DotNet.CodeAnalysis.ruleset file and modify the level as needed.
If individual projects need to change the defaults for analyzers they can do so in their own ruleset file.
Each project can also import the common ruleset file.
/cc @pallavit @joperezr @weshaggard
> Create a common ruleset to be used at a repo level for changing analyzer behavior

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/NuGetPack.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/PackageLibs.targets
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
Symbol packages include pdb files for each dll and any source files inside the project root that are referenced in `<Compile>` items. The nuspec contains all these files and the `NuGetPack` task filters using the same logic as the `nuget pack` command.
This is enabled by default in corefx and wcf but will require a change in TFS to turn on (and a change to add a placeholder to a manually-created nuspec that has symbols but no source.)
Tested successfully on Windows with corefx, wcf, and TFS.
On OSX with corefx no symbol packages are created, presumably because the source file paths aren't handled correctly. Looking into it. I might create an issue and get to it later because getting symbols published from TFS to MyGet seems like the higher priority.
For an example of source and symbol …
> Add symbol package creation

- src/Microsoft.DotNet.CodeAnalysis/PackageFiles/codeAnalysis.targets
When enabling the analyzers I missed a condition that would not overwrite the CodeAnalysisRuleset if the analyzers were not enabled.
> We should only overwrite the CodeAnalysisRuleSet property if the analyzers are enabled

- src/Microsoft.DotNet.Build.CloudTestTasks.net45/project.json
- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
This is to update the checks on the properties passed in to allow builds to be marked as "official".
@ChadNedzlek
> Modify checks for IsOfficial CloudTest build

- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
Recent changes made it so that non-platform specific tests build into an AnyOS folder.  Switch to using this.  
@jhendrixMSFT  @tarekgh @sokket 
Needs perf once-over from @dsgouda .
> Bring in AnyOS as well as platform specific paths in test discovery 

- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets
This change enable running the test against the desktop on Helix. the change add missed entries in the file assemblylist.txt so Helix can restore the right list of assemblies. also it add the needed parameters for the test runner command to enable the desktop
> Support running test against desktop on Helix

- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
Changes to support picking up test archives from the Unix.* folder if the target platform supports Unix.  This includes OSX and all flavors of Linux.
@jhendrixMSFT  @sokket @joshfree 
For Helix folks:
OSX run id: 540452dd-bf28-46fe-be14-86b4b9320f74 
Ubuntu Run id: 314b42dd-0514-4b33-b420-90165c905dfa
> Add Unix to folders to search for test archives

- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
FilterToTargetGroup is the property we'll use to filter on TargetGroup. for the desktop we'll have FilterToTargetGroup=net46
> Use TagetGroup Filtering property instead of TargetGroup

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/NuGetPack.cs
Not making a symbol package is relatively normal, and the warnings were noisy. Changing them to high-importance messages still lets us track the cause of a missing symbol package.
> Change "not creating symbol package" from warning to message

- src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/xunitrunner-perf/xunitrunner-perf.py
CscBench.csproj perf test in CoreCLR needs CORE_ROOT to be set for execution, setting this so we run the test correctly
@brianrob @MattGal
> Setting CORE_RUN for perf tests

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets
This target generates a version source file which contains one line like:
```c
static char sccsid[] __attribute__((used)) = "@(#)Version 1.0.12345.0";
```
When adding this source file to any compilation, we will be able to get the version of native binaries built in non-Windows platforms by using either `what(1)` or `strings+grep`
related: dotnet/coreclr#3133
cc: @ellismg @weshaggard 
FYI: @gkhanna79
> Adding target that generates version.c

- src/xunit.netcore.extensions/Attributes/ConditionalFactAttribute.cs
- src/xunit.netcore.extensions/Attributes/ConditionalTheoryAttribute.cs
- src/xunit.netcore.extensions/Discoverers/ConditionalFactDiscoverer.cs
- src/xunit.netcore.extensions/Discoverers/ConditionalTestDiscoverer.cs
- src/xunit.netcore.extensions/Discoverers/ConditionalTheoryDiscoverer.cs
- src/xunit.netcore.extensions/xunit.netcore.extensions.csproj
Modifies [ConditionalFact] and [ConditionalTheory] attributes to accept
a variable number of condition member names.
Modifies ConditionalFactDiscoverer and ConditionalTheoryDiscoverer to
evaluate all of the conditions in the attributes.  Conditions are
logically "and'ed", so any condition returning false marks the test
to be skipped.
Existing tests using [ConditionalFact] or [ConditionalTheory] do not
need to be modified.  The only behavioral change is the phrasing of
the skip message which now begins "Conditions not met:..."
Fixes #610
> Support multiple conditions in [ConditionalFact] and [ConditionalTheory]

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/NuGetPack.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
Adds `AdditionalLibPackageExcludes` and `AdditionalSymbolPackageExcludes` that let packaging projects configure what belongs in their symbol packages. For example, an OSX native symbol project would add `**/*.dwarf` (escaped to `%2A%2A\%2A.dwarf` in MSBuild) to `AdditionalLibPackageExcludes`.
Also brings in an xplat path separator fix from NuGet's `_libPackageExcludes` and `_symbolPackageExcludes`.
/cc @weshaggard @ericstj @mikem8361
> Add customizability to symbol packages

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/GenerateRuntimeDependencies.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/GetMinimumNETStandard.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/Microsoft.DotNet.Build.Tasks.Packaging.csproj
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/SplitDependenciesBySupport.cs
This PR does the following:
- Fix perf for building package project references to use all cores
- Preserve supports section in runtime.json (a bug I noticed when examining the generated runtime.json)
- Feature for splitting pkgproj dependencies by minimum netstandard version, needed to fix https://github.com/dotnet/corefx/issues/6561.
For the last feature I initially coded it to use the validation report but this created unnecessary complexity and sequencing restrictions, so I changed to plumb it through as meta-data on the resolved pkgproj reference.
> Packaging fixes/features for open meta-packages

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
Working around the issue in .Net Core MSBuild Exec task where the return code is not processed correctly. This will basically check if there were any failures in the run, and if so, then it will fail the exec call.
related: dotnet/corefx#7362 , microsoft/msbuild#566
FYI: @mellinoe
> Work around to MSBuild issue were Exec task doesn't read exit code correctly

- src/Microsoft.DotNet.Build.Tasks/ExceptionFromResource.cs
- src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj
- src/Microsoft.DotNet.Build.Tasks/NuGetPackageObject.cs
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/depProj.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/packageresolve.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
- src/Microsoft.DotNet.Build.Tasks/Preprocessor.cs
- src/Microsoft.DotNet.Build.Tasks/PrereleaseResolveNuGetPackageAssets.cs
- src/Microsoft.DotNet.Build.Tasks/Strings.Designer.cs
- src/Microsoft.DotNet.Build.Tasks/Strings.resx
- src/Microsoft.DotNet.Build.Tasks/ValidateProjectDependencyVersions.cs
This updates the fork we have of PrereleaseResolveNugetPackageAssets in order to support the use of project references in dependencies. This will allow us to reference the test-runtime project in corefx from the dependencies of each test project. This will allow nuget to do proper resolution of the combined set of dependencies, which is an improvement over the error-prone way we are currently combining the two. It will also allow us to more easily reference a different test-runtime, for example.
Includes the following changes:
* Updated fork of Nuget code. This is mostly verbatim from the nuget sources, but does include some changes to maintain compatibility with our build system. Long-term we need to move off of having a fork of this code.
* Update ValidateProjectDependencyVersions to …
> Update PrereleaseResolveNugetPackageAssets to support project references, use project reference for test-runtime

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets
When adding native versioning to Windows binaries, a few warnings were introduced because some of the variables that we define in version.h were previously defined by a macro. To fix this, we should ensure that we first undefine the variables before assigning the values to them.
FYI: @BruceForstall @AndyAyersMS 
related: dotnet/coreclr#4208
> Fixing warnings that were introduced in coreclr

- src/Microsoft.DotNet.Build.Tasks/AddDependenciesToProjectJson.cs
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/buildagainstpackages.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/packageresolve.targets
Enable project reference to package conversion for test builds
- support multiple dependencies sections in project.json
- support multiple frameworks passed as target groups
- flow target group to generation
- Propagate OSGroup and TargetGroup for creating per config project.json files.  OSGroup
project.json's are typically identical but we generate separate json's to prevent a 
"binclash" scenario
> Fixes for project reference to package dependency conversion in test builds

- src/Microsoft.DotNet.Build.Tasks/AddDependenciesToProjectJson.cs
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/buildagainstpackages.targets
- src/Microsoft.DotNet.Build.Tasks/ParsePackageNames.cs
- Move _BuildAgainstPackages property into buildtools common targets
- Project Reference to package dependency fixes
- Use ParsePackageNames task to determine assembly version (I know this is "bad" and is on 
the list of things to fix)
- A couple of tasks were eliminated in favor of the ParsePackageNames before previous PR's 
were merged, one fallout was that determining a version number broke because it wasn't 
updated correctly to use the ParsePackageNames task
- PackageNameRegEx explicitly looks for the "buildnumber-buildminor" instead of just grabbing 
the rest of the package name as the Prerelease version because I noticed a bug in some of 
the packages being produced on xplatforms where the package names 
where "buildnumber.buildminor" instead of "-"
- Move RegEx up to the top of …
> Project Reference to package dependency conversion fixes for corefx and build pipeline

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets
Fixing issue where sometimes the package name will have a '.' in the name instead of a '-'
cc: @jhendrixMSFT @maririos @chcosta
> Fix small versioning issue on packages name

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/GetAssemblyReferences.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/Microsoft.DotNet.Build.Tasks.Packaging.csproj
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/baseline.packages.targets
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/native.library.packages.targets
Currently we don't automatically harvest package dependencies for
private packages.  Instead we exclude them completely.
This change adds harvesting for private packages, including those that
come from native dependencies.
Corresponding changes to
CoreFx: https://github.com/ericstj/corefx/commit/b76ac1c538506a41719a13bcb5ff38e3b28e5247
WCF: https://github.com/ericstj/wcf/commit/6f1b85067628c37439cccbf4ff98480bc13f4de0
> Harvest private package dependencies

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/IL.targets
ilasm.exe is not on PATH by default. I'm making it conditional on
BuildingInsideVisualStudio because the way to get to it is very
Windows-specific - this still gives ILPROJ files a chance to build on
Unix.
> Allow building ILPROJ files from within Visual Studio

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/CodeCoverage.targets
Fixes https://github.com/dotnet/buildtools/issues/637
cc: @mmitche
> Filter out xunit assemblies from code coverage

- src/Microsoft.DotNet.Build.CloudTestTasks/GetPerfTestAssemblies.cs
- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
Fix issue reported by @dsgouda . @lt72  as FYI.
There were two bugs here:
- The build task that discovers whether tests are perf tests doesn't do duplicate checking... added a Distinct() call to fix that.
- The .targets file section that brings in perf tests could not have worked for > 1 output directory due to trying to resolve just the name of every perf test found without checking for the existence of the archives.
Note that in CoreFX, System.Globalization.Calendars.Tests.zip and System.Globalization.Tests.zip currently will still cause duplication specifically because they literally do build both for AnyOS and WIndows_NT builds.  However, there also really are two test archives.
> Fix discovery logic in perf tests

- dir.props
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/Microsoft.DotNet.Build.Tasks.Packaging.csproj
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
Per previous PR feedback softening the baseline error messages.
Also fixing an old bug where we were missing the runtime.json from buildtools.  I also added a condition to search for it in the repo in order to help us remove some repo-configuration from corefx.
> Make baseline errors less aggressive & include RID graph

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/sign.targets
To run the desktop test we need to have the test assembly get signed with the test.snk. Currently we have some workaround in some of the test projects to disable the delay signing. The change here is to centerline this in the tools and avoid duplicating the workaround in every test project
https://github.com/dotnet/buildtools/issues/596
> Disable delay signing for Desktop tests

- src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj
- src/Microsoft.DotNet.Build.Tasks/ValidateExactRestore.cs
- src/Microsoft.DotNet.Build.Tasks/VisitProjectDependencies.cs
Examines lockfiles to make sure all dependencies were found and restored correctly.
When a `project.json` specifies a version of a package that doesn't exist, NuGet tries to find a best match. In our case, we want an error when this happens because it can cause a bunch of problems:
1. The build isn't repeatable. If these fuzzy-matched dependencies are used, the build depends on which packages are available on the feed which may change at any time. (Similar to `*` dependencies.)
1. Restore is slowed. Now that NuGet depends on the feed state, it needs to fetch a list of versions from the feed every restore.
1. NuGet can encounter corrupted files that otherwise would be ignored, like in https://github.com/dotnet/corefx/issues/7902.
1. The wrong packages sometimes break builds.
This would …
> Add lockfile validation for exact nuget restores

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/FrameworkTargeting.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/IL.targets
This is a few small changes to enable building "ilproj" files as a regular participant in the build. This just imports the existing targets file if the file's extension is detected as ".ilproj". This will be used to build the `System.Unsafe` library in corefx (https://github.com/mellinoe/corefx/tree/system.unsafe).
There is also a minor modification to the calling syntax for ilasm so that it will work with the x-plat version of ilasm. "Forward-slash syntax" doesn't work in the x-plat version of ilasm. Currently it seems like the nuget packages for ilasm are broken, though, so I have not been able to incorporate it into the tool runtime yet. I have done manual testing of the scenario.
* Import IL.targets if the project extension is ".ilproj"
* Use hyphen syntax for ilasm flags, the …
> Hook .ilproj files into the build

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
We were not running ExpandProjectReferences during GetPackageIdentity
evaluation if the Version was explicitly set by the project.  The result
was a race condition when calculating NETStandard version.  If the
pkgproj had previously built it would have gotten the correct version,
if not it would have gotten the default: NETStandard1.0.
This was causing https://github.com/dotnet/corefx/issues/7881.
I've cleaned up a bit of the target sequence to make it clearer when
thing run.
> Fix calculation of NETStandard min version

- src/Microsoft.Cci.Extensions/project.json
We use this library in tools that run on desktop.  As such it needs to
be built as a PCL.
/cc @mellinoe @weshaggard
> MS.CCI.Extensions needs to support desktop

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh
Given that you can set your packages dir, our script had a bug in the case where the packages dir is in a different drive, since we used 'cd'. 
cc: @weshaggard @dagood
> Fixing issue of relying on 'cd'

- src/Microsoft.DotNet.Build.Tasks/UpdatePackageDependencyVersion.cs
In corefx this fixes references to 'test-runtime' and 'net46-test-runtime', which don't have `version` values.
I only noticed this now because `UpdatePackageDependencyVersion` is the easiest way to fix incorrect package versions when a prerelease upgrade doesn't account for the major, minor, or patch version changing, and I tried out this flow when preparing the corefx lockfile validation PR.
> Fix UpdatePackageDependencyVersion: shouldn't require a version on all dependencies

- src/Microsoft.Cci.Extensions/Microsoft.Cci.Extensions.csproj
I missed this when I made https://github.com/dotnet/buildtools/commit/911c044a01f4ae23d4092206326007a5edb61b54.
/cc @weshaggard @mellinoe
> Update NuGetTargetMoniker in CCI.Ext fix warning

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh
Looks like `set -x` and `set +x` don't exactly work as using `echo on/off` on Windows, since even if you are redirecting the output to a file, it would still get printed in the standard output. Rolling back to have the echos for now, until we have a better solution for that.
cc: @dagood
> Rolling back the change where I added 'set -x' since it doesnt work as expected

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh
Previously we had a nested 'packages' dir inside the BuildTools package, which made paths of the restored packages to be super long. This PR will use the original packages dir instead.
Note: this doesn't require the packages dir to be passed in from the consumer's init-tools, but if it is not passed, we will assume that the packages dir is `{repoRoot}/packages`
fixes: #632
> Fixing long paths in some packages due to the restore location

- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/PublishContent.targets
- src/Microsoft.DotNet.Build.Tasks/GenerateCurrentVersion.cs
Allows buildId in the form "[build number major]-[revision]".  Azure container names only permit letters (lower-case), numbers, and hyphens (non-consecutive).  This change allows us to specify an OfficialBuildId in an Azure container name conformant format.
<s>Also, minor fix to PublishContent.targets to set the token expiration to 1 day.  We aren't currently using these tokens anywhere (or even retrieving them), but a token expiration of 0 causes a warning in the build.</s>
/cc @weshaggard , @joperezr , @jhendrixMSFT , @maririos
> Support OfficialBuildId with '-' 

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/PackageLibs.targets
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/ValidatePackage.cs
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.props
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/ReferenceAssemblies.props
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/ReferenceAssemblies.targets
Desktop projects by default use packages.config, we shouldn't require
folks to use project.json + RID if we don't actually depend on RID
selection as is the case for most desktop packages.
We should make sure that project types that can use packages.config
are supported by our packages.  I've added empty RID entires to the
DefaultValidateFramework list for all of these frameworks.
I'm also addressing a problem where we might get a different asset when
someone uses a RID over not having a RID: eg the package has lib/net45
asset that is different from its runtimes/win/lib/netstandard1.1 asset.
To catch this case I added a check that tries to see if there is a
better matching asset by framework for any runtime asset.
This caught a number of cases where we were making this mistake for …
> Ensure Desktop assets work with packages.config

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets
When we added versioning to native components to coreclr repo, we broke the File Description of the assemblies when they had one defined. This changes will only force the versions to be changed, everything else will stay the same if it is already defined.
Once this is merged and consumed by coreclr, it will fix dotnet/coreclr#4367
FYI: @AndyAyersMS @mikedn
> Fixing issues in version.h that were causing file description changes.

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/FrameworkTargeting.targets
coreclr repo has their own IL.targets which are similar to the ones we have in buildtools except they have additional flags they use to build. For now, We are just conditioning the import of the buildtools il.targets with this PR, and eventually we will merge the coreclr and buildtools version of them to only have one targets file.
cc: @mellinoe 
related: dotnet/coreclr#4598
> Conditioning import of IL Targets as a temp workaround to allow coreclr onboard the new buildtools

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Generations.json
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/PackageLibs.targets
- src/Microsoft.DotNet.Build.Tasks.Packaging/test/GenerationsTests.cs
Remove UsePackageTargetRuntimeDefaults since it is no longer used and replaced with OSGroup > PackageTargetRuntime mapping.
Remove System.Numerics.Vectors from generations as part of https://github.com/dotnet/corefx/issues/5900
/cc @chcosta @weshaggard
> Packaging cleanup

- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
When xunit runner does shadow copy for used assemblies it causes a problem when running agaist the desktop. the framework will disallow loading our assemblies which is open source signed.
we pass -noshadow to xunit runner to avoid such issues
> Avoid having xunit runner do shadow copy

- src/Microsoft.DotNet.Build.CloudTestTasks/UploadToAzure.cs
The task UploadToAzure was always returning true even if there were failures in the execution.
With this change we validate that if an exception happened we are returning false. 
cc: @karajas @chcosta @jhendrixMSFT
> Fix to UploadToAzure to return false when something fail

- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets
Some tests build for multiple target groups; in these cases include the
target group in the archive directory to avoid collisions.
> Include TargetGroup in the test archive directory as required.

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/scripts/docker/cleanup-docker.sh
Cleanup script removes all containers and images from a VM using docker.
It would be nice to have more fine grained control over what is removed, but having a cleanup script available from BuildTools puts us in a much better place for having clean build machines in our build lab which aren't running out of disk space issues due to docker images / containers lingering.
It would also be nice if this functionality was a part of clean.sh, but I'm not really certain how it would fit into the flow seamlessly (perhaps checking for 'docker' and then running the script if docker is installed).  We wouldn't want this to be a default as it could be extremely disruptive to have all of a devs images / containers disappear.
/cc @weshaggard , @jhendrixMSFT
> Add docker cleanup script

- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
with Azure Container Name requirements and the rest of the container name is sufficient to uniquely identity a container.
/cc @MattGal @karajas @jhendrixMSFT
> Remove TargetOS from ContainerName since it is not always compliant 

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/resources.targets
Doing so prevents tools such as ReSharper from trying to analyze files that are not valid if we do not met the condition.
> Hides non-compiled entries from VisualStudio

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh
turns out we were not caching the exit codes when calling dotnet cli for restore or publish commands, so if they failed we were not returning the failure, which in some cases makes the user think that init tools succeeded even though it didin't.
This, plus a change in the consumer's init-tools script to read the exit code of this scripts, will hopefully make errors more clear.
fixes: #473
> Capture exit codes, and set the exit code correctly

- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
This allows differentiating between different target OS'es.  Previously TargetOS was used, but now that we need this value to be set properly and since when set properly it can be the same across different OS'es (I.e. all Windows SKUs get Windows_NT) we need a mechanism to keep the containers separate.
> AddCloudTestContainerSuffix, new optionally property for container name

- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
chmod +777 does not work on OSX, but +x works fine in both *Nix and OSX
> Fix chmod on OSX

- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.Perf.targets
- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
- src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/xunitrunner-perf/ubuntu-dotnet-local-install.sh
- src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/xunitrunner-perf/xunitrunner-perf.py
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/PerfTesting.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/test-runtime/project.json
•Modifying python commands to run for Linux runs
•Modifying xunit perf runner to set up execution environment for running perf tests
•Modifying test runtime dependencies to restore the cli version of xunit perf runner for Linux
•Installing dotnet cli per correlation id (by referring to version number specified under xunit performance repo) 
P.S.: xunit perffornance package version 0032 is yet to be published
@lt72 @MattGal
>  Adding linux support for perf tests  

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
This is needed for stress runs as we run an xunit shim assembly in lieu of the assembly we are actually building.  So we need a way of replacing the assembly argument passed to xunit without overriding the well known property TargetFileName which has other consumers.
@MattGal for further review and context.
> Updating test.targets to make the xunit test assembly configurable

- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
- src/Microsoft.DotNet.Build.Tasks/GenerateAssemblyList.cs
- src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
- src/Microsoft.DotNet.Build.Tasks/ZipFileCreateFromDependencyLists.cs
First draft of writing dependency lists to disk during build, and only including these files in the resulting zip archive.  This results in a drop in packed size from ~300 MB to ~18 MB, and a drop in unpacked sized from ~1.5 GB to ~46 MB.
(Note whitespace changes in CloudTest.targets are just VS automated formatting)
@weshaggard @Petermarcu
> Change .NET Helix packaging to zip up only needed files

- src/Microsoft.DotNet.Build.CloudTestTasks/CreateAzureContainer.cs
- src/Microsoft.DotNet.Build.CloudTestTasks/DownloadFromAzure.cs
- src/Microsoft.DotNet.Build.CloudTestTasks/ListAzureContainers.cs
- src/Microsoft.DotNet.Build.CloudTestTasks/SendToEventHub.cs
- src/Microsoft.DotNet.Build.CloudTestTasks/UploadClient.cs
- src/Microsoft.DotNet.Build.CloudTestTasks/UploadToAzure.cs
Some tasks don't check the HTTP status code for success, as a result they
report success even though they failed.  This change adds status code
checks as required to ensure that tasks report the correct result.  Also
included is some light clean-up.
> Fix false positives in cloud tasks.

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
NuGet is adding support for NETStandard to 2.12.  As such we can make
our packages depend on this version as the minimum.  Unfortunately there
is no way to express 2.12 <= version < 3.0 || 3.4 <= version, so I added
a note to the package descriptions that says we require 3.4 when using
NuGet 3.x.
> Change NuGet MinClient version to 2.12

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
We can hit file lock issues if a test library is built targeting multiple TargetGroups because the dependencylist.txt file was not unique per targetgroup.  This change fixes the condition by adding the targetgroup to the dependencylist.txt path name.
/cc @MattGal @jhendrixMSFT
> Fix race condition in dependencylist.txt

- src/Microsoft.DotNet.Build.CloudTestTasks/AzureHelper.cs
Fix for errors introduced in #714 . There was a failure during upload due to the use of encoded url parameters instead of decoded ones during the construction of the string to sign for authorization.
/cc @schaabs @jhendrixMSFT
> Fix for incorrect auth signing using encoded url parameters

- src/Microsoft.DotNet.Build.CloudTestTasks/AzureHelper.cs
- src/Microsoft.DotNet.Build.CloudTestTasks/CreateAzureContainer.cs
- src/Microsoft.DotNet.Build.CloudTestTasks/DownloadFromAzure.cs
- src/Microsoft.DotNet.Build.CloudTestTasks/ListAzureContainers.cs
- src/Microsoft.DotNet.Build.CloudTestTasks/SendToEventHub.cs
- src/Microsoft.DotNet.Build.CloudTestTasks/UploadClient.cs
- src/Microsoft.DotNet.Build.CloudTestTasks/UploadToAzure.cs
Sometimes the REST APIs fail due to transient issues.  I've added some
retry logic, the same that we use in Helix.
> Add retry logic to Azure REST calls.

- src/common/CommandLine.cs
When tools need to parse arguments for other platforms (i.e. Linux/OSX)
they have files that begin with "/" and that messes up the parser and
causes an "undefined qualifer" error. The best way to handle this is
to disable the uses of slash for qualifiers by default. People can still
manually enable it if they chose to want to support it but for most
of our tools that are now running x-plat we need to disable this and
only support dash for qualifiers.
cc @stephentoub @ellismg
> Change default to not use slash for qualifiers

- src/Microsoft.DotNet.Build.CloudTestTasks/CreateAzureContainer.cs
- src/Microsoft.DotNet.Build.CloudTestTasks/DownloadFromAzure.cs
- src/Microsoft.DotNet.Build.CloudTestTasks/ListAzureContainers.cs
- src/Microsoft.DotNet.Build.CloudTestTasks/UploadClient.cs
- src/Microsoft.DotNet.Build.CloudTestTasks/UploadToAzure.cs
The lambda to create HttpRequestMessage was incorrectly capturing a local
variable for DataTime instead of reading the current DateTime when
creating a new request; this lead to reusing the old DateTime causing the
value to be stale thus failing retries.
> Azure retry logic incorrectly using stale DateTime in HTTP header.

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/PerfTesting.targets
The fix that reverts the assembly list workflow does not copy xunit performance executables for desktop which is not generated as a part of the assembly list
Packaging these as supplemental payloads instead.
@lt72 @MattGal
> Copying xunit performance executables as supplemental payload

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets
#694 changed the location of where _version.h file is dropped by default to be BaseIntermediateOutputPath instead of IntermediateOutputPath, so we also need to update the NativeResourceCompile to also include this folder in the include path.
> Add bin/obj dir to the include folders for NativeResourceCompile

- src/Microsoft.DotNet.Build.CloudTestTasks/UploadToAzure.cs
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
Introduced property MaxClients which is used to throttle the number of UploadClients which will be used concurrently to upload blobs
> Fix for OOM in UploadToAzure when a large number of items are specified

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/GenerateNetStandardSupportTable.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/Generations.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/Microsoft.DotNet.Build.Tasks.Packaging.csproj
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageItem.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/ValidatePackage.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/ValidationReport.cs
Please review commits individually.
Fail on error.  Previously we'd miss package breaks during CI because we didn't halt the build.  This change ensures that the build will fail.
Refactor validation report: serialize the object graph rather than manually writing JSON.  Also save off the asset resolution info.
Refactor build sequence & rearrange targets.  I needed this to prepare for the last change, but it is split up to show a cleaner diff.  I've confirmed that this change produces no diff in nuspecs.
Automatically reference RID-graph and lineup.  Previously we required an external reference to these packages so folks building stand-alone/ala'carte apps needed to know that they had to reference them.  This adds the reference automatically.
/cc @weshaggard @mellinoe @chcosta
> Packaging fixes

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets
cc: @gkhanna79 @markwilkie @jhendrixMSFT 
version.c will look something like this:
```c
static char sccsid[] __attribute__((used)) = "@(#)Version 1.0.24117.0 built by: joperezr-MyMachine. Commit Hash: 1d963d41e5b56623ff054b567ec85a650f581275";
```
I'm open to suggestions on the string format.
> Adding Commit hash for native binaries

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/GetApplicableAssetsFromPackages.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/Microsoft.DotNet.Build.Tasks.Packaging.csproj
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/NuGetAssetResolver.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/PackageLibs.targets
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageItem.cs
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/FrameworkTargeting.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/packageresolve.targets
Support P2P reference from test to PkgProj.
This adds support for CSProj referencing PkgProj.  I chose a basic way to plug in the resolve task.  Depending on how we decide to deal with publishing for different TestFrameworks/Runtimes we might want to change how this plugs in.
/cc @weshaggard @karajas @tarekgh @MattGal @mellinoe 
PS: will rebase/squash before comitting.
> PkgProj test reference

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.json
I missed this runtime dependency with my last merge, and due to it the xplat build won't work when upgrading buildtools. With this change that adds it, building xplat should work now.
> Add missing dependency of System.Runtime.Serialization.Primitives required for xplat builds

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
* In Packaging.targets, allow the AsFrameworkReference metadata on InboxOntargetFramework item to contain a list of assemblies which should be automatically referenced on the given framework.
This augments the already existing use of AsFrameworkReference. Currently, if you set that to "true", a FrameworkReference item will be added with the same name as the package. Now, you can specify a list of assembly names to include in the FrameworkReference ItemGroup. This will let us solve https://github.com/dotnet/corefx/issues/5952 without a lot of pkgproj churn.
@ericstj
> Allow FrameworkReference metadata on InboxOnTargetFramework 

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/buildagainstpackages.targets
Permit additional release values in version structure Regex.
BuildNumberOverrideStructureRegex and VersionStructureRegEx are now nearly identical and these should be collapsed into one regex in an additional cleanup PR (not part of this PR).
/cc @jhendrixMSFT @weshaggard
> Relax version structure Regex

- src/Microsoft.DotNet.Build.CloudTestTasks/SendToHelix.cs
The SendToHelix task has retry logic but it doesn't sleep between
iterations; as a result the retries fail.  I've added a delay between
iterations that scales based on the iteration number.
> Add a delay when retrying in SendToHelix task.

- init-tools.cmd
Downloading from Azure can transiently fail for a number of reasons.  Add
some retry logic when downloading to avoid transient failures.
> Add retry logic when downloading the CLI from Azure blob storage.

- src/Microsoft.DotNet.Build.Tasks/AddDependenciesToProjectJson.cs
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/buildagainstpackages.targets
This is an interim change while we sort out inter-dependency versioning.
This change allows us to specify package versions for packages not built in the current repo, and then use those package versions when generating a new project.json during the test library build when we are adding a new package dependency into a framework.  ie, Supersede package versions we find in a PackagesDrop with those specified in ExternalPackages ITaskItem.  
I don't expect this to be how we ultimately handle these external packages (though perhaps some form of this will be involved), but this will unblock the corefx repo for Helix failures where it is trying to use the latest build of System.IO.Compression from the CoreFx repo instead of the publically published version which has stable bits.
There is a small …
> Add support for external package dependencies with fixed versions

- src/Microsoft.DotNet.Build.Tasks.Packaging/test/CreateTrimDependencyGroupsTests.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/test/EnsureOOBFrameworkTests.cs
- src/Microsoft.DotNet.Build.Tasks/AddDependenciesToProjectJson.cs
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/FrameworkTargeting.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/codeOptimization.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/test-runtime/project.json
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
- src/Microsoft.DotNet.CodeAnalysis/Microsoft.DotNet.CodeAnalysis.csproj
- src/Microsoft.DotNet.CodeAnalysis/project.json
- src/nuget/xunit.console.netcore.nuspec
- src/nuget/xunit.netcore.extensions.nuspec
This switches the default framework and the test framework from
DNXCore50 to netcoreapp1.0.  I've also taken the opportunity to clean
up all non-essential refs to DNXCore50, DNXCore, and DNX.
The only remaining references to these deprecated monikers are:
1. Import statements: needed until all packages are updated.
2. Microsoft.DotNet.Build.Tasks.Packaging.Tests: needed until we can
update the version of BuildTools used by BuildTools to get this change.
/cc @weshaggard @karajas @MattGal @joshfree
> Switch test framework to netcoreapp1.0

- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
- src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/xunitrunner-perf/ubuntu-dotnet-local-install.sh
- src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/xunitrunner-perf/xunitrunner-perf.py
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/PerfTesting.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/test-runtime/project.json
- Installing a local copy of dotnet cli compatible with the xunit cli tools and running perf tests on linux machine after build targets
- Generating a csv along with html report since this allows us to view results on internal apps
@lt72 @MattGal
> Enabling local execution of Perf tests on linux

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
Conditionally include perf targets since otherwise we would end up running perf tests by default.
Some perf tests take a long time to finish and this affects the CI for build tools dependent repos
@MattGal
> Conditional include for perf targets

- src/Microsoft.DotNet.Build.Tasks/AddDependenciesToProjectJson.cs
The ExternalPackages property is optional, so check for null first.
> Handle case when ExternalPackages is null.

- src/Microsoft.DotNet.Build.Tasks/AddDependenciesToProjectJson.cs
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/buildagainstpackages.targets
We have a situation where new RIDs have been added to the product but we
don't yet have the actual packages; as a result the test build fails when
buliding against packages as it can't resolve these runtime packages.  To
work around this I have added an optional property to filter out RIDs when
generating the test project.json files.
> Add the ability to filter out RIDs when building tests against packages.

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets
As part of the universal runner work, BUILDTOOLS_OVERRIDE_RUNTIME no
longer would copy content from the folder into the test folder (however
the generated RunTests.cmd/sh file would correctly not try to deploy the
items from pacakges)
> Fix BUILDTOOLS_OVERRIDE_RUNTIME for tests

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh
I broke building on RHEL with my previous change to simplify the publishing RID, since we don't explicitly list rhel.7.2-x64 in our `tool-runtime.json`.
This change forces us to `rhel.7-x64` as the rid to restore on RHEL. The other supported distros don't bump `$VERSION_ID` for minor releases.
> Always use 'rhel.7-x64' as the RHEL 7 publish RID

- src/xunit.netcore.extensions/XunitConstants.cs
We'll use this in CoreFX to mark tests which require an elevated
context to run (e.g root or Administrator). Previously we conflated
this with OuterLoop.
> Add RequiresElevation constant

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
Permit repos to define their own ReleaseNotes and Project URLs.
/cc @weshaggard @joshfree
> Allow ReleaseNotes and ProjectUrl to be set

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/PerfTesting.targets
When building on windows build machine and targeting linux, build tools tries to install dotnet cli on windows, disabling this since we don't want to run linux tests locally on a windows machine and we don't want linux commands to be executed on a windows machine
@jhendrixMSFT @MattGal @lt72
> Disabling dotnet installation on non-unix build machines

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/RunnerTemplate.Windows.txt
Fix for https://github.com/dotnet/corefx/issues/8634 from @krwq .  Also adding @weshaggard  to comment.
If mklink fails, it will now fall back to copying the files (and logs that it did so).   I explored doing this with symbolic links, but this did not work properly with CoreRun.exe.
> Address CoreFX issue # 8634

- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
We shouldn't be using the staging endpoint as it's not production quality
and goes down as changes are made and tested.
> Switch to the release Helix API.

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/CodeCoverage.targets
The rename from mscorlib to System.Private.Corelib broke our corefx code coverage runs, and more generally, broke the OpenCover tool, which hard codes the "mscorlib" name.  Until OpenCover can be updated to support .NET Core with an alternate core library name, this commit works around it by employing the "-oldStyle" flag to change the instrumentation mechanism to one that doesn't rely on mscorlib instrumentation.
cc: @mmitche
> Fix code coverage with workaround after mscorlib rename

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets
@ellismg @weshaggard 
Looks like we were not handling the case when whoami or hostname commands fail right, and we were setting a wrong built by string. With this, in case of any of those two commands failing, we will just not set a built by string in the version string.
> Do not set built by string when unix commands fail

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/packageresolve.targets
-added a property, DisableReferenceCopyLocal, which can be user supplied to dissable copying package references locally
> updating packageresolve.targets to allow dissabling the local copy of references

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets
@weshaggard 
Fixing issue introduced here: #774
> Fixing Windows case where exit codes are not defined.

- src/Microsoft.DotNet.Build.Tasks/GenerateAssemblyList.cs
This is required for coreclr perf test runs where the NETCore.Jit deps are now being packaged separately from the runtime libraries
@MattGal @karajas @lt72
> Classifying NETCore.Jit deps as CoreRun deps

- dir.props
- src/Microsoft.DotNet.Build.CloudTestTasks.net45/project.json
- src/Microsoft.DotNet.Build.Tasks.Packaging/src.Desktop/project.json
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/project.json
- src/Microsoft.DotNet.Build.Tasks.Packaging/test.Desktop/project.json
- src/Microsoft.DotNet.Build.Tasks.Packaging/test/project.json
- src/Microsoft.DotNet.Build.Tasks.net45/project.json
- src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.json
- src/Microsoft.DotNet.Build.Tasks/project.json
- src/packages.builds
We need the latest version to unblock pack on Unix.
Remove the workaround for project.json that I added before as it is no longer needed: fixed in latest NuGet.
/cc @weshaggard @joshfree @schellap
> Update to NuGet 3.5.0-beta2-1437

- src/packages.builds
Official build sets ConfigurationGroup and not Configuration.
> Use ConfigurationGroup specific packaging task

- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/GetApplicableAssetsFromPackages.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/PackageLibs.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
- src/Microsoft.DotNet.BuildTools.TestSuite/Microsoft.DotNet.BuildTools.TestSuite.depproj
- src/Microsoft.DotNet.BuildTools.TestSuite/project.json
- src/Microsoft.DotNet.BuildTools.TestSuite/runtime.json
- src/Microsoft.xunit.extensibility.execution.netcore/Microsoft.xunit.extensibility.execution.netcore.depproj
- src/Microsoft.xunit.extensibility.execution.netcore/project.json
- src/nuget/Microsoft.DotNet.BuildTools.TestSuite.nuspec
- src/nuget/Microsoft.xunit.extensibility.execution.netcore.nuspec
- src/nuget/Microsoft.xunit.netcore.extensions.nuspec
- src/nuget/xunit.console.netcore.nuspec
- src/nuget/xunit.netcore.extensions.nuspec
This change will introduce 3 changes to buildtools. 
1. It allows for the restoration of xunit packages to the netstandard framework moniker. It introduces a new Microsoft.DotNet.BuildTools.TestSuite package which will be the metapackage brought down in test-runtime for all xunit dependencies. This is a set of repackaged xunit dependencies until official xunit  packages update to rc2. This package also contains the runtime.json which specifies the supported (Target Framework Moniker X Runtime Identifier) combination which will be used by test project.jsons to list their supported platforms.
2. GetApplicableAssetsFromPackages will now error out instead of falling back onto older generations during resolution of compile/runtime assets. (Change done by @ericstj )
3. This change introduces …
> Resolve correct test assets for netstandard

- src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/xunitrunner-perf/ubuntu-dotnet-local-install.sh
Downloading the dotnet cli installation script to a temporary location (the directory where dotnet cli will be installed). This ensures that the installation script is not lying around in the repo in case we try to run perf tests locally on a linux machine and also prevents accidental check-in of this file.
@MattGal
> Downloading dotnet-install.sh to temporary location

- dir.props
- src/Microsoft.DotNet.Build.CloudTestTasks.net45/project.json
- src/Microsoft.DotNet.Build.Tasks.Packaging/src.Desktop/project.json
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/project.json
- src/Microsoft.DotNet.Build.Tasks.Packaging/test.Desktop/project.json
- src/Microsoft.DotNet.Build.Tasks.Packaging/test/project.json
- src/Microsoft.DotNet.Build.Tasks.net45/project.json
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.json
- src/Microsoft.DotNet.Build.Tasks/project.json
This fixes a regression caused by the Serviceable attribute addition.  
Same fix is in release/1.0.0, this ports it to master.
> Update NuGet to 3.5.0-beta2-1456

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/RunnerTemplate.Unix.txt
This change should enable (limited) core file generation on OS X when running tests. To prevent flooding CI machines with dumps, we will only enable core file generation for a test run if, at the time the test run is started, the "/cores" directory on the machine is empty.
The reason for this change is that CoreFX CI runs have occasionally been hitting mysterious segfaults lately, and having some dumps would be really useful for investigating what could be going on.
@ellismg @ericstj @MattGal PTAL. I've made this change in what seems to be an appropriate and safe place (for instance, we'll definitely know what OS we're on at that point), but my entire experience with this test running infrastructure is limited to the past couple of hours :smile:.
I opened this PR against release/1.0.0 per …
> Add some conditional core dump generation for OS X to Unix RunnerTemplate

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/RunnerTemplate.Unix.txt
This change should enable core file generation on Linux when running tests. To prevent flooding CI machines with dumps, we will print the backtrace for each thread from the dump and delete it immediately. The idea here is to see something more useful than "Segmentation fault" when something crashes. It will be nice to have the core files transferred somewhere rather than just deleted, but this is a reasonable starting point (and a vast improvement over the current state of affairs).
The reason for using GDB is that LLDB-3.6 (which is what's on many or most of our CI machines) seems to have a bug on Linux where operations like `bt` and `thread list` don't work in batch mode. If/when we unify all the machines to a working LLDB version with a compatible SOS, we should switch to that instead. …
> Enable core dump generation on Linux in Unix RunnerTemplate

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/RunnerTemplate.Unix.txt
Looks like there's no facepalm emoji on GitHub, so this will have to do:
:smile: :palm_tree: 
@ellismg @sergiy-k
> Fix logic for when to enable core file generation on OS X.

- dir.props
- src/Microsoft.DotNet.Build.Tasks.Packaging/test/Microsoft.DotNet.Build.Tasks.Packaging.Tests.csproj
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
This change is to prevent locally built assemblies being included in the dependency list. This happens during the test csproj to pkgproj reference change being introduced in corefx. The dependency list should only have package dependencies when TestWithLocalLibraries is false.
/cc @MattGal @maririos
> Ensure that all locally built assemblies are not included in the dependency list

- netci.groovy
Our CI was building the Build Tools repo without running the tests.
Now that we have test to run, we want to build and run them.
cc: @joperezr @karajas @mmitche
> Enable running tests in our CI builds

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/PackageLibs.targets
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
This is a fix for corefx to allow test projects that now reference the pkgprojs to build in VS.
MS.Common.Targets hardcodes GetTargetPath when resolving projectrefs in the IDE.
Currently VS(+Nuget Extensions 3.5 beta) doesn't understand the p2p reference to the test-runtime, so the nuget restore must be done via msbuild.
This also resolves rebuildandtest on commandline msbuild, by mapping it to the first usage of ProjectReference in a target which happens on both the Build and Rebuild paths.
Changes done with @ericstj 's help.
> Fix for building test projects in VS and rebuildandtest on command line

- src/xunit.netcore.extensions/Discoverers/ConditionalTestDiscoverer.cs
If the condition member throws an exception, we should treat it as not meeting the condition so that we mark the test(s) as skipped.
Fixes https://github.com/dotnet/buildtools/issues/808
cc: @cipop, @Priya91, @roncain
> Fail ConditionalFacts/Theories with throwing conditions

- src/Microsoft.DotNet.CodeAnalysis/Analyzers/MembersMustExistAnalyzer.cs
- src/Microsoft.DotNet.CodeAnalysis/Helpers.cs
This change enhances the MembersMustExistAnalyzer to check the existence of fields.
In order to have a decent debugging experience, some debuggers (e.g. Visual Studio) will have to inspect some fields (mostly private ones). Since private fields are not part of the contract, this dependency is pretty fragile. 
In order to strengthen this dependency, this change allows us to make sure the field exist during build. With the change, we can catch a breaking change (e.g. rename/remove of the interesting fields) as soon as we build, this should hopefully solve the problem of the fragility of the dependency.
> Enhance MembersMustExistAnalyzer to check the existence of fields

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/packageresolve.targets
We weren't filtering items that came from pkgproj refs.  Those items are
directly added to the reference item today, so filter that item.
I could have made the pkgproj references behave more like project
references and have them add their output to
_ResolvedProjectReferencePaths, but this would bypass RAR and be less
like an actual package reference.
/cc @karajas @weshaggard
> Filter nupkg assets that overlap with projectrefs

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/toolruntime.targets
We need to make the Tool Host overridable because internal builds have to run it from a different location.
> Make Tool Host Overridable for Internal Builds

- src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Methods.cs
We had a discussion about this offline. throw null results in simpler source and smaller IL.
> Changed writers to output "throw null;" in empty method bodies

- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
- src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/xunitrunner-perf/xunitrunner-perf.py
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/PerfTesting.targets
This change introduces the following changes
- Uploads only perf assemblies during CloudTest build for perf.
- Search for matching TestTFM directories if the TestTFM variable is set in CloudTest.targets if exists (only in corefx). If it is not set, continue uploading from the same directory.
- Update perf version to 0036 (which can restore for netstandard1.3)
@dsgouda @MattGal
> Search for TestTFM directories in CloudTest.targets if they exist

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets
Previously this was using OSGroup which is the OS the test is building
for not the OS the test is running against.  TargetOS is what the test
is running against.
/cc @weshaggard @karajas
> TestWithLocalLibraries should use TargetOS

- src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Attributes.cs
Before it'd use the current culture when writing the constant value, which results in float/double
using `,` as the decimal separator in cultures where this is the default.
The generated code is invalid C# and doesn't compile. Fixing the problem by using culture-neutral formatting.
Sample code:
```
public class TestLib
{
public const double PI = 3.141592;
}
```
> Use InvariantCulture for writing constants in MS.CCI.Extensions

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/RunnerTemplate.Unix.txt
This change should enable (limited) core file generation on Linux and OS X when running tests. There is also some logic for printing the callstacks for each thread if GDB is available on the machine.
As for storing the dumps, we will keep one dump around (in /cores on OS X and in /tmp/coredumps on Linux). For now, they will need to be retrieved and deleted manually from the machine. Until then, further dumps will not be saved.
@ellismg
> Generate core dumps on Linux/OS X

- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
To be able to track the test progress of tests in Helix we need the correlation id. Currently the only way to read it is during build time, when executing this target. This change uploads a file that contains the correlation id to the same place as the test drop builds are placed making it accessible to retrieve at a later time.
@chcosta @jhendrixMSFT
> Add file with correlation id to test drop

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/RunnerTemplate.Unix.txt
Turns out we don't have GDB installed on the CI machines yet, so the strategy of printing stacks from core files and deleting them isn't going to work. Instead, for now, let's copy the core files to a known location that won't be wiped out right after the run.
Like on OS X, we'll only store one core file there at a time in order to avoid filling up the disk.
@ellismg @sergiy-k PTAL
> Copy generated core files on Linux to a location that won't be deleted after the run

- src/Microsoft.DotNet.BuildTools.TestSuite/runtime.json
- src/xunit.console.netcore/Program.cs
- src/xunit.console.netcore/Visitors/StandardOutputVisitor.cs
These changes enable consuming and using xunit.console.netcore from netcore50 and netcore50aot setups.  
Once merged, we'll need to update the versions of both this and Microsoft.DotNet.BuildTools.TestSuite to reflect this in CoreFX.
> Handle Console API NotSupported exceptions

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets
resolution from being included in the dependency list.
This was an extra step that was adding local dependencies to the dependency list. The resolution of the package references and project references is now done in https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/packageresolve.targets#L90-L108 
/cc @MattGal
> Remove the local dependencies from project references/package references

- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
- Increase default write access time for Helix results to 4 days, to deal with long running jobs and deep queues.  
- Add properties CloudResultsReadTokenValidDays and CloudResultsWriteTokenValidDays to allow changing these values.
@schaabs
> Allow customization of Read/Write tokens for .NET Helix results shares

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh
* Also, fall back to Ubuntu 14.04 if an unsupported Ubuntu
version is encountered.
Similar change as in https://github.com/dotnet/corefx/pull/9646. This lets you override the RID that the tool-runtime project is published for. It also adds a fallback from unsupported Ubuntu versions to 14.04.
@ellismg , @joperezr
> Allow override of __PUBLISH_RID

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/PackageLibs.targets
We'll want to be able to test without building a package.
We're thinking to control package builds for the repo via the
packages.builds file and we don't want a test build to trigger
nupkg build for something we aren't shipping.
/cc @weshaggard @karajas
> Don't run build on pkgproj references

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/EnsureOOBFramework.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/GenerateNuSpec.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
- src/Microsoft.DotNet.Build.Tasks.Packaging/test/EnsureOOBFrameworkTests.cs
EnsureOOBFramework makes sure that an oob implementation will always
take precedence over a placeholder in the case we have a framework that
transitioned from targeting-pack to package as was the case with
netcore50.
The problem here is that if it promotes only one of the ref or lib we'll
only get the dependencies from that asset, since the other asset's
dependencies will be in the less specific dependency group.
This became a problem when we started merging runtime specific
assets into the same packages as the ref: the fat package work.
Since a netstandard lib that is rid specific will be preferred over the
placeholder that is not rid specific we didn't need to copy the
implementation.   The result was the dependencies would only
be in the netstandard group.
To fix this I added a phase …
> EnsureOOBFramework should promote impl deps

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/EnsureOOBFramework.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/GenerateNuSpec.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
- src/Microsoft.DotNet.Build.Tasks.Packaging/test/EnsureOOBFrameworkTests.cs
EnsureOOBFramework makes sure that an oob implementation will always
take precedence over a placeholder in the case we have a framework that
transitioned from targeting-pack to package as was the case with
netcore50.
The problem here is that if it promotes only one of the ref or lib we'll
only get the dependencies from that asset, since the other asset's
dependencies will be in the less specific dependency group.
This became a problem when we started merging runtime specific
assets into the same packages as the ref: the fat package work.
Since a netstandard lib that is rid specific will be preferred over the
placeholder that is not rid specific we didn't need to copy the
implementation.   The result was the dependencies would only
be in the netstandard group.
To fix this I added a phase …
> [release/1.0.0] EnsureOOBFramework should promote impl deps

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/msbuild.sh
> Changing corerun to dotnetcli on msbuild.sh

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/RunnerTemplate.Unix.txt
This change makes it so the core files generated in CI test runs on Linux will include memory in the shared libraries we load (such as libcoreclr.so). We didn't need it when the plan was just to print stacks when there was a crash in CI, but now that we're actually keeping the dumps sometimes, it's obviously useful for debugging purposes.
@sergiy-k @ellismg PTAL
> Set coredump_filter to include shared library code.

- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
- src/Microsoft.DotNet.Build.Tasks/GenerateTestExecutionScripts.cs
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/RunnerTemplate.Windows.txt
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
- src/Microsoft.DotNet.Build.Tasks/ZipFileCreateFromDirectory.cs
- src/xunit.console.netcore/CommandLine.cs
- src/xunit.console.netcore/Program.cs
- src/xunit.console.netcore/Visitors/StandardOutputVisitor.cs
@crummel , @karajas 
- Support zipping up TestILC package's "TestILC" content folder as a .NET Helix Payload.
- Remove injection of "call" before every command in script (moves this to build task).  Sometimes this caused undesired side effects.
- Work around disabled console output by writing to a text file when specified, and swallow PlatformNotSupported exceptions for CancelKeyPress.
> BuildTools Changes to support native compilation.

- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.Perf.targets
- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
- src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/xunitrunner-perf/csvjsonconvertor.py
- src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/xunitrunner-perf/dotnetcliinstaller.py
- src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/xunitrunner-perf/postprocessperfresults.py
- src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/xunitrunner-perf/xunitrunner-perf.py
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/PerfTesting.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
- install dotnet cli for linux via commands in runtests.sh
- copy over xunit perf runner packages as supplemental payload
- skip generation of assembly list when using the universal script runner
- use flag UseLegacyXunitPerfRunner to ensure backward compatibility with the old xunit perf runner since CoreCLR still relies on it
- refactored csvtojsonconvertor to allow easier command line execution from runtests.sh/cmd
- refactored/cleaned up xunitrunner-perf.py
@MattGal @lt72
> Enabling perf tests' execution via universal script runner

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/FrameworkLists/MonoAndroid,Version=v1.0/FrameworkList.xml
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/FrameworkLists/MonoTouch,Version=v1.0/FrameworkList.xml
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/FrameworkLists/Xamarin.Mac,Version=v2.0/FrameworkList.xml
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/FrameworkLists/Xamarin.TVOS,Version=v1.0/FrameworkList.xml
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/FrameworkLists/Xamarin.WatchOS,Version=v1.0/FrameworkList.xml
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/FrameworkLists/Xamarin.iOS,Version=v1.0/FrameworkList.xml
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/ValidatePackage.cs
This change turns on validation of Xamarin frameworks and updates our
inbox assembly lists to represent the files which must be provided by
the xamarin SDK (either because they already are, or because they
contain types which overlap with types already in their SDK).
/cc @mhutch @migueldeicaza @marek-safar
> Enable Validation of Xamarin frameworks

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/FrameworkLists/MonoAndroid,Version=v1.0/FrameworkList.xml
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/FrameworkLists/MonoTouch,Version=v1.0/FrameworkList.xml
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/FrameworkLists/Xamarin.Mac,Version=v2.0/FrameworkList.xml
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/FrameworkLists/Xamarin.TVOS,Version=v1.0/FrameworkList.xml
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/FrameworkLists/Xamarin.WatchOS,Version=v1.0/FrameworkList.xml
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/FrameworkLists/Xamarin.iOS,Version=v1.0/FrameworkList.xml
Xamarin has added facades for these WCF contracts which were already
part of PCL profiles that were supported.
Additionally I am including the list of classic assemblies which are
important as we start to add support for classic surface area to .NET
Core.
We need this to unblock our builds today since we're failing validation
for WCF and System.Json.
/cc @mhutch @marek-safar @StephenBonikowsky
> Update Xamarin profiles - WCF contracts + classic

- src/BuildTools.sln
- src/Microsoft.DotNet.Build.Tasks/Microsoft.DotNet.Build.Tasks.csproj
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/VersionTools.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.json
- src/Microsoft.DotNet.Build.Tasks/VersionTools/MsBuildTraceListener.cs
- src/Microsoft.DotNet.Build.Tasks/VersionTools/TraceListenerCollectionExtensions.cs
- src/Microsoft.DotNet.Build.Tasks/VersionTools/UpdateDependencies.cs
- src/Microsoft.DotNet.Build.Tasks/VersionTools/UpdatePublishedVersions.cs
- src/Microsoft.DotNet.Build.Tasks/project.json
- src/Microsoft.DotNet.VersionTools.net45/Microsoft.DotNet.VersionTools.net45.csproj
- src/Microsoft.DotNet.VersionTools.net45/project.json
- src/Microsoft.DotNet.VersionTools/Automation/DependencyUpdater.cs
- src/Microsoft.DotNet.VersionTools/Automation/GitHubAuth.cs
- src/Microsoft.DotNet.VersionTools/Automation/GitHubHttpClient.cs
- src/Microsoft.DotNet.VersionTools/Automation/NupkgNameInfo.cs
- src/Microsoft.DotNet.VersionTools/Automation/VersionRepoUpdater.cs
- src/Microsoft.DotNet.VersionTools/BuildInfo.cs
- src/Microsoft.DotNet.VersionTools/Dependencies/FileRegexPackageUpdater.cs
- src/Microsoft.DotNet.VersionTools/Dependencies/FileRegexReleaseUpdater.cs
- src/Microsoft.DotNet.VersionTools/Dependencies/FileRegexUpdater.cs
- src/Microsoft.DotNet.VersionTools/Dependencies/IDependencyUpdater.cs
- src/Microsoft.DotNet.VersionTools/Dependencies/ProjectJsonUpdater.cs
- src/Microsoft.DotNet.VersionTools/Microsoft.DotNet.VersionTools.csproj
- src/Microsoft.DotNet.VersionTools/Util/ArgumentEscaper.cs
- src/Microsoft.DotNet.VersionTools/Util/Command.cs
- src/Microsoft.DotNet.VersionTools/Util/CommandResult.cs
- src/Microsoft.DotNet.VersionTools/project.json
- src/nuget/Microsoft.DotNet.BuildTools.nuspec
- src/nuget/Microsoft.DotNet.VersionTools.nuspec
Created a new project for "VersionTools" that so far includes auto-upgrade and build-info update. Started with the files in https://github.com/dotnet/cli/tree/rel/1.0.0/build_projects/update-dependencies and [`Command.cs` and `CommandResult.cs`](https://github.com/dotnet/cli/tree/rel/1.0.0/build_projects/Microsoft.DotNet.Cli.Build.Framework), then refactored and added a few features to work with coreclr/corefx requirements. The library should be sharable as an independent package with a little extra work. (For context, @eerhardt's comment on this approach: https://github.com/dotnet/buildtools/pull/848#issuecomment-229671100)
Added a .targets file and two msbuild tasks to integrate with corefx/coreclr/wcf. Example configuration: https://github.com/dagood/corefx/commit/50ad7f7
Test PR the …
> Add dependency auto-upgrade and versions repo update to buildtools

- src/Microsoft.DotNet.Build.CloudTestTasks.net45/project.json
- src/Microsoft.DotNet.Build.CloudTestTasks/project.json
- src/Microsoft.DotNet.Build.Tasks.Packaging/src.Desktop/project.json
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/project.json
- src/Microsoft.DotNet.Build.Tasks.Packaging/test.Desktop/project.json
- src/Microsoft.DotNet.Build.Tasks.Packaging/test/project.json
Upgrade remaining projects to newer NewtonSoft to avoid FileNotFound Exception at runtime
Tested to run using local .NET Helix run (05b56f31-df45-499a-9806-0b8fca37e4cc), and via inspection of assembly manifests for affected files.
@dagood 
@karajas
> Fix Newtonsoft issue with BuildTasks

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/BuildVersion.targets
cc: @Chrisboh @jhendrixMSFT @chcosta 
This fixes the issue of some builds failing whenever the props was generated using date.now, since that varies during the time of your build. The problem with this, is that now we will depend on `$(OfficialBuildId)` property to get passed in for every step of the Build Pipeline flow so that we know where to load the props file from. I don't love this approach, but I can't really think of a better way to handle this.
> Fix issue of not finding the props file when OfficialBuildId is passed in

- clean.cmd
When no option is provided clean.cmd should run `clean -b`.
cc: @joperezr @Priya91 @tyoverby
> Fix clean.cmd when no option is provided

- src/Run/CommandLine.cs
- src/Run/Setup.cs
Before, the Run Command Tool was concatenating all the unknown parameters that were passed by the user. When running the command, it was passing this new string and it was the responsibility of the tool (i.e. msbuild) to work with those unknown parameters.
`build.cmd cross /p:ConfigurationGroup=Debug => msbuild cross /p:ConfigurationGroup=Debug`
With this change, the Run Command Tool will throw an error when there is an unknown parameter.
To pass extra parameters to the command, the user can use `--`, meaning that all the text that is after `--` will be passed and then it would be the responsibility of the tool (i.e. msbuild) to work with them.
```
build.cmd cross /p:ConfigurationGroup=Debug => Error: Parameter not recognized: cross
build.cmd -- cross /p:ConfigurationGroup=Debug => …
```
> Remove support for unknown parameters

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets
When we are building the native binaries in CoreFx, we have a condition in the script that checks if the file `_verison.h` is present. If it is not present then it would run the `GenerateVersionHeader` target.
```
if not exist "%__binDir%\obj\_version.h" (
msbuild "%~dp0build.proj" /nologo /t:GenerateVersionHeader /p:GenerateNativeVersionInfo=true
)
```
With this change I'm deleting the condition from the script and adding it to the version.targets file.
cc: @joperezr
> Add if file "_version.h" exist condition

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/CodeCoverage.targets
The FullCoverage report at some point recently stopped getting the Target that calls it invoked.  I made the below change in my repo and was able to get it working again.   There may be other Jenkins issues affecting this, as if incremental build happens, coverage measurement does not.
@stephentoub
> Change AfterTargets value for GenerateFullCoverageReport

- src/Run/Executor.cs
If there was a failure when parsing arguments, the Run Command Tool was returning 0 as the exit code.
With this change the tool returns the correct exit code.
cc: @Priya91 @joperezr
> Returning exit code of the DefineParameters function

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/BuildVersion.targets
Reverting the recent change for the props file since it broke corefx build in Linux.
cc: @MattGal @jhendrixMSFT
> Revert "Fix issue of not finding the props file when OfficialBuildId is passed in"

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/RunnerTemplate.Unix.txt
Don't print anything if files have already been copied. This is in line with the Windows runner template. Indentation was also a bit off on this block.
@MattGal 
Addresses #853
> Lower Unix test runner verbosity

- src/Microsoft.DotNet.Build.Tasks/TarGzFileCreateFromDirectory.cs
Adds a TarGzFileCreateFromDirectory task to create tar.gz files on Linux & OS X. The task implements the same signature as ZipFileCreateFromDirectory. It requires that `tar` be available on the PATH.
> TarGzFileCreateFromDirectory

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/packageresolve.targets
@stephentoub @mellinoe PTAL
This will enable us to start referencing S.P.CoreLib as opposed to mscorlib for CoreCLR based partial facades.
> Enable S.P.CoreLib as core assembly for partial facades

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/PackageLibs.targets
When we start referencing S.P.CoreLib generation validation starts complaining about it. So we need to add it to the ignore list similar to mscorlib. 
cc @stephentoub @ericstj
> Add S.P.CoreLib to the ignore list for generation validation

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/Microsoft.DotNet.Build.Tasks.Packaging.csproj
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/NuGetPack.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/NugetPropertyStringProvider.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/test.Desktop/Microsoft.DotNet.Build.Tasks.Packaging.Tests.Desktop.nuget.props
- src/Microsoft.DotNet.Build.Tasks.Packaging/test/Microsoft.DotNet.Build.Tasks.Packaging.Tests.csproj
- src/Microsoft.DotNet.Build.Tasks.Packaging/test/Microsoft.DotNet.Build.Tasks.Packaging.Tests.nuget.props
- src/Microsoft.DotNet.Build.Tasks.Packaging/test/NugetPropertyStringProviderTests.cs
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/packages.targets
With MSBuild nuget packages, we want to have versioned project to project dependencies. For this, nuspec properties seem like an ideal solution: we add a `$version$` variable in the nuspecs and then compute and inject the actual value at build time.
I also changed packages.targets to allow the user to override the package version and not have it automatically generated.
Usage example of the changes (WIP msbuild branch):
- https://github.com/cdmihai/msbuild/commit/18ea882c144a0a0bc9a8b9fab550eb127675f926#diff-aade4fae49f1d220b531687680bb6718
- https://github.com/cdmihai/msbuild/commit/18ea882c144a0a0bc9a8b9fab550eb127675f926#diff-fcc4a9bafd113347e0ca9e95377d8f73
> Enable NugetPack to pass through nuspec properties

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/PackageLibs.targets
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
- src/Microsoft.DotNet.BuildTools.TestSuite/runtime.json
unblocks building CoreFX tests for ARM64.
> Adds RID arm64 to Testing runtime.json

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.json
This is breaking with new NuGet in the CLI.
@dagood @weshaggard
> Correct the casing of Microsoft.Net.Compilers.netcore

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/RunnerTemplate.Unix.txt
@jhendrixMSFT @karajas 
For the scenario where the execution directory is not the same as the one the test + script lives in, switch to a command that works on both Linux + OSX.
This didn't affect .NET Helix because there is still code copying it to the destination already, but it may as well work properly and not put unnecessary errors on the log.
> Fix RunTests.sh copy behavior on OSX

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
Addresses Issues #699 and #700, with a couple typos fixed as well (searched repository, did not find other usages of the incorrectly spelled properties).
In order for the F5 scenario to work for CoreFX and other tests that use these .targets files, we need the files which are normally copied by the runner scripts (RunTests.cmd / .sh) to be copied before starting CoreRun.exe.  Running the script before debugging was a workaround, but by adding a target that executes at the end of other test copying code and only when the condition '$(BuildingInsideVisualStudio)'=='true'  is met works around this.  It uses the exact same file list generated for RunTests, and would not affect execution of the RunTests script before or after it is used.
@weshaggard @stephentoub @AtsushiKan
> VS debugging fixes for tests

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
Allows sequential commands to be run after a test completes.  These can perform cleanup, call post-run scripts, etc.
@hongdai
> Add support for PostExecutionTestCommandLines

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/VersionTools.targets
- src/Microsoft.DotNet.Build.Tasks/VersionTools/UpdatePublishedVersions.cs
- src/Microsoft.DotNet.VersionTools/Automation/VersionsRepoUpdater.cs
- src/Microsoft.DotNet.VersionTools/Microsoft.DotNet.VersionTools.csproj
Makes naming consistent with the repository name "dotnet/versions" and parameters in the existing `UpdatePublishedVersions.ps1`. I found this issue when I was removing the powershell script functionality and noticed the msbuild properties' names don't match up.
`VersionsRepoUpdater` is called `VersionRepoUpdater` in the CLI repository, but I think `Versions` makes more sense here too.
Minor change, but I wanted to make it before I worked VersionTools into the repositories, making it hard to change later.
@eerhardt It looks like CLI isn't depending on `VersionsRepoUpdater` yet--is that true, making this free to change?
> Rename "version" to "versions" when referring to dotnet/versions repository

- src/Microsoft.Cci.Extensions/Filters/PublicOnlyCciFilter.cs
- src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Methods.cs
- src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Properties.cs
- src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Types.cs
- src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.cs
Fixes 3 issues found while compiling generated code for v4.6.1 mscorlib.dll.
Attributes not visible outside the assembly are now filtered.
Attributes using arguments with typeof expression of a type not visible
outside assembly are also filtered.
When we are generating structs for builtin types such as System.Double, we
cannot use the keyword double while declaring operators.
This fixes bad generated methods such as:
public static decimal operator +(decimal d1, decimal d2) { throw null; }
public static implicit operator decimal (char value) { throw null; }
This changes the generator to not replace a type for its keyword when we
are generating the type itself.
DllImportAttribute was added to methods without modifier extern,
this would cause an error while compiling them.
Fixes: …
> Attribute, operators, extern modifier fixes

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
@ianhays 
Without this I get an error attempting to find CoreRun for VS test debugging.
> Put back expected slash in TestHostDirectory property.

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets
The current mechanism for copying supplemental test data assumes that the
RecusiveDir metadata is defined.  Added new metadata, DestinationDir, for
copying supplemental test data to be preferred over RecursiveDir.
> Add mechanism to specify destination dir for supplemental test data.

- src/Microsoft.DotNet.Build.Tasks/VersionTools/UpdateDependencies.cs
This enables upgrading things like [`CoreClrPackageVersion`](https://github.com/dotnet/coreclr/blob/0bb191d/tests/dir.props#L47), so we can use the VersionTools msbuild task to upgrade coreclr.
/cc @eerhardt @weshaggard
> Add a way to config VersionTools task to upgrade full version for a package id

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/ApiCompat.targets
> Run ResolveProjectReferences before ResolveAssemblyReferences in ApiCompat

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets
The change introduced in commit 04599fa caused the ordering of items
between SupplementalTestData and TestDir/OutDir items to be incorrect when
a group of SupplementalTestData items contained data with and without the
DestinationDir metadata set.  To avoid this mismatch we now coalesce both
groups of SupplementalDataData into an intermediate item group and use
that when copying.
> Fix copying of supplemental test data.

- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
- src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/scriptrunner/scriptrunner.py
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/RunnerTemplate.Unix.txt
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/RunnerTemplate.Windows.txt
@jhendrixMSFT @weshaggard 
Alternate fix for https://github.com/dotnet/buildtools/pull/940.   Now, runner scripts don't copy over everything to an alternate directory on execution, they simply run as is (1 argument only). 
In case someone manages to run their script and produce a testResults.xml in an unexpected location, I also added support to scriptrunner to walk the entire work item directory looking for testResults.xml if it happens to be missing.
> Remove execution directory from RunTests scripts

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh
Allows callers of init-tools.cmd/sh to set `INIT_TOOLS_RESTORE_ARGS`/`__INIT_TOOLS_RESTORE_ARGS` to add arguments to the restore commands. This also refactors the restore calls to reuse the arg strings where appropriate.
~~Makes init-tools.sh "dotnet restore" calls configurable by appending `__BUILDTOOLS_EXTRA_RESTORE_ARGS` to the restore commands called in the package's `init-tools.sh`. Specifically, this lets core-setup pass in `--disable-parallel` to access a workaround.~~
~~Also upgrades the `Microsoft.NETCore.App` runtime dependency for MSBuild, since the fixes to core-setup include upgrading the version of CLI being used and the old version of CLI was apparently the only place that specific version of App was available.~~
> Allow adding args to restore calls in init-tools.cmd/sh

- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
This change is intending to fix this error in automating stress runs.
```
2016-07-14 07:22:56,382: INFO: proc(60): run_and_log_output: Output: ./corerun xunit.console.netcore.exe stress.execution.dll -xml testResults.xml -notrait Benchmark=true -notrait category=OuterLoop -notrait category=failing -notrait category=nonlinuxtests
2016-07-14 07:22:56,382: INFO: proc(60): run_and_log_output: Output: /home/DotNetBot/dotnetbuild/work/129a60f2-2789-43af-85a2-f2bb8e5d201b/Work/67ec5509-5464-4ae1-81f7-4781ca25132d/Unzip/RunTests.sh: line 254: ./corerun: Permission denied
```
> dotnet stress runs require corerun to be executable.

- src/Microsoft.DotNet.Build.CloudTestTasks/RunnerScripts/xunitrunner-perf/ubuntu-dotnet-local-install.sh
Updating link to download the dotnet cli installer since the dotnet cli version used to build xunit perf runner has been updated
@lt72 @MattGal
> Update dotnet cli installer link for newer version

- src/Run/CommandLine.cs
When a setting was directly passed by the user, the assigned value was always true. Now it assigns the default value of the setting.
Fix issue: #958 
cc: @weshaggard  @joperezr
> Fix passthrough setting

- src/Microsoft.DotNet.VersionTools/Util/FileUtils.cs
Fixes https://github.com/dotnet/buildtools/issues/964
I confirmed that a verify using this change works with a read-only `project.json` and `dependenices.props` (and still detects invalid dependencies), and that `UpgradeDependencies` hits errors when trying to upgrade read-only files.
@naamunds @AtsushiKan 
(FYI @eerhardt)
> When reading a file to verify dependencies, use FileAccess.Read

- src/Microsoft.DotNet.Build.Tasks.Packaging/src.Desktop/project.json
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/project.json
Currently we pick up these dependencies from the Packaging projects,
make sure we add the new NuGet.ProjectModel dependency here to
get it in our package.
> Add NuGet.ProjectModel to buildtools PackageLibs

- src/RepoUtil.Desktop/App.config
- src/RepoUtil.Desktop/RepoUtil.Desktop.csproj
- src/RepoUtil.Desktop/project.json
- src/RepoUtil/ChangeCommand.cs
- src/RepoUtil/ConflictingPackagesException.cs
- src/RepoUtil/Constants.cs
- src/RepoUtil/ConsumesCommand.cs
- src/RepoUtil/FileName.cs
- src/RepoUtil/GenerateData.cs
- src/RepoUtil/GenerateUtil.cs
- src/RepoUtil/ICommand.cs
- src/RepoUtil/NuGetConfigUtil.cs
- src/RepoUtil/NuGetFeed.cs
- src/RepoUtil/NuGetPackage.cs
- src/RepoUtil/NuGetPackageChange.cs
- src/RepoUtil/NuGetPackageSource.cs
- src/RepoUtil/NuSpecUtil.cs
- src/RepoUtil/ProducesCommand.cs
- src/RepoUtil/Program.cs
- src/RepoUtil/ProjectJsonUtil.cs
- src/RepoUtil/README.md
- src/RepoUtil/RepoConfig.cs
- src/RepoUtil/RepoData.cs
- src/RepoUtil/RepoUtil.csproj
- src/RepoUtil/UsageCommand.cs
- src/RepoUtil/VerifyCommand.cs
- src/RepoUtil/ViewCommand.cs
- src/RepoUtil/project.json
- src/RepoUtil/repoutil.runtimeconfig.json
- src/nuget/Microsoft.DotNet.BuildTools.RepoUtil.nuspec
We have a tool, RepoUtil, created by the Roslyn team for implementing the
produces and consumes repo APIs.  Since this is meant to be a general
purpose tool to be consumed by various repos I'm moving the sources to the
build tools repo.  I have also added nuget package authoring for this tool
so that it can easily be consumed by other repos.  In the process I have
converted the tool to be a .NET Core app.
> Add RepoUtil sources to the build tools repo.

- src/Run/Executor.cs
Fix #889 
cc: @joperezr @TyOverby
> Add error message when no command is passed to run.exe

- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
This change is required, but needs to go in to another location as it turns out that there are different code paths being taken in build tools depending on requirements.
> undoing #938

- src/nuget/Microsoft.DotNet.BuildTools.RepoUtils.nuspec
This package will likely end up containing multiple utilities for repo
dependency management so changing the name as there are no dependencies on
this package at present.
> Rename RepoUtil package to RepoUtils.

- config.json
- src/Run/Setup.cs
With this change we could add specific tools parameters to pass to all the commands. For example, MsBuildParameters like: /nologo /verbosity:minimal /clp:Summary /maxcpucount are always going to be pass when a command uses the tool MsBuild,
That way we could customize them per OS and we only have to declare the parameters in one place.
I don't intend to merge this PR with the config.json file as it woul break the build. It is here for information purposes. Once the PR is approved I'll create a different PR updating the version of BT and adding the changes to config.json
Related to dotnet/corefx#10864.
Also, fix #890 
cc: @weshaggard @TyOverby
> Add properties to the tools section for run.exe

- src/Microsoft.DotNet.Build.Tasks/VersionTools/BaseDependenciesTask.cs
- src/Microsoft.DotNet.VersionTools/Dependencies/DependencyBuildInfo.cs
- src/Microsoft.DotNet.VersionTools/Dependencies/FileRegexPackageUpdater.cs
This will normally not be used ([it is needed in the dev/api branch](https://github.com/dotnet/corefx/pull/10970#issuecomment-241046344)), but it allows a package to be ignored from a buildinfo and not used for verification and auto-upgrade. Example usage: https://github.com/dotnet/corefx/commit/f61cbf732569f5b3a7c8a5d7dee24abc53c32ac1 (I added the package to a different `DependencyBuildInfo` to ensure it stays at a given version, even though it won't be auto-upgraded.)
> Add "DisabledPackages" buildinfo metadata that ignores a package by id

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/ApplyBaseLine.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/ApplyPreReleaseSuffix.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/GetLastStablePackage.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/GetPackageFromModule.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/Microsoft.DotNet.Build.Tasks.Packaging.csproj
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageIndex.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/UpdatePackageIndex.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/ValidatePackage.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/VersionUtility.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/test/ApplyBaseLineTests.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/test/Microsoft.DotNet.Build.Tasks.Packaging.Tests.csproj
- src/Microsoft.DotNet.Build.Tasks.Packaging/test/packageIndex.json
Now that package versions are divorced from assembly version we need a
data file to track the mapping.
In addition to tracking assembly version to package version, this data
file will track stable packages, baseline packages, and module-to-
package mappings.  This will help speed up our builds by caching the
data rather than parsing giant item lists in every msbuild project.
To keep the data file up to date I added validation with an error
message that tells folks to run a command to update the data file.  I
don't update the file automatically because I can't be certain that
packages with stale data have already been created.
CoreFx change which supports this: https://github.com/dotnet/corefx/pull/10971/commits/254ce644dc75132f787053b67177decf9651a86e
> Add package index

- src/Microsoft.DotNet.Build.Tasks/VersionTools/BaseDependenciesTask.cs
- src/Microsoft.DotNet.Build.Tasks/VersionTools/UpdateDependenciesAndSubmitPullRequest.cs
- src/Microsoft.DotNet.VersionTools/Dependencies/FileRegexUpdater.cs
- src/Microsoft.DotNet.VersionTools/Dependencies/ProjectJsonUpdater.cs
- src/Microsoft.DotNet.VersionTools/Util/FileUtils.cs
Implements the buildtools side of this idea: https://github.com/dotnet/corefx/pull/10970#discussion_r75404356. The CoreFX-side config: https://github.com/dotnet/corefx/commit/1392eaf5b71e893e8cd61089de4949348239d932
An example auto-PR, simulating the point where dev/api has just split off from master, and this is the first auto-PR with dev/api packages available: https://github.com/dagood/corefx/pull/22
It works the same way as the CurrentRef update, but writes the name of the `AutoUpgradeBranch`, which in this case is passed in as `BranchBeingUpgraded`.
@weshaggard @joperezr
> During auto-update, update CurrentBranch property

- src/Run/Executor.cs
- src/Run/Setup.cs
https://github.com/dotnet/buildtools/issues/973
Adds a "RunQuiet" option (default false), which, if true, suppresses extra output from the run tool itself.  The default values for RunQuiet are part of the run tool, but a repo may override these values by either adding a setting with a default value in that repo's config.json, adding a "RunQuiet" property to a Command, or specifying the value on the command-line.
/cc @maririos , @weshaggard
> Enable run quiet mode for run tool (suppress run tool output, only display exec output)

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
In CoreFx we started hitting the problem that the result of the build was `Build Succeeded` even when we had test failures. It was not obvious until run.exe got implemented.
The problem relies on how the value of the MsBuild property `MSBuildLastTaskResult` was being propagated.
With the AfterTargets property, the result of the subsequent targets, like [RunTestsForProject](https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets#L151) was not being returned to the target `Test` as this one had already finished before the execution of the tests happened.
With this change, the target `CheckTestPlatforms` and all its dependencies are executed and they return the exit code value before `Test` is executed, so the propagation of the value of …
> Calling target `Test` with BeforeTargets in tests.targets

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/ReferenceAssemblies.targets
We weren't honoring TargetGroup for subdirectories in reference assembly projects.
> Permit the use of TargetGroup in refs

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
Packages can filter build by specifying PackagePlatform but we were
ignoring this when scheduling ValidatePackage.
> Don't run ValidatePackage for noop builds

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/FilterUnknownPackages.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/Microsoft.DotNet.Build.Tasks.Packaging.csproj
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
I broke this filtering when switching to package index.  Previously we'd
only trim System.Private package references if they were "unknown"
packages.  We did this to handle the netcore50 cases where we have
assemblies that don't ship as packages.
Previously we determined "unkown" by checking if the package was in the
BaselinePackage item.  Now we need to check both that item and the index.
This is a targeted fix to restore the thing I broke.
I'd like to refactor the entire dependency harvesting into a smaller
number of tasks but I'll do that in a future commit.
/cc @weshaggard @roncain
> Fix System.Private package filtering

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/HarvestPackage.cs
Previously we weren't ensuring a trailing slash in the path, then doing
a startswith comparison.  This made paths like "lib/net" match
"lib/netstandard" which is not what we want.  Fix this by ensuring
a trailing slash on all exclusion paths.
/cc @tarekgh @weshaggard
> Ensure trailing slash for harvest path exclusions

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/HarvestPackage.cs
My previous change didn't account for some targetpaths which may include
filenames.  Here we'll identify paths that have filenames and trim the
the filename.
/cc @weshaggard @tarekgh
> Handle fillenames in TargetPath for exclusion dirs

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets
cc: @ericstj @weshaggard 
This is required in order to remove the use of TestWithLocalLibraries in corefx CI.
related comment: https://github.com/dotnet/corefx/issues/11203#issuecomment-243207773
> Condition the use of locally built shims on a new property instead of TestWithLocalLibraries

- src/Microsoft.DotNet.BuildTools.TestSuite/runtime.json
Ubuntu 16.10, openSUSE 42.1, and Fedora 24 are new supported RIDs.
@karajas
> Update TestSuite runtime.json with 3 new test RIDs

- src/Run/CommandLine.cs
- src/Run/Setup.cs
- Changes output message after running the command
- Fix #969 
cc: @chcosta @weshaggard 
As an example, for the [produces](https://github.com/dotnet/corefx/blob/master/config.json#L404) command in CoreFx it will print:
```
produces
Usage: run produces [Action] (global settings)
Settings:
Project = src/packages.builds
ProducesTarget =
It will run:
D:\mariariCoreFx\Tools\msbuild.cmd /nologo /verbosity:minimal /clp:Summary
/maxcpucount /nodeReuse:false
/l:BinClashLogger,Tools\net45\Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log
src/packages.builds /t:ProducesTarget
```
> Fix help for command without alias

- src/xunit.netcore.extensions/Attributes/OuterLoopAttribute.cs
We're often using comments to indicate why a test is being marked as OuterLoop.  This lets us do that as a string.  Then once all use has been updated to specify a message, we can remove the ctor without the message, and devs will be forced to specify a reason for why a test is marked as OuterLoop.
cc: @weshaggard, @bartonjs, @ianhays
> Add reason message to OuterLoopAttribute

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/ApplyBaseLine.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/ApplyPreReleaseSuffix.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/FilterUnknownPackages.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/GetLastStablePackage.cs
Allow for packaging to work in the absense of a package index, stable
package list, baseline package list, and native module to package list.
@dagood this should fix the issue you were seeing with coreclr.
> Support repos that don't define package lists

- dependencies.props
- src/ApiCompat/project.json
- src/BinaryRewriting/BclRewriter/project.json
- src/GenAPI.Desktop/project.json
- src/GenAPI/project.json
- src/GenFacades.Desktop/project.json
- src/GenFacades/project.json
- src/Microsoft.Cci.Extensions/project.json
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.json
This allows openSUSE 42.1 and ubuntu 16.10 to publish buildtools without an alternate `__PUBLISH_RID`. The NETStandard.Library version referenced here is a recent build, from after [this](https://github.com/dotnet/corefx/pull/11356) was merged in last week.
@ericstj , @dagood
> Support ubuntu.16.10 and opensuse.42.1 in tool-runtime project.json

- src/Microsoft.DotNet.CodeAnalysis/PackageFiles/codeAnalysis.targets
The description of the assignment of ValidPinvokeMappings says that it is
OneCoreUwp for UWP and OneCore otherwise; but the implementation is
a much more complicated setup.
Projects may need to build for two different netstandard versions, and the
easiest way for them to do so in corefx is with the TargetGroup property
(e.g. TargetGroup=netstandard1.3); but assigning TargetGroup to anything
which is not a special value in this file makes the ValidPinvokeMappings
variable be unset, which means all p/invokes fail.
This change makes all Windows_NT builds use the OneCore list, unless
the stronger OneCoreUWP list should be chosen instead.
cc: @ericstj @weshaggard @AlexGhiondea
> Register ValidPinvokeMappings for netstandard TargetGroups

- src/xunit.runner.uwp/Package.appxmanifest
The System.Net.Http tests use a loopback server as well as possibly
other intranet servers. So, these additional capabilities are required
in order to run the tests in a UWP app container.
> Add required networking capabilities for Http UWP tests

- src/Microsoft.DotNet.BuildTools.TestSuite/runtime.json
Official builds for this rid have connection issues, so packages have never been published. We can add these back later when the official builds are working.
> Remove fedora.24 from TestSuite runtime.json

- run.cmd
- src/Run/Executor.cs
Remove a hard-coded assumption on the location of the run tool, using the
current working directory instead.  Removed some duplicate code.
> Fix default config file path for run tool.

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.json
@ericstj , @dagood 
I still get hundreds of downgrade warnings, but that seems to be due to bad dependencies in the MSBuild packages (we have the same versions of all those), which were pre-existing.
> Fix package downgrade in tool-runtime project.json

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/ApplyPreReleaseSuffix.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageIndex.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/UpdatePackageIndex.cs
This allows for PackageIndexes to specify a PreReleaseGroup.  This can
be specified at the index level or package level in the package index
file.
If PreReleaseGroups are used in the index then the PreReleaseGroup item
should be defined to provide a mapping from group name to the version
suffix to be used for that group.
For example, for the WCF repo:
```xml
<ItemGroup>
<PreReleaseGroup Include="CoreFx">
<PreRelease>$(CoreFxExpectedPrerelease)</PreRelease>
</PreReleaseGroup>
<PreReleaseGroup Include="WCF">
<PreRelease>$(VersionSuffix)</PreRelease>
</PreReleaseGroup>
<ItemGroup>
```
Fixes https://github.com/dotnet/buildtools/issues/1013
/cc @StephenBonikowsky @weshaggard
> Add PreReleaseGroup support

- bootstrap/bootstrap.ps1
Some repos might require restoring some packages from nuget.org so I have
added this feed to the list of sources.  In the future we can consider
making the list of feeds configurable at the repo level.
> Add nuget.org feed to boot-strapper.

- src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets
Production helix is now https://helix.dot.net, so update this in case someone does not specify HelixApiAccessKey
@ChadNedzlek
> Update Helix API endpoint default

- src/xunit.console.uwp/HostedAppxTest.cs
- src/xunit.runner.uwp/App.xaml.cs
MSBuild looks for "ERROR" in the output to mark a build step failed.  This removes the string from our output so we don't trigger its error detection.
Additionally, this fixes the output from the XUnit UWP app to correctly include the arguments passed and fixes the return code of xunit.console.uwp to be an error if the UWP app failed to launch or timed out.
> Fix false error caused by xunit.console.uwp output and other log issues

- bootstrap/bootstrap.ps1
For packages with content that follows defined conventions copy the
contents into specific locations.  Please see the comment added in this
commit that describes the algorithm in more detail.
> Make the staging of boot-strapped package contents more generic.

- src/GenFacades/Program.cs
When a contract contains nested class type-forwards they are getting filtered out by GenFacades because their type is `NonGenericNestedType` which doesn't implement `INamespaceTypeReference`. With this change, I'm using `INamedTypeReference` which they do  implement and is actually also implemented by `INamespaceTypeReference` so they will be includded.
> Use INamedTypeReference instead in order to also copy the nested class type forwards from the contract assembly

- src/xunit.netcore.extensions/Attributes/ActiveIssueAttribute.cs
- src/xunit.netcore.extensions/Attributes/PlatformSpecificAttribute.cs
- src/xunit.netcore.extensions/Discoverers/ActiveIssueDiscoverer.cs
- src/xunit.netcore.extensions/Discoverers/PlatformSpecificDiscoverer.cs
- src/xunit.netcore.extensions/TestPlatforms.cs
- src/xunit.netcore.extensions/xunit.netcore.extensions.csproj
`Xunit.PlatformID` conflicts with `System.PlatformID` and should be plural according to the naming guidelines for flags enums.
This commit adds a new `Xunit.TestPlatforms` enum as a replacement for `Xunit.PlatformID`. `Xunit.PlatformID` remains for now, until all uses have transitioned to the new enum.
Part of: #999
> Replace Xunit.PlatformID with Xunit.TestPlatforms

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
Setting IgnoreStandardErrorWarningFormat="true" can prevent the case where specific unusual output  (despite no other problems in execution) leads to the exit code of an msbuild task being changed from 0 to -1, thus "breaking" test build.
This fixes test execution on my local box despite this being the "default" value per: 
https://msdn.microsoft.com/en-us/library/microsoft.build.tasks.exec.ignorestandarderrorwarningformat.aspx?f=255&MSPPError=-2147217396 
@weshaggard @crummel
> Add IgnoreStandardErrorWarningFormat to tests

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/UpdatePackageIndex.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/ValidatePackage.cs
Some packages have placeholders in ref but no reference assembly
(eg: System.Private assemblies)
Make sure we index these to get the correct assembly version.
I noticed this issue when reviewing the dev-api merge.
> Handle packages with placeholders only in ref

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/GetLastStablePackage.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/HarvestPackage.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
HarvestAdditionalPackageIds can be specified to tell packaging to
harvest additional packages other than the current package and its
runtime packages.
This is needed when transitioning from a split package to a fat package.
Fixes #1039
/cc @weshaggard @SedarG
> Add support for HarvestAdditionalPackageIds

- run.cmd
The arguments passed to run.ps1 are intended for the run.exe tool, so
prefix the args to run.ps1 with a double dash so that powershell doesn't
attempt to parse them (without this it will "eat" any double dashes passed
to run.ps1).
> Prevent run.ps1 from parsing arguments.

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/ApiCompat.targets
Writing lines to file which has ";" delimited turns it into multiple lines
and our tools don't support multiple line response files. So switching to
use ',' as the delimiter to ensure it is only one line in the response file.
cc @ericstj
> Fix APICompat targets to handle multiple contract depends with response file

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/HarvestPackage.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageItem.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PromoteReferenceDependencies.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/ValidatePackage.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/test/HarvestPackageTests.cs
Previously we'd always prefer live assets over harvested assets from the
previous shipped package.  That put the burden on the developer to
know when to include references.
This change lets us keep references in the package and only use them
when they are significant.  This should help reduce the concept count
required by folks working in corefx.
/cc @weshaggard @joperezr @stephentoub
> Make package harvesting replace refs

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
To prevent collisions seen when archiving a build with > 1 TFM included. 
I'm still testing this but it definitely produces valid test archives that look the same as before, now coming from paths like "\bin\tests\Windows_NT.AnyCPU.Release\System.IO.FileSystem.DriveInfo.Tests\netcoreapp1.0" instead of "\bin\Windows_NT.AnyCPU.Release\System.IO.FileSystem.DriveInfo.Tests"
@chcosta , @weshaggard
> Change test-archiving command's source over to TFM-aware folder path 

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/FrameworkTargeting.targets
This change fixes a bug with building inside VS where the Configuration property would flow through ProjectReferences and break the build because a project is build with mismatched configurations. e.g. mismatched NuGetTargetMoniker and TargetGroup.
@weshaggard @tarekgh @JeremyKuhne @ericstj @joperezr
> Remove Configuration and set ConfigurationGroup on ProjectReferences

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
Before, renaming a file took 30s+, now takes less than 1s. Delay in opening projects is also almost completely gone
<details>
<summary>Previous Design Time Build Log</summary>
```
115 ms  HarvestStablePackage                       1 calls
118 ms  ResolveAssemblyReferences                  9 calls
124 ms  OpenSourceSign                             3 calls
212 ms  GetLatestCommitHash                        4 calls
1152 ms  RestorePackages                            2 calls
2055 ms  ValidateApiCompatForSrc                    2 calls
3067 ms  FillPartialFacade                          2 calls
5396 ms  CoreCompile                                8 calls
13395 ms  BuildAllProjects                           1 calls
23182 ms  ExpandProjectReferences                    1 calls
```
</details> …
> Significantly reduce the amount of time spent in DesignTimeBuilds

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
The DesignTimeBuild property is not defined during a commandline build
causing this condition to evaluate to false and skip building the project
references.  This broke CoreFx build when trying to pick up buildtools.
/cc @hughbe
> Fix Condition on pkgproj references build

- src/Microsoft.Cci.Extensions/Extensions/TypeExtensions.cs
- src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Methods.cs
The first constructor in the base class is sometimes one that is marked as [Obsolete("message", true)] meaning any usage of that ctor results in a compilation error. Example: System.ComponentModel.AsyncCompletedEventArgs
We now skip those constructors when generating the base call so classes that inherit from those types compile out of the box.
> GenAPI: Ignore obsolete-as-error ctors when generating base call

- src/xunit.runner.uwp/App.xaml.cs
I was getting crashes in the UWPTestRunner every time I tried to run the 'netcore50' tests for any library:
```
msbuild /t:rebuildandtest /p:TestTFM=netcore50  /p:TestNugetRuntimeId=win10-x64
```
The exception in the UWPTestRunner just after running the tests and writing out the logs:
```
0:023> !pe
Exception object: 0000011cc11f1df8
Exception type:   System.ObjectDisposedException
Message:          Cannot access a closed Stream.
InnerException:   <none>
StackTrace (generated):
SP               IP               Function
00000014DBC3EE30 00007FFD6DFB833B mscorlib_ni!System.IO.__Error.StreamIsClosed()+0x3b
00000014DBC3EE60 00007FFD6D7995E4 mscorlib_ni!System.IO.BufferedStream.Flush()+0x14
00000014DBC3EE90 00007FFD10F0AC9A XunitUwpRunner!XunitUwpRunner.App+<WriteLogs>d__4.MoveNext()+0x33a …
```
> Fix UWPTestRunner ObjectDisposedException when writing logs

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets
Test projects building with different TargetGroups were clashing on
TestArchiveDir
/cc @weshaggard @MattGal
> Fix clash on TestArchiveDir

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageIndex.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/UpdatePackageIndex.cs
- src/Microsoft.DotNet.Build.Tasks.Packaging/src/ValidatePackage.cs
This improves the indexing to also index implementation versions,
potentially from runtime-specific packages.  Previously we only indexed
references which missed cases where impl assemblies compiled against
other impl assemblies and the ref didn't change.  Such is the case for
partial facades.
I've also added some validation to catch cases where we add new shim
packages.
This change requires CoreFx change: https://github.com/ericstj/corefx/commit/6965cf0b5a0ce9073f79b8bbeaa8a488f41b4202
> Update package indexing and Validation

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/UpdatePackageIndex.cs
I had removed a call to ToArray which caused the removal to happen while
enumerating over the collection.  Add it back.
> Fix issue with removing orphaned versions

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/buildagainstpackages.targets
This prevents us from generating project.json's in the build step after we
have already generated them in the sync step.
> Don't generate a project.json file if 'RestoreDuringBuild' is 'false'.

- src/Microsoft.DotNet.Build.Tasks/AddDependenciesToProjectJson.cs
This change doesn't write a new generated project.json for test projects if the contents match the exisiting project.json.  Doing this allows us to make use of the "IsRestoreRequired" task in CoreFx and improves perf for restoring generated test packages when no changes have been made.  On my machine, restore time goes from ~11 minutes to ~10 seconds.
> Don't write generate project.json if contents match

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/sign.targets
This is useful if a project wants to specify a key other than the MSFT.snk, ECMA.snk or Open.snk.
> Allow overriding the AssemblyOriginatorKeyFile property

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
Currently test publishing happens during PrepareForRun which is a
post step of build. However we need TestTFM as a parameter in test
publishing which we don't know until test runtime because a given
test build can have a set of TestTFM's that apply to it. To address
this we are moving test publishing as a pre-step for test running.
To do this we are overriding the Test target and adding a set of
DependsOnTargets to allow for ordering them correctly.
cc @joperezr @tarekgh 
fyi @stephentoub this should fix the issue we saw with CodeDom tests.
> Move test publishing from post-build to pre-test-run

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets
Redirect git rev-parse HEAD error output to avoid bogus messages about missing git tool when building inside VS and not having git on the path. Any errors are ignored anyway.
> Redirect git rev-parse HEAD error output

- src/Run/Executor.cs
- src/Run/Setup.cs
- Create a new property on Command that allows specifying a "DefaultAlias" value where Aliases are listed.  This value is only used if no other flags are provided.  
In this incarnation still allows things to continue if the user fails to specify an alias because there might be a scenario where that makes some kind of sense  (I haven't found that yet).   This was inspired by what happened when a user called "clean.cmd --all.   Since Clean.cmd was explicitly matching on "-all", this ended up passing "clean --all" to Run.exe, which failed to match the letters to the actual aliases allowed (b, p, c), and since these aliases were needed to pick a build target, no  build target gets specified, and thus "Build" is invoked.  
Once this change is in CoreFX / other repos, we simply need to tweak …
> Add support for commands to have a "default alias"

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets
Change
https://github.com/dotnet/buildtools/commit/499458e3889a68b633be1bccc31eae6fe4f30191
broken running tests in VS when you didn't actually build from the command line first.
This change hooks the test publishing step, not the running, to the PrepareForRun
so that the default test configuration can be F5'ed and work in VS.
Note this isn't full-proof because it does rely on the default configuration to
exist and be .NET Core based but it will enable most of our test projects to just work.
cc @ericstj
> Fix default test runs from VS

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
Our official build does some work that filtered ProjectReferences
to replace them with package references instead. The filtering
of the ProjectReferences currently happens as part of BeforeResolveReferences https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/buildagainstpackages.targets#L64
(we might consider changing that to hook ResolveProjectReferences).
However in our DiscoverTestInputs target we do ResolveProjectReferences
first which means the filtering does happen before that. To eliminate
the need for us to know about the ordering of references we should just
depend on ResolveReferences instead.
@ericstj @chcosta can you please take a look.
> DiscoverTestInputs should depend on ResolveReferences

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/GetApplicableAssetsFromPackages.cs
This allows placeholders from a pkgproj ref.  Previously we'd error
when a pkgproj reference provided only placeholders.  The idea was
"why even reference the project if you don't get anything out of it?"
but this makes constructing the project references cumbersome:
consider a project that builds for netstandard1.3 but needs to run on
net46.  No implementation may be needed for net46 since many contracts
are inbox, but we don't want to force folks to condition their project
references on the TestTFM.
/cc @weshaggard @karajas
> Allow placeholders from pkgproj refs

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
RunTestsForProject not only runs the tests but also generates the
test runner script. As part of a recent clean-up that aspect was missed
with change https://github.com/dotnet/buildtools/commit/499458e3889a68b633be1bccc31eae6fe4f30191.
To get our official test runs working again we need to move the condition
to of TestDisabled!=true to the actual execution of thests instead of the
RunTestsForProject target.
In the future we need to split this logic into mutliple targets if we need the
logic for different purposes.
@MattGal PTAL - This should get us unblocked for the time being until we can spend some time refactoring these targets.
> Fix test script generation

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets
Creating a version.txt file in the PackagesBasePath folder was not optimal because PackageBasePath contains the $(OSGroup) which gets filtered for a build.  The result is that you could have multiple PackageBasePaths, which meant generating redundant version.txt files.  We really just want to generate one version.txt file and use that for all of the produced packages.  In some repo's, like buildtools, this doesn't matter as much as in other repo's, like CoreFx, where there are multiple OSGroups for a build.  
This change moves the version.txt file to get generated in the obj directory, and creates a traversal build dependency so that the target gets called once before a traversal build.
@joperezr @weshaggard
> Move version.txt to obj directory

- Documentation/annotated-dependency-props.md
- Documentation/dependency-auto-update.md
Adds `dependency-auto-update.md`, an overview of auto-update PR flow, and `annotated-dependency-props.md`, a breakdown of dependencies.props.
This is the current state--the proposal using Repo API Compose commands is https://github.com/dotnet/buildtools/pull/1069. That proposal replaces some of this, but the Maestro and subscription parts will be mostly unchanged. Also, this info should be useful until the proposal has actually been implemented across all repos.
@chcosta @weshaggard @gkhanna79 
/cc @markwilkie @dleeapho
> Document dependency auto-update PR process

- src/Microsoft.DotNet.VersionTools/Automation/GitHubApi/GitHubApiModel.cs
- src/Microsoft.DotNet.VersionTools/Automation/GitHubApi/GitHubClient.cs
- src/Microsoft.DotNet.VersionTools/Automation/VersionsRepoUpdater.cs
- src/Microsoft.DotNet.VersionTools/BuildInfo.cs
Adds a new build-info file `Last_Build_Packages.txt` that stores only the new packages. When creating `Last_Build_Packages` is enabled, the update to `Latest_Packages` carries the existing `Latest_Packages` entries over into the new version.
Also includes changes to publish all build-info files in a single commit.
Fixes (once uptaken) https://github.com/dotnet/buildtools/issues/1117.
Example commit, using some odd packages I had lying around: https://github.com/dagood/versions/commit/e34d05821c5c713ce8fa1a4f0d95bc7428fc893a.
@chcosta @weshaggard @karajas
/cc @eerhardt
> Keep old packages in file when updating Latest_Packages

- Documentation/annotated-dependency-props.md
- Documentation/project-nuget-dependencies.md
Brings over https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/project-nuget-dependencies.md with some edits to make it more general. Slight edit to annotated-dependency-props.md for more generality.
This doc is for the non-auto-update side of the dependency tooling.
I changed https://github.com/dotnet/corefx/pull/12554 to point to this new buildtools doc instead of adding another link for auto-update.
@weshaggard @markwilkie
> Move project-nuget-dependencies.md from corefx

- src/Microsoft.DotNet.Build.Tasks/AddDependenciesToProjectJson.cs
- src/Microsoft.DotNet.Build.Tasks/PackageFiles/buildagainstpackages.targets
Check for use of common test project.json
Change AddDependenciesToProjectJson to allow for compile only assets in framework specific dependencies of common project.json
> Allow BuildAgainstPackages to work with global test project.json 

- src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets
cc: @weshaggard @MattGal 
FYI: @karajas @tarekgh 
Adding `TargetGroup` to the dependency list file name, which will help avoid race conditions of two builds trying to write to the same file, which has caused some intermittent build brakes.
> Add TargetGroup to the dependency list file to avoid clashes

- src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets
Packages can be built without building all binaries by specifying
AllowPartialPackages=true.
To build a partial package without rebuilding any of the projects use
the following
msbuild <pkgproj> /p:AllowPartialPackages=true;BuildPackageLibraryReferences=false
/cc @ellismg
> Partial package support
